import {NextResponse} from 'next/server';
import {currentUser} from '@/src/lib/supabase/server';
import type {OrbyJsonObject} from '@/src/lib/orby/core/contracts';
import type {OrbyIntelligenceJob} from '@/src/lib/orby/intelligence/contracts';
import {createServerOrbyIntelligence} from '@/src/lib/orby/intelligence/server';
import {intelligenceErrorResponse,intelligenceIdentity,object} from '@/src/lib/orby/intelligence/http';
export const runtime='nodejs';export const dynamic='force-dynamic';
function cronInterval(expression:string){const value=expression.trim();if(value==='0 * * * *')return 3600;if(/^0 \d{1,2} \* \* \*$/.test(value))return 86400;if(/^0 \d{1,2} \* \* [0-6]$/.test(value))return 604800;throw new Error('ORBY_CRON_UNSUPPORTED');}
export async function GET(request:Request){try{const user=await currentUser();if(!user)return NextResponse.json({ok:false},{status:401});const url=new URL(request.url),identity=await intelligenceIdentity(user,{organizationId:url.searchParams.get('organizationId'),workspaceId:url.searchParams.get('workspaceId')},{admin:true}),runtime=await createServerOrbyIntelligence(),schedules=await runtime.repository.listSchedules(identity,Math.min(100,Math.max(1,Number(url.searchParams.get('limit')||50))));return NextResponse.json({ok:true,schedules},{headers:{'Cache-Control':'no-store'}});}catch(error){return intelligenceErrorResponse(error);}}
export async function POST(request:Request){try{const user=await currentUser();if(!user)return NextResponse.json({ok:false},{status:401});const body=object(await request.json()),identity=await intelligenceIdentity(user,body,{admin:true}),runtime=await createServerOrbyIntelligence(),cron=typeof body.cronExpression==='string'?body.cronExpression.trim():undefined,interval=cron?cronInterval(cron):Math.max(3600,Number(body.intervalSeconds||86400)),schedule=await runtime.repository.saveSchedule({organizationId:identity.organizationId,workspaceId:identity.workspaceId,jobType:String(body.jobType||'detector.run') as OrbyIntelligenceJob['type'],cronExpression:cron,intervalSeconds:interval,payload:{...object(body.payload),userId:identity.userId} as OrbyJsonObject,enabled:body.enabled!==false,nextRunAt:typeof body.nextRunAt==='string'?body.nextRunAt:new Date().toISOString(),timezone:typeof body.timezone==='string'?body.timezone:'Asia/Aden',createdBy:identity.userId});return NextResponse.json({ok:true,schedule},{status:201,headers:{'Cache-Control':'no-store'}});}catch(error){return intelligenceErrorResponse(error);}}
