'use client';

import {useActionState} from 'react';
import {configureOrbyPlusPlan,reviewOrbyPlusPayment,type OrbyPlusActionState} from '@/app/actions/orby-plus';
import {formatStoreMoney,type CurrencyDefinition} from '@/src/lib/store/currency';

type Plan={price:number|string;currency:string;billing_months:number;is_available:boolean}|null;
type RequestRow={id:string;user_id:string;display_name:string;email:string;original_amount:number|string;original_currency:string;payment_amount:number|string;payment_currency:string;payment_reference:string;storage_path:string|null;created_at:string;method_name:string};
export default function OrbyPlusAdmin({plan,currencies,requests}:{plan:Plan;currencies:CurrencyDefinition[];requests:RequestRow[]}){
 const[configState,configAction,configPending]=useActionState<OrbyPlusActionState,FormData>(configureOrbyPlusPlan,{}),[reviewState,reviewAction,reviewPending]=useActionState<OrbyPlusActionState,FormData>(reviewOrbyPlusPayment,{});
 return <div className="mt-8 grid gap-6 xl:grid-cols-[22rem_minmax(0,1fr)]"><section className="md-panel p-5"><h2 className="text-lg font-black">إعداد الخطة</h2><p className="mt-1 text-xs leading-6 text-slate-500">السعر والعملة وحالة الإتاحة من هنا فقط. لا يوجد سعر Hardcoded.</p><form action={configAction} className="mt-5 grid gap-4"><label className="grid gap-2 text-xs"><span>السعر</span><input name="price" type="number" min="0" step="any" defaultValue={plan?.price??0} className="field" required/></label><label className="grid gap-2 text-xs"><span>العملة</span><select name="currency" defaultValue={plan?.currency||currencies[0]?.code||'SAR'} className="field">{currencies.map(item=><option key={item.code} value={item.code}>{item.name} — {item.code}</option>)}</select></label><label className="grid gap-2 text-xs"><span>مدة الاشتراك بالأشهر</span><input name="billing_months" type="number" min="1" max="36" defaultValue={plan?.billing_months??1} className="field" required/></label><label className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3 text-sm"><span>متاح للشراء</span><select name="is_available" defaultValue={plan?.is_available?'true':'false'} className="field max-w-32"><option value="false">لا</option><option value="true">نعم</option></select></label>{configState.error?<p className="rounded-lg bg-rose-300/10 p-2 text-xs text-rose-200">{configState.error}</p>:null}{configState.success?<p className="rounded-lg bg-emerald-300/10 p-2 text-xs text-emerald-200">{configState.success}</p>:null}<button disabled={configPending} className="md-button md-button-primary">{configPending?'جارٍ الحفظ…':'حفظ ORBY Plus'}</button></form></section>
 <section className="md-panel p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-black">طلبات الدفع المعلقة</h2><p className="mt-1 text-xs text-slate-500">الموافقة تنشئ/تمدّد اشتراك Plus مرة واحدة فقط.</p></div><span className="md-badge">{requests.length}</span></div>{reviewState.error?<p className="mt-3 rounded-lg bg-rose-300/10 p-2 text-xs text-rose-200">{reviewState.error}</p>:null}{reviewState.success?<p className="mt-3 rounded-lg bg-emerald-300/10 p-2 text-xs text-emerald-200">{reviewState.success}</p>:null}<div className="mt-4 grid gap-3">{requests.length?requests.map(request=><article key={request.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-sm">{request.display_name||request.email||request.user_id}</strong><span dir="ltr" className="mt-1 block text-right text-[11px] text-slate-500">{request.email}</span></div><span className="text-sm font-black text-emerald-200">{formatStoreMoney(request.payment_amount,request.payment_currency,currencies)}</span></div><div className="mt-3 grid gap-1 text-xs text-slate-400 sm:grid-cols-2"><span>السعر الأصلي: {formatStoreMoney(request.original_amount,request.original_currency,currencies)}</span><span>وسيلة الدفع: {request.method_name}</span><span>رقم العملية: <b dir="ltr" className="text-slate-200">{request.payment_reference}</b></span><span>التاريخ: {new Date(request.created_at).toLocaleString('ar-YE')}</span></div>{request.storage_path?<a href={`/admin/orby-plus/proof/${request.id}`} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-bold text-violet-200 underline">فتح الإيصال</a>:<p className="mt-3 text-[11px] text-slate-500">لم يُرفق إيصال؛ الاعتماد على رقم العملية.</p>}<form action={reviewAction} className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input type="hidden" name="request_id" value={request.id}/><input name="note" maxLength={500} className="field" placeholder="ملاحظة المراجعة (اختياري)"/><button disabled={reviewPending} name="decision" value="approve" className="md-button md-button-primary md-button-sm">موافقة</button><button disabled={reviewPending} name="decision" value="reject" className="md-button md-button-danger md-button-sm">رفض</button></form></article>):<p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">لا توجد طلبات ORBY Plus معلقة.</p>}</div></section></div>;
}
