import {createHash,randomUUID} from 'node:crypto';
import type {OrbyJsonObject} from '../core/contracts';
import type {OrbyVerticalKey} from '../os/verticals';

export type OrbyVerticalEvidence={metric:string;current:number;previous?:number;unit?:string;sourceRef:string;observedAt:string};
export type OrbyVerticalSuggestedAction={id:string;title:string;description:string;operation:string;riskLevel:'low'|'medium'|'high'|'critical';requiresApproval:true;payload:OrbyJsonObject};
export type OrbyVerticalInsight={
 id:string;vertical:OrbyVerticalKey;fingerprint:string;title:string;reason:string;severity:'info'|'low'|'medium'|'high'|'critical';
 confidence:number;priority:number;evidence:readonly OrbyVerticalEvidence[];recommendations:readonly string[];
 suggestedActions:readonly OrbyVerticalSuggestedAction[];status:'open'|'acknowledged'|'dismissed'|'confirmed'|'resolved';
 detectedAt:string;cooldownUntil?:string;metadata:OrbyJsonObject;
};
export type OrbyCommerceSnapshot={sales:number;previousSales:number;grossProfit:number;revenue:number;lowStockItems:number;stagnantProducts:number;expenses:number;previousExpenses:number;sourceRef:string;observedAt:string};
export type OrbyFoodServiceSnapshot={revenue:number;foodCost:number;wasteCost:number;previousWasteCost:number;lowMarginRecipes:number;delayedOrders:number;sourceRef:string;observedAt:string};
export type OrbyHospitalitySnapshot={availableRooms:number;occupiedRooms:number;previousOccupancyRate:number;roomRevenue:number;outOfServiceRooms:number;housekeepingBacklog:number;cancellations:number;reservations:number;sourceRef:string;observedAt:string};

function clamp(value:number,min=0,max=1){return Math.min(max,Math.max(min,value));}
function ratio(current:number,previous:number){return previous===0?(current===0?0:1):(current-previous)/Math.abs(previous);}
function fingerprint(vertical:OrbyVerticalKey,title:string,evidence:readonly OrbyVerticalEvidence[]){return createHash('sha256').update(`${vertical}:${title}:${evidence.map(item=>`${item.metric}:${item.current}`).join('|')}`).digest('hex').slice(0,40);}
function action(title:string,description:string,operation:string,riskLevel:OrbyVerticalSuggestedAction['riskLevel'],payload:OrbyJsonObject):OrbyVerticalSuggestedAction{return{id:randomUUID(),title,description,operation,riskLevel,requiresApproval:true,payload};}
function insight(input:Omit<OrbyVerticalInsight,'id'|'fingerprint'|'status'>):OrbyVerticalInsight{if(!input.reason.trim()||!input.evidence.length||!input.suggestedActions.length)throw new Error('ORBY_INSIGHT_INCOMPLETE');if(input.suggestedActions.some(item=>item.requiresApproval!==true))throw new Error('ORBY_INSIGHT_ACTION_APPROVAL_REQUIRED');return{...input,id:randomUUID(),fingerprint:fingerprint(input.vertical,input.title,input.evidence),status:'open'};}

export class OrbyVerticalAnalysisEngine{
 analyzeCommerce(snapshot:OrbyCommerceSnapshot):readonly OrbyVerticalInsight[]{const values:OrbyVerticalInsight[]=[],salesChange=ratio(snapshot.sales,snapshot.previousSales),expenseChange=ratio(snapshot.expenses,snapshot.previousExpenses),margin=snapshot.revenue>0?snapshot.grossProfit/snapshot.revenue:0;
  if(salesChange<=-.12){const evidence=[{metric:'sales',current:snapshot.sales,previous:snapshot.previousSales,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'commerce',title:'انخفاض في المبيعات',reason:`انخفضت المبيعات بنسبة ${Math.abs(salesChange*100).toFixed(1)}% عن الفترة السابقة.`,severity:salesChange<-.3?'high':'medium',confidence:clamp(.65+Math.min(.3,Math.abs(salesChange))),priority:Math.round(Math.min(100,55+Math.abs(salesChange)*100)),evidence,recommendations:['مقارنة المنتجات والقنوات والعملاء بين الفترتين.','فحص المخزون والتسعير قبل إطلاق أي إجراء.'],suggestedActions:[action('إعداد تحليل تفصيلي','تجهيز تحليل المنتجات والقنوات المسببة للانخفاض.','COMMERCE_SALES_ANALYSIS','low',{sourceRef:snapshot.sourceRef}),action('تجهيز خطة استجابة','إنشاء مسودة خطة مبيعات قابلة للمراجعة.','COMMERCE_RECOVERY_DRAFT','medium',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{salesChange}}));}
  if(expenseChange>=.15){const evidence=[{metric:'expenses',current:snapshot.expenses,previous:snapshot.previousExpenses,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'commerce',title:'ارتفاع غير معتاد في المصروفات',reason:`ارتفعت المصروفات بنسبة ${(expenseChange*100).toFixed(1)}% مقارنة بالفترة السابقة.`,severity:expenseChange>.35?'high':'medium',confidence:clamp(.7+Math.min(.25,expenseChange)),priority:Math.round(Math.min(100,60+expenseChange*80)),evidence,recommendations:['تفصيل المصروفات حسب النوع والمورد.','التحقق من المصروفات المتكررة أو غير المعتادة.'],suggestedActions:[action('مراجعة المصروفات','تجهيز تقرير فروقات المصروفات للمراجعة.','COMMERCE_EXPENSE_REVIEW','low',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{expenseChange}}));}
  if(snapshot.lowStockItems>0||snapshot.stagnantProducts>0){const evidence=[{metric:'low_stock_items',current:snapshot.lowStockItems,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt},{metric:'stagnant_products',current:snapshot.stagnantProducts,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'commerce',title:'فرصة لتحسين المخزون',reason:`يوجد ${snapshot.lowStockItems} صنفًا منخفضًا و${snapshot.stagnantProducts} صنفًا راكدًا.`,severity:snapshot.lowStockItems>10?'high':'medium',confidence:.9,priority:75,evidence,recommendations:['إعادة الطلب للأصناف السريعة بعد مراجعة مدة التوريد.','اقتراح تصريف مدروس للأصناف الراكدة.'],suggestedActions:[action('تجهيز إعادة طلب','إنشاء مسودة احتياج توريد دون إرسالها.','INVENTORY_REORDER_DRAFT','high',{sourceRef:snapshot.sourceRef}),action('تجهيز حملة تصريف','إنشاء مسودة حملة للأصناف الراكدة.','STAGNANT_STOCK_CAMPAIGN_DRAFT','medium',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{margin}}));}
  return values;
 }
 analyzeFoodService(snapshot:OrbyFoodServiceSnapshot):readonly OrbyVerticalInsight[]{const values:OrbyVerticalInsight[]=[],foodCostRate=snapshot.revenue>0?snapshot.foodCost/snapshot.revenue:0,wasteChange=ratio(snapshot.wasteCost,snapshot.previousWasteCost);
  if(foodCostRate>.38||snapshot.lowMarginRecipes>0){const evidence=[{metric:'food_cost_percentage',current:foodCostRate*100,unit:'%',sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt},{metric:'low_margin_recipes',current:snapshot.lowMarginRecipes,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'food_service',title:'ربحية وصفات تحتاج مراجعة',reason:`بلغت تكلفة الطعام ${(foodCostRate*100).toFixed(1)}% مع ${snapshot.lowMarginRecipes} وصفات منخفضة الربحية.`,severity:foodCostRate>.5?'high':'medium',confidence:.92,priority:82,evidence,recommendations:['مراجعة كميات ومكونات الوصفات الأعلى تكلفة.','محاكاة سعر أو حجم حصة جديد قبل أي تعديل.'],suggestedActions:[action('محاكاة ربحية الوصفات','حساب أثر تعديل المكونات أو السعر دون تطبيق.','FOOD_RECIPE_MARGIN_SIMULATION','low',{sourceRef:snapshot.sourceRef}),action('تجهيز تعديل وصفة','إنشاء مسودة تعديل تحتاج موافقة مدير.','FOOD_RECIPE_UPDATE_DRAFT','high',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{foodCostRate}}));}
  if(wasteChange>.15){const evidence=[{metric:'waste_cost',current:snapshot.wasteCost,previous:snapshot.previousWasteCost,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'food_service',title:'ارتفاع في هدر المكونات',reason:`ارتفعت تكلفة الهدر بنسبة ${(wasteChange*100).toFixed(1)}%.`,severity:wasteChange>.4?'high':'medium',confidence:.87,priority:78,evidence,recommendations:['ربط الهدر بالوردية والوصفة والمكوّن.','مراجعة التحضير والشراء والتخزين.'],suggestedActions:[action('تحليل الهدر','تجهيز تحليل مصادر الهدر حسب الوصفة والمكوّن.','FOOD_WASTE_ANALYSIS','low',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{wasteChange}}));}
  if(snapshot.delayedOrders>0){const evidence=[{metric:'delayed_orders',current:snapshot.delayedOrders,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'food_service',title:'تأخر في الطلبات أو المطبخ',reason:`تم رصد ${snapshot.delayedOrders} طلبات متأخرة.`,severity:snapshot.delayedOrders>15?'high':'medium',confidence:.84,priority:70,evidence,recommendations:['تحديد محطة الاختناق وأوقات الذروة.'],suggestedActions:[action('تحليل تدفق المطبخ','تجهيز توزيع التأخير حسب المحطة والوردية.','FOOD_KITCHEN_FLOW_ANALYSIS','low',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{}}));}
  return values;
 }
 analyzeHospitality(snapshot:OrbyHospitalitySnapshot):readonly OrbyVerticalInsight[]{const values:OrbyVerticalInsight[]=[],capacity=Math.max(1,snapshot.availableRooms+snapshot.occupiedRooms),occupancy=snapshot.occupiedRooms/capacity,occupancyChange=occupancy-snapshot.previousOccupancyRate,adr=snapshot.occupiedRooms>0?snapshot.roomRevenue/snapshot.occupiedRooms:0,revpar=snapshot.roomRevenue/capacity;
  if(occupancyChange<=-.1){const evidence=[{metric:'occupancy_rate',current:occupancy*100,previous:snapshot.previousOccupancyRate*100,unit:'%',sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt},{metric:'revpar',current:revpar,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'hospitality',title:'انخفاض في إشغال الفندق',reason:`انخفض الإشغال بمقدار ${Math.abs(occupancyChange*100).toFixed(1)} نقطة مئوية.`,severity:occupancyChange<-.25?'high':'medium',confidence:.9,priority:84,evidence,recommendations:['مقارنة القنوات والأسعار وأنواع الغرف.','مراجعة التوفر والإلغاءات قبل اقتراح حملة.'],suggestedActions:[action('تحليل الإشغال','تجهيز تحليل القنوات والأسعار والتوفر.','HOTEL_OCCUPANCY_ANALYSIS','low',{sourceRef:snapshot.sourceRef}),action('تجهيز حملة إشغال','إنشاء مسودة حملة أو عرض دون نشر.','HOTEL_OCCUPANCY_CAMPAIGN_DRAFT','medium',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{occupancy,adr,revpar}}));}
  if(snapshot.outOfServiceRooms>0||snapshot.housekeepingBacklog>0){const evidence=[{metric:'out_of_service_rooms',current:snapshot.outOfServiceRooms,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt},{metric:'housekeeping_backlog',current:snapshot.housekeepingBacklog,sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'hospitality',title:'غرف غير متاحة تحتاج تدخلًا',reason:`يوجد ${snapshot.outOfServiceRooms} غرف خارج الخدمة و${snapshot.housekeepingBacklog} مهام تنظيف متأخرة.`,severity:snapshot.outOfServiceRooms>5?'high':'medium',confidence:.95,priority:88,evidence,recommendations:['ترتيب الصيانة والتنظيف حسب أثرها على التوفر.'],suggestedActions:[action('تجهيز خطة استعادة الغرف','إنشاء مسودة أولويات التنظيف والصيانة.','HOTEL_ROOM_RECOVERY_DRAFT','medium',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{}}));}
  if(snapshot.reservations>0&&snapshot.cancellations/snapshot.reservations>.15){const cancellationRate=snapshot.cancellations/snapshot.reservations,evidence=[{metric:'cancellation_rate',current:cancellationRate*100,unit:'%',sourceRef:snapshot.sourceRef,observedAt:snapshot.observedAt}];values.push(insight({vertical:'hospitality',title:'ارتفاع في إلغاءات الحجوزات',reason:`بلغ معدل الإلغاء ${(cancellationRate*100).toFixed(1)}%.`,severity:cancellationRate>.3?'high':'medium',confidence:.86,priority:72,evidence,recommendations:['تحليل الإلغاء حسب القناة والمهلة والسعر.'],suggestedActions:[action('تحليل الإلغاءات','تجهيز تحليل أسباب الإلغاء والقنوات.','HOTEL_CANCELLATION_ANALYSIS','low',{sourceRef:snapshot.sourceRef})],detectedAt:snapshot.observedAt,metadata:{cancellationRate}}));}
  return values;
 }
}

export class OrbyProactiveInsightLifecycle{
 private readonly insights=new Map<string,OrbyVerticalInsight>();
 upsert(value:OrbyVerticalInsight,cooldownMinutes=60){const existing=this.insights.get(value.fingerprint),now=Date.parse(value.detectedAt);if(existing&&existing.cooldownUntil&&Date.parse(existing.cooldownUntil)>now)return{insight:existing,created:false,suppressed:true};const next={...value,id:existing?.id||value.id,cooldownUntil:new Date(now+cooldownMinutes*60_000).toISOString(),metadata:{...existing?.metadata,...value.metadata,occurrences:Number(existing?.metadata.occurrences||0)+1}};this.insights.set(next.fingerprint,next);return{insight:next,created:!existing,suppressed:false};}
 decide(fingerprintValue:string,decision:'acknowledged'|'dismissed'|'confirmed'|'resolved'){const current=this.insights.get(fingerprintValue);if(!current)throw new Error('ORBY_INSIGHT_NOT_FOUND');const updated={...current,status:decision};this.insights.set(fingerprintValue,updated);return updated;}
 list(){return[...this.insights.values()];}
}
