import Link from 'next/link';
import {requireSuperAdmin} from '@/src/lib/auth';
import type {JsonObject} from '@/src/lib/integration/contracts';
import {IntegrationDatabase} from '@/src/lib/integration/platform';
import {setIntegrationFlag} from '../actions';
import {runIntegrationReadinessLab} from './actions';

export const dynamic='force-dynamic';
export const metadata={title:'مختبر جاهزية الموصلات | مَدار'};

type Flag={enabled:boolean;updated_at:string};
type Organization={id:string;name:string;slug:string;status:string};
type Run={id:string;organization_id:string|null;status:string;suite_version:string;connector_version:string;total_checks:number;passed_checks:number;failed_checks:number;summary:JsonObject;started_at:string;finished_at:string|null};
type Check={id:string;run_id:string;check_key:string;title:string;status:string;duration_ms:number;details:JsonObject;error_code:string|null;error_message:string|null;created_at:string};

const criteria=[
 'اتصال مستقل لكل مساحة عمل','تشفير الأسرار وعدم إعادتها للواجهة','جلب البيانات التاريخية','جلب التحديثات الجديدة فقط','الاستكمال من Checkpoint بعد الانقطاع','منع التكرار والمطابقة','التحويل إلى UDM','عزل السجلات الخاطئة دون إسقاط الدفعة','REST وWebhook وCSV وExcel وقاعدة بيانات وLocal Bridge','انتهاء المفتاح وتدويره وOAuth','حالة الاتصال وآخر مزامنة','سجل المراجعة','القراءة فقط وإضافة موصل بلا تعديل القلب',
];
const connectors=['madar-reference-commerce','madar-test-rest','madar-test-webhook','madar-test-csv-excel','madar-test-database-readonly','madar-test-local-bridge','madar-test-oauth'];
const date=(value:string|null)=>value?new Date(value).toLocaleString('ar-EG'):'—';
const statusClass=(status:string)=>status==='passed'||status==='active'?'bg-emerald-300/10 text-emerald-200':status==='running'?'bg-amber-300/10 text-amber-100':'bg-rose-300/10 text-rose-100';

export default async function ReadinessLabPage(){
 await requireSuperAdmin();const database=new IntegrationDatabase();
 const flagParams=new URLSearchParams({select:'enabled,updated_at',key:'eq.integration_readiness_lab_enabled',organization_id:'is.null',limit:'1'}),orgParams=new URLSearchParams({select:'id,name,slug,status',type:'neq.STUDENT',order:'created_at.desc',limit:'100'}),runParams=new URLSearchParams({select:'id,organization_id,status,suite_version,connector_version,total_checks,passed_checks,failed_checks,summary,started_at,finished_at',order:'started_at.desc',limit:'12'}),checkParams=new URLSearchParams({select:'id,run_id,check_key,title,status,duration_ms,details,error_code,error_message,created_at',order:'created_at.desc',limit:'240'});
 const [flagRows,organizations,runs,checks]=await Promise.all([database.select<Flag>('integration_feature_flags',flagParams),database.select<Organization>('organizations',orgParams),database.select<Run>('integration_readiness_runs',runParams),database.select<Check>('integration_readiness_checks',checkParams)]),flag=flagRows[0],organizationById=new Map(organizations.map(item=>[item.id,item])),checksByRun=new Map<string,Check[]>();
 for(const check of checks){const group=checksByRun.get(check.run_id)||[];group.push(check);checksByRun.set(check.run_id,group);}
 return <main className="mx-auto max-w-[1500px] p-5 py-8 sm:p-8">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-violet-200">Integration Readiness Laboratory</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">مختبر الجاهزية والموصل المرجعي</h1><p className="mt-3 max-w-4xl leading-8 text-slate-400">بيئة قبول مصطنعة تعمل في وضع القراءة فقط وتختبر التاريخ، التحديثات، الأعطال، الاستكمال، التكرار، UDM، الأسرار، OAuth وLocal Bridge قبل لمس بيانات عميل حقيقي.</p></div><div className="flex gap-2"><Link href="/admin/integrations" className="md-button md-button-secondary">مركز الاتصالات</Link><Link href="/admin/integrations/audit" className="md-button md-button-secondary">سجل المراجعة</Link></div></div>

  <section className="mt-8 grid gap-5 xl:grid-cols-[1fr_.8fr]"><div className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">بوابة المختبر</h2><p className="mt-2 text-sm text-slate-400">مغلقة افتراضيًا. تشغيلها لا يفعّل الكتابة الخارجية ولا يتصل بعميل حقيقي.</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${flag?.enabled?'bg-emerald-300/10 text-emerald-200':'bg-slate-400/10 text-slate-400'}`}>{flag?.enabled?'مفعّل':'متوقف'}</span></div><form action={setIntegrationFlag} className="mt-5"><input type="hidden" name="flag_key" value="integration_readiness_lab_enabled"/><input type="hidden" name="flag_enabled" value={String(!flag?.enabled)}/><button className="md-button md-button-secondary" type="submit">{flag?.enabled?'إيقاف المختبر':'تفعيل المختبر'}</button></form>{flag?.enabled&&<form action={runIntegrationReadinessLab} className="mt-6 grid gap-4 rounded-2xl border border-violet-300/20 bg-violet-300/[.04] p-5"><label className="grid gap-2 text-sm font-bold">مساحة اختبار لعزل السجلات وكتابة حدث المراجعة<select name="organization_id" className="field rounded-xl p-3" defaultValue=""><option value="">تشغيل عام دون ربط بمساحة</option>{organizations.map(organization=><option key={organization.id} value={organization.id}>{organization.name} — /{organization.slug}</option>)}</select></label><button className="md-button md-button-primary" type="submit">تشغيل اختبارات القبول كاملة</button><p className="text-xs leading-6 text-slate-500">يستخدم التشغيل Fixtures مصطنعة فقط. جميع الموصلات الداخلية تعلن write=false، ولا تنفذ أي أمر تعديل على نظام خارجي.</p></form>}</div><div className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><h2 className="text-2xl font-black">الموصلات المسجلة</h2><div className="mt-5 space-y-2">{connectors.map((connector,index)=><div key={connector} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><code className="text-xs text-violet-200">{connector}</code><span className="md-badge">{index===0?'مرجعي':'تقني'}</span></div>)}</div></div></section>

  <section className="mt-8 rounded-3xl border border-white/10 p-6"><h2 className="text-2xl font-black">بوابة القبول قبل العميل الحقيقي</h2><p className="mt-2 text-sm text-slate-400">لا تعتبر المرحلة ناجحة ما لم تمر جميع النقاط التالية في تشغيل واحد.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{criteria.map((item,index)=><div key={item} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><span className="text-xs font-black text-violet-300">AC-{String(index+1).padStart(2,'0')}</span><p className="mt-2 font-bold leading-7">{item}</p></div>)}</div></section>

  <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">تشغيلات القبول</h2><p className="mt-2 text-sm text-slate-400">كل نتيجة محفوظة مع مدة التنفيذ وتفاصيل الفشل دون أي سر اتصال.</p></div><span className="md-badge">{runs.length} تشغيلات حديثة</span></div><div className="mt-5 space-y-5">{runs.map(run=>{const runChecks=checksByRun.get(run.id)||[],organization=run.organization_id?organizationById.get(run.organization_id):null;return <article key={run.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-sm font-bold ${statusClass(run.status)}`}>{run.status}</span><span className="md-badge">{run.suite_version}</span><span className="md-badge">موصل {run.connector_version}</span></div><h3 className="mt-3 text-xl font-black">{organization?organization.name:'تشغيل عام'} · {date(run.started_at)}</h3><p className="mt-2 text-xs text-slate-500">Run: {run.id}</p></div><div className="grid grid-cols-3 gap-2 text-center"><Metric label="الإجمالي" value={run.total_checks}/><Metric label="ناجح" value={run.passed_checks}/><Metric label="فاشل" value={run.failed_checks}/></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{runChecks.sort((a,b)=>a.check_key.localeCompare(b.check_key)).map(check=><details key={check.id} className="rounded-2xl border border-white/10 p-4"><summary className="flex cursor-pointer items-center justify-between gap-3"><span className="font-bold">{check.title}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusClass(check.status)}`}>{check.status} · {check.duration_ms}ms</span></summary>{check.error_message&&<p className="mt-3 rounded-xl border border-rose-300/20 bg-rose-300/[.05] p-3 text-sm text-rose-100">{check.error_code}: {check.error_message}</p>}<pre className="mt-3 overflow-x-auto whitespace-pre-wrap rounded-xl bg-black/20 p-3 text-left text-xs leading-6 text-slate-400" dir="ltr">{JSON.stringify(check.details,null,2)}</pre></details>)}</div><p className="mt-5 text-xs text-slate-500">اكتمل: {date(run.finished_at)}</p></article>})}{!runs.length&&<div className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-500">لم يُشغّل مختبر الجاهزية بعد.</div>}</div></section>
 </main>;
}

function Metric({label,value}:{label:string;value:number}){return <div className="min-w-20 rounded-xl border border-white/10 p-3"><strong className="block text-xl">{value}</strong><span className="text-xs text-slate-500">{label}</span></div>;}
