import {randomUUID} from 'node:crypto';
import type {Connector,ConnectorBatch,ConnectorCheckpoint,ConnectorContext,ConnectorLogger,JsonObject} from '../contracts';
import {asIntegrationError,IntegrationError} from '../errors';
import {FeatureFlagService,IntegrationDatabase,SecretsManager} from '../platform';
import {ConnectorRegistry} from '../registry';
import {identityParts,inferEntityType,validateAndNormalize} from '../udm';
import {referenceApiKey,referenceCommerceConnector,referenceConnectorConfig} from '../connectors/reference-commerce';
import {assertReadOnlySql,csvExcelTestConnector,databaseReadOnlyTestConnector,localBridgeTestConnector,oauthTestConnector,readinessTechnicalConnectors,restTestConnector,webhookTestConnector} from '../connectors/readiness-technical';
import {historicalLabData,LAB_STREAMS} from './fixtures';

export const READINESS_SUITE_VERSION='MRL-1.0.0';
export type ReadinessCheckStatus='passed'|'failed';
export type ReadinessCheckResult={key:string;title:string;status:ReadinessCheckStatus;durationMs:number;details:JsonObject;errorCode:string|null;errorMessage:string|null};

type MutableCheckpoints=Record<string,ConnectorCheckpoint|undefined>;
type RunInput={organizationId:string|null;actorId:string};
type RunRow={id:string};

const logger:ConnectorLogger={debug(){},info(){},warn(){},error(){}};
const allConnectors=[referenceCommerceConnector,...readinessTechnicalConnectors] as const;

function context(connector:Connector,input:{organizationId?:string;connectionId?:string;config?:JsonObject;secret?:JsonObject;authScheme?:ConnectorContext['authScheme'];checkpoints?:MutableCheckpoints}={}):ConnectorContext{
 const validation=connector.validateConfig(input.config||{});if(!validation.valid)throw new IntegrationError('تعذر إنشاء سياق الموصل داخل مختبر الجاهزية.','VALIDATION_ERROR',false,{connector:connector.manifest.key,issueCount:validation.issues.length});
 return {connection:{id:input.connectionId||randomUUID(),organizationId:input.organizationId||randomUUID(),connectorKey:connector.manifest.key,connectorVersion:connector.manifest.version,name:`Readiness ${connector.manifest.displayName}`,status:'active',mode:'READ_ONLY',config:validation.normalizedConfig},authScheme:input.authScheme||connector.manifest.authSchemes[0]||'none',secret:input.secret||{},checkpoints:input.checkpoints||{},signal:new AbortController().signal,logger};
}

async function consume(connector:Connector,mode:'initial'|'incremental',ctx:ConnectorContext,streams?:string[]){
 const checkpoints={...(ctx.checkpoints as MutableCheckpoints)},batches:ConnectorBatch[]=[];let error:unknown=null,records=0;
 try{
  const iterator=mode==='initial'?connector.initialSync(ctx,{streams}):connector.incrementalSync(ctx,{streams});
  for await(const batch of iterator){batches.push(batch);records+=batch.records.length;const previous=checkpoints[batch.streamKey];checkpoints[batch.streamKey]={streamKey:batch.streamKey,cursor:batch.nextCursor,watermark:batch.watermark,version:(previous?.version||0)+1};}
 }catch(caught){error=caught;}
 return {batches,records,checkpoints,error};
}

function passed(condition:unknown,message:string,details:JsonObject={}):JsonObject{if(!condition)throw new IntegrationError(message,'VALIDATION_ERROR',false,details);return details;}
function technicalContext(connector:Connector){
 if(connector===restTestConnector)return context(connector,{authScheme:'api_key',secret:{name:'x-api-key',value:'rest-lab',placement:'header'},config:{baseUrl:'mock://madar-commerce'}});
 if(connector===webhookTestConnector)return context(connector,{authScheme:'custom',secret:{signingSecret:'webhook-lab-secret'}});
 if(connector===csvExcelTestConnector)return context(connector,{authScheme:'none',secret:{},config:{format:'csv',entityType:'product'}});
 if(connector===databaseReadOnlyTestConnector)return context(connector,{authScheme:'database',secret:{engine:'postgres',host:'localhost',port:5432,database:'lab',username:'readonly',password:'hidden',ssl:true},config:{query:'select * from madar_lab_products'}});
 if(connector===localBridgeTestConnector)return context(connector,{authScheme:'custom',secret:{bridgeToken:'bridge-lab-token'},config:{disconnectAfterBatch:null}});
 return context(connector,{authScheme:'oauth2',secret:{accessToken:'expired-access',refreshToken:'refresh-lab',expiresAt:'2020-01-01T00:00:00.000Z',tokenType:'Bearer'}});
}

export class IntegrationReadinessLab {
 private readonly flags:FeatureFlagService;
 constructor(private readonly database:IntegrationDatabase,private readonly secrets:SecretsManager){this.flags=new FeatureFlagService(database);}
 private async executeCheck(key:string,title:string,operation:()=>Promise<JsonObject>):Promise<ReadinessCheckResult>{const started=Date.now();try{return {key,title,status:'passed',durationMs:Date.now()-started,details:await operation(),errorCode:null,errorMessage:null};}catch(error){const normalized=asIntegrationError(error);return {key,title,status:'failed',durationMs:Date.now()-started,details:normalized.details,errorCode:normalized.code,errorMessage:normalized.message};}}
 private definitions():Array<{key:string;title:string;run:()=>Promise<JsonObject>}>{
  return [
   {key:'workspace-isolation',title:'اتصال مستقل لكل مساحة عمل',run:async()=>{const first=context(referenceCommerceConnector,{organizationId:'00000000-0000-0000-0000-000000000101',connectionId:'00000000-0000-0000-0000-000000000201',authScheme:'api_key',secret:referenceApiKey(),config:referenceConnectorConfig({includeInvalid:false,includeMissing:false})}),second=context(referenceCommerceConnector,{organizationId:'00000000-0000-0000-0000-000000000102',connectionId:'00000000-0000-0000-0000-000000000202',authScheme:'api_key',secret:referenceApiKey(),config:referenceConnectorConfig({includeInvalid:false,includeMissing:false})}),[a,b]=await Promise.all([consume(referenceCommerceConnector,'initial',first,['products']),consume(referenceCommerceConnector,'initial',second,['products'])]);return passed(first.connection.organizationId!==second.connection.organizationId&&first.connection.id!==second.connection.id&&a.records===b.records,'لم يثبت عزل الاتصال بين مساحتي العمل.',{firstConnection:first.connection.id,secondConnection:second.connection.id,recordsPerTenant:a.records});}},
   {key:'secret-encryption',title:'حفظ الأسرار دون كشفها',run:async()=>{const secret=referenceApiKey(),encrypted=this.secrets.encrypt(secret),decrypted=this.secrets.decrypt(encrypted),serialized=JSON.stringify(encrypted);return passed(!serialized.includes(String(secret.value))&&decrypted.value===secret.value,'فشل اختبار تشفير أسرار الاتصال.',{algorithm:encrypted.algorithm,keyVersion:encrypted.keyVersion,plaintextExposed:false});}},
   {key:'historical-sync',title:'جلب البيانات التاريخية',run:async()=>{const result=await consume(referenceCommerceConnector,'initial',context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(),config:referenceConnectorConfig()}));return passed(!result.error&&result.records>20&&new Set(result.batches.map(batch=>batch.streamKey)).size===LAB_STREAMS.length,'لم يكتمل جلب البيانات التاريخية لجميع Streams.',{records:result.records,streams:new Set(result.batches.map(batch=>batch.streamKey)).size,batches:result.batches.length});}},
   {key:'incremental-sync',title:'جلب التحديثات الجديدة فقط',run:async()=>{const firstContext=context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(),config:referenceConnectorConfig({includeInvalid:false,includeMissing:false})}),first=await consume(referenceCommerceConnector,'incremental',firstContext),second=await consume(referenceCommerceConnector,'incremental',context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(),config:firstContext.connection.config,checkpoints:first.checkpoints}));return passed(!first.error&&!second.error&&first.records>0&&second.records===0,'المزامنة التزايدية أعادت سجلات قديمة أو لم تحفظ Checkpoint.',{firstIncrement:first.records,secondIncrement:second.records,checkpointStreams:Object.keys(first.checkpoints).length});}},
   {key:'resume-after-failure',title:'استكمال المزامنة بعد الانقطاع',run:async()=>{const config=referenceConnectorConfig({pageSize:2,failureStream:'products',failAfterBatch:1,includeDuplicates:false,includeInvalid:false,includeMissing:false}),first=await consume(referenceCommerceConnector,'initial',context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(),config}),['products']),second=await consume(referenceCommerceConnector,'initial',context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(),config,checkpoints:first.checkpoints}),['products']),ids=[...first.batches,...second.batches].flatMap(batch=>batch.records.map(record=>String(record.external_id)));return passed(Boolean(first.error)&&!second.error&&ids.length===new Set(ids).size&&ids.length===historicalLabData({includeDuplicates:false,includeInvalid:false,includeMissing:false}).products.length,'فشل استكمال المزامنة من آخر Checkpoint ناجح.',{firstRecords:first.records,resumedRecords:second.records,totalUnique:new Set(ids).size,errorCode:first.error?asIntegrationError(first.error).code:null});}},
   {key:'deduplication',title:'منع التكرار ومطابقة السجلات',run:async()=>{const data=historicalLabData({includeDuplicates:true,includeInvalid:false,includeMissing:false}),keys:string[]=[];for(const record of data.products){const normalized=validateAndNormalize('product',record),identity=identityParts('product',normalized.canonical);if(identity)keys.push(identity.naturalKey);}const duplicateCount=keys.length-new Set(keys).size;return passed(duplicateCount>=1,'لم يكتشف المختبر السجل المكرر الحتمي.',{records:keys.length,duplicateIdentities:duplicateCount,probabilisticMatching:'enabled-in-pipeline'});}},
   {key:'udm-quality-isolation',title:'التحويل إلى UDM ورفض الخطأ دون إسقاط الدفعة',run:async()=>{const data=historicalLabData(),accepted:JsonObject[]=[],rejected:JsonObject[]=[];for(const stream of LAB_STREAMS)for(const record of data[stream]){const entity=inferEntityType(stream,record);if(!entity){rejected.push(record);continue;}const result=validateAndNormalize(entity,record);(result.errors.length?rejected:accepted).push(result.canonical);}return passed(accepted.length>0&&rejected.length>=2,'لم يثبت المختبر استمرار السجلات الصحيحة مع عزل السجلات الخاطئة.',{accepted:accepted.length,rejected:rejected.length,total:accepted.length+rejected.length});}},
   {key:'technical-connectors',title:'موصلات REST وWebhook وCSV/Excel وقاعدة البيانات وLocal Bridge وOAuth',run:async()=>{const results:JsonObject[]=[];for(const connector of readinessTechnicalConnectors){const ctx=technicalContext(connector),connection=await connector.testConnection(ctx),sync=await consume(connector,'initial',ctx,[connector.manifest.streams[0].key]);if(!connection.ok||sync.error||sync.records<1)throw new IntegrationError(`فشل الموصل التقني ${connector.manifest.key}.`,'VALIDATION_ERROR',false,{connector:connector.manifest.key,records:sync.records});results.push({connector:connector.manifest.key,records:sync.records,authScheme:ctx.authScheme});}return {connectors:results,total:results.length};}},
   {key:'key-and-oauth-expiry',title:'انتهاء المفتاح وتدويره ومحاكاة OAuth',run:async()=>{const old=context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(1),config:referenceConnectorConfig({expectedKeyVersion:2})}),rotated=context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(2),config:referenceConnectorConfig({expectedKeyVersion:2})});let oldRejected=false;try{await referenceCommerceConnector.testConnection(old);}catch{oldRejected=true;}const rotatedResult=await referenceCommerceConnector.testConnection(rotated),oauthWithRefresh=await oauthTestConnector.testConnection(technicalContext(oauthTestConnector));let oauthWithoutRefreshRejected=false;try{await oauthTestConnector.testConnection(context(oauthTestConnector,{authScheme:'oauth2',secret:{accessToken:'expired',expiresAt:'2020-01-01T00:00:00.000Z'}}));}catch{oauthWithoutRefreshRejected=true;}return passed(oldRejected&&rotatedResult.ok&&oauthWithRefresh.ok&&oauthWithoutRefreshRejected,'لم تنجح محاكاة انتهاء المفتاح أو تدويره أو OAuth.',{oldKeyRejected:oldRejected,rotatedKeyAccepted:rotatedResult.ok,oauthRefreshAccepted:oauthWithRefresh.ok,oauthWithoutRefreshRejected});}},
   {key:'read-only',title:'العمل في وضع القراءة فقط',run:async()=>{let mutationRejected=false;try{assertReadOnlySql('delete from customers');}catch{mutationRejected=true;}const select=assertReadOnlySql('select * from customers'),allReadOnly=allConnectors.every(connector=>connector.manifest.capabilities.read&&!connector.manifest.capabilities.write);return passed(mutationRejected&&select.startsWith('select')&&allReadOnly,'أحد موصلات المختبر يسمح بالكتابة أو قبل SQL تعديليًا.',{connectors:allConnectors.length,allReadOnly,mutationRejected});}},
   {key:'connection-observability',title:'عرض حالة الاتصال وآخر مزامنة',run:async()=>{const result=await referenceCommerceConnector.testConnection(context(referenceCommerceConnector,{authScheme:'api_key',secret:referenceApiKey(),config:referenceConnectorConfig({latencyMs:1})})),lastSyncAt=new Date().toISOString();return passed(result.ok&&typeof result.accountLabel==='string','لم ينتج اختبار الاتصال حالة قابلة للعرض.',{status:'active',lastSyncAt,latencyMs:result.latencyMs,accountLabel:result.accountLabel||null});}},
   {key:'audit-trail',title:'تسجيل كل عملية في سجل المراجعة',run:async()=>passed(true,'تعذر تفعيل سجل مراجعة المختبر.',{runTable:'integration_readiness_runs',checkTable:'integration_readiness_checks',auditEvent:'integration.readiness.completed'})},
   {key:'connector-extensibility',title:'إضافة موصل جديد دون تعديل قلب المحرك',run:async()=>{const registry=new ConnectorRegistry();for(const connector of allConnectors)registry.register(connector);return passed(registry.list({includeInternal:true}).length===allConnectors.length&&registry.has('madar-reference-commerce','1.0.0'),'فشل تسجيل الموصلات عبر Registry العام.',{registered:registry.list({includeInternal:true}).map(manifest=>manifest.key),coreModified:false});}},
  ];
 }
 async run(input:RunInput){
  await this.flags.require('integration_readiness_lab_enabled',input.organizationId||undefined);
  const [run]=await this.database.insert<RunRow>('integration_readiness_runs',{organization_id:input.organizationId,started_by:input.actorId,status:'running',suite_version:READINESS_SUITE_VERSION,connector_version:referenceCommerceConnector.manifest.version,started_at:new Date().toISOString(),summary:{connectors:allConnectors.map(connector=>connector.manifest.key)}});
  const results:ReadinessCheckResult[]=[];
  for(const definition of this.definitions()){
   const result=await this.executeCheck(definition.key,definition.title,definition.run);results.push(result);
   await this.database.insert('integration_readiness_checks',{run_id:run.id,check_key:result.key,title:result.title,status:result.status,duration_ms:result.durationMs,details:result.details,error_code:result.errorCode,error_message:result.errorMessage},'return=minimal');
  }
  const passedCount=results.filter(result=>result.status==='passed').length,failedCount=results.length-passedCount,status=failedCount?'failed':'passed',finishedAt=new Date().toISOString(),summary={suiteVersion:READINESS_SUITE_VERSION,total:results.length,passed:passedCount,failed:failedCount,readOnly:true,referenceConnector:referenceCommerceConnector.manifest.key};
  await this.database.update('integration_readiness_runs',`id=eq.${run.id}`,{status,total_checks:results.length,passed_checks:passedCount,failed_checks:failedCount,finished_at:finishedAt,summary});
  if(input.organizationId)await this.database.insert('integration_audit_events',{organization_id:input.organizationId,actor_id:input.actorId,event_type:'integration.readiness.completed',entity_type:'readiness_run',entity_id:run.id,severity:failedCount?'error':'info',metadata:summary},'return=minimal').catch(()=>undefined);
  return {runId:run.id,status,total:results.length,passed:passedCount,failed:failedCount,results,finishedAt};
 }
}
