'use client';

import {useState} from 'react';

export default function StudentAssistant({organizationId}:{organizationId:string}){
 const[mode,setMode]=useState('PLAN'),[prompt,setPrompt]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();setPending(true);setError('');setAnswer('');try{const response=await fetch('/api/student/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,mode,prompt})});const data=await response.json();if(!response.ok)throw new Error(data.error);setAnswer(data.text);}catch(e){setError(e instanceof Error?e.message:'تعذر تشغيل المساعد.');}finally{setPending(false)}}
 return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={submit} className="grid gap-3"><select value={mode} onChange={e=>setMode(e.target.value)} className="field rounded-xl p-3"><option value="PLAN">خطة مذاكرة ذكية</option><option value="SUMMARY">تلخيص أكاديمي</option><option value="QUIZ">أسئلة مراجعة</option><option value="EXPLAIN">شرح مفهوم</option></select><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} required minLength={10} maxLength={12000} rows={8} className="field rounded-xl p-3" placeholder="ألصق النص أو اكتب المواد والمهام والوقت المتاح…"/><p className="text-xs leading-6 text-slate-400">لا تضع معلومات شخصية حساسة. لا تُرسل ملفاتك تلقائيًا؛ أنت تختار النص الذي تريد تحليله.</p><button disabled={pending} className="rounded-xl bg-gradient-to-l from-violet-500 to-emerald-400 p-3 font-black text-white disabled:opacity-50">{pending?'يعمل مساعد مَدار…':'إنشاء النتيجة'}</button>{error&&<p role="alert" className="rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}</form><article className="min-h-72 whitespace-pre-wrap rounded-2xl border border-violet-300/20 bg-slate-950/60 p-5 leading-8 text-slate-100">{answer||<span className="text-slate-500">ستظهر الخطة أو الملخص أو أسئلة المراجعة هنا.</span>}</article></div>
}
