'use client';

import {useActionState,useEffect,useState} from 'react';
import {addCourse,addEvent,addGoal,addNote,addSchedule,addStudySession,addTask,uploadStudentPdf,type StudentState} from '@/app/actions/student';

type Course={id:string;name:string};
const initial:StudentState={};
const field='field w-full rounded-xl p-3';
function Message({state}:{state:StudentState}){return <>{state.error&&<p role="alert" className="rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{state.error}</p>}{state.success&&<p className="rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-200">{state.success}</p>}</>}
function Submit({pending,label}:{pending:boolean;label:string}){return <button disabled={pending} className="rounded-xl bg-[#70E4D4] p-3 font-black text-slate-950 transition hover:-translate-y-0.5 disabled:opacity-50">{pending?'جارٍ الحفظ…':label}</button>}
function CourseSelect({courses}:{courses:Course[]}){return <select name="course_id" className={field}><option value="">دون ربط بمقرر</option>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}

export function CourseForm({org}:{org:string}){const[s,a,p]=useActionState(addCourse,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><div className="grid gap-3 sm:grid-cols-2"><input name="name" required className={field} placeholder="اسم المقرر"/><input name="code" className={field} placeholder="رمز المقرر"/></div><div className="grid grid-cols-2 gap-3"><input name="credits" type="number" min="0.5" max="30" step="0.5" required className={field} placeholder="الساعات"/><input name="grade" type="number" min="0" max="100" step="0.01" required className={field} placeholder="الدرجة الحالية"/></div><div className="grid gap-3 sm:grid-cols-2"><input name="target_grade" type="number" min="0" max="100" className={field} placeholder="الدرجة المستهدفة"/><input name="instructor" className={field} placeholder="اسم المدرس"/></div><div className="grid grid-cols-[1fr_auto] gap-3"><input name="semester" className={field} placeholder="الفصل الدراسي"/><input name="color" type="color" defaultValue="#6C3BFF" className="h-12 w-16 rounded-xl bg-slate-900 p-1" aria-label="لون المقرر"/></div><Submit pending={p} label="إضافة المقرر"/><Message state={s}/></form>}

export function TaskForm({org,courses}:{org:string;courses:Course[]}){const[s,a,p]=useActionState(addTask,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="عنوان المهمة"/><textarea name="description" rows={2} className={field} placeholder="تفاصيل مختصرة"/><CourseSelect courses={courses}/><div className="grid gap-3 sm:grid-cols-2"><select name="priority" className={field}><option value="LOW">أولوية منخفضة</option><option value="MEDIUM">أولوية متوسطة</option><option value="HIGH">أولوية عالية</option></select><input name="due_at" type="datetime-local" className={field} aria-label="موعد التسليم"/></div><label className="text-sm text-slate-300">ذكّرني في<input name="reminder_at" type="datetime-local" className={`${field} mt-1`}/></label><Submit pending={p} label="إضافة المهمة"/><Message state={s}/></form>}

export function NoteForm({org}:{org:string}){const[s,a,p]=useActionState(addNote,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="عنوان الملاحظة"/><textarea name="content" required maxLength={5000} rows={5} className={field} placeholder="اكتب أفكارك أو ملخص المحاضرة…"/><input name="tags" className={field} placeholder="وسوم مفصولة بفواصل"/><div className="grid grid-cols-2 gap-3"><select name="color" className={field}><option value="amber">ذهبي</option><option value="violet">بنفسجي</option><option value="emerald">أخضر</option><option value="blue">أزرق</option></select><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3"><input name="is_pinned" type="checkbox"/> تثبيت</label></div><Submit pending={p} label="حفظ الملاحظة"/><Message state={s}/></form>}

export function ScheduleForm({org,courses}:{org:string;courses:Course[]}){const[s,a,p]=useActionState(addSchedule,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="المحاضرة أو جلسة المذاكرة"/><CourseSelect courses={courses}/><div className="grid grid-cols-2 gap-3"><select name="weekday" className={field}>{['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map((x,i)=><option key={x} value={i}>{x}</option>)}</select><select name="kind" className={field}><option value="LECTURE">محاضرة</option><option value="LAB">تطبيقي</option><option value="STUDY">مذاكرة</option><option value="OTHER">أخرى</option></select></div><div className="grid grid-cols-2 gap-3"><input name="starts_at" type="time" required className={field}/><input name="ends_at" type="time" required className={field}/></div><input name="location" className={field} placeholder="القاعة أو المكان"/><Submit pending={p} label="إضافة إلى الجدول"/><Message state={s}/></form>}

export function EventForm({org,courses}:{org:string;courses:Course[]}){const[s,a,p]=useActionState(addEvent,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="اختبار، تسليم أو عرض"/><CourseSelect courses={courses}/><div className="grid gap-3 sm:grid-cols-2"><select name="kind" className={field}><option value="EXAM">اختبار</option><option value="ASSIGNMENT">واجب</option><option value="PRESENTATION">عرض</option><option value="DEADLINE">موعد نهائي</option><option value="OTHER">أخرى</option></select><input name="starts_at" required type="datetime-local" className={field}/></div><input name="reminder_at" type="datetime-local" className={field} aria-label="موعد التذكير"/><input name="location" className={field} placeholder="المكان"/><textarea name="notes" rows={2} className={field} placeholder="ملاحظات الاستعداد"/><Submit pending={p} label="حفظ الموعد"/><Message state={s}/></form>}

export function StudySessionForm({org,courses}:{org:string;courses:Course[]}){const[s,a,p]=useActionState(addStudySession,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="عنوان جلسة المذاكرة"/><CourseSelect courses={courses}/><div className="grid grid-cols-3 gap-3"><input name="minutes" required type="number" min="1" max="1440" className={field} placeholder="دقيقة"/><input name="studied_on" required type="date" defaultValue={new Date().toISOString().slice(0,10)} className={field}/><select name="focus_score" className={field} aria-label="درجة التركيز"><option value="">التركيز</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></div><textarea name="notes" rows={2} className={field} placeholder="ما الذي أنجزته؟"/><Submit pending={p} label="تسجيل الجلسة"/><Message state={s}/></form>}

export function GoalForm({org}:{org:string}){const[s,a,p]=useActionState(addGoal,initial);return <form action={a} className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="مثال: مذاكرة إدارة العمليات"/><div className="grid grid-cols-3 gap-3"><input name="target_value" required type="number" min="1" className={field} placeholder="الهدف"/><input name="unit" required defaultValue="ساعة" className={field}/><input name="deadline" type="date" className={field}/></div><Submit pending={p} label="إضافة الهدف"/><Message state={s}/></form>}

export function PdfForm({org}:{org:string}){const[s,a,p]=useActionState(uploadStudentPdf,initial);return <form action={a} encType="multipart/form-data" className="grid gap-3"><input type="hidden" name="organization_id" value={org}/><input name="title" required className={field} placeholder="عنوان الملزمة أو المرجع"/><div className="grid gap-3 sm:grid-cols-2"><input name="subject" className={field} placeholder="المادة"/><select name="category" className={field}><option value="SUMMARY">ملخص</option><option value="HANDOUT">ملزمة</option><option value="BOOK">كتاب</option><option value="RESEARCH">بحث</option><option value="REFERENCE">مرجع</option></select></div><textarea name="description" rows={2} className={field} placeholder="وصف مختصر"/><input name="file" type="file" accept="application/pdf" required className="rounded-xl border border-white/10 p-3"/><Submit pending={p} label="إضافة إلى الرف"/><Message state={s}/></form>}

export function StudyTimer(){const[seconds,setSeconds]=useState(25*60),[running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>window.clearInterval(id)},[running]);return <div className="text-center"><p className="font-mono text-5xl font-black text-[#70E4D4]">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</p><div className="mt-4 flex justify-center gap-2"><button type="button" onClick={()=>setRunning(v=>!v)} className="rounded-xl bg-violet-500 px-5 py-2 font-bold">{running?'إيقاف':'ابدأ التركيز'}</button><button type="button" onClick={()=>{setRunning(false);setSeconds(25*60)}} className="rounded-xl border border-white/20 px-5 py-2">إعادة</button></div></div>}
