/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link';
import {requireUser} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import {deleteDocument,deleteStudentItem,ensureStudentWorkspace,toggleDocumentFavorite,toggleTask} from '@/app/actions/student';
import {CourseForm,EventForm,GoalForm,NoteForm,PdfForm,ScheduleForm,StudySessionForm,StudyTimer,TaskForm} from './forms';
import StudentAssistant from './assistant';

export const dynamic='force-dynamic';
const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const priority:{[key:string]:string}={HIGH:'عالية',MEDIUM:'متوسطة',LOW:'منخفضة'};
const eventKinds:{[key:string]:string}={EXAM:'اختبار',ASSIGNMENT:'واجب',PRESENTATION:'عرض',DEADLINE:'موعد نهائي',OTHER:'أخرى'};
const category:{[key:string]:string}={SUMMARY:'ملخص',HANDOUT:'ملزمة',BOOK:'كتاب',RESEARCH:'بحث',REFERENCE:'مرجع'};

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;sort?:string;subject?:string}>}){
 const user=await requireUser(),params=await searchParams;
 const members=await supabaseFetch(`/rest/v1/organization_members?user_id=eq.${user.id}&select=organization_id,organizations(id,name,type,status)&order=created_at.asc`);
 const workspace=members?.map((x:any)=>x.organizations).find((x:any)=>x?.type==='STUDENT'&&x.status==='active');
 if(!workspace)return <CreateStudentSpace/>;
 const org=workspace.id;
 await supabaseFetch('/rest/v1/rpc/sync_student_reminders',{method:'POST',body:JSON.stringify({target_organization:org})}).catch(()=>null);
 const[courses,tasks,notes,schedule,allDocuments,events,sessions,goals,aiHistory]=await Promise.all([
  supabaseFetch(`/rest/v1/student_courses?organization_id=eq.${org}&select=*&order=created_at.desc`),
  supabaseFetch(`/rest/v1/student_tasks?organization_id=eq.${org}&select=*,student_courses(name,color)&order=is_done.asc,due_at.asc.nullslast`),
  supabaseFetch(`/rest/v1/student_notes?organization_id=eq.${org}&select=*&order=is_pinned.desc,updated_at.desc`),
  supabaseFetch(`/rest/v1/student_schedule?organization_id=eq.${org}&select=*,student_courses(name,color)&order=weekday.asc,starts_at.asc`),
  supabaseFetch(`/rest/v1/student_documents?organization_id=eq.${org}&select=*&order=created_at.desc`),
  supabaseFetch(`/rest/v1/student_events?organization_id=eq.${org}&select=*,student_courses(name,color)&order=starts_at.asc`),
  supabaseFetch(`/rest/v1/student_study_sessions?organization_id=eq.${org}&select=*,student_courses(name,color)&order=studied_on.desc,created_at.desc&limit=30`),
  supabaseFetch(`/rest/v1/student_goals?organization_id=eq.${org}&select=*&order=is_done.asc,deadline.asc.nullslast`),
  supabaseFetch(`/rest/v1/student_ai_history?organization_id=eq.${org}&select=id,mode,prompt_excerpt,response,created_at&order=created_at.desc&limit=5`)
 ]);
 const credits=courses.reduce((n:number,x:any)=>n+Number(x.credits),0),average=credits?courses.reduce((n:number,x:any)=>n+Number(x.grade)*Number(x.credits),0)/credits:null;
 const weekMinutes=sessions.filter((x:any)=>+new Date()-new Date(x.studied_on).getTime()<7*86400000).reduce((n:number,x:any)=>n+x.minutes,0);
 const upcoming=events.filter((x:any)=>new Date(x.starts_at)>=new Date()).slice(0,5);
 const q=String(params.q||'').trim().toLowerCase(),subject=String(params.subject||''),sort=params.sort||'date-desc';
 let documents=allDocuments.filter((x:any)=>(!q||`${x.title} ${x.subject||''} ${x.original_filename}`.toLowerCase().includes(q))&&(!subject||x.subject===subject));
 documents=[...documents].sort((a:any,b:any)=>sort==='name'?a.title.localeCompare(b.title,'ar'):sort==='size-desc'?b.file_size-a.file_size:sort==='size-asc'?a.file_size-b.file_size:sort==='date-asc'?+new Date(a.created_at)-+new Date(b.created_at):+new Date(b.created_at)-+new Date(a.created_at));
 const subjects=[...new Set(allDocuments.map((x:any)=>x.subject).filter(Boolean))] as string[];
 return <main className="mx-auto max-w-7xl p-4 py-8 sm:p-6">
  <header className="overflow-hidden rounded-[2rem] bg-gradient-to-l from-violet-700 via-indigo-700 to-emerald-600 p-7 shadow-2xl sm:p-10"><p className="font-bold text-white/75">مساهمة مَدار المجتمعية · مجانية لكل حساب</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">مساحة الطالب · {workspace.name}</h1><p className="mt-4 max-w-3xl leading-8 text-white/85">مركز جامعي خاص يجمع معدلك ومقرراتك ومكتبتك ومواعيدك وتركيزك وأهدافك، مع مساعد مَدار الذكي.</p><nav className="mt-6 flex flex-wrap gap-2 text-sm font-bold">{[['overview','نظرة عامة'],['courses','المقررات'],['tasks','المهام'],['library','المكتبة'],['calendar','الجدول والمواعيد'],['notes','الملاحظات'],['focus','التركيز والأهداف'],['ai','مساعد مَدار']].map(x=><a key={x[0]} href={`#${x[0]}`} className="rounded-full bg-white/10 px-4 py-2 backdrop-blur hover:bg-white/20">{x[1]}</a>)}</nav></header>
  <section id="overview" className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat label="المعدل الموزون" value={average===null?'—':`${average.toFixed(2)}%`} accent/><Stat label="المقررات" value={courses.length}/><Stat label="المهام المتبقية" value={tasks.filter((x:any)=>!x.is_done).length}/><Stat label="مذاكرة آخر 7 أيام" value={`${Math.round(weekMinutes/60*10)/10} ساعة`}/><Stat label="المراجع" value={allDocuments.length}/></section>
  {upcoming.length>0&&<section className="mt-6 rounded-3xl border border-amber-300/20 bg-amber-300/5 p-5"><h2 className="text-xl font-black text-amber-200">القادم في تقويمك</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{upcoming.map((x:any)=><div key={x.id} className="rounded-xl bg-white/5 p-3"><b>{eventKinds[x.kind]} · {x.title}</b><p className="mt-1 text-sm text-slate-300">{formatDate(x.starts_at)} {x.student_courses?.name&&`· ${x.student_courses.name}`}</p></div>)}</div></section>}
  <div className="mt-6 grid gap-6 lg:grid-cols-2">
   <Panel id="courses" title="المقررات وحساب المعدل" description="معدل موزون بالساعات مع الدرجة الحالية والمستهدفة."><CourseForm org={org}/><List empty="لم تضف مقررات بعد.">{courses.map((x:any)=><Item key={x.id} color={x.color}><div><b>{x.name}</b><p className="text-sm text-slate-400">{x.code||'دون رمز'} · {x.credits} ساعة {x.instructor&&`· ${x.instructor}`}</p></div><div className="text-left"><b>{x.grade}%</b>{x.target_grade&&<p className="text-xs text-[#70E4D4]">الهدف {x.target_grade}%</p>}</div><Delete org={org} id={x.id} table="student_courses"/></Item>)}</List></Panel>
   <Panel id="tasks" title="المهام والتذكيرات" description="أولوية وموعد تسليم وتنبيه يظهر في مركز إشعاراتك."><TaskForm org={org} courses={courses}/><List empty="لا توجد مهام معلقة.">{tasks.map((x:any)=><form action={toggleTask} key={x.id} className="flex items-start gap-3 rounded-xl bg-white/5 p-3"><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={x.id}/><input type="hidden" name="is_done" value={String(x.is_done)}/><button aria-label="تغيير حالة المهمة" className={`mt-1 grid h-7 w-7 shrink-0 place-items-center rounded-full border ${x.is_done?'bg-emerald-400 text-black':'border-white/30'}`}>{x.is_done?'✓':''}</button><div className="min-w-0 flex-1"><b className={x.is_done?'text-slate-500 line-through':''}>{x.title}</b><p className="text-xs text-slate-400">{priority[x.priority]} {x.student_courses?.name&&`· ${x.student_courses.name}`} {x.due_at&&`· ${formatDate(x.due_at)}`}</p></div></form>)}</List></Panel>
  </div>
  <Panel id="library" title="مكتبة الطالب" description="ملازم وملخصات وكتب PDF خاصة، مرتبة على رفوف رقمية."><PdfForm org={org}/><form className="mt-6 grid gap-3 rounded-2xl bg-white/5 p-4 sm:grid-cols-4"><input name="q" defaultValue={params.q} className="field rounded-xl p-3" placeholder="ابحث بالاسم أو المادة"/><select name="subject" defaultValue={subject} className="field rounded-xl p-3"><option value="">كل المواد</option>{subjects.map(x=><option key={x}>{x}</option>)}</select><select name="sort" defaultValue={sort} className="field rounded-xl p-3"><option value="date-desc">الأحدث</option><option value="date-asc">الأقدم</option><option value="name">حسب الاسم</option><option value="size-desc">الحجم: الأكبر</option><option value="size-asc">الحجم: الأصغر</option></select><button className="rounded-xl bg-white px-4 py-3 font-black text-slate-950">تطبيق التصفية</button></form><div className="mt-7 border-b-8 border-amber-950/70 pb-3"><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{documents.map((x:any)=><article key={x.id} className="group relative flex aspect-[3/4] flex-col justify-between rounded-r-md rounded-l-2xl border-r-8 border-amber-300 bg-gradient-to-br from-violet-700 to-slate-950 p-4 shadow-xl transition hover:-translate-y-2"><span className="text-xs text-white/60">{category[x.category]} · {x.subject||'عام'}</span><strong className="line-clamp-4">{x.title}</strong><div><span className="block text-xs text-white/60">{formatBytes(x.file_size)} · {new Date(x.created_at).toLocaleDateString('ar-YE')}</span><a href={`/student/documents/${x.id}`} target="_blank" className="mt-2 inline-block text-sm font-bold text-[#70E4D4]">فتح PDF</a></div><div className="absolute left-2 top-2 flex gap-1"><form action={toggleDocumentFavorite}><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={x.id}/><input type="hidden" name="is_favorite" value={String(x.is_favorite)}/><button aria-label="المفضلة" className="rounded-full bg-black/40 p-2">{x.is_favorite?'★':'☆'}</button></form><form action={deleteDocument}><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={x.id}/><button aria-label="حذف الملف" className="rounded-full bg-black/40 p-2 text-red-200">×</button></form></div></article>)}</div>{documents.length===0&&<p className="py-12 text-center text-slate-400">لا توجد ملفات مطابقة.</p>}</div></Panel>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel id="calendar" title="الجدول الأسبوعي"><ScheduleForm org={org} courses={courses}/><List empty="الجدول فارغ.">{schedule.map((x:any)=><Item key={x.id} color={x.student_courses?.color}><div><b>{days[x.weekday]} · {String(x.starts_at).slice(0,5)}–{String(x.ends_at).slice(0,5)}</b><p className="text-sm text-slate-400">{x.title}{x.location?` · ${x.location}`:''}</p></div><Delete org={org} id={x.id} table="student_schedule"/></Item>)}</List><h3 className="mb-3 mt-8 text-xl font-black">الاختبارات والمواعيد النهائية</h3><EventForm org={org} courses={courses}/><List empty="لا توجد مواعيد.">{events.map((x:any)=><Item key={x.id} color={x.student_courses?.color}><div><b>{eventKinds[x.kind]} · {x.title}</b><p className="text-sm text-slate-400">{formatDate(x.starts_at)} {x.location&&`· ${x.location}`}</p></div><Delete org={org} id={x.id} table="student_events"/></Item>)}</List></Panel>
  <Panel id="notes" title="دفتر الملاحظات"><NoteForm org={org}/><div className="mt-5 grid gap-3 sm:grid-cols-2">{notes.map((x:any)=><article key={x.id} className={`${noteColor(x.color)} relative rounded-2xl p-4 text-slate-950 shadow`}><div className="flex items-start justify-between"><h3 className="font-black">{x.is_pinned&&'📌 '}{x.title}</h3><Delete org={org} id={x.id} table="student_notes" dark/></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{x.content}</p>{x.tags?.length>0&&<div className="mt-3 flex flex-wrap gap-1">{x.tags.map((t:string)=><span key={t} className="rounded-full bg-black/10 px-2 py-1 text-xs">#{t}</span>)}</div>}</article>)}</div></Panel></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel id="focus" title="التركيز وسجل المذاكرة"><StudyTimer/><div className="mt-7"><StudySessionForm org={org} courses={courses}/></div><List empty="لم تسجل جلسات بعد.">{sessions.map((x:any)=><Item key={x.id} color={x.student_courses?.color}><div><b>{x.title}</b><p className="text-sm text-slate-400">{x.minutes} دقيقة · تركيز {x.focus_score||'—'}/5 · {x.studied_on}</p></div><Delete org={org} id={x.id} table="student_study_sessions"/></Item>)}</List></Panel><Panel title="الأهداف الدراسية"><GoalForm org={org}/><List empty="أضف هدفك الدراسي الأول.">{goals.map((x:any)=>{const percent=Math.min(100,Math.round(x.current_value/x.target_value*100));return <Item key={x.id}><div className="w-full"><div className="flex justify-between"><b>{x.title}</b><span>{x.current_value}/{x.target_value} {x.unit}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-emerald-400" style={{width:`${percent}%`}}/></div></div><Delete org={org} id={x.id} table="student_goals"/></Item>})}</List></Panel></div>
  <Panel id="ai" title="مساعد مَدار الذكي" description="خطط مذاكرة وتلخيص وشرح وأسئلة مراجعة بالعربية، مع حفظ آخر النتائج في مساحتك."><StudentAssistant organizationId={org}/>{aiHistory.length>0&&<details className="mt-6 rounded-2xl bg-white/5 p-4"><summary className="cursor-pointer font-bold">آخر نتائج المساعد</summary><div className="mt-4 grid gap-3">{aiHistory.map((x:any)=><article key={x.id} className="rounded-xl border border-white/10 p-4"><p className="text-xs text-[#70E4D4]">{x.mode} · {formatDate(x.created_at)}</p><b className="mt-1 block">{x.prompt_excerpt}</b><p className="mt-2 line-clamp-5 whitespace-pre-wrap text-sm text-slate-300">{x.response}</p></article>)}</div></details>}</Panel>
 </main>;
}

function CreateStudentSpace(){return <main className="mx-auto max-w-2xl p-6 py-16"><section className="rounded-[2rem] border border-violet-300/20 bg-gradient-to-br from-violet-700/30 to-emerald-500/10 p-8 text-center"><span className="text-6xl">🎓</span><h1 className="mt-5 text-4xl font-black">مساحة الطالب المجانية</h1><p className="mt-4 leading-8 text-slate-300">متاحة لكل حساب في مَدار، بما في ذلك حساب المالك وأصحاب المساحات التجارية. تنشأ كمساحة مستقلة ولا تؤثر على نشاطك الحالي.</p><form action={ensureStudentWorkspace}><button className="mt-7 rounded-xl bg-[#70E4D4] px-7 py-4 font-black text-slate-950">إنشاء مساحتي الجامعية</button></form><Link href="/account" className="mt-5 block text-sm text-slate-400">العودة إلى حسابي</Link></section></main>}
function Panel({id,title,description,children}:{id?:string;title:string;description?:string;children:React.ReactNode}){return <section id={id} className="mt-6 scroll-mt-24 rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><h2 className="text-2xl font-black">{title}</h2>{description&&<p className="mb-5 mt-2 leading-7 text-slate-400">{description}</p>}{!description&&<div className="h-5"/>}{children}</section>}
function Stat({label,value,accent}:{label:string;value:string|number;accent?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><span className="text-sm text-slate-400">{label}</span><p className={`mt-2 text-3xl font-black ${accent?'text-[#70E4D4]':''}`}>{value}</p></div>}
function List({empty,children}:{empty:string;children:React.ReactNode[]}){return <div className="mt-5 space-y-2">{children.length?children:<p className="rounded-xl bg-white/5 p-4 text-center text-sm text-slate-500">{empty}</p>}</div>}
function Item({color,children}:{color?:string;children:React.ReactNode}){return <div className="flex items-center gap-3 rounded-xl bg-white/5 p-3" style={{borderInlineStart:`4px solid ${color||'#334155'}`}}>{children}</div>}
function Delete({org,id,table,dark}:{org:string;id:string;table:string;dark?:boolean}){return <form action={deleteStudentItem} className="mr-auto"><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="id" value={id}/><input type="hidden" name="table" value={table}/><button aria-label="حذف" className={`rounded-lg px-2 py-1 text-sm ${dark?'text-red-800':'text-red-300'}`}>حذف</button></form>}
function formatBytes(n:number){if(n<1024*1024)return `${Math.ceil(n/1024)} ك.ب`;return `${(n/1024/1024).toFixed(1)} م.ب`}
function formatDate(value:string){return new Intl.DateTimeFormat('ar-YE',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Aden'}).format(new Date(value))}
function noteColor(value:string){return value==='violet'?'bg-violet-200':value==='emerald'?'bg-emerald-200':value==='blue'?'bg-blue-200':'bg-amber-200'}
