import {randomUUID} from 'node:crypto';
import type {OrbyModelDescriptor} from '../core/contracts';
import type {OrbyBudget,OrbyCostEvent,OrbyEvaluationCase,OrbyEvaluationResult,OrbyModelHealth,OrbyProviderCircuit,OrbyRelease,OrbyRoutingCandidate,OrbyRoutingTask,OrbyTrace,OrbyTraceSpan} from './contracts';

function capabilityFit(model:OrbyModelDescriptor,task:OrbyRoutingTask){return task.requiredCapabilities.every(capability=>model.capabilities[capability]===true);}
function estimate(model:OrbyModelDescriptor,task:OrbyRoutingTask){const inputTokens=Math.ceil((task.contextCharacters||4000)/4),outputTokens=task.requiresLongReasoning?2500:800;return(inputTokens*(model.inputCostPerMillion||0)+outputTokens*(model.outputCostPerMillion||0))/1_000_000;}
export class OrbyMultiModelRouter{
 rank(models:readonly OrbyModelDescriptor[],task:OrbyRoutingTask,health:readonly OrbyModelHealth[]=[],circuits:readonly OrbyProviderCircuit[]=[]):readonly OrbyRoutingCandidate[]{return models.filter(model=>model.enabled&&capabilityFit(model,task)&&(!task.allowedModelIds||task.allowedModelIds.includes(model.id))&&(!task.allowedProviderIds||task.allowedProviderIds.includes(model.providerId))).map(model=>{const modelHealth=health.find(item=>item.modelId===model.id&&item.providerId===model.providerId),circuit=circuits.find(item=>item.providerId===model.providerId),cost=estimate(model,task),reasons:string[]=[];let score=1000-model.priority*5;if(task.preferredModelId===model.id){score+=500;reasons.push('preferred');}if(circuit?.state==='open'){score-=10_000;reasons.push('circuit-open');}if(modelHealth){score+=Math.round(modelHealth.successRate*200)-Math.round(modelHealth.latencyMs/50);reasons.push(modelHealth.ok?'healthy':'unhealthy');}if(task.maxEstimatedCost!==undefined&&cost>task.maxEstimatedCost){score-=5000;reasons.push('over-budget');}else score-=Math.round(cost*1000);if(task.requiresTools&&model.tags?.includes('tools'))score+=100;if(task.requiresLongReasoning&&model.tags?.includes('reasoning'))score+=100;if(task.language==='ar'&&model.tags?.includes('arabic'))score+=50;return{model,score,estimatedCost:cost,reasons};}).filter(item=>item.score>-4000).sort((a,b)=>b.score-a.score||a.estimatedCost-b.estimatedCost||a.model.id.localeCompare(b.model.id));}
 select(models:readonly OrbyModelDescriptor[],task:OrbyRoutingTask,health?:readonly OrbyModelHealth[],circuits?:readonly OrbyProviderCircuit[]){const candidate=this.rank(models,task,health,circuits)[0];if(!candidate)throw new Error('ORBY_NO_ROUTING_CANDIDATE');return candidate;}
}

function budgetScopeMatches(budget:OrbyBudget,event:OrbyCostEvent){return(!budget.scope.organizationId||budget.scope.organizationId===event.identity.organizationId)&&(!budget.scope.workspaceId||budget.scope.workspaceId===event.identity.workspaceId)&&(!budget.scope.userId||budget.scope.userId===event.identity.userId);}
export class OrbyBudgetEngine{
 evaluate(event:OrbyCostEvent,budgets:readonly OrbyBudget[],spent:number){const budget=budgets.filter(item=>item.enabled&&item.currency===event.currency&&budgetScopeMatches(item,event)).sort((a,b)=>Object.values(b.scope).filter(Boolean).length-Object.values(a.scope).filter(Boolean).length)[0];if(!budget)return{allowed:true,warning:false};const projected=spent+event.amount,warning=projected>=budget.limit*(budget.warningPercentage/100),allowed=!budget.hardStop||projected<=budget.limit;return{allowed,warning,projected,limit:budget.limit,currency:budget.currency};}
}

export class OrbyObservability{
 private readonly traces=new Map<string,OrbyTrace>();private readonly spans:OrbyTraceSpan[]=[];private readonly costs:OrbyCostEvent[]=[];
 startTrace(input:Omit<OrbyTrace,'id'|'status'|'startedAt'|'totalCost'|'currency'> & {currency?:string}){const trace:OrbyTrace={...input,id:randomUUID(),status:'running',startedAt:new Date().toISOString(),totalCost:0,currency:input.currency||'USD'};this.traces.set(trace.id,trace);return trace;}
 startSpan(traceId:string,input:Omit<OrbyTraceSpan,'id'|'traceId'|'status'|'startedAt'|'metadata'> & {metadata?:OrbyTraceSpan['metadata']}){if(!this.traces.has(traceId))throw new Error('ORBY_TRACE_NOT_FOUND');const span:OrbyTraceSpan={...input,id:randomUUID(),traceId,status:'running',startedAt:new Date().toISOString(),metadata:input.metadata||{}};this.spans.push(span);return span;}
 finishSpan(spanId:string,status:'succeeded'|'failed'|'cancelled',patch:Partial<OrbyTraceSpan>={}){const index=this.spans.findIndex(item=>item.id===spanId);if(index<0)throw new Error('ORBY_SPAN_NOT_FOUND');const current=this.spans[index],completedAt=new Date().toISOString();const updated={...current,...patch,status,completedAt,durationMs:Date.parse(completedAt)-Date.parse(current.startedAt)};this.spans[index]=updated;return updated;}
 recordCost(event:OrbyCostEvent){this.costs.push(event);const trace=this.traces.get(event.traceId);if(trace)this.traces.set(trace.id,{...trace,totalCost:trace.totalCost+event.amount,currency:event.currency});}
 finishTrace(traceId:string,status:'succeeded'|'failed'|'cancelled',metadata={}){const trace=this.traces.get(traceId);if(!trace)throw new Error('ORBY_TRACE_NOT_FOUND');const completedAt=new Date().toISOString(),updated={...trace,status,completedAt,durationMs:Date.parse(completedAt)-Date.parse(trace.startedAt),metadata:{...trace.metadata,...metadata}};this.traces.set(traceId,updated);return updated;}
 snapshot(){return{traces:[...this.traces.values()],spans:[...this.spans],costs:[...this.costs]};}
}

export type EvaluationExecutor=(test:OrbyEvaluationCase)=>Promise<{score:number;dimensionScores:OrbyEvaluationResult['dimensionScores'];findings?:readonly string[];cost?:number;metadata?:OrbyEvaluationResult['metadata']}>;
export class OrbyEvaluationEngine{async run(cases:readonly OrbyEvaluationCase[],executor:EvaluationExecutor){const results:OrbyEvaluationResult[]=[];for(const test of cases){const started=Date.now();try{const timeout=new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('EVALUATION_TIMEOUT')),test.timeoutMs));const output=await Promise.race([executor(test),timeout]);results.push({caseId:test.id,passed:output.score>=test.minimumScore,score:output.score,dimensionScores:output.dimensionScores,durationMs:Date.now()-started,cost:output.cost||0,findings:output.findings||[],metadata:output.metadata||{}});}catch(error){results.push({caseId:test.id,passed:false,score:0,dimensionScores:{},durationMs:Date.now()-started,cost:0,findings:[error instanceof Error?error.message:'EVALUATION_FAILED'],metadata:{}});}}return{passed:results.every(item=>item.passed),score:results.length?results.reduce((sum,item)=>sum+item.score,0)/results.length:0,results};}}

export class OrbyReleaseManager{
 constructor(private readonly releases:OrbyRelease[]=[]){ }
 create(input:Omit<OrbyRelease,'id'|'createdAt'>){const release:OrbyRelease={...input,id:randomUUID(),createdAt:new Date().toISOString()};this.releases.push(release);return release;}
 activate(id:string,rolloutPercentage=100){const release=this.releases.find(item=>item.id===id);if(!release)throw new Error('ORBY_RELEASE_NOT_FOUND');if(rolloutPercentage<1||rolloutPercentage>100)throw new Error('ORBY_RELEASE_ROLLOUT_INVALID');release.status=rolloutPercentage<100?'canary':'active';release.rolloutPercentage=rolloutPercentage;release.activatedAt=new Date().toISOString();return release;}
 rollback(id:string){const release=this.releases.find(item=>item.id===id);if(!release||!release.previousVersion)throw new Error('ORBY_RELEASE_ROLLBACK_UNAVAILABLE');release.status='archived';return this.create({component:release.component,componentKey:release.componentKey,version:release.previousVersion,status:'active',rolloutPercentage:100,previousVersion:release.version,metadata:{rollbackOf:release.id}});}
 list(){return[...this.releases];}
}
