import {randomUUID} from 'node:crypto';
import type {OrbyIdentity,OrbyJsonObject,OrbyJsonValue,OrbyModelDescriptor} from '../core/contracts';
import type {OrbyWorkflowNode} from '../execution/contracts';
import {IntegrationDatabase} from '@/src/lib/integration/platform';
import type {OrbyCostEvent,OrbyEvaluationResult,OrbyTrace,OrbyTraceSpan} from './contracts';

type TemplateRow={id:string;key:string;workflow_version_id:string;name:string;description:string;domain:string;enabled:boolean;metadata:OrbyJsonObject};
type VersionRow={id:string;workflow_id:string;version:number;definition:OrbyWorkflowNode;input_schema:OrbyJsonObject;output_schema:OrbyJsonObject;checksum:string;max_duration_seconds:number;status:string};
type DefinitionRow={id:string;key:string;name:string;description:string;domain:string;status:string;required_permissions:string[];tags:string[];metadata:OrbyJsonObject};
type TraceRow={id:string;request_id:string;organization_id:string;workspace_id?:string;user_id?:string;operation:string;status:OrbyTrace['status'];provider_id?:string;model_id?:string;workflow_key?:string;plugin_key?:string;total_cost:number;currency:string;metadata:OrbyJsonObject;started_at:string;completed_at?:string;duration_ms?:number};
type ModelRow={id:string;provider_id:string;provider_model:string;display_name:string;enabled:boolean;priority:number;capabilities:OrbyModelDescriptor['capabilities'];limits:OrbyJsonObject;pricing:OrbyJsonObject;metadata:OrbyJsonObject};

const iso=()=>new Date().toISOString();
const params=(value:Record<string,string>)=>new URLSearchParams(value);
export class SupabaseOrbyOsRepository{
 constructor(readonly database=new IntegrationDatabase()){}
 async template(key:string){
  const template=(await this.database.select<TemplateRow>('orby_workflow_templates',params({select:'id,key,workflow_version_id,name,description,domain,enabled,metadata',key:`eq.${key}`,enabled:'eq.true',limit:'1'})))[0];
  if(!template)return null;
  const version=(await this.database.select<VersionRow>('orby_workflow_versions',params({select:'id,workflow_id,version,definition,input_schema,output_schema,checksum,max_duration_seconds,status',id:`eq.${template.workflow_version_id}`,status:'in.(active,canary,testing)',limit:'1'})))[0];
  if(!version)return null;
  const definition=(await this.database.select<DefinitionRow>('orby_workflow_definitions',params({select:'id,key,name,description,domain,status,required_permissions,tags,metadata',id:`eq.${version.workflow_id}`,limit:'1'})))[0];
  return definition?{template,version,definition}:null;
 }
 async models():Promise<OrbyModelDescriptor[]>{const rows=await this.database.select<ModelRow>('orby_model_registry',params({select:'id,provider_id,provider_model,display_name,enabled,priority,capabilities,limits,pricing,metadata',enabled:'eq.true',order:'priority.desc'}));return rows.map(row=>({id:row.id,providerId:row.provider_id,providerModel:row.provider_model,displayName:row.display_name,enabled:row.enabled,priority:row.priority,capabilities:row.capabilities,maxInputTokens:Number(row.limits?.maxInputTokens||0)||undefined,maxOutputTokens:Number(row.limits?.maxOutputTokens||0)||undefined,inputCostPerMillion:Number(row.pricing?.inputCostPerMillion||0)||undefined,outputCostPerMillion:Number(row.pricing?.outputCostPerMillion||0)||undefined,tags:Array.isArray(row.metadata?.tags)?row.metadata.tags.map(String):undefined,metadata:row.metadata}));}
 async traceByRequest(organizationId:string,requestId:string){const row=(await this.database.select<TraceRow>('orby_traces',params({select:'*',organization_id:`eq.${organizationId}`,request_id:`eq.${requestId}`,limit:'1'})))[0];return row?this.trace(row):null;}
 async startTrace(input:{requestId:string;identity:OrbyIdentity;operation:string;workflowKey?:string;pluginKey?:string;metadata?:OrbyJsonObject}){const row=(await this.database.upsert<TraceRow>('orby_traces',{id:randomUUID(),request_id:input.requestId,organization_id:input.identity.organizationId,workspace_id:input.identity.workspaceId||null,user_id:input.identity.userId,operation:input.operation,status:'running',workflow_key:input.workflowKey||null,plugin_key:input.pluginKey||null,total_cost:0,currency:'USD',metadata:input.metadata||{},started_at:iso()},'organization_id,request_id'))[0];if(!row)throw new Error('ORBY_TRACE_CREATE_FAILED');return this.trace(row);}
 async finishTrace(traceId:string,status:'succeeded'|'failed'|'cancelled',metadata:OrbyJsonObject={}){const current=(await this.database.select<TraceRow>('orby_traces',params({select:'*',id:`eq.${traceId}`,limit:'1'})))[0];if(!current)throw new Error('ORBY_TRACE_NOT_FOUND');const completedAt=iso(),row=(await this.database.update<TraceRow>('orby_traces',`id=eq.${traceId}`,{status,completed_at:completedAt,duration_ms:Math.max(0,Date.parse(completedAt)-Date.parse(current.started_at)),metadata:{...(current.metadata||{}),...metadata}}))[0];return row?this.trace(row):null;}
 async startSpan(traceId:string,input:{parentSpanId?:string;name:string;kind:OrbyTraceSpan['kind'];input?:OrbyJsonObject;metadata?:OrbyJsonObject}){const row=(await this.database.insert<Record<string,unknown>>('orby_trace_spans',{id:randomUUID(),trace_id:traceId,parent_span_id:input.parentSpanId||null,name:input.name,kind:input.kind,status:'running',input:input.input||null,metadata:input.metadata||{},started_at:iso()}))[0];if(!row)throw new Error('ORBY_SPAN_CREATE_FAILED');return row as unknown as {id:string;started_at:string};}
 async finishSpan(spanId:string,status:'succeeded'|'failed'|'cancelled',patch:{output?:OrbyJsonValue;errorCode?:string;metadata?:OrbyJsonObject}={}){const current=(await this.database.select<{id:string;started_at:string;metadata:OrbyJsonObject}>('orby_trace_spans',params({select:'id,started_at,metadata',id:`eq.${spanId}`,limit:'1'})))[0];if(!current)return null;const completedAt=iso();return(await this.database.update('orby_trace_spans',`id=eq.${spanId}`,{status,completed_at:completedAt,duration_ms:Math.max(0,Date.parse(completedAt)-Date.parse(current.started_at)),output:patch.output??null,error_code:patch.errorCode||null,metadata:{...(current.metadata||{}),...(patch.metadata||{})}}))[0]||null;}
 async recordCost(event:OrbyCostEvent){await this.database.insert('orby_cost_events',{trace_id:event.traceId,organization_id:event.identity.organizationId,workspace_id:event.identity.workspaceId||null,user_id:event.identity.userId,provider_id:event.providerId||null,model_id:event.modelId||null,tool_name:event.toolName||null,workflow_key:event.workflowKey||null,plugin_key:event.pluginKey||null,task_type:event.taskType,amount:event.amount,currency:event.currency,input_units:event.inputUnits||null,output_units:event.outputUnits||null,metadata:event.metadata,occurred_at:event.occurredAt},'return=minimal');}
 async recordEvaluation(input:{suiteId:string;releaseId?:string;status:'passed'|'failed';score:number;results:readonly OrbyEvaluationResult[];startedBy?:string;startedAt:string;completedAt:string;metadata?:OrbyJsonObject}){const run=(await this.database.insert<{id:string}>('orby_evaluation_runs',{suite_id:input.suiteId,release_id:input.releaseId||null,status:input.status,score:input.score,passed_cases:input.results.filter(item=>item.passed).length,failed_cases:input.results.filter(item=>!item.passed).length,total_cost:input.results.reduce((sum,item)=>sum+item.cost,0),duration_ms:Math.max(0,Date.parse(input.completedAt)-Date.parse(input.startedAt)),metadata:input.metadata||{},started_by:input.startedBy||null,started_at:input.startedAt,completed_at:input.completedAt}))[0];if(!run)throw new Error('ORBY_EVALUATION_RUN_CREATE_FAILED');const cases=await this.database.select<{id:string;case_key:string}>('orby_evaluation_cases',params({select:'id,case_key',suite_id:`eq.${input.suiteId}`}));const caseIds=new Map(cases.map(item=>[item.case_key,item.id]));const rows=input.results.map(result=>({run_id:run.id,case_id:caseIds.get(result.caseId),passed:result.passed,score:result.score,dimension_scores:result.dimensionScores,duration_ms:result.durationMs,cost:result.cost,findings:result.findings,metadata:result.metadata})).filter(item=>item.case_id) as unknown as OrbyJsonObject[];if(rows.length)await this.database.insert('orby_evaluation_results',rows,'return=minimal');return run.id;}
 private trace(row:TraceRow):OrbyTrace{return{id:row.id,requestId:row.request_id,identity:{organizationId:row.organization_id,userId:row.user_id||'system',workspaceId:row.workspace_id},operation:row.operation,status:row.status,startedAt:row.started_at,completedAt:row.completed_at,durationMs:row.duration_ms,providerId:row.provider_id,modelId:row.model_id,workflowKey:row.workflow_key,pluginKey:row.plugin_key,totalCost:Number(row.total_cost||0),currency:row.currency,metadata:row.metadata||{}};}
}
