'use client';

import Link from 'next/link';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';

type Conversation={id:string;title:string;last_message_at:string;organization_id:string|null;service_code:string|null};
type Scope={organizationId:string;serviceCode:string;name:string};
const dayKey=(value:string)=>new Date(value).toISOString().slice(0,10);
const todayKey=()=>new Date().toISOString().slice(0,10);
const yesterdayKey=()=>new Date(Date.now()-86400000).toISOString().slice(0,10);
const groupLabel=(value:string)=>{const key=dayKey(value);return key===todayKey()?'اليوم':key===yesterdayKey()?'أمس':'أقدم';};
const serviceLabel=(code:string|null)=>code==='MADAR_RETAIL'?'Retail':code==='CONNECT_EXISTING'?'ربط قائم':code==='BUILD_ON_MADAR'?'تجارة مَدار':'عام';

export default function OrbyConversationSidebar({conversations,selectedId,scopes,selectedOrganizationId,tier}:{conversations:Conversation[];selectedId:string|null;scopes:Scope[];selectedOrganizationId:string|null;tier:string}){
 const router=useRouter(),[query,setQuery]=useState(''),[editing,setEditing]=useState<string|null>(null),[title,setTitle]=useState(''),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState('');
 const filtered=useMemo(()=>{const clean=query.trim().toLowerCase();return clean?conversations.filter(item=>item.title.toLowerCase().includes(clean)):conversations;},[conversations,query]);
 const groups=useMemo(()=>{const result=new Map<string,Conversation[]>();for(const item of filtered){const label=groupLabel(item.last_message_at),bucket=result.get(label)||[];bucket.push(item);result.set(label,bucket);}return [...result.entries()];},[filtered]);
 const baseNew=selectedOrganizationId?`/orby?conversation=new&organization=${encodeURIComponent(selectedOrganizationId)}`:'/orby?conversation=new';
 async function mutate(conversationId:string,action:'rename'|'archive',nextTitle?:string){setBusy(conversationId);setError('');try{const response=await fetch('/api/orby/conversations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId,action,title:nextTitle})}),data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر تحديث المحادثة.');setEditing(null);router.refresh();if(action==='archive'&&selectedId===conversationId)router.push(baseNew);}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحديث المحادثة.');}finally{setBusy(null);}}
 async function remove(conversationId:string){if(!window.confirm('سيتم حذف هذه المحادثة ورسائلها. هل تريد المتابعة؟'))return;setBusy(conversationId);setError('');try{const response=await fetch(`/api/orby/conversations?conversationId=${encodeURIComponent(conversationId)}`,{method:'DELETE'}),data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر حذف المحادثة.');router.refresh();if(selectedId===conversationId)router.push(baseNew);}catch(reason){setError(reason instanceof Error?reason.message:'تعذر حذف المحادثة.');}finally{setBusy(null);}}
 return <div className="space-y-5" aria-label="قائمة أوربي">
  <section><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-black">المحادثات</h2><Link href={baseNew} className="rounded-lg border border-emerald-300/20 bg-emerald-300/10 px-2.5 py-1.5 text-[11px] font-bold text-emerald-100">جديدة</Link></div><label className="mt-3 block"><span className="sr-only">البحث في المحادثات</span><input value={query} onChange={event=>setQuery(event.target.value)} className="field h-10 text-xs" placeholder="بحث في المحادثات…"/></label>{error?<p role="alert" className="mt-2 rounded-lg border border-red-300/20 bg-red-300/10 p-2 text-[11px] text-red-100">{error}</p>:null}<div className="mt-3 max-h-[42dvh] space-y-4 overflow-y-auto pe-1">{groups.length?groups.map(([label,items])=><section key={label}><h3 className="mb-2 px-1 text-[10px] font-bold text-slate-500">{label}</h3><div className="space-y-1.5">{items.map(item=><article key={item.id} className={`rounded-xl border p-2.5 transition ${selectedId===item.id?'border-violet-300/20 bg-violet-300/10 text-white':'border-transparent text-slate-400 hover:bg-white/[.04]'}`}>{editing===item.id?<form onSubmit={event=>{event.preventDefault();void mutate(item.id,'rename',title);}} className="grid gap-2"><input autoFocus value={title} onChange={event=>setTitle(event.target.value)} minLength={2} maxLength={120} className="field h-9 text-xs"/><div className="flex gap-1"><button disabled={busy===item.id} className="rounded-md border border-emerald-300/20 px-2 py-1 text-[10px] text-emerald-200">حفظ</button><button type="button" onClick={()=>setEditing(null)} className="rounded-md border border-white/10 px-2 py-1 text-[10px]">إلغاء</button></div></form>:<><Link href={`/orby?conversation=${item.id}`} className="block"><strong className="line-clamp-2 text-xs">{item.title}</strong><span className="mt-1 flex items-center justify-between gap-2 text-[9px]"><span>{serviceLabel(item.service_code)}</span><span>{new Date(item.last_message_at).toLocaleDateString('ar-YE')}</span></span></Link><div className="mt-2 flex gap-1 opacity-70"><button type="button" onClick={()=>{setEditing(item.id);setTitle(item.title);}} className="rounded-md border border-white/10 px-2 py-1 text-[9px]">تسمية</button><button type="button" disabled={busy===item.id} onClick={()=>void mutate(item.id,'archive')} className="rounded-md border border-white/10 px-2 py-1 text-[9px]">أرشفة</button><button type="button" disabled={busy===item.id} onClick={()=>void remove(item.id)} className="rounded-md border border-red-300/15 px-2 py-1 text-[9px] text-red-200">حذف</button></div></>}</article>)}</div></section>):<p className="rounded-xl border border-dashed border-white/10 p-4 text-center text-xs text-slate-500">{query?'لا توجد نتائج مطابقة.':'ابدأ أول محادثة مع أوربي.'}</p>}</div></section>
  <section className="border-t border-white/10 pt-4"><h2 className="text-xs font-black text-slate-300">سياق الخدمة</h2><div className="mt-2 grid gap-1.5"><Link href="/orby?conversation=new" className={`rounded-lg px-3 py-2 text-xs ${!selectedOrganizationId?'bg-white/[.07] text-white':'text-slate-400 hover:bg-white/[.04]'}`}>محادثة عامة</Link>{scopes.map(scope=><Link key={scope.organizationId} href={`/orby?conversation=new&organization=${scope.organizationId}`} className={`rounded-lg px-3 py-2 text-xs ${selectedOrganizationId===scope.organizationId?'bg-emerald-300/10 text-emerald-100':'text-slate-400 hover:bg-white/[.04]'}`}><span className="block font-bold">{scope.name}</span><span className="mt-0.5 block text-[9px] opacity-70">{serviceLabel(scope.serviceCode)}</span></Link>)}</div></section>
  <section className="border-t border-white/10 pt-4"><h2 className="text-xs font-black text-slate-300">أدوات ORBY</h2><div className="mt-2 grid grid-cols-3 gap-1.5"><Link href={`${baseNew}&starter=analysis`} className="rounded-lg border border-white/10 p-2 text-center text-[10px] text-slate-300 hover:bg-white/[.04]">تحليل</Link><Link href={`${baseNew}&starter=plan`} className="rounded-lg border border-white/10 p-2 text-center text-[10px] text-slate-300 hover:bg-white/[.04]">خطة</Link><Link href={`${baseNew}&starter=report`} className="rounded-lg border border-white/10 p-2 text-center text-[10px] text-slate-300 hover:bg-white/[.04]">تقرير</Link></div><p className="mt-2 text-[9px] leading-4 text-slate-500">هذه اختصارات فقط. يمكنك طلب الشيء نفسه بكتابته طبيعيًا في المحادثة.</p></section>
  <section className="border-t border-white/10 pt-4"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">الخطة</span><strong className="text-xs">{tier==='plus'?'ORBY Plus':tier==='customer'?'عميل مَدار':'ORBY Free'}</strong></div><div className="mt-2 grid gap-1"><Link href="/orby/plus" className="rounded-lg px-3 py-2 text-xs text-violet-200 hover:bg-violet-300/10">إدارة ORBY Plus</Link><Link href="/account/privacy" className="rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/[.04]">الخصوصية والبيانات</Link></div></section>
 </div>;
}
