'use client';

import {useActionState,useMemo,useState} from 'react';
import {submitOrbyPlusPayment,type OrbyPlusActionState} from '@/app/actions/orby-plus';
import {convertStoreAmount,formatStoreMoney,type CurrencyDefinition,type ExchangeRateDefinition} from '@/src/lib/store/currency';

type Method={id:string;name:string;account_name:string|null;account_identifier:string|null;instructions:string|null;currency_agnostic:boolean};
type Restriction={payment_method_id:string;currency_code:string};

export default function OrbyPlusCheckout({price,currency,currencies,rates,methods,restrictions}:{price:number;currency:string;currencies:CurrencyDefinition[];rates:ExchangeRateDefinition[];methods:Method[];restrictions:Restriction[]}){
 const[state,action,pending]=useActionState<OrbyPlusActionState,FormData>(submitOrbyPlusPayment,{}),[paymentCurrency,setPaymentCurrency]=useState(currency),[methodId,setMethodId]=useState(methods[0]?.id||'');
 const availableMethods=useMemo(()=>methods.filter(method=>method.currency_agnostic||restrictions.some(item=>item.payment_method_id===method.id&&item.currency_code===paymentCurrency)),[methods,restrictions,paymentCurrency]),selected=availableMethods.find(item=>item.id===methodId)||availableMethods[0],converted=convertStoreAmount(price,currency,paymentCurrency,rates,currencies);
 return <form action={action} className="grid gap-5"><input type="hidden" name="payment_method_id" value={selected?.id||''}/>
  <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm"><span className="font-bold">عملة الدفع</span><select name="payment_currency" value={paymentCurrency} onChange={event=>{setPaymentCurrency(event.target.value);setMethodId('');}} className="field">{currencies.filter(item=>item.is_active!==false).map(item=><option key={item.code} value={item.code}>{item.name} — {item.code}</option>)}</select></label><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><span className="text-xs text-slate-500">المبلغ المطلوب</span><strong className="mt-1 block text-xl">{converted===null?'لا يتوفر سعر تحويل':formatStoreMoney(converted,paymentCurrency,currencies)}</strong>{paymentCurrency!==currency?<span className="mt-1 block text-[11px] text-slate-500">السعر الأصلي: {formatStoreMoney(price,currency,currencies)}</span>:null}</div></div>
  {converted===null?<div className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100">لا يوجد سعر تحويل فعّال بين {currency} و{paymentCurrency}. اختر عملة أخرى أو انتظر تحديث الإدارة لسعر الصرف.</div>:null}
  <div><span className="text-sm font-bold">وسيلة الدفع</span><div className="mt-2 grid gap-2 sm:grid-cols-2">{availableMethods.length?availableMethods.map(method=><button type="button" key={method.id} onClick={()=>setMethodId(method.id)} className={`rounded-xl border p-4 text-start transition ${selected?.id===method.id?'border-emerald-300/30 bg-emerald-300/10':'border-white/10 bg-white/[.025] hover:bg-white/[.04]'}`}><strong className="block text-sm">{method.name}</strong>{method.account_name?<span className="mt-1 block text-xs text-slate-400">{method.account_name}</span>:null}{method.account_identifier?<span dir="ltr" className="mt-1 block text-right text-xs text-slate-300">{method.account_identifier}</span>:null}{method.instructions?<span className="mt-2 block text-[11px] leading-5 text-slate-500">{method.instructions}</span>:null}</button>):<p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-slate-500">لا توجد وسيلة دفع تقبل العملة المحددة.</p>}</div></div>
  <label className="grid gap-2 text-sm"><span className="font-bold">رقم الحوالة / العملية <b className="text-rose-300">*</b></span><input required minLength={3} maxLength={120} name="payment_reference" className="field" placeholder="اكتب الرقم كما يظهر في التحويل"/></label>
  <label className="grid gap-2 text-sm"><span className="font-bold">إيصال التحويل <span className="font-normal text-slate-500">(اختياري)</span></span><input type="file" name="proof" accept="image/jpeg,image/png,image/webp,application/pdf" className="field file:me-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-xs file:text-white"/><span className="text-[11px] text-slate-500">JPG / PNG / WebP / PDF حتى 10MB.</span></label>
  {state.error?<p role="alert" className="rounded-xl border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-100">{state.error}</p>:null}{state.success?<p className="rounded-xl border border-emerald-300/20 bg-emerald-300/10 p-3 text-sm text-emerald-100">{state.success}</p>:null}
  <button disabled={pending||!selected||converted===null} className="md-button md-button-primary w-full">{pending?'جارٍ إرسال الطلب…':'إرسال طلب ORBY Plus'}</button>
 </form>;
}
