'use client';

import Link from 'next/link';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';

type Conversation={id:string;title:string;last_message_at:string};
const dayKey=(value:string)=>new Date(value).toISOString().slice(0,10);
const todayKey=()=>new Date().toISOString().slice(0,10);
const yesterdayKey=()=>new Date(Date.now()-86400000).toISOString().slice(0,10);
const groupLabel=(value:string)=>{const key=dayKey(value);return key===todayKey()?'اليوم':key===yesterdayKey()?'أمس':'أقدم';};

export default function OrbyConversationSidebar({organizationId,conversations,selectedId}:{organizationId:string;conversations:Conversation[];selectedId:string|null}){
 const router=useRouter(),[query,setQuery]=useState(''),[editing,setEditing]=useState<string|null>(null),[title,setTitle]=useState(''),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState('');
 const filtered=useMemo(()=>{const clean=query.trim().toLowerCase();return clean?conversations.filter(item=>item.title.toLowerCase().includes(clean)):conversations;},[conversations,query]);
 const groups=useMemo(()=>{const result=new Map<string,Conversation[]>();for(const item of filtered){const label=groupLabel(item.last_message_at),bucket=result.get(label)||[];bucket.push(item);result.set(label,bucket);}return [...result.entries()];},[filtered]);
 async function mutate(conversationId:string,action:'rename'|'archive',nextTitle?:string){setBusy(conversationId);setError('');try{const response=await fetch('/api/orby/conversations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,conversationId,action,title:nextTitle})}),data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر تحديث المحادثة.');setEditing(null);router.refresh();if(action==='archive'&&selectedId===conversationId)router.push('/workspace/orby?conversation=new');}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحديث المحادثة.');}finally{setBusy(null);}}
 async function remove(conversationId:string){if(!window.confirm('سيتم حذف هذه المحادثة ورسائلها وفق سياسة البيانات. هل تريد المتابعة؟'))return;setBusy(conversationId);setError('');try{const response=await fetch(`/api/orby/conversations?organizationId=${encodeURIComponent(organizationId)}&conversationId=${encodeURIComponent(conversationId)}`,{method:'DELETE'}),data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر حذف المحادثة.');router.refresh();if(selectedId===conversationId)router.push('/workspace/orby?conversation=new');}catch(reason){setError(reason instanceof Error?reason.message:'تعذر حذف المحادثة.');}finally{setBusy(null);}}
 return <aside className="md-panel p-3" aria-label="سجل محادثات أوربي"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-black">المحادثات</h3><Link href="/workspace/orby?conversation=new" className="md-button md-button-primary md-button-sm">جديدة</Link></div><label className="mt-3 block"><span className="sr-only">البحث في المحادثات</span><input value={query} onChange={event=>setQuery(event.target.value)} className="field h-10 text-xs" placeholder="بحث في المحادثات…"/></label>{error&&<p role="alert" className="mt-2 rounded-lg border border-red-300/20 bg-red-300/10 p-2 text-[11px] text-red-100">{error}</p>}<div className="mt-3 max-h-[650px] space-y-4 overflow-y-auto">{groups.length?groups.map(([label,items])=><section key={label}><h4 className="mb-2 px-1 text-[10px] font-bold text-slate-500">{label}</h4><div className="space-y-2">{items.map(item=><article key={item.id} className={`rounded-lg p-2.5 ${selectedId===item.id?'bg-violet-300/15 text-white':'text-slate-400 hover:bg-white/[.04]'}`}>{editing===item.id?<form onSubmit={event=>{event.preventDefault();void mutate(item.id,'rename',title);}} className="grid gap-2"><input autoFocus value={title} onChange={event=>setTitle(event.target.value)} minLength={2} maxLength={120} className="field h-9 text-xs"/><div className="flex gap-1"><button disabled={busy===item.id} className="rounded-md border border-emerald-300/20 px-2 py-1 text-[10px] text-emerald-200">حفظ</button><button type="button" onClick={()=>setEditing(null)} className="rounded-md border border-white/10 px-2 py-1 text-[10px]">إلغاء</button></div></form>:<><Link href={`/workspace/orby?conversation=${item.id}`} className="block"><strong className="line-clamp-2 text-xs">{item.title}</strong><span className="mt-1 block text-[10px]">{new Date(item.last_message_at).toLocaleString('ar-YE')}</span></Link><div className="mt-2 flex flex-wrap gap-1 opacity-70 transition group-hover:opacity-100"><button type="button" onClick={()=>{setEditing(item.id);setTitle(item.title);}} className="rounded-md border border-white/10 px-2 py-1 text-[9px]">إعادة تسمية</button><button type="button" disabled={busy===item.id} onClick={()=>void mutate(item.id,'archive')} className="rounded-md border border-white/10 px-2 py-1 text-[9px]">أرشفة</button><button type="button" disabled={busy===item.id} onClick={()=>void remove(item.id)} className="rounded-md border border-red-300/15 px-2 py-1 text-[9px] text-red-200">حذف</button></div></>}</article>)}</div></section>):<p className="rounded-lg border border-dashed border-white/10 p-4 text-center text-xs text-slate-500">{query?'لا توجد نتائج مطابقة.':'لم تبدأ محادثة بعد.'}</p>}</div></aside>;
}
