'use client';

import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';

type Message={id:string;role:'user'|'assistant';content:string;source?:string};
type Tier='guest'|'registered'|'customer'|'plus';
type Citation={label?:string;source?:string;certainty?:string};
type Props={authenticated:boolean;organizationId:string|null;serviceCode:string|null;initialConversationId:string|null;initialMessages:Message[];initialRemaining:number;initialLimit:number;tier:Tier;starter?:string|null};
type SseEvent={event:string;data:Record<string,unknown>};

const starterText=(value?:string|null)=>value==='analysis'?'حلل البيانات المتاحة في هذا السياق وحدد أهم ما يحتاج انتباهي.':value==='plan'?'اعمل لي خطة عملية مرتبة للأسبوع القادم اعتمادًا على السياق المتاح.':value==='report'?'جهز لي تقريرًا تنفيذيًا موجزًا عن الوضع الحالي.':'';
function parseSse(buffer:string){const blocks=buffer.split('\n\n'),rest=blocks.pop()||'',events:SseEvent[]=[];for(const block of blocks){let event='message',data='';for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim();}if(data)try{events.push({event,data:JSON.parse(data)});}catch{}}return{events,rest};}
function Inline({text}:{text:string}){const parts=text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);return <>{parts.map((part,index)=>part.startsWith('**')&&part.endsWith('**')?<strong key={index}>{part.slice(2,-2)}</strong>:part.startsWith('`')&&part.endsWith('`')?<code key={index} dir="ltr" className="rounded bg-black/30 px-1 py-0.5 font-mono text-[.9em] text-emerald-100">{part.slice(1,-1)}</code>:part)}</>;}
function Markdown({content}:{content:string}){const chunks=content.split(/```/);return <div className="space-y-2 text-[15px] leading-7 sm:text-base">{chunks.map((chunk,index)=>index%2?<pre key={index} dir="ltr" className="overflow-x-auto rounded-xl border border-white/10 bg-black/35 p-3 text-left text-xs leading-6"><code>{chunk.replace(/^\w+\n/,'')}</code></pre>:<div key={index} className="whitespace-pre-wrap break-words">{chunk.split('\n').map((line,lineIndex)=>{const clean=line.trim();if(/^#{1,3}\s/.test(clean))return <strong key={lineIndex} className="mt-3 block text-base">{clean.replace(/^#{1,3}\s/,'')}</strong>;if(/^[-•]\s/.test(clean))return <div key={lineIndex} className="flex gap-2"><span>•</span><span><Inline text={clean.replace(/^[-•]\s/,'')}/></span></div>;return <span key={lineIndex}><Inline text={line}/>{lineIndex<chunk.split('\n').length-1?<br/>:null}</span>;})}</div>)}</div>;}

export default function OrbyChat({authenticated,organizationId,serviceCode,initialConversationId,initialMessages,initialRemaining,initialLimit,tier:initialTier,starter}:Props){
 const router=useRouter(),[messages,setMessages]=useState<Message[]>(initialMessages),[conversationId,setConversationId]=useState<string|null>(initialConversationId),[prompt,setPrompt]=useState(starterText(starter)),[remaining,setRemaining]=useState(initialRemaining),[limit,setLimit]=useState(initialLimit),[tier,setTier]=useState<Tier>(initialTier),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[citations,setCitations]=useState<Citation[]>([]),[generationState,setGenerationState]=useState<{status:'idle'|'streaming'|'stopped'}>({status:'idle'}),controllerRef=useRef<AbortController|null>(null),scrollRef=useRef<HTMLDivElement|null>(null),nearBottom=useRef(true),textareaRef=useRef<HTMLTextAreaElement|null>(null);
 useEffect(()=>{setMessages(initialMessages);setConversationId(initialConversationId);setCitations([]);},[initialMessages,initialConversationId]);
 useEffect(()=>{if(starterText(starter))setPrompt(starterText(starter));},[starter]);
 useEffect(()=>{const element=scrollRef.current;if(!element||!nearBottom.current)return;element.scrollTo({top:element.scrollHeight,behavior:'smooth'});},[messages,status]);
 useEffect(()=>{const box=textareaRef.current;if(!box)return;box.style.height='auto';box.style.height=`${Math.min(box.scrollHeight,180)}px`;},[prompt]);
 const blocked=remaining===0&&tier!=='plus',usageLabel=useMemo(()=>tier==='plus'?'Plus · استخدام مرن':limit>0?`${Math.max(limit-remaining,0)} من ${limit} اليوم`:null,[tier,limit,remaining]);
 function scrollChanged(){const element=scrollRef.current;if(!element)return;nearBottom.current=element.scrollHeight-element.scrollTop-element.clientHeight<120;}
 async function send(text=prompt,options:{retry?:boolean}={}){
  const clean=text.trim();if(!clean||busy||blocked)return;
  setError('');setStatus('');setCitations([]);setBusy(true);setGenerationState({status:'streaming'});nearBottom.current=true;
  if(!options.retry){setMessages(current=>[...current,{id:crypto.randomUUID(),role:'user',content:clean}]);setPrompt('');}
  const assistantId=crypto.randomUUID();setMessages(current=>[...current,{id:assistantId,role:'assistant',content:''}]);
  const controller=new AbortController();controllerRef.current=controller;
  try{
   const response=await fetch('/api/orby/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,conversationId,prompt:clean}),signal:controller.signal});
   if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(String(payload.error||'تعذر تشغيل أوربي.'));}
   if(!response.body)throw new Error('لم يبدأ بث أوربي.');
   const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
   while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parsed=parseSse(buffer);buffer=parsed.rest;for(const item of parsed.events){
    if(item.event==='status')setStatus(String(item.data.label||''));
    else if(item.event==='delta'){const delta=String(item.data.text||'');setMessages(current=>current.map(message=>message.id===assistantId?{...message,content:message.content+delta}:message));}
    else if(item.event==='citations'&&Array.isArray(item.data.items))setCitations(item.data.items as Citation[]);
    else if(item.event==='error')throw new Error(String(item.data.message||'تعذر إكمال الرد.'));
    else if(item.event==='complete'){
     const nextConversation=typeof item.data.conversationId==='string'?item.data.conversationId:null;
     if(nextConversation)setConversationId(nextConversation);
     if(typeof item.data.remaining==='number')setRemaining(item.data.remaining);
     if(typeof item.data.dailyLimit==='number')setLimit(item.data.dailyLimit);
     if(typeof item.data.tier==='string')setTier(item.data.tier as Tier);
     setStatus('');setGenerationState({status:'idle'});
     if(authenticated&&nextConversation&&!conversationId){window.history.replaceState(null,'',`/orby?conversation=${encodeURIComponent(nextConversation)}`);router.refresh();}
    }
   }}
  }catch(reason){if((reason as Error)?.name==='AbortError'){setStatus('تم إيقاف التوليد.');setGenerationState({status:'stopped'});}else{const message=reason instanceof Error?reason.message:'تعذر تشغيل أوربي.';setError(message);setMessages(current=>current.filter(item=>item.id!==assistantId));setGenerationState({status:'idle'});}}
  finally{controllerRef.current=null;setBusy(false);setTimeout(()=>setStatus(''),1200);}
 }
 function stop(){controllerRef.current?.abort();controllerRef.current=null;setBusy(false);setGenerationState({status:'stopped'});}
 function retry(messageIndex:number){const previous=[...messages].slice(0,messageIndex).reverse().find(item=>item.role==='user');if(!previous)return;setMessages(current=>current.slice(0,messageIndex));void send(previous.content,{retry:true});}
 return <div className="flex h-[calc(100dvh-8.5rem)] min-h-[34rem] flex-col sm:h-[calc(100dvh-9.5rem)]">
  <div className="flex items-center justify-between gap-3 border-b border-white/10 px-4 py-2 text-[11px] text-slate-500 sm:px-6"><span>{organizationId?`سياق خاص · ${serviceCode==='MADAR_RETAIL'?'MADAR Retail':serviceCode==='CONNECT_EXISTING'?'تجارة مرتبطة':'تجارة مَدار'}`:'محادثة عامة'}</span>{usageLabel?<span className={remaining<=2&&remaining>=0&&tier!=='plus'?'text-amber-200':'text-slate-500'}>{usageLabel}</span>:null}</div>
  <div ref={scrollRef} onScroll={scrollChanged} className="min-h-0 flex-1 overflow-y-auto px-3 py-6 sm:px-6 lg:px-10">
   <div className="mx-auto max-w-3xl space-y-6">{messages.length===0?<div className="grid min-h-[45vh] place-items-center text-center"><div><Image src="/brand/orby-assistant.svg" width={80} height={80} alt="ORBY" className="mx-auto h-20 w-20 drop-shadow-[0_0_30px_rgba(95,70,255,.25)]"/><h1 className="mt-5 text-2xl font-black sm:text-3xl">كيف أقدر أساعدك؟</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-7 text-slate-400">اكتب بطريقتك الطبيعية. لا تحتاج اختيار تحليل أو خطة أو تقرير؛ أوربي يفهم نية طلبك من الرسالة نفسها.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{(organizationId?['حلل مبيعات هذا الشهر.','اعمل لي خطة للشهر القادم.','جهز لي تقريرًا عن الوضع الحالي.']:['ما اسمك؟','ساعدني أرتب فكرة مشروع.','اشرح لي مفهومًا تقنيًا ببساطة.']).map(item=><button key={item} type="button" onClick={()=>setPrompt(item)} className="rounded-xl border border-white/10 bg-white/[.035] px-3 py-2 text-xs text-slate-300 hover:bg-white/[.06]">{item}</button>)}</div></div></div>:messages.map((message,index)=><article key={message.id} className={message.role==='user'?'ms-auto max-w-[88%] rounded-2xl rounded-es-md bg-violet-500/15 px-4 py-3 sm:max-w-[80%]':'max-w-full'}>{message.role==='assistant'?<div className="group"><div className="mb-2 flex items-center gap-2 text-xs font-black text-slate-400"><Image src="/brand/orby-assistant.svg" width={24} height={24} alt="" className="h-6 w-6"/>ORBY</div><Markdown content={message.content|| (busy&&index===messages.length-1?'…':'')}/>{message.content?<div className="mt-3 flex gap-1 opacity-60 transition group-hover:opacity-100"><button type="button" onClick={()=>navigator.clipboard.writeText(message.content)} className="rounded-lg border border-white/10 px-2 py-1 text-[10px]">نسخ</button><button type="button" onClick={()=>retry(index)} disabled={busy} className="rounded-lg border border-white/10 px-2 py-1 text-[10px]">إعادة المحاولة</button></div>:null}</div>:<div className="whitespace-pre-wrap text-[15px] leading-7">{message.content}</div>}</article>)}{citations.length?<div className="flex flex-wrap gap-2 text-[10px] text-slate-500">{citations.map((citation,index)=><span key={`${citation.label}-${index}`} className="rounded-full border border-white/10 px-2 py-1">{citation.label||'مصدر'}{citation.source?` · ${citation.source}`:''}</span>)}</div>:null}{generationState.status==='stopped'?<p className="text-[10px] text-slate-600">توقف الرد بناءً على طلبك.</p>:null}{status?<p className="text-xs text-slate-500" role="status">{status}</p>:null}{error?<div role="alert" className="rounded-xl border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-100"><p>{error}</p><button type="button" onClick={()=>setError('')} className="mt-2 text-xs underline">إخفاء</button></div>:null}</div>
  </div>
  <div className="border-t border-white/10 bg-[#080b12]/90 p-3 backdrop-blur sm:p-4"><div className="mx-auto max-w-3xl">{blocked?<div className="mb-3 rounded-xl border border-violet-300/20 bg-violet-300/10 p-3 text-sm"><p>{authenticated?'استخدمت رسائل ORBY المتاحة اليوم. يمكنك الترقية إلى ORBY Plus للمتابعة.':'استخدمت 5 رسائل ORBY المتاحة للزائر اليوم.'}</p><Link href={authenticated?'/orby/plus':'/register?next=/orby'} className="mt-2 inline-block font-bold text-violet-200 underline">{authenticated?'الترقية إلى ORBY Plus':'أنشئ حسابًا للاستمرار'}</Link></div>:null}<form onSubmit={event=>{event.preventDefault();void send();}} className="rounded-2xl border border-white/12 bg-[#111620] p-2 shadow-2xl shadow-black/20 focus-within:border-violet-300/30"><textarea ref={textareaRef} value={prompt} onChange={event=>setPrompt(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send();}}} disabled={blocked} rows={1} maxLength={12000} placeholder="اكتب لأوربي…" className="max-h-44 min-h-12 w-full resize-none bg-transparent px-2 py-2 text-[16px] leading-7 text-white outline-none placeholder:text-slate-600"/><div className="flex items-center justify-between gap-3 px-1 pb-1"><span className="text-[10px] text-slate-600">Enter للإرسال · Shift+Enter لسطر جديد</span>{busy?<button type="button" onClick={stop} className="grid h-9 w-9 place-items-center rounded-xl bg-white text-black" aria-label="إيقاف التوليد"><span className="h-3 w-3 rounded-sm bg-black"/></button>:<button type="submit" disabled={!prompt.trim()||blocked} className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-emerald-300 to-violet-400 font-black text-slate-950 disabled:opacity-30" aria-label="إرسال">↑</button>}</div></form><p className="mt-2 text-center text-[10px] text-slate-600">قد يخطئ ORBY. راجع القرارات المهمة، ولا يملك وصولًا إلا للسياق المصرح به.</p></div></div>
 </div>;
}
