'use client';

import Link from 'next/link';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button,ButtonLink,EmptyState,Field,Input} from '@/components/ui/Enterprise';
import {ConfirmDialog} from '@/components/ui/EnterpriseClient';
import {formatDate} from '@/src/lib/format';

type Conversation={id:string;title:string;last_message_at:string;organization_id:string|null;service_code:string|null};
type Scope={organizationId:string;serviceCode:string;name:string};
const dayKey=(value:string)=>new Date(value).toISOString().slice(0,10);
const todayKey=()=>new Date().toISOString().slice(0,10);
const yesterdayKey=()=>new Date(Date.now()-86400000).toISOString().slice(0,10);
const groupLabel=(value:string)=>{const key=dayKey(value);return key===todayKey()?'اليوم':key===yesterdayKey()?'أمس':'أقدم';};
const serviceLabel=(code:string|null)=>code==='MADAR_RETAIL'?'Retail':code==='CONNECT_EXISTING'?'ربط قائم':code==='BUILD_ON_MADAR'?'تجارة مَدار':'عام';

export default function OrbyConversationSidebar({conversations,selectedId,scopes,selectedOrganizationId,tier}:{conversations:Conversation[];selectedId:string|null;scopes:Scope[];selectedOrganizationId:string|null;tier:string}){
 const router=useRouter(),[query,setQuery]=useState(''),[editing,setEditing]=useState<string|null>(null),[title,setTitle]=useState(''),[busy,setBusy]=useState<string|null>(null),[pendingDelete,setPendingDelete]=useState<string|null>(null),[error,setError]=useState('');
 const filtered=useMemo(()=>{const clean=query.trim().toLowerCase();return clean?conversations.filter(item=>item.title.toLowerCase().includes(clean)):conversations;},[conversations,query]);
 const groups=useMemo(()=>{const result=new Map<string,Conversation[]>();for(const item of filtered){const label=groupLabel(item.last_message_at),bucket=result.get(label)||[];bucket.push(item);result.set(label,bucket);}return [...result.entries()];},[filtered]);
 const baseNew=selectedOrganizationId?`/orby?conversation=new&organization=${encodeURIComponent(selectedOrganizationId)}`:'/orby?conversation=new';
 async function mutate(conversationId:string,action:'rename'|'archive',nextTitle?:string){setBusy(conversationId);setError('');try{const response=await fetch('/api/orby/conversations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId,action,title:nextTitle})}),data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر تحديث المحادثة.');setEditing(null);router.refresh();if(action==='archive'&&selectedId===conversationId)router.push(baseNew);}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحديث المحادثة.');}finally{setBusy(null);}}
 async function remove(conversationId:string){setBusy(conversationId);setError('');try{const response=await fetch(`/api/orby/conversations?conversationId=${encodeURIComponent(conversationId)}`,{method:'DELETE'}),data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر حذف المحادثة.');setPendingDelete(null);router.refresh();if(selectedId===conversationId)router.push(baseNew);}catch(reason){setError(reason instanceof Error?reason.message:'تعذر حذف المحادثة.');throw reason;}finally{setBusy(null);}}
 return <div className="md-orby-sidebar" aria-label="قائمة أوربي">
  <section><div className="md-orby-sidebar-heading"><h2>المحادثات</h2><ButtonLink href={baseNew} size="sm" variant="secondary">جديدة</ButtonLink></div><Field label="البحث في المحادثات"><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="اكتب جزءًا من العنوان…" type="search"/></Field>{error?<p role="alert" className="md-orby-sidebar-error">{error}</p>:null}<div className="md-orby-conversation-groups">{groups.length?groups.map(([label,items])=><section key={label}><h3>{label}</h3><div>{items.map(item=><article key={item.id} className={selectedId===item.id?'md-orby-conversation is-active':'md-orby-conversation'}>{editing===item.id?<form onSubmit={event=>{event.preventDefault();void mutate(item.id,'rename',title);}} className="md-stack md-stack-sm"><Input autoFocus value={title} onChange={event=>setTitle(event.target.value)} minLength={2} maxLength={120}/><div className="flex gap-1"><Button size="sm" loading={busy===item.id}>حفظ</Button><Button size="sm" type="button" onClick={()=>setEditing(null)} variant="ghost">إلغاء</Button></div></form>:<><Link href={`/orby?conversation=${item.id}`} className="md-orby-conversation-link"><strong>{item.title}</strong><span><span>{serviceLabel(item.service_code)}</span><time dateTime={item.last_message_at}>{formatDate(item.last_message_at)}</time></span></Link><div className="md-orby-conversation-actions"><Button size="sm" variant="ghost" onClick={()=>{setEditing(item.id);setTitle(item.title);}}>تسمية</Button><Button size="sm" variant="ghost" disabled={busy===item.id} onClick={()=>void mutate(item.id,'archive')}>أرشفة</Button><Button size="sm" variant="danger" disabled={busy===item.id} onClick={()=>setPendingDelete(item.id)}>حذف</Button></div></>}</article>)}</div></section>):<EmptyState compact title={query?'لا توجد نتائج مطابقة':'لا توجد محادثات بعد'} description={query?'جرّب كلمات بحث أخرى.':'ابدأ أول محادثة مع ORBY.'}/>}</div></section>
  <section className="md-orby-sidebar-section"><h2>سياق الخدمة</h2><div className="md-orby-scope-list"><Link href="/orby?conversation=new" aria-current={!selectedOrganizationId?'page':undefined}>محادثة عامة</Link>{scopes.map(scope=><Link key={scope.organizationId} href={`/orby?conversation=new&organization=${scope.organizationId}`} aria-current={selectedOrganizationId===scope.organizationId?'page':undefined}><strong>{scope.name}</strong><span>{serviceLabel(scope.serviceCode)}</span></Link>)}</div></section>
  <section className="md-orby-sidebar-section"><h2>اختصارات الطلب</h2><div className="md-orby-shortcuts"><ButtonLink href={`${baseNew}&starter=analysis`} variant="outline" size="sm">تحليل</ButtonLink><ButtonLink href={`${baseNew}&starter=plan`} variant="outline" size="sm">خطة</ButtonLink><ButtonLink href={`${baseNew}&starter=report`} variant="outline" size="sm">تقرير</ButtonLink></div><p className="md-type-caption md-muted mt-2">يمكنك طلب الشيء نفسه بكتابته طبيعيًا.</p></section>
  <section className="md-orby-sidebar-section"><div className="md-orby-plan-row"><span>الخطة</span><strong>{tier==='plus'?'ORBY Plus':tier==='customer'?'عميل مَدار':'ORBY Free'}</strong></div><div className="md-orby-scope-list"><Link href="/orby/plus">إدارة ORBY Plus</Link><Link href="/account/privacy">الخصوصية والبيانات</Link></div></section>
  <ConfirmDialog open={Boolean(pendingDelete)} onClose={()=>setPendingDelete(null)} title="حذف المحادثة؟" description="سيتم حذف هذه المحادثة ورسائلها نهائيًا." confirmLabel="حذف المحادثة" danger busy={Boolean(pendingDelete&&busy===pendingDelete)} onConfirm={()=>pendingDelete?remove(pendingDelete):Promise.resolve()}/>
 </div>;
}
