'use server';
import { cookies } from 'next/headers';import { redirect } from 'next/navigation';import { supabaseConfig,siteUrl } from '@/src/lib/env';import { safeReturnTo } from '@/src/lib/auth';import { email,password } from '@/src/lib/validation';
async function auth(path:string,body:unknown){const {url,key}=supabaseConfig();const r=await fetch(`${url}/auth/v1/${path}`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const json=await r.json();if(!r.ok)throw new Error(json.msg||json.error_description||'تعذر إتمام العملية.');return json;}
const cookieOptions=(maxAge:number)=>({httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge});
async function setSession(session:{access_token:string;refresh_token:string;expires_in:number}){const jar=await cookies();jar.set('madar-access-token',session.access_token,cookieOptions(session.expires_in));jar.set('madar-refresh-token',session.refresh_token,cookieOptions(60*60*24*30));}
export async function login(form:FormData){try{const result=await auth('token?grant_type=password',{email:email(String(form.get('email')||'')),password:password(String(form.get('password')||''))});await setSession(result);redirect(safeReturnTo(String(form.get('next')||''),'/dashboard'));}catch(e){return {error:e instanceof Error?e.message:'تعذر تسجيل الدخول.'};}}
export async function register(form:FormData){try{const full_name=String(form.get('full_name')||'').trim();if(full_name.length<2)throw new Error('الاسم الكامل يجب أن يكون حرفين على الأقل.');const userEmail=email(String(form.get('email')||''));const userPassword=password(String(form.get('password')||''),String(form.get('confirm')||''));if(form.get('terms')!=='on')throw new Error('يلزم قبول الشروط.');await auth('signup',{email:userEmail,password:userPassword,data:{full_name},options:{emailRedirectTo:`${siteUrl()}/auth/callback`}});return {success:'أرسلنا رسالة تأكيد إلى بريدك الإلكتروني.'};}catch(e){return {error:e instanceof Error?e.message:'تعذر إنشاء الحساب.'};}}
export async function forgotPassword(form:FormData){try{const userEmail=String(form.get('email')||'').trim();if(/^\S+@\S+\.\S+$/.test(userEmail))await auth('recover',{email:userEmail,options:{redirectTo:`${siteUrl()}/auth/callback?next=/reset-password`}});return {success:'إذا كان البريد مسجلاً، ستصلك رسالة استعادة.'};}catch{return {success:'إذا كان البريد مسجلاً، ستصلك رسالة استعادة.'};}}
export async function resetPassword(_previous:unknown,form:FormData){try{const value=password(String(form.get('password')||''),String(form.get('confirm')||''));const {currentUser,supabaseFetch}=await import('@/src/lib/supabase/server');if(!await currentUser())throw new Error('انتهت جلسة الاستعادة؛ اطلب رابطاً جديداً.');await supabaseFetch('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:value})});return {success:'تم تغيير كلمة المرور بنجاح. يمكنك تسجيل الدخول بها الآن.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر تغيير كلمة المرور.'};}}
export async function logout(){const jar=await cookies();jar.set('madar-access-token','',{...cookieOptions(0),maxAge:0});jar.set('madar-refresh-token','',{...cookieOptions(0),maxAge:0});redirect('/');}
export async function updateProfile(form:FormData){const {currentUser,supabaseFetch}=await import('@/src/lib/supabase/server');const user=await currentUser();if(!user)return {error:'يجب تسجيل الدخول.'};try{const full_name=String(form.get('full_name')||'').trim();if(full_name.length<2)throw new Error('الاسم الكامل يجب أن يكون حرفين على الأقل.');await supabaseFetch(`/rest/v1/profiles?id=eq.${user.id}`,{method:'PATCH',body:JSON.stringify({full_name,phone:String(form.get('phone')||'').trim()||null})});return {success:'تم حفظ الملف الشخصي.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر حفظ الملف الشخصي.'};}}
