'use server';
import{revalidatePath}from'next/cache';
import{requireUser}from'@/src/lib/auth';
import{supabaseFetch}from'@/src/lib/supabase/server';
import{removeLocalPaymentProof,uploadLocalPaymentProof}from'@/src/lib/local-payments';
export type CheckoutState={error?:string;orderId?:string};
const messages:Record<string,string>={PRODUCT_UNAVAILABLE:'المنتج غير متاح للشراء.',PRODUCT_FILE_REQUIRED:'ملف المنتج غير جاهز بعد.',PAYMENT_REFERENCE_REQUIRED:'رقم الحوالة أو العملية إلزامي.',PAYMENT_CURRENCY_INACTIVE:'عملة الدفع غير متاحة.',ORIGINAL_CURRENCY_INACTIVE:'عملة المنتج غير مفعلة.',PAYMENT_METHOD_UNAVAILABLE:'وسيلة الدفع غير متاحة.',PAYMENT_METHOD_CURRENCY_UNAVAILABLE:'وسيلة الدفع لا تقبل العملة المختارة.',FX_RATE_MISSING:'لا يوجد سعر صرف معتمد بين العملتين حاليًا.'};
function friendly(error:unknown){const value=error instanceof Error?error.message:'';for(const[k,v]of Object.entries(messages))if(value.includes(k))return v;return value&&/^[\u0600-\u06ff]/.test(value)?value:'تعذر إنشاء طلب الشراء.'}
export async function createProductPaymentRequest(_previous:CheckoutState,form:FormData):Promise<CheckoutState>{let proof:Awaited<ReturnType<typeof uploadLocalPaymentProof>>|undefined;try{const user=await requireUser(),orderId=crypto.randomUUID(),productId=String(form.get('product_id')||''),paymentCurrency=String(form.get('payment_currency')||'').trim().toUpperCase(),paymentMethodId=String(form.get('payment_method_id')||''),reference=String(form.get('payment_reference')||'').trim();if(!/^[0-9a-f-]{36}$/i.test(productId)||!/^[0-9a-f-]{36}$/i.test(paymentMethodId))throw new Error('بيانات الطلب غير صالحة.');if(reference.length<3||reference.length>120)throw new Error('PAYMENT_REFERENCE_REQUIRED');const file=form.get('proof');if(file instanceof File&&file.size)proof=await uploadLocalPaymentProof(file,user.id,`store/${orderId}`);const result=await supabaseFetch('/rest/v1/rpc/create_product_payment_request',{method:'POST',body:JSON.stringify({p_order_id:orderId,p_product_id:productId,p_payment_currency:paymentCurrency,p_payment_method_id:paymentMethodId,p_payment_reference:reference,p_proof_path:proof?.storagePath??null,p_proof_name:proof?.originalFilename??null,p_proof_mime:proof?.mimeType??null,p_proof_size:proof?.fileSize??null})});const created=String(result||orderId);revalidatePath('/admin/orders');revalidatePath('/account/orders');revalidatePath('/account/notifications');return{orderId:created}}catch(error){if(proof)await removeLocalPaymentProof(proof.storagePath);return{error:friendly(error)}}}
