'use server';
import { revalidatePath } from 'next/cache';
import { requireUser } from '@/src/lib/auth';
import { supabaseFetch } from '@/src/lib/supabase/server';
import { required } from '@/src/lib/validation';
import { organizationTypes, workspaceSlug } from '@/src/lib/workspace';
export async function createWorkspace(form:FormData){try{await requireUser();const name=required(form.get('name'),'اسم المساحة');const slug=workspaceSlug(String(form.get('slug')||name));const type=String(form.get('type'));
if(slug.length<3)throw new Error('استخدم رابطاً مختصراً من 3 أحرف إنجليزية أو أرقام على الأقل.');if(!organizationTypes.includes(type as typeof organizationTypes[number]))throw new Error('نوع الحساب غير صالح.');
await supabaseFetch('/rest/v1/rpc/create_organization',{method:'POST',body:JSON.stringify({workspace_name:name,workspace_slug:slug,workspace_type:type})});revalidatePath('/dashboard');return {success:'تم إنشاء مساحتك بنجاح.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر إنشاء المساحة. حاول مرة أخرى.'};}}
export async function updateWorkspace(_previous:unknown,form:FormData){try{const user=await requireUser();const id=required(form.get('id'),'المساحة');const name=required(form.get('name'),'اسم المساحة');const type=String(form.get('type'));if(!organizationTypes.includes(type as typeof organizationTypes[number]))throw new Error('نوع الحساب غير صالح.');
const rows=await supabaseFetch(`/rest/v1/organization_members?organization_id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(user.id)}&select=role`);if(rows?.[0]?.role!=='OWNER')throw new Error('مالك المساحة فقط يستطيع تعديل إعداداتها.');
await supabaseFetch(`/rest/v1/organizations?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({name,type,description:String(form.get('description')||'').trim()||null,whatsapp:String(form.get('whatsapp')||'').trim()||null,website:String(form.get('website')||'').trim()||null,country:String(form.get('country')||'').trim()||null,city:String(form.get('city')||'').trim()||null})});revalidatePath('/dashboard');revalidatePath('/account/business');return {success:'تم حفظ إعدادات المساحة.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر حفظ الإعدادات.'};}}
export async function manageWorkspaceMember(_previous:unknown,form:FormData){try{await requireUser();const organizationId=required(form.get('organization_id'),'المساحة');const memberEmail=required(form.get('email'),'البريد الإلكتروني');const role=String(form.get('role')||'MEMBER');const operation=String(form.get('operation')||'add');if(!['MEMBER','ADMIN'].includes(role)||!['add','remove'].includes(operation))throw new Error('طلب إدارة العضوية غير صالح.');await supabaseFetch('/rest/v1/rpc/manage_organization_member',{method:'POST',body:JSON.stringify({target_organization:organizationId,target_email:memberEmail,requested_role:role,operation})});revalidatePath('/account/business/members');return {success:operation==='add'?'تمت إضافة العضو.':'تمت إزالة العضو.'};}catch(error){return {error:error instanceof Error?error.message:'تعذر تحديث العضوية.'};}}
