import type { Metadata } from "next";
import Link from "next/link";
import { Brand } from "@/components/retail-v0/layout/brand";
import { FlashMessage } from "@/components/retail-v0/ui/flash-message";
import { SubmitButton } from "@/components/retail-v0/ui/submit-button";
import { formatDateTime, formatMoney } from "@/src/lib/retail/format";
import { createClient } from "@/src/lib/retail/supabase/server";
import { relationName } from "@/src/lib/retail/relations";
import { requirePlatformAdmin } from "@/src/lib/retail/server/auth/context";
import { reviewPaymentAction, setWorkspaceStatusAction, upsertPaymentMethodAction, upsertPlanAction } from "./actions";

export const metadata: Metadata = { title: "إدارة MADAR Retail" };

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const [, params] = await Promise.all([requirePlatformAdmin(), searchParams]);
  const supabase = await createClient();
  const [profiles, workspaces, subscriptions, paymentRequests, plans, methods, audits, devices] = await Promise.all([
    supabase.from("profiles").select("id,email,full_name,platform_role,status,created_at").order("created_at", { ascending: false }).limit(100),
    supabase.from("retail_workspaces").select("id,name,status,currency,created_at").order("created_at", { ascending: false }).limit(100),
    supabase.from("subscriptions").select("id,workspace_id,status,trial_ends_at,ends_at,retail_workspaces(name),plans(name_ar)").order("created_at", { ascending: false }).limit(100),
    supabase.from("payment_requests").select("id,workspace_id,amount,currency,status,payment_reference,proof_path,created_at,retail_workspaces(name),plans(name_ar),payment_methods(name_ar)").order("created_at", { ascending: false }).limit(50),
    supabase.from("plans").select("id,code,name_ar,status,is_public,price_amount,currency,billing_months,trial_days,limits").order("created_at"),
    supabase.from("payment_methods").select("id,code,name_ar,status,kind,account_identifier,currency").order("sort_order"),
    supabase.from("audit_logs").select("id,action,entity_type,workspace_id,created_at,metadata").order("created_at", { ascending: false }).limit(60),
    supabase.from("sync_devices").select("id,status,last_seen_at").limit(1000),
  ]);
  const errors = [profiles, workspaces, subscriptions, paymentRequests, plans, methods, audits, devices].filter((result) => result.error);
  if (errors.length) throw errors[0]?.error;
  const pending = (paymentRequests.data ?? []).filter((request) => request.status === "under_review");
  const suspended = (workspaces.data ?? []).filter((workspace) => workspace.status === "suspended").length;
  const activeDevices = (devices.data ?? []).filter((device) => device.status === "active").length;
  return <main className="container-shell py-6"><header className="flex flex-wrap items-center justify-between gap-4"><Brand /><div className="flex gap-2"><Link className="button-secondary" href="/retail/workspace">مساحة التجارة</Link><span className="status-pill">Retail Admin</span></div></header><div className="mt-7 content-grid"><FlashMessage {...params} />
    <div><p className="eyebrow">PLATFORM OPERATIONS</p><h1 className="mt-1 text-3xl font-black">إدارة MADAR Retail</h1><p className="muted mt-1">لوحة صغيرة للمستخدمين والمساحات والاشتراكات والدفع والصحة.</p></div>
    <section className="metric-grid">{[["المستخدمون", profiles.data?.length ?? 0], ["المساحات", workspaces.data?.length ?? 0], ["طلبات بانتظار المراجعة", pending.length], ["مساحات موقوفة", suspended], ["أجهزة مزامنة نشطة", activeDevices], ["خطط معرفة", plans.data?.length ?? 0]].map(([label, value]) => <article className="surface metric-card" key={String(label)}><p className="muted text-xs">{label}</p><p className="value">{value}</p></article>)}</section>
    <section className="surface p-5"><h2 className="text-lg font-black">طلبات الدفع</h2><div className="mt-4 grid gap-3">{pending.map((request) => <article className="surface-soft p-4" key={request.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{relationName(request.retail_workspaces)}</strong><p className="muted text-xs">{request.payment_reference} · {formatDateTime(request.created_at)}</p></div><strong>{formatMoney(request.amount, request.currency)}</strong></div><p className="muted mt-2 text-sm">الإثبات محفوظ في مسار خاص: {request.proof_path}</p><form action={reviewPaymentAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="request_id" value={request.id} /><input className="input max-w-md" name="note" placeholder="ملاحظة المراجعة" /><button className="button-primary" name="decision" value="approve">موافقة</button><button className="button-danger" name="decision" value="reject">رفض</button></form></article>)}{!pending.length ? <p className="muted py-8 text-center">لا توجد طلبات معلقة.</p> : null}</div></section>
    <section className="grid gap-4 xl:grid-cols-2"><article className="surface p-5"><h2 className="text-lg font-black">المساحات والاشتراكات</h2><div className="mt-3 grid gap-2">{(workspaces.data ?? []).map((workspace) => { const sub = subscriptions.data?.find((item) => item.workspace_id === workspace.id); return <div className="surface-soft p-3" key={workspace.id}><div className="flex justify-between gap-3"><div><strong>{workspace.name}</strong><p className="muted text-xs">{sub?.status ?? "دون اشتراك"} · {workspace.currency}</p></div><span className={`status-pill ${workspace.status === "suspended" ? "status-danger" : ""}`}>{workspace.status}</span></div><form action={setWorkspaceStatusAction} className="mt-3 flex gap-2"><input type="hidden" name="workspace_id" value={workspace.id} /><input type="hidden" name="note" value="Admin console" /><button className={workspace.status === "suspended" ? "button-primary !min-h-9 text-xs" : "button-danger !min-h-9 text-xs"} name="status" value={workspace.status === "suspended" ? "active" : "suspended"}>{workspace.status === "suspended" ? "إعادة التفعيل" : "إيقاف"}</button></form></div>; })}</div></article><article className="surface p-5"><h2 className="text-lg font-black">المستخدمون</h2><div className="table-wrap mt-3"><table className="data-table"><thead><tr><th>الاسم</th><th>البريد</th><th>الدور</th><th>الحالة</th></tr></thead><tbody>{(profiles.data ?? []).map((profile) => <tr key={profile.id}><td>{profile.full_name ?? "—"}</td><td dir="ltr">{profile.email}</td><td>{profile.platform_role}</td><td>{profile.status}</td></tr>)}</tbody></table></div></article></section>
    <section className="grid gap-4 xl:grid-cols-2"><form action={upsertPlanAction} className="surface grid gap-3 p-5"><h2 className="text-lg font-black">خطة جديدة/معتمدة</h2><div className="grid grid-cols-2 gap-3"><label className="field"><span>Code</span><input className="input" name="code" dir="ltr" placeholder="RETAIL_MONTHLY" required /></label><label className="field"><span>الاسم</span><input className="input" name="name_ar" required /></label></div><label className="field"><span>الوصف</span><input className="input" name="description_ar" /></label><div className="grid grid-cols-2 gap-3"><label className="field"><span>السعر (اختياري)</span><input className="input" type="number" name="price_amount" min="0" step="0.01" /></label><label className="field"><span>العملة</span><input className="input" name="currency" value="YER" readOnly /></label></div><div className="grid grid-cols-3 gap-3"><label className="field"><span>أشهر</span><input className="input" type="number" name="billing_months" min="1" max="36" defaultValue="1" required /></label><label className="field"><span>تجربة</span><input className="input" type="number" name="trial_days" min="0" max="90" defaultValue="0" /></label><label className="field"><span>سماح</span><input className="input" type="number" name="grace_days" min="0" max="30" defaultValue="0" /></label></div><label className="field"><span>الحالة</span><select className="input" name="status"><option value="draft">مسودة</option><option value="active">نشطة</option></select></label><label className="surface-soft flex gap-3 p-3"><input type="checkbox" name="is_public" /><span>إظهار للعملاء</span></label><SubmitButton>حفظ الخطة</SubmitButton></form>
      <form action={upsertPaymentMethodAction} className="surface grid gap-3 p-5"><h2 className="text-lg font-black">طريقة دفع محلية</h2><div className="grid grid-cols-2 gap-3"><label className="field"><span>Code</span><input className="input" name="code" dir="ltr" placeholder="LOCAL_TRANSFER" required /></label><label className="field"><span>الاسم</span><input className="input" name="name_ar" required /></label></div><label className="field"><span>النوع</span><select className="input" name="kind"><option value="MANUAL">يدوي</option><option value="LOCAL_WALLET">محفظة محلية</option><option value="BANK_TRANSFER">تحويل بنكي</option></select></label><div className="grid grid-cols-2 gap-3"><label className="field"><span>اسم الحساب</span><input className="input" name="account_name" /></label><label className="field"><span>رقم الحساب</span><input className="input" name="account_identifier" dir="ltr" /></label></div><label className="field"><span>التعليمات</span><textarea className="input" name="instructions_ar" /></label><input type="hidden" name="currency" value="YER" /><label className="field"><span>الحالة</span><select className="input" name="status"><option value="draft">مسودة</option><option value="active">نشطة</option><option value="disabled">معطلة</option></select></label><SubmitButton>حفظ الطريقة</SubmitButton></form></section>
    <section className="surface p-5"><h2 className="text-lg font-black">آخر سجلات التدقيق</h2><div className="table-wrap mt-3"><table className="data-table"><thead><tr><th>الوقت</th><th>الإجراء</th><th>الكيان</th><th>Workspace</th></tr></thead><tbody>{(audits.data ?? []).map((audit) => <tr key={audit.id}><td>{formatDateTime(audit.created_at)}</td><td>{audit.action}</td><td>{audit.entity_type}</td><td dir="ltr">{audit.workspace_id ?? "GLOBAL"}</td></tr>)}</tbody></table></div></section>
  </div></main>;
}
