import {NextResponse} from 'next/server';
import {currentUser,supabaseFetch,type AuthUser} from '@/src/lib/supabase/server';

export const runtime='nodejs';
export const dynamic='force-dynamic';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const allowed=new Set(['TASK_STATUS_UPDATE','KITCHEN_TICKET_STATUS','HOUSEKEEPING_STATUS']);
type Fetcher=(path:string,init?:RequestInit)=>Promise<unknown>;
type MobileAuth={user:AuthUser;fetcher:Fetcher};
const tokenFrom=(request:Request)=>{const header=request.headers.get('authorization')||'';const[scheme,token]=header.split(/\s+/,2);return scheme?.toLowerCase()==='bearer'&&token?token:undefined;};

async function context(request:Request,organizationId:string):Promise<{auth?:MobileAuth;response?:NextResponse}>{const token=tokenFrom(request),user=await currentUser(token);if(!user)return{response:NextResponse.json({error:'يجب تسجيل الدخول أولًا.'},{status:401})};const fetcher:Fetcher=(path,init={})=>supabaseFetch(path,init,token);if(!uuid.test(organizationId))return{response:NextResponse.json({error:'لا تملك صلاحية هذه المساحة.'},{status:403})};const memberships=await fetcher(`/rest/v1/organization_members?organization_id=eq.${encodeURIComponent(organizationId)}&user_id=eq.${encodeURIComponent(user.id)}&select=organization_id,organizations(type,status)`) as Array<{organizations?:{type?:string;status?:string}}> ;if(memberships[0]?.organizations?.status!=='active'||memberships[0]?.organizations?.type==='STUDENT')return{response:NextResponse.json({error:'لا تملك صلاحية هذه المساحة.'},{status:403})};return{auth:{user,fetcher}};}
function actionError(error:unknown){const message=error instanceof Error?error.message:String(error||'');if(message.includes('ENTITLEMENT')||message.includes('PERMISSION')||message.includes('MANAGER'))return NextResponse.json({error:'هذه الكتابة غير متاحة ضمن الباقة أو الصلاحيات الحالية.'},{status:403});if(message.includes('CONFLICT'))return NextResponse.json({error:'تغير السجل منذ إنشاء المعاينة. حدّث البيانات وأنشئ معاينة جديدة.'},{status:409});return NextResponse.json({error:'تعذر إنشاء معاينة الإجراء. تحقق من البيانات وحاول مجددًا.'},{status:400});}

export async function GET(request:Request){const organizationId=new URL(request.url).searchParams.get('organizationId')||'',resolved=await context(request,organizationId);if(resolved.response)return resolved.response;try{const actions=await resolved.auth!.fetcher(`/rest/v1/mobile_action_status?organization_id=eq.${encodeURIComponent(organizationId)}&user_id=eq.${encodeURIComponent(resolved.auth!.user.id)}&select=id,action_type,entity_type,entity_id,source_of_truth,preview,result,status,effective_status,error_code,external_error_code,expires_at,confirmed_at,completed_at,created_at,updated_at&order=created_at.desc&limit=50`);return NextResponse.json({ok:true,actions},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل سجل الإجراءات.'},{status:503});}}

export async function POST(request:Request){const body=await request.json() as Record<string,unknown>,organizationId=String(body.organizationId||''),resolved=await context(request,organizationId);if(resolved.response)return resolved.response;const actionType=String(body.actionType||'').toUpperCase(),entityId=String(body.entityId||''),status=String(body.status||''),idempotencyKey=String(body.idempotencyKey||''),connectionId=body.connectionId?String(body.connectionId):null;if(!allowed.has(actionType)||!uuid.test(entityId)||idempotencyKey.length<8||idempotencyKey.length>160||connectionId&&!uuid.test(connectionId))return NextResponse.json({error:'بيانات الإجراء غير صالحة.'},{status:400});try{const result=await resolved.auth!.fetcher('/rest/v1/rpc/preview_mobile_action_v2',{method:'POST',body:JSON.stringify({target_organization:organizationId,action_type:actionType,entity_id:entityId,desired_change:{status},idempotency_key:idempotencyKey,target_connection:connectionId})});return NextResponse.json({ok:true,action:Array.isArray(result)?result[0]:result},{status:201,headers:{'Cache-Control':'no-store'}});}catch(error){return actionError(error);}}
