import type {Connector,ConnectorBatch,ConnectorContext,ConnectorManifest,ConnectorSyncRequest,JsonObject} from '../contracts';
import {oauthTokenExpiresSoon} from '../auth';
import {IntegrationError} from '../errors';
import {defaultCsvFixture,defaultExcelXmlFixture,historicalLabData,incrementalLabData,operationalWebhookEvents} from '../lab/fixtures';

const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const jsonObject=(value:unknown):value is JsonObject=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const pageSize=(request:ConnectorSyncRequest,context:ConnectorContext)=>Math.min(100,Math.max(1,Number(request.pageSize||context.connection.config.pageSize||25)));
const cursor=(context:ConnectorContext,key:string)=>{const value=context.checkpoints[key]?.cursor;return typeof value==='number'&&value>=0?Math.floor(value):0;};
const selected=(manifest:ConnectorManifest,request:ConnectorSyncRequest)=>{const available=new Set(manifest.streams.map(stream=>stream.key));const requested=request.streams?.filter(key=>available.has(key));return requested?.length?requested:[...available];};

async function* batches(context:ConnectorContext,request:ConnectorSyncRequest,manifest:ConnectorManifest,data:Record<string,JsonObject[]>,options:{disconnectAfterBatch?:number|null}={}):AsyncIterable<ConnectorBatch>{
 const size=pageSize(request,context);
 for(const stream of selected(manifest,request)){
  const records=data[stream]||[];let offset=cursor(context,stream);
  while(offset<records.length){
   if(context.signal.aborted)throw new DOMException('Aborted','AbortError');
   const end=Math.min(records.length,offset+size),batchNumber=Math.floor(offset/size)+1,page=records.slice(offset,end);
   yield {streamKey:stream,records:page,nextCursor:end,watermark:new Date(Date.parse('2026-01-01T00:00:00.000Z')+end*60_000).toISOString(),hasMore:end<records.length,metadata:{technicalLab:true,batchNumber}};
   if(options.disconnectAfterBatch===batchNumber)throw new IntegrationError('انقطع Local Bridge المصطنع بعد دفعة محفوظة.','SOURCE_UNAVAILABLE',true,{stream,batchNumber,checkpoint:end});
   offset=end;
  }
 }
}

function authPresent(context:ConnectorContext){
 if(context.authScheme==='api_key'&&typeof context.secret.value!=='string')throw new IntegrationError('مفتاح REST التجريبي مفقود.','AUTHENTICATION_FAILED',false);
 if(context.authScheme==='bearer'&&typeof context.secret.token!=='string')throw new IntegrationError('رمز Bearer التجريبي مفقود.','AUTHENTICATION_FAILED',false);
 if(context.authScheme==='oauth2'){
  if(typeof context.secret.accessToken!=='string')throw new IntegrationError('رمز OAuth التجريبي مفقود.','AUTHENTICATION_FAILED',false);
  if(oauthTokenExpiresSoon(context.secret,0)&&typeof context.secret.refreshToken!=='string')throw new IntegrationError('انتهت صلاحية OAuth ولا يوجد Refresh Token.','AUTHENTICATION_FAILED',false,{expired:true});
 }
}

const restManifest:ConnectorManifest={key:'madar-test-rest',version:'1.0.0',displayName:'MADAR REST Test Connector',description:'موصل REST داخلي يحاكي pagination والمصادقة والمزامنة التاريخية والتزايدية.',authSchemes:['api_key','bearer','oauth2'],streams:[{key:'rest.products',label:'REST products',supportsInitial:true,supportsIncremental:true,defaultPageSize:3},{key:'rest.customers',label:'REST customers',supportsInitial:true,supportsIncremental:true,defaultPageSize:3}],capabilities:{read:true,write:false,webhooks:false,polling:true,files:false,database:false,localBridge:false},internalOnly:true};
const restData=(incremental=false)=>{const source=incremental?incrementalLabData():historicalLabData();return {'rest.products':source.products,'rest.customers':source.customers};};
export const restTestConnector:Connector={manifest:restManifest,validateConfig(input){const value=object(input),baseUrl=typeof value.baseUrl==='string'&&value.baseUrl.trim()?value.baseUrl.trim():'mock://madar-commerce';if(!/^(mock|https):\/\//.test(baseUrl))return {valid:false,issues:[{path:'baseUrl',message:'يجب استخدام mock:// أو HTTPS في موصل REST التجريبي.'}]};return {valid:true,normalizedConfig:{baseUrl,pageSize:Math.min(100,Math.max(1,Number(value.pageSize)||3))}};},async testConnection(context){authPresent(context);return {ok:true,latencyMs:1,accountLabel:'MADAR REST sandbox',grantedScopes:['read:products','read:customers'],warnings:context.authScheme==='oauth2'&&oauthTokenExpiresSoon(context.secret)?['تمت محاكاة تحديث رمز OAuth باستخدام Refresh Token.']:[]};},initialSync(context,request){authPresent(context);return batches(context,request,restManifest,restData(false));},incrementalSync(context,request){authPresent(context);return batches(context,request,restManifest,restData(true));}};

const webhookManifest:ConnectorManifest={key:'madar-test-webhook',version:'1.0.0',displayName:'MADAR Webhook Test Connector',description:'موصل داخلي يعيد تشغيل صندوق أحداث Webhook موقّع ومحدد الترتيب.',authSchemes:['custom'],streams:[{key:'webhook.events',label:'Webhook events',supportsInitial:true,supportsIncremental:true,defaultPageSize:10}],capabilities:{read:true,write:false,webhooks:true,polling:false,files:false,database:false,localBridge:false},internalOnly:true};
function webhookData(context:ConnectorContext){const configured=context.connection.config.events,events=Array.isArray(configured)?configured.filter(jsonObject):operationalWebhookEvents();return {'webhook.events':events};}
export const webhookTestConnector:Connector={manifest:webhookManifest,validateConfig(input){const value=object(input),events=Array.isArray(value.events)?value.events.filter(jsonObject):operationalWebhookEvents();return {valid:true,normalizedConfig:{events,maxReplay:Math.min(1000,Math.max(1,Number(value.maxReplay)||100))}};},async testConnection(context){if(typeof context.secret.signingSecret!=='string')return {ok:false,latencyMs:0,warnings:['Webhook signing secret is missing']};return {ok:true,latencyMs:0,accountLabel:'MADAR Webhook inbox',grantedScopes:['receive:webhooks','replay:webhooks']};},initialSync(context,request){return batches(context,request,webhookManifest,webhookData(context));},incrementalSync(context,request){return batches(context,request,webhookManifest,webhookData(context));}};

function decodeXml(value:string){return value.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();}
function parseCsvLine(line:string){const cells:string[]=[];let value='',quoted=false;for(let index=0;index<line.length;index++){const char=line[index];if(char==='"'){if(quoted&&line[index+1]==='"'){value+='"';index++;}else quoted=!quoted;}else if(char===','&&!quoted){cells.push(value.trim());value='';}else value+=char;}cells.push(value.trim());return cells;}
function rowsFromMatrix(matrix:string[][],entityType:string){const headers=matrix[0]||[];return matrix.slice(1).filter(row=>row.some(Boolean)).map(row=>Object.fromEntries([...headers.map((header,index)=>[header||`column_${index+1}`,row[index]??'']),['entity_type',entityType]]) as JsonObject);}
function parseFileRows(format:string,content:string,entityType:string){if(format==='csv'){const matrix=content.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).map(parseCsvLine);return rowsFromMatrix(matrix,entityType);}const rows=[...content.matchAll(/<(?:\w+:)?Row\b[^>]*>([\s\S]*?)<\/(?:\w+:)?Row>/gi)].map(match=>[...match[1].matchAll(/<(?:\w+:)?Data\b[^>]*>([\s\S]*?)<\/(?:\w+:)?Data>/gi)].map(cell=>decodeXml(cell[1])));return rowsFromMatrix(rows,entityType);}
const fileManifest:ConnectorManifest={key:'madar-test-csv-excel',version:'1.0.0',displayName:'MADAR CSV & Excel Test Connector',description:'موصل ملفات داخلي يقرأ CSV وExcel SpreadsheetML دون كتابة أو تنفيذ صيغ.',authSchemes:['none'],streams:[{key:'file.rows',label:'File rows',supportsInitial:true,supportsIncremental:false,defaultPageSize:100}],capabilities:{read:true,write:false,webhooks:false,polling:false,files:true,database:false,localBridge:false},internalOnly:true};
function normalizedFileConfig(input:unknown){const value=object(input),format=value.format==='excel_xml'?'excel_xml':'csv',content=typeof value.content==='string'?value.content:(format==='excel_xml'?defaultExcelXmlFixture():defaultCsvFixture()),entityType=typeof value.entityType==='string'&&value.entityType.trim()?value.entityType.trim():'product';return {format,content:content.slice(0,1_000_000),entityType,pageSize:Math.min(500,Math.max(1,Number(value.pageSize)||100))};}
export const csvExcelTestConnector:Connector={manifest:fileManifest,validateConfig(input){const config=normalizedFileConfig(input);if(!config.content.trim())return {valid:false,issues:[{path:'content',message:'محتوى الملف التجريبي فارغ.'}]};return {valid:true,normalizedConfig:config};},async testConnection(context){const config=normalizedFileConfig(context.connection.config),rows=parseFileRows(config.format,config.content,config.entityType);return {ok:rows.length>0,latencyMs:0,accountLabel:config.format==='csv'?'CSV fixture':'Excel SpreadsheetML fixture',metadata:{rows:rows.length,formulasExecuted:false}};},initialSync(context,request){const config=normalizedFileConfig(context.connection.config);return batches(context,request,fileManifest,{'file.rows':parseFileRows(config.format,config.content,config.entityType)});},incrementalSync(context,request){return batches(context,request,fileManifest,{'file.rows':[]});}};

export function assertReadOnlySql(query:string){const normalized=query.replace(/--.*$/gm,' ').replace(/\/\*[\s\S]*?\*\//g,' ').trim();if(!/^(select|with)\b/i.test(normalized)||/\b(insert|update|delete|merge|alter|drop|truncate|create|grant|revoke|copy|call|execute|vacuum|analyze)\b/i.test(normalized)||normalized.replace(/;\s*$/,'').includes(';'))throw new IntegrationError('موصل قاعدة البيانات التجريبي يسمح باستعلام قراءة واحد فقط.','VALIDATION_ERROR',false,{readOnly:true});return normalized.replace(/;\s*$/,'');}
const databaseManifest:ConnectorManifest={key:'madar-test-database-readonly',version:'1.0.0',displayName:'MADAR Read-only Database Test Connector',description:'موصل قاعدة بيانات تقني يرفض DDL وDML ويعيد صفوف View تجريبية للقراءة فقط.',authSchemes:['database'],streams:[{key:'database.rows',label:'Database rows',supportsInitial:true,supportsIncremental:true,defaultPageSize:100}],capabilities:{read:true,write:false,webhooks:false,polling:true,files:false,database:true,localBridge:false},internalOnly:true};
function databaseConfig(input:unknown){const value=object(input),query=assertReadOnlySql(typeof value.query==='string'?value.query:'select * from madar_lab_products'),rows=Array.isArray(value.rows)?value.rows.filter(jsonObject):historicalLabData().products;return {query,rows,pageSize:Math.min(500,Math.max(1,Number(value.pageSize)||100))};}
export const databaseReadOnlyTestConnector:Connector={manifest:databaseManifest,validateConfig(input){try{return {valid:true,normalizedConfig:databaseConfig(input)};}catch(error){return {valid:false,issues:[{path:'query',message:error instanceof Error?error.message:'استعلام غير صالح.'}]};}},async testConnection(context){if(context.connection.mode!=='READ_ONLY')return {ok:false,latencyMs:0,warnings:['Database lab connector must remain READ_ONLY']};assertReadOnlySql(String(context.connection.config.query||''));return {ok:true,latencyMs:1,accountLabel:'Read-only database fixture',grantedScopes:['SELECT']};},initialSync(context,request){const config=databaseConfig(context.connection.config);return batches(context,request,databaseManifest,{'database.rows':config.rows});},incrementalSync(context,request){const changes=incrementalLabData().products;return batches(context,request,databaseManifest,{'database.rows':changes});}};

const bridgeManifest:ConnectorManifest={key:'madar-test-local-bridge',version:'1.0.0',displayName:'MADAR Local Bridge Simulator',description:'محاكاة وكيل محلي يرسل أغلفة مرتبة، يتوقف بعد دفعة، ثم يستأنف من Checkpoint.',authSchemes:['custom'],streams:[{key:'bridge.events',label:'Bridge envelopes',supportsInitial:true,supportsIncremental:true,defaultPageSize:2}],capabilities:{read:true,write:false,webhooks:false,polling:true,files:true,database:true,localBridge:true},internalOnly:true};
function bridgeData(context:ConnectorContext){const configured=context.connection.config.envelopes,envelopes=Array.isArray(configured)?configured.filter(jsonObject):operationalWebhookEvents();return {'bridge.events':envelopes};}
export const localBridgeTestConnector:Connector={manifest:bridgeManifest,validateConfig(input){const value=object(input),envelopes=Array.isArray(value.envelopes)?value.envelopes.filter(jsonObject):operationalWebhookEvents();return {valid:true,normalizedConfig:{envelopes,disconnectAfterBatch:Number.isInteger(Number(value.disconnectAfterBatch))?Number(value.disconnectAfterBatch):null,pageSize:Math.min(100,Math.max(1,Number(value.pageSize)||2))}};},async testConnection(context){if(typeof context.secret.bridgeToken!=='string')return {ok:false,latencyMs:0,warnings:['Local Bridge token is missing']};return {ok:true,latencyMs:2,accountLabel:'Local Bridge simulator',grantedScopes:['read:local-snapshot','replay:envelopes']};},initialSync(context,request){const disconnect=typeof context.connection.config.disconnectAfterBatch==='number'?context.connection.config.disconnectAfterBatch:null;return batches(context,request,bridgeManifest,bridgeData(context),{disconnectAfterBatch:disconnect});},incrementalSync(context,request){return batches(context,request,bridgeManifest,bridgeData(context));}};

const oauthManifest:ConnectorManifest={key:'madar-test-oauth',version:'1.0.0',displayName:'MADAR OAuth Expiry Simulator',description:'محاكاة OAuth2 لاختبار الرمز الصالح والمنتهي ووجود Refresh Token.',authSchemes:['oauth2'],streams:[{key:'oauth.orders',label:'OAuth orders',supportsInitial:true,supportsIncremental:true,defaultPageSize:3}],capabilities:{read:true,write:false,webhooks:false,polling:true,files:false,database:false,localBridge:false},internalOnly:true};
const oauthData=(incremental=false)=>({'oauth.orders':incremental?incrementalLabData().orders:historicalLabData().orders});
export const oauthTestConnector:Connector={manifest:oauthManifest,validateConfig(input){const value=object(input);return {valid:true,normalizedConfig:{tenant:typeof value.tenant==='string'?value.tenant:'madar-lab',pageSize:Math.min(100,Math.max(1,Number(value.pageSize)||3))}};},async testConnection(context){authPresent(context);return {ok:true,latencyMs:1,accountLabel:'OAuth sandbox',grantedScopes:['orders.read'],warnings:oauthTokenExpiresSoon(context.secret)?['Access Token منتهي؛ نجحت محاكاة التجديد عبر Refresh Token.']:[]};},initialSync(context,request){authPresent(context);return batches(context,request,oauthManifest,oauthData(false));},incrementalSync(context,request){authPresent(context);return batches(context,request,oauthManifest,oauthData(true));}};

export const readinessTechnicalConnectors=[restTestConnector,webhookTestConnector,csvExcelTestConnector,databaseReadOnlyTestConnector,localBridgeTestConnector,oauthTestConnector] as const;
