import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);const read=path=>readFile(new URL(path,root),'utf8');

test('Stage 4 exposes ORBY OS without replacing previous layers',async()=>{const index=await read('src/lib/orby/index.ts');assert.match(index,/export \* from '\.\/os'/);assert.match(index,/key:'orby-os'/);for(const prior of ["'\.\/execution'","'\.\/intelligence'"])assert.match(index,new RegExp(prior));});
test('workflow engine is versioned, bounded and reusable',async()=>{const [contracts,source]=await Promise.all([read('src/lib/orby/os/contracts.ts'),read('src/lib/orby/os/workflow.ts')]);assert.match(contracts,/version:number/);assert.match(source,/maxLoopIterations/);assert.match(source,/OrbyWorkflowCatalog/);for(const key of ['business.sales-drop-analysis','store.inventory-review','finance.overdue-payments-review','student.weekly-plan'])assert.match(source,new RegExp(key));});
test('plugins are compile-time and domain isolated',async()=>{const source=await read('src/lib/orby/os/plugins.ts');assert.match(source,/ENTRYPOINTS/);assert.match(source,/ORBY_PLUGIN_ENTRYPOINT_NOT_COMPILED/);for(const domain of ['business','store','finance','student'])assert.match(source,new RegExp(`key:'${domain}'`));assert.doesNotMatch(source,/eval\(|new Function|import\(manifest/);});
test('governance is deterministic and default deny',async()=>{const source=await read('src/lib/orby/os/governance.ts');assert.match(source,/default-deny/);assert.match(source,/deny-secret-storage/);assert.match(source,/deny-cross-tenant/);assert.match(source,/deny-external-channel/);assert.match(source,/require_approval/);});
test('operations include routing, costs, traces, evaluation and rollback',async()=>{const source=await read('src/lib/orby/os/operations.ts');for(const token of ['OrbyMultiModelRouter','OrbyBudgetEngine','OrbyObservability','OrbyEvaluationEngine','OrbyReleaseManager','circuit-open','rollback'])assert.match(source,new RegExp(token));});
test('database control plane is RLS protected and provider/OCR/channel gates stay closed',async()=>{const sql=await read('supabase/migrations/20260729190000_orby_os_v1.sql');for(const table of ['orby_os_releases','orby_feature_flags','orby_workflow_definitions','orby_plugins','orby_governance_policies','orby_traces','orby_cost_events','orby_evaluation_runs','orby_channels']){assert.match(sql,new RegExp(`create table if not exists public\\.${table}`));assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));}for(const flag of ['orby_provider_execution_enabled','orby_ocr_enabled','orby_external_channels_enabled'])assert.match(sql,new RegExp(`${flag}[^;]+false`,'s'));assert.doesNotMatch(sql,/api_key\s+(text|jsonb)|provider_secret\s+(text|jsonb)|dynamic_code/);});
test('admin control center and API are founder protected',async()=>{const page=await read('app/admin/orby-os/page.tsx'),actions=await read('app/admin/orby-os/actions.ts'),api=await read('app/api/orby/os/health/route.ts');assert.match(page,/requireSuperAdmin/);assert.match(actions,/requireSuperAdmin/);assert.match(api,/requireSuperAdmin/);assert.match(page,/ORBY OS v1/);});
