import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const safeReturnTo=(value,fallback='/account')=>value?.startsWith('/')&&!value.startsWith('//')?value:fallback;
const workspaceSlug=value=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80);
test('return paths reject open redirects',()=>{assert.equal(safeReturnTo('/dashboard'),'/dashboard');assert.equal(safeReturnTo('//evil.example'),'/account');assert.equal(safeReturnTo('https://evil.example'),'/account');});
test('workspace slug and type validation constraints are deterministic',()=>{assert.equal(workspaceSlug(' متجر تجريبي! '),'');assert.equal(workspaceSlug('My Store 2026'),'my-store-2026');assert.match('my-store-2026',/^[a-z0-9][a-z0-9-]{1,78}[a-z0-9]$/);});
test('migration creates an atomic owner membership and tenant isolation policies',()=>{const sql=fs.readFileSync('supabase/migrations/20260720000000_phase_two_workspaces.sql','utf8');assert.match(sql,/insert into public\.organization_members[\s\S]*'OWNER'/);assert.match(sql,/organization member read/);assert.match(sql,/organization owner update/);assert.match(sql,/prevent_last_organization_owner/);});
test('private digital storage remains protected in phase one',()=>{const sql=fs.readFileSync('supabase/migrations/20260719000000_phase_one.sql','utf8');assert.match(sql,/digital-products','digital-products',false/);assert.match(sql,/digital admin only/);});
test('member-management RPC limits admins and preserves ownership',()=>{const sql=fs.readFileSync('supabase/migrations/20260720010000_member_management.sql','utf8');assert.match(sql,/actor_role not in \('OWNER','ADMIN'\)/);assert.match(sql,/Admins may add members only/);assert.match(sql,/Admins may remove members only/);assert.match(sql,/Ownership transfer is not available here/);});
test('admin uploads validate storage types and use private digital bucket',()=>{const source=fs.readFileSync('app/actions/admin.ts','utf8');assert.match(source,/MAX_IMAGE_BYTES=5\*1024\*1024/);assert.match(source,/MAX_FILE_BYTES=100\*1024\*1024/);assert.match(source,/DIGITAL_TYPES/);assert.match(source,/storageUpload\('digital-products'/);assert.match(source,/storageDelete\('digital-products'/);});
