import {createHash} from 'node:crypto';
import type {JsonObject,JsonValue,StoredIntegrationJob} from './contracts';
import {IntegrationError} from './errors';
import {FeatureFlagService,IntegrationDatabase,IntegrationQueue} from './platform';
import {getPath,identityParts,inferEntityType,isUdmEntityType,mapSourceRecord,sourceKey,validateAndNormalize,type UdmEntityType,type UdmIssue} from './udm';

type RawBatch={id:string;organization_id:string;connection_id:string;sync_run_id:string;stream_key:string;records:JsonObject[];record_count:number;created_at:string};
type Connection={id:string;organization_id:string;connector_key:string;status:string};
type MappingRule={id:string;organization_id:string|null;connection_id:string|null;connector_key:string|null;stream_key:string;entity_type:string;field_map:JsonObject;defaults:JsonObject;relation_map:JsonObject;source_timezone:string;default_currency:string|null;default_unit:string|null;priority:number;version:number};
type ValidationRule={rule_key:string;severity:UdmIssue['severity'];field_path:string|null;rule_type:'required'|'type'|'enum'|'range'|'pattern'|'relation'|'custom';config:JsonObject};
type PipelineRun={id:string;status:string};
type PipelineRecord={id:string};
type UnifiedRecord={id:string;identity_hash:string;canonical_data:JsonObject;source_count:number};
type Candidate={id:string;canonical_data:JsonObject};

function object(value:unknown):value is JsonObject{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function stringValue(value:unknown){return value===null||value===undefined?null:String(value).trim()||null;}
function numberValue(value:unknown){const result=typeof value==='number'?value:Number(value);return Number.isFinite(result)?result:null;}
function hashIdentity(organizationId:string,entityType:UdmEntityType,parts:string[]){return createHash('sha256').update(JSON.stringify([organizationId,entityType,...parts])).digest('hex');}
function asJson(value:unknown):JsonValue{return value as JsonValue;}
function normalizedText(value:unknown){return stringValue(value)?.toLocaleLowerCase('en').normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,' ').trim()||'';}
function dice(left:string,right:string){if(!left||!right)return 0;if(left===right)return 1;const pairs=(value:string)=>{const result:string[]=[];for(let index=0;index<value.length-1;index++)result.push(value.slice(index,index+2));return result;};const a=pairs(left),b=pairs(right);if(!a.length||!b.length)return left===right?1:0;const counts=new Map<string,number>();for(const item of b)counts.set(item,(counts.get(item)||0)+1);let matches=0;for(const item of a){const count=counts.get(item)||0;if(count>0){matches++;counts.set(item,count-1);}}return 2*matches/(a.length+b.length);}
function matchScore(incoming:JsonObject,candidate:JsonObject){const fields=['external_id','email','phone','sku','barcode','registration_number','order_number','transaction_reference','employee_number','name'];let score=0,weight=0;for(const field of fields){const left=normalizedText(getPath(incoming,field)),right=normalizedText(getPath(candidate,field));if(!left||!right)continue;const fieldWeight=field==='name'?2:4;score+=(left===right?1:dice(left,right))*fieldWeight;weight+=fieldWeight;}return weight?score/weight:0;}
function issueValue(value:unknown){return value===undefined?null:asJson(value);}

export class DataPipelineEngine {
 constructor(private readonly database:IntegrationDatabase,private readonly queue:IntegrationQueue,private readonly flags:FeatureFlagService){}
 private async rawBatch(job:StoredIntegrationJob){const rawBatchId=typeof job.payload.raw_batch_id==='string'?job.payload.raw_batch_id:null;if(!rawBatchId)throw new IntegrationError('مهمة خط البيانات لا تحتوي على raw_batch_id.','CONFIGURATION_ERROR',false,{jobId:job.id});const params=new URLSearchParams({select:'id,organization_id,connection_id,sync_run_id,stream_key,records,record_count,created_at',id:`eq.${rawBatchId}`,organization_id:`eq.${job.organization_id}`,limit:'1'});const batch=(await this.database.select<RawBatch>('integration_raw_batches',params))[0];if(!batch)throw new IntegrationError('دفعة البيانات الخام غير موجودة.','CONNECTION_NOT_FOUND',false,{rawBatchId});if(!Array.isArray(batch.records))throw new IntegrationError('صيغة السجلات الخام غير صالحة.','VALIDATION_ERROR',false,{rawBatchId});return batch;}
 private async connection(batch:RawBatch){const params=new URLSearchParams({select:'id,organization_id,connector_key,status',id:`eq.${batch.connection_id}`,organization_id:`eq.${batch.organization_id}`,limit:'1'});const connection=(await this.database.select<Connection>('integration_connections',params))[0];if(!connection)throw new IntegrationError('اتصال دفعة البيانات غير موجود.','CONNECTION_NOT_FOUND',false,{connectionId:batch.connection_id});return connection;}
 private async mappings(batch:RawBatch,connection:Connection){const params=new URLSearchParams({select:'id,organization_id,connection_id,connector_key,stream_key,entity_type,field_map,defaults,relation_map,source_timezone,default_currency,default_unit,priority,version',stream_key:`eq.${batch.stream_key}`,is_active:'eq.true',order:'priority.asc,version.desc'});const rows=await this.database.select<MappingRule>('integration_mapping_rules',params);return rows.filter(row=>row.connection_id===connection.id||(row.connector_key===connection.connector_key&&(row.organization_id===connection.organization_id||row.organization_id===null))).sort((left,right)=>Number(right.connection_id===connection.id)-Number(left.connection_id===connection.id)||Number(right.organization_id===connection.organization_id)-Number(left.organization_id===connection.organization_id)||left.priority-right.priority||right.version-left.version);}
 private async validationRules(organizationId:string,entityType:UdmEntityType){const params=new URLSearchParams({select:'rule_key,severity,field_path,rule_type,config',is_active:'eq.true',or:`(organization_id.is.null,organization_id.eq.${organizationId})`,or:`(entity_type.is.null,entity_type.eq.${entityType})`,order:'version.desc'});return this.database.select<ValidationRule>('integration_validation_rules',params);}
 private applyRules(data:JsonObject,rules:ValidationRule[]){const issues:UdmIssue[]=[];for(const rule of rules){const value=rule.field_path?getPath(data,rule.field_path):data,config=rule.config||{};let failed=false;switch(rule.rule_type){case'required':failed=value===undefined||value===null||value==='';break;case'type':failed=typeof config.type==='string'&&typeof value!==config.type;break;case'enum':failed=Array.isArray(config.values)&&!config.values.includes(value as never);break;case'range':{const number=numberValue(value),min=numberValue(config.min),max=numberValue(config.max);failed=number===null||(min!==null&&number<min)||(max!==null&&number>max);break;}case'pattern':{try{failed=typeof config.pattern==='string'&&!new RegExp(config.pattern).test(String(value??''));}catch{failed=true;}break;}case'relation':failed=value===undefined||value===null||value==='';break;default:failed=false;}if(failed)issues.push({severity:rule.severity,category:rule.rule_type==='required'?'missing':'validation',ruleKey:rule.rule_key,fieldPath:rule.field_path||undefined,message:typeof config.message==='string'?config.message:`فشلت قاعدة التحقق ${rule.rule_key}.`,sourceValue:issueValue(value)});}return issues;}
 private async createIssue(input:{organizationId:string;connectionId:string;rawBatchId:string;runId:string;recordId?:string;unifiedRecordId?:string;issue:UdmIssue}){await this.database.insert('integration_quality_issues',{organization_id:input.organizationId,connection_id:input.connectionId,raw_batch_id:input.rawBatchId,pipeline_run_id:input.runId,pipeline_record_id:input.recordId||null,unified_record_id:input.unifiedRecordId||null,severity:input.issue.severity,category:input.issue.category,rule_key:input.issue.ruleKey,field_path:input.issue.fieldPath||null,message:input.issue.message,source_value:input.issue.sourceValue??null},'return=minimal');}
 private async pipelineRun(batch:RawBatch){const [existing]=await this.database.select<PipelineRun>('integration_pipeline_runs',new URLSearchParams({select:'id,status',raw_batch_id:`eq.${batch.id}`,limit:'1'}));if(existing?.status==='succeeded'||existing?.status==='partial')return {run:existing,complete:true};if(existing){const [run]=await this.database.update<PipelineRun>('integration_pipeline_runs',`id=eq.${existing.id}`,{status:'running',current_stage:'raw',last_error_code:null,last_error_message:null,started_at:new Date().toISOString(),finished_at:null});return {run,complete:false};}const [run]=await this.database.insert<PipelineRun>('integration_pipeline_runs',{organization_id:batch.organization_id,connection_id:batch.connection_id,raw_batch_id:batch.id,status:'running',current_stage:'raw',total_records:batch.records.length});return {run,complete:false};}
 private async pipelineRecord(batch:RawBatch,runId:string,index:number,source:JsonObject){const [record]=await this.database.upsert<PipelineRecord>('integration_pipeline_records',{organization_id:batch.organization_id,connection_id:batch.connection_id,raw_batch_id:batch.id,pipeline_run_id:runId,record_index:index,status:'processing',current_stage:'raw',source_payload:source,transformed_payload:{},canonical_payload:{},validation_errors:[],warnings:[]},'raw_batch_id,record_index');return record;}
 private async existingIdentity(organizationId:string,entityType:UdmEntityType,identityHash:string){const params=new URLSearchParams({select:'id,identity_hash,canonical_data,source_count',organization_id:`eq.${organizationId}`,entity_type:`eq.${entityType}`,identity_hash:`eq.${identityHash}`,limit:'1'});return (await this.database.select<UnifiedRecord>('integration_udm_records',params))[0];}
 private async fuzzyCandidates(organizationId:string,entityType:UdmEntityType,data:JsonObject){const params=new URLSearchParams({select:'id,canonical_data',organization_id:`eq.${organizationId}`,entity_type:`eq.${entityType}`,duplicate_of:'is.null',order:'updated_at.desc',limit:'50'});const rows=await this.database.select<Candidate>('integration_udm_records',params);return rows.map(candidate=>({candidate,score:matchScore(data,candidate.canonical_data)})).filter(item=>item.score>=0.82).sort((a,b)=>b.score-a.score).slice(0,5);}
 private async sourceKeyLink(batch:RawBatch,entityType:UdmEntityType,key:string,unifiedId:string){await this.database.upsert('integration_udm_source_keys',{organization_id:batch.organization_id,connection_id:batch.connection_id,entity_type:entityType,source_key:key,unified_record_id:unifiedId,raw_batch_id:batch.id,last_seen_at:new Date().toISOString()},'organization_id,connection_id,entity_type,source_key');await this.database.update('integration_udm_relations',`organization_id=eq.${batch.organization_id}&to_entity_type=eq.${entityType}&target_source_key=eq.${encodeURIComponent(key)}&to_record_id=is.null`,{to_record_id:unifiedId,status:'resolved'}).catch(()=>undefined);}
 private async relations(batch:RawBatch,runId:string,recordId:string,unifiedId:string,relationMap:JsonObject,source:JsonObject){for(const [relationKey,rawConfig] of Object.entries(relationMap)){if(!object(rawConfig)||!isUdmEntityType(rawConfig.entity_type)||typeof rawConfig.source_path!=='string')continue;const targetKey=stringValue(getPath(source,rawConfig.source_path));if(!targetKey)continue;const params=new URLSearchParams({select:'unified_record_id',organization_id:`eq.${batch.organization_id}`,entity_type:`eq.${rawConfig.entity_type}`,source_key:`eq.${targetKey}`,order:'last_seen_at.desc',limit:'1'});const target=(await this.database.select<{unified_record_id:string}>('integration_udm_source_keys',params))[0];await this.database.upsert('integration_udm_relations',{organization_id:batch.organization_id,from_record_id:unifiedId,relation_key:relationKey,to_entity_type:rawConfig.entity_type,target_source_key:targetKey,to_record_id:target?.unified_record_id||null,status:target?'resolved':'unresolved',metadata:{source_path:rawConfig.source_path}},'from_record_id,relation_key,to_entity_type,target_source_key');if(!target)await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId,recordId,unifiedRecordId:unifiedId,issue:{severity:'warning',category:'reference',ruleKey:'unresolved_foreign_key',fieldPath:rawConfig.source_path,message:`تعذر ربط المرجع ${relationKey} بالسجل الهدف.`,sourceValue:targetKey}});}}
 private async health(batch:RawBatch,status:string,total:number,invalid:number,qualityTotal:number){const openIssues=(await this.database.select<{count:number}>('integration_quality_issues',new URLSearchParams({select:'count',connection_id:`eq.${batch.connection_id}`,status:'eq.open'})))[0]?.count||0,deadJobs=(await this.database.select<{count:number}>('integration_jobs',new URLSearchParams({select:'count',connection_id:`eq.${batch.connection_id}`,status:'eq.dead'})))[0]?.count||0,invalidRatio=total?invalid/total:0,quality=total?qualityTotal/total:100,healthStatus=status==='failed'||invalidRatio>.25?'unhealthy':invalidRatio>.05||openIssues>20?'degraded':'healthy';await this.database.insert('integration_health_snapshots',{organization_id:batch.organization_id,connection_id:batch.connection_id,status:healthStatus,freshness_seconds:Math.max(0,Math.floor((Date.now()-Date.parse(batch.created_at))/1000)),success_rate:Math.max(0,100-invalidRatio*100),quality_score:Math.max(0,Math.min(100,quality)),processing_lag_seconds:Math.max(0,Math.floor((Date.now()-Date.parse(batch.created_at))/1000)),queue_depth:0,dead_jobs:Number(deadJobs),open_issues:Number(openIssues),invalid_ratio:invalidRatio,metrics:{raw_batch_id:batch.id,total_records:total}},'return=minimal');}
 async processBatch(job:StoredIntegrationJob,workerId:string){await this.flags.require('integration_pipeline_enabled',job.organization_id);const batch=await this.rawBatch(job),connection=await this.connection(batch),state=await this.pipelineRun(batch);if(state.complete){await this.queue.complete(job.id,workerId,{raw_batch_id:batch.id,pipeline_run_id:state.run.id,idempotent:true});return;}const run=state.run,mappings=await this.mappings(batch,connection);let valid=0,invalid=0,unified=0,duplicates=0,warnings=0,errors=0,qualityTotal=0;
  await this.database.update('integration_pipeline_runs',`id=eq.${run.id}`,{current_stage:'validate',total_records:batch.records.length});
  for(let index=0;index<batch.records.length;index++){
   const source=batch.records[index];if(!object(source)){invalid++;errors++;await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId:run.id,issue:{severity:'error',category:'validation',ruleKey:'record_not_object',message:'السجل الخام ليس كائن بيانات صالحًا.',sourceValue:asJson(source)}});continue;}
   const record=await this.pipelineRecord(batch,run.id,index,source),mapping=mappings[0],entityType=inferEntityType(batch.stream_key,source,mapping?.entity_type);
   if(!entityType){invalid++;errors++;const issue:UdmIssue={severity:'error',category:'mapping',ruleKey:'entity_mapping_missing',message:'لم يمكن تحديد نوع الكيان لهذا Stream؛ أضف قاعدة Mapping.'};await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId:run.id,recordId:record.id,issue});await this.database.update('integration_pipeline_records',`id=eq.${record.id}`,{status:'quarantined',current_stage:'map',validation_errors:[issue],processed_at:new Date().toISOString()});continue;}
   const transformed=mapSourceRecord(source,mapping?.field_map||{},mapping?.defaults||{}),normalized=validateAndNormalize(entityType,transformed,{timezone:mapping?.source_timezone||'UTC',defaultCurrency:mapping?.default_currency,defaultUnit:mapping?.default_unit}),customIssues=this.applyRules(normalized.canonical,await this.validationRules(batch.organization_id,entityType)),allIssues=[...normalized.errors,...customIssues.filter(issue=>issue.severity==='error'||issue.severity==='critical')],allWarnings=[...normalized.warnings,...customIssues.filter(issue=>issue.severity==='info'||issue.severity==='warning')];warnings+=allWarnings.length;errors+=allIssues.length;qualityTotal+=normalized.qualityScore;
   if(allIssues.length){invalid++;for(const issue of [...allIssues,...allWarnings])await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId:run.id,recordId:record.id,issue});await this.database.update('integration_pipeline_records',`id=eq.${record.id}`,{entity_type:entityType,status:'rejected',current_stage:'validate',transformed_payload:transformed,canonical_payload:normalized.canonical,validation_errors:allIssues,warnings:allWarnings,processed_at:new Date().toISOString()});continue;}
   const identity=identityParts(entityType,normalized.canonical);if(!identity){invalid++;errors++;const issue:UdmIssue={severity:'critical',category:'missing',ruleKey:'identity_missing',message:'لا توجد مجموعة حقول كافية لبناء هوية موحدة ومنع التكرار.'};await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId:run.id,recordId:record.id,issue});await this.database.update('integration_pipeline_records',`id=eq.${record.id}`,{entity_type:entityType,status:'quarantined',current_stage:'deduplicate',transformed_payload:transformed,canonical_payload:normalized.canonical,validation_errors:[issue],warnings:allWarnings,processed_at:new Date().toISOString()});continue;}
   const identityHash=hashIdentity(batch.organization_id,entityType,identity.parts),existing=await this.existingIdentity(batch.organization_id,entityType,identityHash),external=sourceKey(normalized.canonical),unifiedRecord=await this.database.rpc<UnifiedRecord>('integration_upsert_udm_record',{target_organization:batch.organization_id,target_entity_type:entityType,target_identity_hash:identityHash,target_natural_key:identity.naturalKey,target_external_id:external,target_canonical_data:normalized.canonical,target_quality_score:normalized.qualityScore,target_currency_code:normalized.currency,target_timezone:normalized.timezone,target_unit_code:normalized.unit,target_quantity:normalized.quantity,target_source_created_at:normalized.sourceCreatedAt,target_source_updated_at:normalized.sourceUpdatedAt});
   if(external)await this.sourceKeyLink(batch,entityType,external,unifiedRecord.id);await this.relations(batch,run.id,record.id,unifiedRecord.id,mapping?.relation_map||{},source);
   const candidates=existing?[]:await this.fuzzyCandidates(batch.organization_id,entityType,normalized.canonical);for(const item of candidates){await this.database.upsert('integration_match_candidates',{organization_id:batch.organization_id,entity_type:entityType,pipeline_record_id:record.id,candidate_record_id:item.candidate.id,score:item.score,strategy:'weighted_identity_similarity',status:'pending',evidence:{fields:['external_id','email','phone','sku','barcode','name']}},'pipeline_record_id,candidate_record_id,strategy');if(item.score>=.9){const issue:UdmIssue={severity:'warning',category:'duplicate',ruleKey:'possible_duplicate',message:`اكتُشف سجل مشابه بنسبة ${(item.score*100).toFixed(1)}٪ ويحتاج مراجعة.`,sourceValue:item.candidate.id};await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId:run.id,recordId:record.id,unifiedRecordId:unifiedRecord.id,issue});warnings++;}}
   valid++;unified++;if(existing)duplicates++;for(const issue of allWarnings)await this.createIssue({organizationId:batch.organization_id,connectionId:batch.connection_id,rawBatchId:batch.id,runId:run.id,recordId:record.id,unifiedRecordId:unifiedRecord.id,issue});await this.database.update('integration_pipeline_records',`id=eq.${record.id}`,{source_key:external,entity_type:entityType,status:existing?'duplicate':'accepted',current_stage:'complete',transformed_payload:transformed,canonical_payload:normalized.canonical,identity_hash:identityHash,unified_record_id:unifiedRecord.id,validation_errors:[],warnings:allWarnings,match_score:candidates[0]?.score||null,duplicate_of:existing?.id||null,processed_at:new Date().toISOString()});
  }
  const status=invalid===0?'succeeded':valid>0?'partial':'failed',finishedAt=new Date().toISOString();await this.database.update('integration_pipeline_runs',`id=eq.${run.id}`,{status,current_stage:'complete',valid_records:valid,invalid_records:invalid,unified_records:unified,duplicate_records:duplicates,warning_count:warnings,error_count:errors,metrics:{acceptance_rate:batch.records.length?valid/batch.records.length:1,quality_score:batch.records.length?qualityTotal/batch.records.length:100},finished_at:finishedAt});await this.database.insert('integration_audit_events',{organization_id:batch.organization_id,connection_id:batch.connection_id,actor_id:job.created_by,event_type:'integration.pipeline.completed',entity_type:'raw_batch',entity_id:batch.id,severity:status==='failed'?'error':status==='partial'?'warning':'info',metadata:{pipeline_run_id:run.id,status,total:batch.records.length,valid,invalid,unified,duplicates,warnings,errors}},'return=minimal');await this.health(batch,status,batch.records.length,invalid,qualityTotal);if(status==='failed')throw new IntegrationError('فشل خط الجودة في قبول أي سجل من الدفعة.','VALIDATION_ERROR',false,{rawBatchId:batch.id,pipelineRunId:run.id});await this.queue.complete(job.id,workerId,{raw_batch_id:batch.id,pipeline_run_id:run.id,status,valid,invalid,unified,duplicates});
 }
}
