'use client';

import {useMemo,useState} from 'react';
import {submitV2LocalPayment} from '@/app/actions/local-payments';

type CatalogItem={id:string;code:string;level_code:string;name_ar:string;term_months:number;currency:string;amount:number;monthly_equivalent:number;launch_notice:string};
type Method={id:string;name:string;currency:string;account_name:string;account_identifier:string;instructions:string|null};
const field='field w-full rounded-xl p-3';

export default function V2PaymentForm({catalog,methods,currentLevel}:{catalog:CatalogItem[];methods:Method[];currentLevel:string}){
 const eligible=useMemo(()=>catalog.filter(item=>rank(item.level_code)>=rank(currentLevel)),[catalog,currentLevel]);const[first]=eligible,[selection,setSelection]=useState(first?`${first.id}:${first.currency}`:'');const variant=eligible.find(item=>`${item.id}:${item.currency}`===selection)||first;const matching=methods.filter(method=>method.currency===variant?.currency);const[methodId,setMethodId]=useState('');
 return <form action={submitV2LocalPayment} encType="multipart/form-data" className="md-panel grid gap-4"><div><h2 className="text-xl font-black">دفع أو ترقية الباقة</h2><p className="mt-2 text-sm leading-7 text-slate-400">الترقية تُفعّل فور اعتماد الدفع. خفض المستوى يُجدول منفصلًا لنهاية الدورة.</p></div><select value={selection} onChange={event=>{setSelection(event.target.value);setMethodId('')}} required className={field}>{eligible.map(item=><option key={`${item.id}-${item.currency}`} value={`${item.id}:${item.currency}`}>{item.name_ar} · {item.term_months} شهر · {item.amount.toLocaleString('ar-SA')} {item.currency}</option>)}</select>{variant&&<><input type="hidden" name="variant_id" value={variant.id}/><input type="hidden" name="currency" value={variant.currency}/><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/5 p-4"><strong className="text-2xl text-emerald-200">{variant.amount.toLocaleString('ar-SA')} {variant.currency}</strong><p className="mt-2 text-xs text-amber-100">{variant.launch_notice}</p></div></>}<select name="payment_method_id" value={methodId} onChange={event=>setMethodId(event.target.value)} required className={field}><option value="">طريقة دفع بعملة {variant?.currency}</option>{matching.map(method=><option key={method.id} value={method.id}>{method.name}</option>)}</select>{matching.find(method=>method.id===methodId)&&<div className="rounded-xl bg-white/[.04] p-4 text-sm"><p>{matching.find(method=>method.id===methodId)?.account_name}</p><strong dir="ltr" className="mt-2 block">{matching.find(method=>method.id===methodId)?.account_identifier}</strong></div>}<input name="payment_reference" required minLength={3} maxLength={120} className={field} placeholder="رقم عملية التحويل"/><input name="proof" type="file" required accept="image/jpeg,image/png,image/webp,application/pdf" className={field}/><button disabled={!methodId} className="md-button md-button-primary">إرسال الدفع للمراجعة</button>{variant&&matching.length===0&&<p className="text-sm text-amber-200">لا توجد طريقة دفع مفعلة بعملة {variant.currency} حاليًا.</p>}</form>;
}
function rank(level:string){return level==='BASIC'?1:level==='PREMIUM'?2:3}
