import {randomUUID} from 'node:crypto';
import type {OrbyIdentity,OrbyJsonObject,OrbyJsonValue} from '../core/contracts';
import type {OrbyExecutionEventBus,OrbyExecutionQueue,OrbyExecutionRepository,OrbyTaskPlan,OrbyTaskPlanner,OrbyWorkflowRecord,OrbyWorkflowRun} from './contracts';
import {OrbyExecutionError,normalizeExecutionError} from './errors';
import {OrbyApprovalEngine,OrbyExecutionLimitsManager,OrbyPermissionEngine,OrbyPolicyEngine} from './governance';
import {OrbyToolDispatcher,OrbyToolRegistry} from './tools';
import {OrbyPlanValidator} from './planning';
import {OrbyActionEngine,OrbyRollbackEngine,OrbySandboxRunner,OrbyWorkflowEngine} from './workflow';

function now(){return new Date().toISOString();}

export class OrbyAgentRuntime {
 private readonly validator:OrbyPlanValidator;
 constructor(
  readonly planner:OrbyTaskPlanner,
  readonly registry:OrbyToolRegistry,
  readonly repository:OrbyExecutionRepository,
  readonly queue:OrbyExecutionQueue,
  readonly permissions:OrbyPermissionEngine,
  readonly approvals:OrbyApprovalEngine,
  readonly workflow:OrbyWorkflowEngine,
  readonly events:OrbyExecutionEventBus,
  limits:OrbyExecutionLimitsManager,
 ){this.validator=new OrbyPlanValidator(registry,limits);}
 async plan(input:{goal:string;identity:OrbyIdentity;reason?:string;metadata?:OrbyJsonObject;signal?:AbortSignal}){const configuration=await this.repository.configuration(input.identity.organizationId);if(!configuration.planningEnabled)throw new OrbyExecutionError('تخطيط وكيل أوربي غير مفعّل لهذه المساحة.','PLANNING_DISABLED');await this.permissions.resolve(input.identity);const plan=await this.planner.plan({goal:input.goal.trim(),identity:input.identity,reason:input.reason||input.goal,metadata:input.metadata,signal:input.signal});this.validator.validate(plan,configuration);return plan;}
 async submit(input:{goal:string;identity:OrbyIdentity;reason?:string;plan?:OrbyTaskPlan;metadata?:OrbyJsonObject;signal?:AbortSignal}){const configuration=await this.repository.configuration(input.identity.organizationId);if(!configuration.enabled)throw new OrbyExecutionError('محرك تنفيذ وكيل أوربي غير مفعّل لهذه المساحة.','EXECUTION_DISABLED');await this.permissions.resolve(input.identity);const plan=input.plan||await this.plan(input);this.validator.validate(plan,configuration);const timestamp=now(),workflow:OrbyWorkflowRecord={id:randomUUID(),organizationId:input.identity.organizationId,createdBy:input.identity.userId,goal:input.goal,plan,status:'active',version:1,createdAt:timestamp,updatedAt:timestamp};await this.repository.saveWorkflow(workflow);const run:OrbyWorkflowRun={id:randomUUID(),workflowId:workflow.id,organizationId:input.identity.organizationId,userId:input.identity.userId,workspaceId:input.identity.workspaceId,status:'pending',reason:input.reason||input.goal,state:{completedNodeIds:[],variables:{},results:{}},createdAt:timestamp,updatedAt:timestamp};await this.repository.createRun(run);await this.queue.enqueue({runId:run.id,organizationId:run.organizationId,idempotencyKey:`orby-run:${run.id}`});await this.repository.appendEvent({runId:run.id,organizationId:run.organizationId,eventType:'workflow.queued',payload:{workflowId:workflow.id,toolNames:plan.toolNames as unknown as OrbyJsonValue}});await this.repository.appendAudit({runId:run.id,organizationId:run.organizationId,actorId:run.userId,eventType:'workflow.submitted',reason:run.reason,outcome:'queued',metadata:{workflowId:workflow.id,toolNames:plan.toolNames as unknown as OrbyJsonValue}});await this.events.emit('workflow.planned',{workflowId:workflow.id,organizationId:run.organizationId,userId:run.userId,toolNames:plan.toolNames});await this.events.emit('workflow.queued',{runId:run.id,workflowId:workflow.id,organizationId:run.organizationId,userId:run.userId});return{workflow,run};}
 async processNext(workerId:string,limit=5){const jobs=await this.queue.claim(workerId,Math.min(20,Math.max(1,limit))),processed:OrbyJsonObject[]=[];for(const job of jobs){try{const result=await this.workflow.execute(job.runId);if(result.status==='waiting'){await this.queue.complete(job.id,workerId,{status:'waiting',...result.pause});if(result.pause.resumeAt)await this.queue.enqueue({runId:job.runId,organizationId:job.organizationId,availableAt:result.pause.resumeAt,idempotencyKey:`orby-resume:${job.runId}:${result.pause.resumeAt}`});processed.push({jobId:job.id,runId:job.runId,status:'waiting'});}else{await this.queue.complete(job.id,workerId,{status:'completed'});processed.push({jobId:job.id,runId:job.runId,status:'completed'});}}catch(error){const normalized=normalizeExecutionError(error),next=normalized.retryable&&job.attempts<job.maxAttempts?new Date(Date.now()+Math.min(60_000,500*2**Math.max(0,job.attempts-1))).toISOString():null;await this.queue.fail(job.id,workerId,normalized.code,normalized.message,next);processed.push({jobId:job.id,runId:job.runId,status:next?'retry':'failed',errorCode:normalized.code});}}return processed;}
 async decideSystemApproval(input:{approvalId:string;reason:string}){const approval=await this.approvals.decideSystem(input);await this.queue.enqueue({runId:approval.runId,organizationId:approval.organizationId,idempotencyKey:`orby-system-approval-resume:${approval.id}`});return approval;}
 async decideApproval(input:{approvalId:string;identity:OrbyIdentity;decision:'approved'|'rejected';reason?:string}){const approval=await this.approvals.decide(input);if(approval.status==='approved')await this.queue.enqueue({runId:approval.runId,organizationId:approval.organizationId,idempotencyKey:`orby-approval-resume:${approval.id}`});else{const run=await this.repository.run(approval.runId);if(run)await this.repository.updateRun(run.id,{status:'failed',errorCode:'APPROVAL_REJECTED',errorMessage:'تم رفض الموافقة المطلوبة.',completedAt:now(),updatedAt:now()});}return approval;}
 async status(runId:string,identity:OrbyIdentity){const run=await this.repository.run(runId);if(!run)throw new OrbyExecutionError('تشغيل أوربي غير موجود.','RUN_NOT_FOUND');if(run.organizationId!==identity.organizationId)throw new OrbyExecutionError('التشغيل يخص مساحة أخرى.','PERMISSION_DENIED');const membership=await this.permissions.resolve(identity);if(run.userId!==identity.userId&&!['OWNER','ADMIN'].includes(membership.role))throw new OrbyExecutionError('لا تملك صلاحية رؤية هذا التشغيل.','PERMISSION_DENIED');return{run,actions:await this.repository.actions(runId)};}
 async cancel(runId:string,identity:OrbyIdentity){const current=await this.status(runId,identity);if(['completed','failed','cancelled'].includes(current.run.status))return current.run;await this.queue.cancelRun(runId);await this.workflow.cancelActions(current.run,current.actions);const updated=await this.repository.updateRun(runId,{status:'cancelled',completedAt:now(),updatedAt:now()});await this.repository.appendAudit({runId,organizationId:updated.organizationId,actorId:identity.userId,eventType:'workflow.cancelled',outcome:'cancelled'});await this.events.emit('workflow.cancelled',{runId,userId:identity.userId});return updated;}
}

export function createOrbyAgentRuntime(input:{planner:OrbyTaskPlanner;registry:OrbyToolRegistry;repository:OrbyExecutionRepository;queue:OrbyExecutionQueue;permissions:OrbyPermissionEngine;policies?:OrbyPolicyEngine;events:OrbyExecutionEventBus;dispatcher?:OrbyToolDispatcher}){
 const dispatcher=input.dispatcher||new OrbyToolDispatcher(input.registry),limits=new OrbyExecutionLimitsManager(input.repository),approvals=new OrbyApprovalEngine(input.repository,input.permissions,input.events),sandbox=new OrbySandboxRunner(dispatcher,input.repository,input.events),actions=new OrbyActionEngine(input.repository,dispatcher,input.permissions,input.policies||new OrbyPolicyEngine(),approvals,limits,sandbox,input.events),rollback=new OrbyRollbackEngine(input.repository,actions,input.events),workflow=new OrbyWorkflowEngine(input.repository,actions,rollback,input.events);return new OrbyAgentRuntime(input.planner,input.registry,input.repository,input.queue,input.permissions,approvals,workflow,input.events,limits);
}
