import type {OrbyJsonObject} from '../core/contracts';
import type {OrbyMadarToolGateway,OrbyTool,OrbyToolManifest} from './contracts';
import {OrbyGatewayTool} from './tools';
const object=(properties:NonNullable<OrbyToolManifest['inputSchema']['properties']>,required:readonly string[]=[],additionalProperties=false)=>({type:'object' as const,properties,required,additionalProperties});
const output=object({status:{type:'string'},id:{type:'string'},data:{type:'object',additionalProperties:true},items:{type:'array',items:{type:'object',additionalProperties:true}},count:{type:'integer'}},[],true);
export const MADAR_EXECUTION_TOOL_MANIFESTS:readonly OrbyToolManifest[]=[
{name:'madar.data.search',description:'البحث الآمن للقراءة فقط داخل نموذج بيانات مَدار الموحد UDM.',version:'1.0.0',category:'data',requiredPermissions:['data.read'],executionType:'read',riskLevel:'low',status:'active',support:'stable',requirements:['integration-udm'],maxTimeoutMs:20_000,supportsSandbox:true,operation:'data.search',inputSchema:object({entityType:{type:'string',minLength:1,maxLength:80},query:{type:'string',maxLength:500},limit:{type:'integer',minimum:1,maximum:100}}),outputSchema:output},
{name:'madar.files.export.request',description:'إنشاء طلب تصدير ملف داخل مَدار دون إنشاء أو تنزيل ملف مباشرة.',version:'1.0.0',category:'files',requiredPermissions:['files.export'],executionType:'write',riskLevel:'low',status:'active',support:'beta',requirements:['orby-action-drafts'],maxTimeoutMs:15_000,supportsSandbox:true,operation:'files.export.request',inputSchema:object({format:{type:'string',enum:['csv','xlsx','pdf']},entityType:{type:'string',minLength:1,maxLength:80},filters:{type:'object',additionalProperties:true}},['format','entityType']),outputSchema:output},
{name:'madar.platform.notify.self',description:'إنشاء إشعار داخل منصة مَدار للمستخدم الذي طلب التنفيذ فقط.',version:'1.0.0',category:'platform',requiredPermissions:['platform.notify'],executionType:'write',riskLevel:'low',status:'active',support:'stable',requirements:['notifications'],maxTimeoutMs:10_000,supportsSandbox:true,operation:'platform.notify.self',inputSchema:object({title:{type:'string',minLength:1,maxLength:120},body:{type:'string',minLength:1,maxLength:1000},link:{type:'string',maxLength:500}},['title','body']),outputSchema:output},
{name:'madar.business.action.draft',description:'إنشاء مسودة إجراء أعمال لا تُنفذ إلا بعد المرور بمسار الموافقة والتأكيد.',version:'1.0.0',category:'business',requiredPermissions:['business.action.draft'],executionType:'write',riskLevel:'low',status:'active',support:'stable',requirements:['orby-action-drafts'],maxTimeoutMs:15_000,supportsSandbox:true,operation:'business.action.draft',inputSchema:object({actionType:{type:'string',minLength:2,maxLength:100},payload:{type:'object',additionalProperties:true}},['actionType','payload']),outputSchema:output},
{name:'orby.intelligence.analyze',description:'إجراء تحليل لغوي عبر نواة ORBY دون تنفيذ أدوات أخرى أو تعديل البيانات.',version:'1.0.0',category:'intelligence',requiredPermissions:['intelligence.analyze'],executionType:'analysis',riskLevel:'low',status:'active',support:'stable',requirements:['orby-kernel'],maxTimeoutMs:60_000,supportsSandbox:true,operation:'intelligence.analyze',inputSchema:object({prompt:{type:'string',minLength:5,maxLength:12000},sessionId:{type:'string',maxLength:100}},['prompt']),outputSchema:object({text:{type:'string'},sessionId:{type:'string'},providerId:{type:'string'},modelId:{type:'string'}},['text'],true)},
{name:'madar.integration.connection.test',description:'إرسال مهمة اختبار اتصال إلى محرك الربط الحالي دون استدعاء الموصل مباشرة.',version:'1.0.0',category:'integration',requiredPermissions:['integration.manage'],executionType:'write',riskLevel:'medium',status:'active',support:'stable',requirements:['integration-gateway','connection-id'],maxTimeoutMs:15_000,supportsSandbox:true,operation:'integration.connection.test',inputSchema:object({connectionId:{type:'string',minLength:10,maxLength:100}},['connectionId']),outputSchema:output},
{name:'madar.integration.sync.initial',description:'إرسال مزامنة تاريخية إلى Queue محرك الربط الحالي بعد الموافقة.',version:'1.0.0',category:'integration',requiredPermissions:['integration.sync'],executionType:'write',riskLevel:'medium',status:'active',support:'stable',requirements:['integration-gateway','connection-id'],maxTimeoutMs:15_000,supportsSandbox:true,operation:'integration.sync.initial',inputSchema:object({connectionId:{type:'string',minLength:10,maxLength:100},streams:{type:'array',items:{type:'string'}}},['connectionId']),outputSchema:output},
{name:'madar.integration.sync.incremental',description:'إرسال مزامنة تزايدية إلى Queue محرك الربط الحالي بعد الموافقة.',version:'1.0.0',category:'integration',requiredPermissions:['integration.sync'],executionType:'write',riskLevel:'medium',status:'active',support:'stable',requirements:['integration-gateway','connection-id'],maxTimeoutMs:15_000,supportsSandbox:true,operation:'integration.sync.incremental',inputSchema:object({connectionId:{type:'string',minLength:10,maxLength:100},streams:{type:'array',items:{type:'string'}}},['connectionId']),outputSchema:output},
];
export function createMadarExecutionTools(gateway:OrbyMadarToolGateway,enabledNames?:readonly string[]):OrbyTool[]{const allowed=enabledNames?new Set(enabledNames):null;return MADAR_EXECUTION_TOOL_MANIFESTS.filter(manifest=>!allowed||allowed.has(manifest.name)).map(manifest=>new OrbyGatewayTool(manifest,gateway));}
export function manifestMap(){return Object.fromEntries(MADAR_EXECUTION_TOOL_MANIFESTS.map(item=>[item.name,item])) as Record<string,OrbyToolManifest>;}
export function toolInput(toolName:string,input:OrbyJsonObject){return{toolName,toolInput:input};}
