import type {OrbyJsonObject,OrbyJsonValue} from '../core/contracts';
import type {OrbyExecutionMode,OrbyJsonSchema,OrbyMadarToolGateway,OrbyTool,OrbyToolAuthorization,OrbyToolContext,OrbyToolHealth,OrbyToolManifest,OrbyToolResult,OrbyToolValidation} from './contracts';
import {OrbyExecutionError,normalizeExecutionError} from './errors';

function valueType(value:unknown){if(value===null)return'null';if(Array.isArray(value))return'array';if(Number.isInteger(value))return'integer';return typeof value;}
export function validateJsonSchema(schema:OrbyJsonSchema,value:unknown,path='$'):readonly {path:string;message:string}[]{const issues:{path:string;message:string}[]=[];if(schema.type){const actual=valueType(value),matches=schema.type==='number'?(actual==='number'||actual==='integer'):schema.type===actual;if(!matches)return[{path,message:`القيمة يجب أن تكون من النوع ${schema.type}.`}];}if(schema.enum&&!schema.enum.some(item=>JSON.stringify(item)===JSON.stringify(value)))issues.push({path,message:'القيمة ليست ضمن القيم المسموحة.'});if(typeof value==='string'){if(schema.minLength!==undefined&&value.length<schema.minLength)issues.push({path,message:`الحد الأدنى للطول ${schema.minLength}.`});if(schema.maxLength!==undefined&&value.length>schema.maxLength)issues.push({path,message:`الحد الأعلى للطول ${schema.maxLength}.`});}if(typeof value==='number'){if(schema.minimum!==undefined&&value<schema.minimum)issues.push({path,message:`القيمة يجب ألا تقل عن ${schema.minimum}.`});if(schema.maximum!==undefined&&value>schema.maximum)issues.push({path,message:`القيمة يجب ألا تتجاوز ${schema.maximum}.`});}if(Array.isArray(value)&&schema.items)value.forEach((item,index)=>issues.push(...validateJsonSchema(schema.items!,item,`${path}[${index}]`)));if(value&&typeof value==='object'&&!Array.isArray(value)&&schema.properties){const record=value as Record<string,unknown>;for(const required of schema.required||[])if(!(required in record))issues.push({path:`${path}.${required}`,message:'الحقل مطلوب.'});for(const [key,child] of Object.entries(schema.properties))if(key in record)issues.push(...validateJsonSchema(child,record[key],`${path}.${key}`));if(schema.additionalProperties===false)for(const key of Object.keys(record))if(!(key in schema.properties))issues.push({path:`${path}.${key}`,message:'الحقل غير مسموح.'});}return issues;}

export class OrbyToolValidator{
 validateManifest(manifest:OrbyToolManifest){if(!/^[a-z0-9]+(?:[._-][a-z0-9]+)+$/.test(manifest.name))throw new OrbyExecutionError('اسم أداة أوربي غير صالح.','TOOL_INVALID',false,{toolName:manifest.name});if(!manifest.description.trim()||!manifest.version.trim()||!manifest.operation.trim())throw new OrbyExecutionError('بيانات تعريف أداة أوربي غير مكتملة.','TOOL_INVALID',false,{toolName:manifest.name});if(manifest.maxTimeoutMs<100||manifest.maxTimeoutMs>300_000)throw new OrbyExecutionError('مهلة الأداة خارج الحدود المسموحة.','TOOL_INVALID',false,{toolName:manifest.name,maxTimeoutMs:manifest.maxTimeoutMs});}
 validateTool(tool:OrbyTool){for(const method of ['metadata','validate','authorize','execute','cancel','health'] as const)if(typeof tool[method]!=='function')throw new OrbyExecutionError(`الأداة لا تطبق ${method}().`,'TOOL_INVALID');this.validateManifest(tool.metadata());return tool;}
 validateInput(manifest:OrbyToolManifest,input:unknown){const issues=validateJsonSchema(manifest.inputSchema,input);if(issues.length)throw new OrbyExecutionError('مدخلات أداة أوربي غير صالحة.','TOOL_INVALID',false,{toolName:manifest.name,issues:issues as unknown as OrbyJsonValue});}
 validateOutput(manifest:OrbyToolManifest,result:OrbyToolResult){if(!result.ok)return;const issues=validateJsonSchema(manifest.outputSchema,result.data);if(issues.length)throw new OrbyExecutionError('مخرجات أداة أوربي لا تطابق العقد المعتمد.','RESULT_INVALID',false,{toolName:manifest.name,issues:issues as unknown as OrbyJsonValue});}
}
export type OrbyToolFactory=()=>OrbyTool|Promise<OrbyTool>;
export class OrbyToolRegistry{private readonly tools=new Map<string,OrbyTool>();constructor(private readonly validator=new OrbyToolValidator()){}register(tool:OrbyTool){const checked=this.validator.validateTool(tool),manifest=checked.metadata();if(this.tools.has(manifest.name))throw new OrbyExecutionError('أداة أوربي مسجلة مسبقًا.','TOOL_INVALID',false,{toolName:manifest.name});this.tools.set(manifest.name,checked);return this;}replace(tool:OrbyTool){const checked=this.validator.validateTool(tool);this.tools.set(checked.metadata().name,checked);return this;}get(name:string){const tool=this.tools.get(name);if(!tool)throw new OrbyExecutionError('أداة أوربي المطلوبة غير مسجلة.','TOOL_NOT_FOUND',false,{toolName:name});if(tool.metadata().status==='disabled')throw new OrbyExecutionError('أداة أوربي المطلوبة معطلة.','TOOL_DISABLED',false,{toolName:name});return tool;}has(name:string){return this.tools.has(name);}list(filter:{enabledOnly?:boolean;category?:string}={}){return[...this.tools.values()].filter(tool=>(!filter.enabledOnly||tool.metadata().status==='active')&&(!filter.category||tool.metadata().category===filter.category)).sort((a,b)=>a.metadata().name.localeCompare(b.metadata().name));}manifests(filter:{enabledOnly?:boolean}={}){return this.list(filter).map(tool=>tool.metadata());}}
export class OrbyToolLoader{constructor(private readonly registry:OrbyToolRegistry){}async load(factories:readonly OrbyToolFactory[],allowedNames?:readonly string[]){const allowed=allowedNames?new Set(allowedNames):null;for(const factory of factories){const tool=await factory();if(!allowed||allowed.has(tool.metadata().name))this.registry.register(tool);}return this.registry;}}
export class OrbyToolTimeoutManager{async run<T>(operation:(signal:AbortSignal)=>Promise<T>,timeoutMs:number,parentSignal?:AbortSignal){const controller=new AbortController(),onAbort=()=>controller.abort(parentSignal?.reason);if(parentSignal?.aborted)controller.abort(parentSignal.reason);else parentSignal?.addEventListener('abort',onAbort,{once:true});const timer=setTimeout(()=>controller.abort(new OrbyExecutionError('انتهت مهلة تنفيذ أداة أوربي.','TOOL_TIMEOUT',true,{timeoutMs})),timeoutMs);try{return await operation(controller.signal);}catch(error){if(controller.signal.aborted&&!parentSignal?.aborted)throw new OrbyExecutionError('انتهت مهلة تنفيذ أداة أوربي.','TOOL_TIMEOUT',true,{timeoutMs},error);throw error;}finally{clearTimeout(timer);parentSignal?.removeEventListener('abort',onAbort);}}}
export class OrbyToolResultParser{constructor(private readonly validator=new OrbyToolValidator()){}parse(manifest:OrbyToolManifest,result:OrbyToolResult){if(!result||typeof result!=='object'||typeof result.ok!=='boolean')throw new OrbyExecutionError('الأداة أعادت نتيجة غير قابلة للمعالجة.','RESULT_INVALID',false,{toolName:manifest.name});this.validator.validateOutput(manifest,result);if(!result.ok&&!result.error)throw new OrbyExecutionError('نتيجة الأداة الفاشلة لا تحمل وصف الخطأ.','RESULT_INVALID',false,{toolName:manifest.name});return result;}}
export class OrbyGatewayTool implements OrbyTool{constructor(private readonly manifest:OrbyToolManifest,private readonly gateway:OrbyMadarToolGateway){}metadata(){return{...this.manifest,requiredPermissions:[...this.manifest.requiredPermissions],requirements:[...this.manifest.requirements]};}validate(input:unknown):OrbyToolValidation{const issues=validateJsonSchema(this.manifest.inputSchema,input);return issues.length?{valid:false,issues}:{valid:true,normalizedInput:structuredClone(input as OrbyJsonObject)};}authorize():OrbyToolAuthorization{return{allowed:true};}execute(context:OrbyToolContext,input:OrbyJsonObject){return this.gateway.execute(this.manifest.operation,input,context);}cancel(context:Omit<OrbyToolContext,'signal'>){return this.gateway.cancel(this.manifest.operation,context);}health(signal?:AbortSignal):Promise<OrbyToolHealth>{return this.gateway.health(this.manifest.operation,signal);}}
export type OrbyDispatchHooks={before?(manifest:OrbyToolManifest,input:OrbyJsonObject,context:Omit<OrbyToolContext,'signal'>):Promise<void>;after?(manifest:OrbyToolManifest,result:OrbyToolResult,context:Omit<OrbyToolContext,'signal'>):Promise<void>};
export class OrbyToolDispatcher{constructor(readonly registry:OrbyToolRegistry,private readonly validator=new OrbyToolValidator(),private readonly timeout=new OrbyToolTimeoutManager(),private readonly parser=new OrbyToolResultParser(),private readonly hooks:OrbyDispatchHooks={}){}async dispatch(input:{toolName:string;payload:unknown;context:Omit<OrbyToolContext,'signal'>;timeoutMs:number;signal?:AbortSignal;mode?:OrbyExecutionMode}){const tool=this.registry.get(input.toolName),manifest=tool.metadata();this.validator.validateInput(manifest,input.payload);const validation=await tool.validate(input.payload,input.context);if(!validation.valid)throw new OrbyExecutionError('مدخلات الأداة مرفوضة من أداة التحقق.','TOOL_INVALID',false,{toolName:manifest.name,issues:validation.issues as unknown as OrbyJsonValue});const authorization=await tool.authorize(input.context,validation.normalizedInput);if(!authorization.allowed)throw new OrbyExecutionError(authorization.reason,'TOOL_UNAUTHORIZED',false,{toolName:manifest.name,code:authorization.code||null});await this.hooks.before?.(manifest,validation.normalizedInput,input.context);const timeoutMs=Math.min(manifest.maxTimeoutMs,input.timeoutMs),started=Date.now();try{const result=await this.timeout.run(signal=>tool.execute({...input.context,mode:input.mode||input.context.mode,signal},validation.normalizedInput),timeoutMs,input.signal),parsed=this.parser.parse(manifest,result);await this.hooks.after?.(manifest,parsed,input.context);return{manifest,result:parsed,durationMs:Date.now()-started};}catch(error){throw normalizeExecutionError(error,'TOOL_FAILED');}}async cancel(toolName:string,context:Omit<OrbyToolContext,'signal'>){return this.registry.get(toolName).cancel(context);}async health(toolName:string,signal?:AbortSignal){return this.registry.get(toolName).health(signal);}}
export function toolResult(data:OrbyJsonValue,metrics?:OrbyJsonObject,warnings?:readonly string[]):OrbyToolResult{return{ok:true,data,metrics,warnings};}
export function toolFailure(code:string,message:string,retryable=false,details?:OrbyJsonObject):OrbyToolResult{return{ok:false,data:null,error:{code,message,retryable,details}};}
