import type {OrbyJsonObject,OrbyJsonValue} from '../core/contracts';
import type {OrbyActionRecord,OrbyExecutionConfiguration,OrbyExecutionEventBus,OrbyExecutionRepository,OrbyRunState,OrbyWorkflowNode,OrbyWorkflowRun} from './contracts';
import {OrbyExecutionError,OrbyExecutionPause,normalizeExecutionError} from './errors';
import {OrbyActionEngine} from './action-engine';
import {OrbyRollbackEngine} from './rollback';
import {condition,getPath,now} from './workflow-helpers';

export class OrbyWorkflowEngine {
 constructor(private readonly repository:OrbyExecutionRepository,private readonly actions:OrbyActionEngine,private readonly rollback:OrbyRollbackEngine,private readonly events:OrbyExecutionEventBus){}
 private completed(state:OrbyRunState,key:string){return state.completedNodeIds.includes(key);}
 private mark(state:OrbyRunState,key:string,result:OrbyJsonValue=null){if(!this.completed(state,key))state.completedNodeIds.push(key);state.results[key]=result;}
 private async node(input:{node:OrbyWorkflowNode;scope:string;run:OrbyWorkflowRun;configuration:OrbyExecutionConfiguration;state:OrbyRunState;environment:OrbyJsonObject;signal?:AbortSignal}):Promise<OrbyJsonValue>{
  const key=`${input.scope}/${input.node.id}`;if(this.completed(input.state,key))return input.state.results[key]??null;const environment={...input.environment,variables:input.state.variables,results:input.state.results};
  if(input.node.type==='action'){for(const dependency of input.node.dependencies||[])if(!input.state.completedNodeIds.some(item=>item.endsWith(`/${dependency}`)))throw new OrbyExecutionError('اعتماد خطوة التنفيذ لم يكتمل.','PLAN_INVALID',false,{nodeId:input.node.id,dependency});const result=await this.actions.execute({run:input.run,stepKey:key,node:input.node,configuration:input.configuration,environment,signal:input.signal});this.mark(input.state,key,result);return result;}
  if(input.node.type==='sequence'){let result:OrbyJsonValue=null;for(const child of input.node.children)result=await this.node({...input,node:child,scope:key});this.mark(input.state,key,result);return result;}
  if(input.node.type==='parallel'){const maximum=Math.min(input.configuration.maxParallelActions,input.node.maxParallel||input.node.children.length),results:OrbyJsonValue[]=[];for(let index=0;index<input.node.children.length;index+=maximum){const chunk=input.node.children.slice(index,index+maximum);results.push(...await Promise.all(chunk.map(child=>this.node({...input,node:child,scope:key}))));}this.mark(input.state,key,results);return results;}
  if(input.node.type==='condition'){const selected=condition(input.node.condition,environment)?input.node.then:input.node.else,result=selected?await this.node({...input,node:selected,scope:key}):null;this.mark(input.state,key,result);return result;}
  if(input.node.type==='loop'){const source=getPath(environment,input.node.itemsPath);if(!Array.isArray(source))throw new OrbyExecutionError('مصدر حلقة سير العمل ليس قائمة.','PLAN_INVALID',false,{nodeId:input.node.id,path:input.node.itemsPath});const limit=Math.min(source.length,input.node.maxIterations,input.configuration.maxLoopIterations),results:OrbyJsonValue[]=[];for(let index=0;index<limit;index++){input.state.variables[input.node.itemVariable]=source[index] as OrbyJsonValue;input.state.variables[`${input.node.itemVariable}Index`]=index;results.push(await this.node({...input,node:input.node.body,scope:`${key}[${index}]`}));}this.mark(input.state,key,results);return results;}
  if(input.node.type==='delay'){const until=input.state.delayUntil?.[key];if(!until){input.state.delayUntil={...(input.state.delayUntil||{}),[key]:new Date(Date.now()+input.node.durationMs).toISOString()};throw new OrbyExecutionPause({reason:'delay',resumeAt:input.state.delayUntil[key]});}if(Date.parse(until)>Date.now())throw new OrbyExecutionPause({reason:'delay',resumeAt:until});this.mark(input.state,key,{resumedAt:now()});return input.state.results[key];}
  if(input.node.type==='approval'){await this.actions.approvalNode({run:input.run,stepKey:key,scope:input.node.scope,reason:input.node.reason,configuration:input.configuration});this.mark(input.state,key,{approved:true});return input.state.results[key];}
  await this.repository.appendEvent({runId:input.run.id,organizationId:input.run.organizationId,eventType:input.node.name,payload:input.node.payload});this.mark(input.state,key,input.node.payload);return input.node.payload;
 }
 async cancelActions(run:OrbyWorkflowRun,actions:readonly OrbyActionRecord[]){for(const action of actions)if(['pending','running','retry','waiting_approval'].includes(action.status))try{await this.actions.cancel(action,run);}catch{}}
 async execute(runId:string,signal?:AbortSignal){
  const run=await this.repository.run(runId);if(!run)throw new OrbyExecutionError('تشغيل أوربي غير موجود.','RUN_NOT_FOUND');if(run.status==='cancelled')throw new OrbyExecutionError('تشغيل أوربي ملغى.','WORKFLOW_CANCELLED');const workflow=await this.repository.workflow(run.workflowId);if(!workflow)throw new OrbyExecutionError('سير عمل أوربي غير موجود.','WORKFLOW_NOT_FOUND');const configuration=await this.repository.configuration(run.organizationId);if(!configuration.enabled)throw new OrbyExecutionError('محرك تنفيذ أوربي غير مفعّل لهذه المساحة.','EXECUTION_DISABLED');const started=Date.now(),state=structuredClone(run.state);await this.repository.updateRun(run.id,{status:'running',startedAt:run.startedAt||now(),state,updatedAt:now()});await this.repository.appendEvent({runId:run.id,organizationId:run.organizationId,eventType:'workflow.started',payload:{workflowId:workflow.id}});await this.events.emit('workflow.started',{runId:run.id,organizationId:run.organizationId,userId:run.userId});
  try{const result=await this.node({node:workflow.plan.root,scope:'root',run,configuration,state,environment:{goal:workflow.goal,variables:state.variables,results:state.results},signal});await this.repository.updateRun(run.id,{status:'completed',state,result,completedAt:now(),errorCode:undefined,errorMessage:undefined,updatedAt:now()});await this.repository.appendEvent({runId:run.id,organizationId:run.organizationId,eventType:'workflow.completed',payload:{durationMs:Date.now()-started}});await this.repository.appendAudit({runId:run.id,organizationId:run.organizationId,actorId:run.userId,eventType:'workflow.completed',reason:run.reason,outcome:'completed',metadata:{durationMs:Date.now()-started}});await this.repository.notify({userId:run.userId,title:'اكتمل تنفيذ أوربي',body:workflow.plan.summary,link:`/account/orby/runs/${run.id}`});await this.events.emit('workflow.completed',{runId:run.id,durationMs:Date.now()-started});return{status:'completed' as const,result};}
  catch(error){if(error instanceof OrbyExecutionPause){await this.repository.updateRun(run.id,{status:'waiting',state,updatedAt:now()});await this.repository.appendEvent({runId:run.id,organizationId:run.organizationId,eventType:'workflow.waiting',payload:{reason:error.pause.reason,resumeAt:error.pause.resumeAt||null,approvalId:error.pause.approvalId||null}});await this.events.emit('workflow.waiting',{runId:run.id,...error.pause});return{status:'waiting' as const,pause:error.pause};}
   const normalized=normalizeExecutionError(error);const rollback=await this.rollback.rollback({...run,state},configuration,signal);await this.repository.updateRun(run.id,{status:normalized.code==='WORKFLOW_CANCELLED'?'cancelled':'failed',state,errorCode:normalized.code,errorMessage:normalized.message,completedAt:now(),updatedAt:now()});await this.repository.appendEvent({runId:run.id,organizationId:run.organizationId,eventType:'workflow.failed',payload:{errorCode:normalized.code,rollback}});await this.repository.appendAudit({runId:run.id,organizationId:run.organizationId,actorId:run.userId,eventType:'workflow.failed',reason:run.reason,outcome:'failed',metadata:{errorCode:normalized.code,rollback}});await this.repository.notify({userId:run.userId,title:'تعذر إكمال تنفيذ أوربي',body:normalized.message,link:`/account/orby/runs/${run.id}`});await this.events.emit('workflow.failed',{runId:run.id,errorCode:normalized.code,durationMs:Date.now()-started});throw normalized;}
 }
}
