import {useEffect,useState} from 'react';
import {Modal,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Badge,Button,Card,EmptyState,ErrorBanner,ScreenHeader,SectionTitle} from '@/components/ui';
import {decideAction,fetchActions,previewAction} from '@/lib/api';
import {dateTime,sourceLabel,statusLabel,verticalLabel} from '@/lib/format';
import type {MadarTheme} from '@/theme';
import type {ActionCapability,DashboardSnapshot,MobileAction,MobileActionType} from '@/types';

type Props={theme:MadarTheme;snapshot:DashboardSnapshot;accessToken:string;refreshing:boolean;onRefresh:()=>void;onChanged:()=>Promise<void>;onAskOrby:()=>void};
type Target={capability:ActionCapability;entityId:string;title:string;subtitle:string;currentStatus:string};

const priorityTone=(priority:string)=>priority==='urgent'?'red':priority==='high'?'amber':'neutral' as const;
const actionTone=(status:string)=>['EXECUTED','SUCCEEDED'].includes(status)?'mint':['FAILED','CONFLICT'].includes(status)?'red':['QUEUED','EXECUTING','VERIFYING'].includes(status)?'sky':['REJECTED','EXPIRED','CANCELLED'].includes(status)?'neutral':'amber' as const;
const scalar=<T,>(value:T|T[]|undefined)=>Array.isArray(value)?value[0]:value;
const mobileSessionNonce=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;let mobileActionSequence=0;
const nextIdempotencySuffix=()=>`${mobileSessionNonce}-${++mobileActionSequence}`;

export function OperationsScreen({theme,snapshot,accessToken,refreshing,onRefresh,onChanged,onAskOrby}:Props){
 const[target,setTarget]=useState<Target|null>(null),[selectedStatus,setSelectedStatus]=useState(''),[preview,setPreview]=useState<MobileAction|null>(null),[remoteActions,setRemoteActions]=useState<MobileAction[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<string|null>(null),actions=remoteActions||snapshot.recentActions;
 const capabilities=new Map<MobileActionType,ActionCapability>(snapshot.permissions.actionCapabilities.map(item=>[item.key,item]));
 useEffect(()=>{let active=true;fetchActions(accessToken,snapshot.workspace.id).then(value=>{if(active)setRemoteActions(value.actions);}).catch(()=>undefined);return()=>{active=false;};},[accessToken,snapshot.workspace.id]);

 function close(){if(busy)return;setTarget(null);setSelectedStatus('');setPreview(null);setError(null);setResult(null);}
 async function createPreview(status:string){
  if(!target)return;setSelectedStatus(status);setBusy(true);setError(null);setResult(null);
  try{const response=await previewAction(accessToken,{organizationId:snapshot.workspace.id,actionType:target.capability.key,entityId:target.entityId,status,idempotencyKey:`dashboard:${snapshot.workspace.id}:${target.capability.key}:${target.entityId}:${status}:${nextIdempotencySuffix()}`});setPreview(response.action);}
  catch(cause){setError(cause instanceof Error?cause.message:'تعذر تجهيز المعاينة.');}
  finally{setBusy(false);}
 }
 async function decide(decision:'confirmed'|'rejected'){
  if(!preview)return;setBusy(true);setError(null);
  try{const response=await decideAction(accessToken,preview.id,decision);setPreview(response.action);setResult(decision==='rejected'?'تم رفض الإجراء ولن تُغيّر البيانات.':response.action.source_of_truth==='EXTERNAL'?'تم التأكيد وإضافة الإجراء إلى صف نظام المصدر.':'تم التنفيذ والتحقق من السجل داخل مَدار.');const fresh=await fetchActions(accessToken,snapshot.workspace.id);setRemoteActions(fresh.actions);await onChanged();}
  catch(cause){setError(cause instanceof Error?cause.message:'تعذر إكمال الإجراء.');}
  finally{setBusy(false);}
 }

 const taskCapability=capabilities.get('TASK_STATUS_UPDATE'),sectorCapability=capabilities.get(snapshot.vertical.extension==='food_service'?'KITCHEN_TICKET_STATUS':'HOUSEKEEPING_STATUS');
 return <>
  <ScrollView style={{backgroundColor:theme.colors.background}} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={theme.colors.mint}/>}>
   <ScreenHeader theme={theme} eyebrow="تنفيذ يومي آمن" title="مركز العمليات" description={`إجراءات ${verticalLabel(snapshot.vertical.extension)} المسموحة فقط، وفق الباقة ودورك ومصدر الحقيقة.`} action={<Badge theme={theme} label={sourceLabel(snapshot.workspace.sourceOfTruth)} tone={snapshot.workspace.sourceOfTruth==='EXTERNAL'?'violet':'mint'}/>}/>
   {!snapshot.permissions.canUseWriteTools?<Card theme={theme} accent={theme.colors.violet}><Text style={[styles.lockTitle,{color:theme.colors.text}]}>أدوات التنفيذ غير مفعلة</Text><Text style={[styles.lockBody,{color:theme.colors.muted}]}>العمليات الكتابية متاحة للاشتراك الكامل وللمالك أو المدير. ما زال بإمكانك قراءة كل المؤشرات وسؤال أوربي.</Text><View style={{marginTop:13}}><Button theme={theme} kind="secondary" label="اسأل أوربي عن البيانات" onPress={onAskOrby}/></View></Card>:null}
   {snapshot.workspace.sourceOfTruth==='EXTERNAL'&&snapshot.permissions.canUseWriteTools&&!snapshot.permissions.canReverseWrite?<ErrorBanner theme={theme} message="الكتابة العكسية غير متاحة حتى تُمنح صلاحية WRITE للموصل وتكون ضمن استحقاقات الباقة."/>:null}

   <SectionTitle theme={theme} title="مهام مساحة العمل" caption="تغيير الحالة فقط؛ لا توجد كتابة مباشرة من الجهاز"/>
   {snapshot.tasks.length?snapshot.tasks.map(task=><OperationRow key={task.id} theme={theme} title={task.title} subtitle={task.dueAt?`الاستحقاق ${dateTime(task.dueAt)}`:'بلا موعد استحقاق'} status={task.status} badge={task.priority} badgeTone={priorityTone(task.priority)} enabled={Boolean(taskCapability)} onPress={()=>taskCapability&&setTarget({capability:taskCapability,entityId:task.id,title:task.title,subtitle:'مهمة مساحة العمل',currentStatus:task.status})}/>):<EmptyState theme={theme} title="لا مهام مفتوحة" body="كل المهام اليومية مكتملة أو لم تُنشأ مهام بعد." symbol="✓"/>}

   {snapshot.vertical.extension!=='commerce'?<><SectionTitle theme={theme} title={snapshot.vertical.extension==='food_service'?'شاشة المطبخ':'التنظيف وتجهيز الغرف'} caption={snapshot.vertical.extension==='food_service'?'حالة تذاكر المطبخ النشطة':'مهام التجهيز اليومية النشطة'}/>{snapshot.sectorOperations.length?snapshot.sectorOperations.map(item=>{const order=scalar(item.restaurant_orders),room=scalar(item.hotel_rooms),title=snapshot.vertical.extension==='food_service'?`تذكرة ${item.ticket_number||'مطبخ'}${order?.order_number?` • طلب ${order.order_number}`:''}`:`غرفة ${room?.room_number||'—'} • ${item.task_type||'تنظيف'}`,subtitle=snapshot.vertical.extension==='food_service'?order?.service_mode||item.priority||'طلب مطبخ':item.service_date?`موعد الخدمة ${item.service_date}`:item.notes||'مهمة فندقية';return <OperationRow key={item.id} theme={theme} title={title} subtitle={subtitle} status={item.status} enabled={Boolean(sectorCapability)} onPress={()=>sectorCapability&&setTarget({capability:sectorCapability,entityId:item.id,title,subtitle,currentStatus:item.status})}/>;}):<EmptyState theme={theme} title="لا عمليات قطاعية مفتوحة" body="لا توجد عناصر تحتاج تحديث حالة الآن."/>}</>:null}

   <SectionTitle theme={theme} title="سجل التنفيذ" caption="المعاينات والتأكيدات والنتائج من هذا الحساب"/>
   <Card theme={theme}>{actions.length?actions.slice(0,15).map((action,index)=><View key={action.id} style={[styles.action,index?{borderTopWidth:1,borderTopColor:theme.colors.border}:null]}><View style={styles.actionText}><Text style={[styles.actionTitle,{color:theme.colors.text}]}>{action.preview?.title||action.action_type}</Text><Text style={[styles.actionMeta,{color:theme.colors.faint}]}>{sourceLabel(action.source_of_truth)} • {dateTime(action.created_at)}</Text></View><Badge theme={theme} label={statusLabel(action.effective_status)} tone={actionTone(action.effective_status)}/></View>):<Text style={[styles.emptyLog,{color:theme.colors.muted}]}>لم تُنشأ إجراءات من التطبيق بعد.</Text>}</Card>
  </ScrollView>
  <Modal visible={Boolean(target)} transparent animationType="slide" onRequestClose={close}><Pressable style={styles.backdrop} onPress={close}><Pressable accessibilityViewIsModal onPress={()=>undefined} style={[styles.sheet,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><View style={[styles.handle,{backgroundColor:theme.colors.border}]}/>{target?<><Text style={[styles.sheetEyebrow,{color:theme.colors.mint}]}>معاينة قبل التنفيذ</Text><Text style={[styles.sheetTitle,{color:theme.colors.text}]}>{target.title}</Text><Text style={[styles.sheetBody,{color:theme.colors.muted}]}>{target.subtitle}</Text>{error?<ErrorBanner theme={theme} message={error}/>:null}{!preview?<><Text style={[styles.chooseLabel,{color:theme.colors.text}]}>اختر الحالة الجديدة</Text><View style={styles.statuses}>{target.capability.statuses.filter(status=>status!==target.currentStatus).map(status=><Pressable key={status} disabled={busy} onPress={()=>createPreview(status)} style={({pressed})=>[styles.statusChoice,{borderColor:selectedStatus===status?theme.colors.mint:theme.colors.border,backgroundColor:selectedStatus===status?theme.colors.mintSoft:theme.colors.surfaceElevated,opacity:pressed?0.72:1}]}><Text style={[styles.statusChoiceText,{color:theme.colors.text}]}>{statusLabel(status)}</Text></Pressable>)}</View>{busy?<Text style={[styles.progress,{color:theme.colors.muted}]}>جارٍ فحص الصلاحيات ومصدر الحقيقة…</Text>:null}<Button theme={theme} kind="ghost" label="إلغاء" onPress={close}/></>:<><View style={[styles.previewBox,{backgroundColor:theme.colors.surfaceElevated,borderColor:theme.colors.border}]}><PreviewLine theme={theme} label="قبل" value={statusLabel(preview.preview?.before?.status||target.currentStatus)}/><PreviewLine theme={theme} label="بعد" value={statusLabel(preview.preview?.after?.status||selectedStatus)} accent/><PreviewLine theme={theme} label="مصدر التنفيذ" value={sourceLabel(preview.source_of_truth)}/><PreviewLine theme={theme} label="صلاحية المعاينة" value={dateTime(preview.expires_at)}/></View>{result?<View style={[styles.result,{backgroundColor:preview.status==='REJECTED'?theme.colors.surfaceElevated:theme.colors.mintSoft}]}><Text style={[styles.resultText,{color:theme.colors.text}]}>{result}</Text></View>:null}{!result&&preview.status==='PREVIEWED'?<View style={styles.decisions}><View style={{flex:1}}><Button theme={theme} label="تأكيد التنفيذ" onPress={()=>decide('confirmed')} loading={busy}/></View><View style={{flex:1}}><Button theme={theme} kind="danger" label="رفض" onPress={()=>decide('rejected')} disabled={busy}/></View></View>:<Button theme={theme} label="إغلاق" onPress={close}/>}</>}</>:null}</Pressable></Pressable></Modal>
 </>;
}

function OperationRow({theme,title,subtitle,status,badge,badgeTone='neutral',enabled,onPress}:{theme:MadarTheme;title:string;subtitle:string;status:string;badge?:string;badgeTone?:'neutral'|'amber'|'red';enabled:boolean;onPress:()=>void}){return <Pressable accessibilityRole={enabled?'button':undefined} accessibilityState={{disabled:!enabled}} onPress={enabled?onPress:undefined} style={({pressed})=>[styles.row,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border,opacity:pressed?0.72:enabled?1:0.68}]}><View style={[styles.rowIcon,{backgroundColor:enabled?theme.colors.mintSoft:theme.colors.surfaceElevated}]}><Text style={{color:enabled?theme.colors.mint:theme.colors.faint}}>{enabled?'✓':'○'}</Text></View><View style={styles.rowText}><Text style={[styles.rowTitle,{color:theme.colors.text}]}>{title}</Text><Text numberOfLines={2} style={[styles.rowSubtitle,{color:theme.colors.muted}]}>{subtitle}</Text></View><View style={styles.rowBadges}>{badge?<Badge theme={theme} label={badge} tone={badgeTone}/>:null}<Badge theme={theme} label={statusLabel(status)} tone="neutral"/></View></Pressable>;}
function PreviewLine({theme,label,value,accent=false}:{theme:MadarTheme;label:string;value:string;accent?:boolean}){return <View style={styles.previewLine}><Text style={[styles.previewLabel,{color:theme.colors.muted}]}>{label}</Text><Text style={[styles.previewValue,{color:accent?theme.colors.mint:theme.colors.text}]}>{value}</Text></View>;}

const styles=StyleSheet.create({content:{padding:20,paddingBottom:34,gap:13},lockTitle:{fontSize:17,fontWeight:'800',textAlign:'right'},lockBody:{fontSize:12,lineHeight:20,textAlign:'right',marginTop:6},row:{borderWidth:1,borderRadius:19,padding:13,flexDirection:'row',alignItems:'center',gap:10},rowIcon:{width:38,height:38,borderRadius:14,alignItems:'center',justifyContent:'center'},rowText:{flex:1,alignItems:'flex-start'},rowTitle:{fontSize:13,fontWeight:'800',textAlign:'right'},rowSubtitle:{fontSize:10,lineHeight:16,textAlign:'right',marginTop:4},rowBadges:{alignItems:'flex-end',gap:5},action:{minHeight:64,flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10},actionText:{flex:1,alignItems:'flex-start'},actionTitle:{fontSize:12,fontWeight:'800',textAlign:'right'},actionMeta:{fontSize:9,marginTop:5,textAlign:'right'},emptyLog:{fontSize:12,textAlign:'center',paddingVertical:20},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.58)'},sheet:{borderWidth:1,borderTopLeftRadius:28,borderTopRightRadius:28,padding:20,paddingBottom:30,maxHeight:'88%'},handle:{width:44,height:4,borderRadius:3,alignSelf:'center',marginBottom:18},sheetEyebrow:{fontSize:11,fontWeight:'800',letterSpacing:.8,textAlign:'right'},sheetTitle:{fontSize:21,fontWeight:'900',textAlign:'right',marginTop:6},sheetBody:{fontSize:12,lineHeight:18,textAlign:'right',marginTop:4,marginBottom:16},chooseLabel:{fontSize:13,fontWeight:'800',textAlign:'right',marginBottom:10},statuses:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:15},statusChoice:{borderWidth:1,borderRadius:14,paddingHorizontal:13,paddingVertical:11},statusChoiceText:{fontSize:12,fontWeight:'700'},progress:{fontSize:11,textAlign:'center',marginBottom:12},previewBox:{borderWidth:1,borderRadius:18,padding:14,gap:12,marginBottom:14},previewLine:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},previewLabel:{fontSize:11},previewValue:{fontSize:12,fontWeight:'800',textAlign:'left'},decisions:{flexDirection:'row',gap:9},result:{borderRadius:16,padding:14,marginBottom:12},resultText:{fontSize:12,lineHeight:19,textAlign:'right'}});
