import type {OrbyJsonObject} from '../../core/contracts';
import type {OrbyInsight,OrbyIntelligenceEvent,OrbyIntelligenceJob,OrbyKnowledgeChunk,OrbyKnowledgeDocument,OrbyKnowledgeSource,OrbyMemoryPolicy,OrbyMemoryRecord,OrbyPeriodicReport,OrbyProactiveNotification,OrbySchedule} from '../contracts';

export type MemoryRow={id:string;organization_id:string;user_id:string|null;workspace_id:string|null;session_id:string|null;kind:OrbyMemoryRecord['kind'];memory_key:string;content:string;summary:string|null;source:OrbyMemoryRecord['source'];sensitivity:OrbyMemoryRecord['sensitivity'];confidence:number;importance:number;metadata:OrbyJsonObject;created_at:string;updated_at:string;last_accessed_at:string|null;expires_at:string|null;deleted_at:string|null};
export type SourceRow={id:string;organization_id:string;workspace_id:string|null;name:string;source_type:OrbyKnowledgeSource['type'];status:OrbyKnowledgeSource['status'];citation_label:string;trust_level:OrbyKnowledgeSource['trustLevel'];metadata:OrbyJsonObject;version:number;created_by:string|null;created_at:string;updated_at:string;last_indexed_at:string|null;last_error:string|null};
export type DocumentRow={id:string;source_id:string;organization_id:string;workspace_id:string|null;external_id:string|null;title:string;mime_type:string;checksum:string;language:string|null;status:OrbyKnowledgeDocument['status'];metadata:OrbyJsonObject;version:number;created_at:string;updated_at:string;extracted_at:string|null;indexed_at:string|null;last_error:string|null;raw_text?:string|null};
export type ChunkRow={id:string;document_id:string;source_id:string;organization_id:string;workspace_id:string|null;ordinal:number;content:string;token_estimate:number;checksum:string;heading:string|null;metadata:OrbyJsonObject;embedding_model:string|null;embedding_dimensions:number|null;created_at:string};
export type EventRow={id:string;organization_id:string;workspace_id:string|null;event_type:string;priority:number;payload:OrbyJsonObject;deduplication_key:string|null;occurred_at:string;available_at:string;processed_at:string|null};
export type JobRow={id:string;organization_id:string;workspace_id:string|null;job_type:OrbyIntelligenceJob['type'];status:OrbyIntelligenceJob['status'];payload:OrbyJsonObject;priority:number;available_at:string;attempts:number;max_attempts:number;idempotency_key:string|null;locked_by:string|null;lease_expires_at:string|null;last_error_code:string|null;last_error_message:string|null;created_at:string;updated_at:string};
export type ScheduleRow={id:string;organization_id:string;workspace_id:string|null;job_type:OrbySchedule['jobType'];cron_expression:string|null;interval_seconds:number|null;payload:OrbyJsonObject;enabled:boolean;next_run_at:string;last_run_at:string|null;timezone:string;created_at:string;updated_at:string};
export type InsightRow={id:string;organization_id:string;workspace_id:string|null;detector:OrbyInsight['detector'];fingerprint:string;status:OrbyInsight['status'];title:string;description:string;category:OrbyInsight['category'];severity:OrbyInsight['severity'];confidence:number;risk_score:number;opportunity_score:number;metrics:OrbyJsonObject;evidence:OrbyInsight['evidence'];root_causes:string[];recommendations:string[];suggested_actions:OrbyInsight['suggestedActions'];draft_workflow:OrbyJsonObject|null;cooldown_until:string|null;first_detected_at:string;last_detected_at:string;occurrences:number;created_at:string;updated_at:string};
export type NotificationRow={id:string;organization_id:string;user_id:string|null;workspace_id:string|null;insight_id:string|null;channel:OrbyProactiveNotification['channel'];title:string;body:string;severity:OrbyProactiveNotification['severity'];status:OrbyProactiveNotification['status'];deduplication_key:string;available_at:string;sent_at:string|null;metadata:OrbyJsonObject;created_at:string};
export type ReportRow={id:string;organization_id:string;workspace_id:string|null;report_type:OrbyPeriodicReport['type'];period_start:string;period_end:string;title:string;summary:string;sections:OrbyPeriodicReport['sections'];citations:OrbyPeriodicReport['citations'];status:OrbyPeriodicReport['status'];created_at:string;updated_at:string};

export const DEFAULT_POLICY:OrbyMemoryPolicy={enabled:false,allowConversationHistory:true,allowSummaries:true,allowShortTerm:true,allowLongTerm:false,allowPreferences:true,allowWorkspaceMemory:true,requireExplicitLongTermConsent:true,maximumConversationMessages:24,summaryTriggerMessages:30,shortTermTtlSeconds:604800,maximumMemoriesPerScope:500,blockedKeys:['password','secret','token','api_key','credential','private_key'],blockedPatterns:['-----BEGIN PRIVATE KEY-----','Bearer ','sk-'],allowedSensitivities:['public','internal','sensitive']};
export function memory(row:MemoryRow):OrbyMemoryRecord{return{id:row.id,organizationId:row.organization_id,userId:row.user_id||undefined,workspaceId:row.workspace_id||undefined,sessionId:row.session_id||undefined,kind:row.kind,key:row.memory_key,content:row.content,summary:row.summary||undefined,source:row.source,sensitivity:row.sensitivity,confidence:Number(row.confidence),importance:Number(row.importance),metadata:row.metadata||{},createdAt:row.created_at,updatedAt:row.updated_at,lastAccessedAt:row.last_accessed_at||undefined,expiresAt:row.expires_at||undefined,deletedAt:row.deleted_at||undefined};}
export function source(row:SourceRow):OrbyKnowledgeSource{return{id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,name:row.name,type:row.source_type,status:row.status,citationLabel:row.citation_label,trustLevel:row.trust_level,metadata:row.metadata||{},version:row.version,createdBy:row.created_by||undefined,createdAt:row.created_at,updatedAt:row.updated_at,lastIndexedAt:row.last_indexed_at||undefined,lastError:row.last_error||undefined};}
export function document(row:DocumentRow):OrbyKnowledgeDocument{return{id:row.id,sourceId:row.source_id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,externalId:row.external_id||undefined,title:row.title,mimeType:row.mime_type,checksum:row.checksum,language:row.language||undefined,status:row.status,metadata:row.metadata||{},version:row.version,createdAt:row.created_at,updatedAt:row.updated_at,extractedAt:row.extracted_at||undefined,indexedAt:row.indexed_at||undefined,lastError:row.last_error||undefined};}
export function chunk(row:ChunkRow):OrbyKnowledgeChunk{return{id:row.id,documentId:row.document_id,sourceId:row.source_id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,ordinal:row.ordinal,content:row.content,tokenEstimate:row.token_estimate,checksum:row.checksum,heading:row.heading||undefined,metadata:row.metadata||{},embeddingModel:row.embedding_model||undefined,embeddingDimensions:row.embedding_dimensions||undefined,createdAt:row.created_at};}
export function event(row:EventRow):OrbyIntelligenceEvent{return{id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,type:row.event_type,priority:row.priority,payload:row.payload||{},deduplicationKey:row.deduplication_key||undefined,occurredAt:row.occurred_at,availableAt:row.available_at,processedAt:row.processed_at||undefined};}
export function job(row:JobRow):OrbyIntelligenceJob{return{id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,type:row.job_type,status:row.status,payload:row.payload||{},priority:row.priority,availableAt:row.available_at,attempts:row.attempts,maxAttempts:row.max_attempts,idempotencyKey:row.idempotency_key||undefined,lockedBy:row.locked_by||undefined,leaseExpiresAt:row.lease_expires_at||undefined,lastErrorCode:row.last_error_code||undefined,lastErrorMessage:row.last_error_message||undefined,createdAt:row.created_at,updatedAt:row.updated_at};}
export function schedule(row:ScheduleRow):OrbySchedule{return{id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,jobType:row.job_type,cronExpression:row.cron_expression||undefined,intervalSeconds:row.interval_seconds||undefined,payload:row.payload||{},enabled:row.enabled,nextRunAt:row.next_run_at,lastRunAt:row.last_run_at||undefined,timezone:row.timezone,createdAt:row.created_at,updatedAt:row.updated_at};}
export function insight(row:InsightRow):OrbyInsight{return{id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,detector:row.detector,fingerprint:row.fingerprint,status:row.status,title:row.title,description:row.description,category:row.category,severity:row.severity,confidence:Number(row.confidence),riskScore:row.risk_score,opportunityScore:row.opportunity_score,metrics:row.metrics||{},evidence:row.evidence||[],rootCauses:row.root_causes||[],recommendations:row.recommendations||[],suggestedActions:row.suggested_actions||[],draftWorkflow:row.draft_workflow||undefined,cooldownUntil:row.cooldown_until||undefined,firstDetectedAt:row.first_detected_at,lastDetectedAt:row.last_detected_at,occurrences:row.occurrences,createdAt:row.created_at,updatedAt:row.updated_at};}
export function notification(row:NotificationRow):OrbyProactiveNotification{return{id:row.id,organizationId:row.organization_id,userId:row.user_id||undefined,workspaceId:row.workspace_id||undefined,insightId:row.insight_id||undefined,channel:row.channel,title:row.title,body:row.body,severity:row.severity,status:row.status,deduplicationKey:row.deduplication_key,availableAt:row.available_at,sentAt:row.sent_at||undefined,metadata:row.metadata||{},createdAt:row.created_at};}
export function report(row:ReportRow):OrbyPeriodicReport{return{id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id||undefined,type:row.report_type,periodStart:row.period_start,periodEnd:row.period_end,title:row.title,summary:row.summary,sections:row.sections||[],citations:row.citations||[],status:row.status,createdAt:row.created_at,updatedAt:row.updated_at};}
