import {randomUUID} from 'node:crypto';
import type {OrbyIdentity,OrbyJsonObject,OrbyJsonValue,OrbyMessage} from '../../core/contracts';
import type {OrbyInsight,OrbyIntelligenceEvent,OrbyIntelligenceJob,OrbyIntelligenceRepository,OrbyKnowledgeChunk,OrbyKnowledgeDocument,OrbyKnowledgeSource,OrbyMemoryPolicy,OrbyMemoryRecord,OrbyNotificationPreference,OrbyPeriodicReport,OrbyProactiveNotification,OrbyReportType,OrbySchedule,OrbyUserPreferences} from '../contracts';
import {IntegrationDatabase} from '@/src/lib/integration/platform';
import {compact,params} from '../../execution/adapters/supabase-shared';
import {DEFAULT_POLICY,memory,source,document,chunk,event,job,schedule,insight,notification,report,type MemoryRow,type SourceRow,type DocumentRow,type ChunkRow,type EventRow,type JobRow,type ScheduleRow,type InsightRow,type NotificationRow,type ReportRow} from './supabase-mappers';

export class SupabaseOrbyIntelligenceRepository implements OrbyIntelligenceRepository {
 constructor(private readonly database=new IntegrationDatabase()){}
 async resolveMemoryPolicy(organizationId:string){const row=(await this.database.select<{enabled:boolean;policy:Partial<OrbyMemoryPolicy>}>('orby_memory_policies',params({select:'enabled,policy',organization_id:`eq.${organizationId}`,limit:'1'})))[0];return{...DEFAULT_POLICY,...(row?.policy||{}),enabled:row?.enabled??false};}
 async setMemoryPolicy(organizationId:string,actorId:string,policy:OrbyMemoryPolicy){await this.database.upsert('orby_memory_policies',{organization_id:organizationId,enabled:policy.enabled,policy:policy as unknown as OrbyJsonValue,created_by:actorId,updated_by:actorId,updated_at:new Date().toISOString()},'organization_id','resolution=merge-duplicates,return=minimal');return this.resolveMemoryPolicy(organizationId);}
 async saveMemory(value:OrbyMemoryRecord){const [row]=await this.database.upsert<MemoryRow>('orby_memories',{id:value.id,organization_id:value.organizationId,user_id:value.userId||null,workspace_id:value.workspaceId||null,session_id:value.sessionId||null,kind:value.kind,memory_key:value.key,content:value.content,summary:value.summary||null,source:value.source,sensitivity:value.sensitivity,confidence:value.confidence,importance:value.importance,metadata:value.metadata,created_at:value.createdAt,updated_at:value.updatedAt,last_accessed_at:value.lastAccessedAt||null,expires_at:value.expiresAt||null,deleted_at:value.deletedAt||null},'id');if(!row)throw new Error('ORBY_MEMORY_SAVE_FAILED');return memory(row);}
 async findMemories(input:{identity:OrbyIdentity;kinds?:readonly OrbyMemoryRecord['kind'][];query?:string;limit:number;now:string}){const rows=await this.database.rpc<MemoryRow[]>('orby_find_memories',{target_organization:input.identity.organizationId,target_user:input.identity.userId,target_workspace:input.identity.workspaceId||null,memory_kinds:(input.kinds||[]) as unknown as OrbyJsonValue,memory_query:input.query?.trim()||null,match_count:input.limit,at_time:input.now});return rows.map(memory);}
 async expireMemories(timestamp:string,limit:number){return this.database.rpc<number>('orby_expire_memories',{cutoff:timestamp,batch_limit:limit});}
 async getPreferences(identity:OrbyIdentity){const row=(await this.database.select<{preferences:OrbyUserPreferences}>('orby_user_preferences',params({select:'preferences',organization_id:`eq.${identity.organizationId}`,user_id:`eq.${identity.userId}`,workspace_id:identity.workspaceId?`eq.${identity.workspaceId}`:'is.null',limit:'1'})))[0];return row?.preferences||null;}
 async setPreferences(identity:OrbyIdentity,preferences:OrbyUserPreferences){await this.database.upsert('orby_user_preferences',{organization_id:identity.organizationId,user_id:identity.userId,workspace_id:identity.workspaceId||null,workspace_scope:identity.workspaceId||'00000000-0000-0000-0000-000000000000',preferences:preferences as unknown as OrbyJsonValue,updated_at:new Date().toISOString()},'organization_id,user_id,workspace_scope','resolution=merge-duplicates,return=minimal');}
 async getConversationSummary(sessionId:string){const row=(await this.database.select<MemoryRow>('orby_memories',params({select:'*',session_id:`eq.${sessionId}`,kind:'eq.conversation_summary',deleted_at:'is.null',order:'updated_at.desc',limit:'1'})))[0];return row?memory(row):null;}
 async listConversationMessages(sessionId:string,limit:number){const rows=await this.database.select<{id:string;role:OrbyMessage['role'];content:string;metadata:OrbyJsonObject;created_at:string}>('orby_session_messages',params({select:'id,role,content,metadata,created_at',session_id:`eq.${sessionId}`,order:'created_at.desc,id.desc',limit:String(Math.min(200,Math.max(1,limit)))}));return rows.reverse().map(row=>({id:row.id,role:row.role,content:row.content,metadata:row.metadata||{},createdAt:row.created_at}));}

 async createKnowledgeSource(value:Omit<OrbyKnowledgeSource,'id'|'createdAt'|'updatedAt'>){const [row]=await this.database.insert<SourceRow>('orby_knowledge_sources',{organization_id:value.organizationId,workspace_id:value.workspaceId||null,name:value.name,source_type:value.type,status:value.status,citation_label:value.citationLabel,trust_level:value.trustLevel,metadata:value.metadata,version:value.version,created_by:value.createdBy||null});if(!row)throw new Error('ORBY_KNOWLEDGE_SOURCE_CREATE_FAILED');return source(row);}
 async listKnowledgeSources(identity:OrbyIdentity,limit:number){const p:Record<string,string>={select:'*',organization_id:`eq.${identity.organizationId}`,order:'updated_at.desc',limit:String(limit)};if(identity.workspaceId)p.or=`(workspace_id.is.null,workspace_id.eq.${identity.workspaceId})`;return(await this.database.select<SourceRow>('orby_knowledge_sources',params(p))).map(source);}
 async updateKnowledgeSource(id:string,patch:Partial<Pick<OrbyKnowledgeSource,'status'|'lastError'|'lastIndexedAt'|'metadata'|'version'>>){await this.database.update('orby_knowledge_sources',`id=eq.${encodeURIComponent(id)}`,compact({status:patch.status,last_error:patch.lastError??(Object.prototype.hasOwnProperty.call(patch,'lastError')?null:undefined),last_indexed_at:patch.lastIndexedAt,metadata:patch.metadata,version:patch.version,updated_at:new Date().toISOString()}),'return=minimal');}
 async getKnowledgeSource(id:string,identity:OrbyIdentity){const row=(await this.database.select<SourceRow>('orby_knowledge_sources',params({select:'*',id:`eq.${id}`,organization_id:`eq.${identity.organizationId}`,limit:'1'})))[0];return row?source(row):null;}
 async createKnowledgeDocument(value:Omit<OrbyKnowledgeDocument,'id'|'createdAt'|'updatedAt'>,rawText?:string){const [row]=await this.database.insert<DocumentRow>('orby_knowledge_documents',{source_id:value.sourceId,organization_id:value.organizationId,workspace_id:value.workspaceId||null,external_id:value.externalId||null,title:value.title,mime_type:value.mimeType,checksum:value.checksum,language:value.language||null,status:value.status,metadata:value.metadata,version:value.version,raw_text:rawText||null,extracted_at:value.extractedAt||null,indexed_at:value.indexedAt||null,last_error:value.lastError||null});if(!row)throw new Error('ORBY_KNOWLEDGE_DOCUMENT_CREATE_FAILED');return document(row);}
 async getKnowledgeDocument(id:string,identity:OrbyIdentity){const row=(await this.database.select<DocumentRow>('orby_knowledge_documents',params({select:'*',id:`eq.${id}`,organization_id:`eq.${identity.organizationId}`,limit:'1'})))[0];return row?document(row):null;}
 async listKnowledgeDocuments(input:{identity:OrbyIdentity;sourceId?:string;limit:number}){const p:Record<string,string>={select:'id,source_id,organization_id,workspace_id,external_id,title,mime_type,checksum,language,status,metadata,version,created_at,updated_at,extracted_at,indexed_at,last_error',organization_id:`eq.${input.identity.organizationId}`,order:'updated_at.desc',limit:String(input.limit)};if(input.sourceId)p.source_id=`eq.${input.sourceId}`;if(input.identity.workspaceId)p.or=`(workspace_id.is.null,workspace_id.eq.${input.identity.workspaceId})`;return(await this.database.select<DocumentRow>('orby_knowledge_documents',params(p))).map(document);}
 async getDocumentRawText(id:string){const row=(await this.database.select<{raw_text:string|null}>('orby_knowledge_documents',params({select:'raw_text',id:`eq.${id}`,limit:'1'})))[0];return row?.raw_text||null;}
 async replaceKnowledgeChunks(documentId:string,values:readonly Omit<OrbyKnowledgeChunk,'id'|'createdAt'>[]){return(await this.database.rpc<ChunkRow[]>('orby_replace_knowledge_chunks',{target_document:documentId,chunk_payload:values as unknown as OrbyJsonValue})).map(chunk);}
 async saveChunkEmbeddings(input:{chunks:readonly OrbyKnowledgeChunk[];vectors:readonly number[][];model:string}){await this.database.rpc('orby_save_chunk_embeddings',{chunk_ids:input.chunks.map(item=>item.id) as unknown as OrbyJsonValue,embedding_vectors:input.vectors as unknown as OrbyJsonValue,embedding_model_name:input.model});}
 async searchKnowledge(input:{identity:OrbyIdentity;vector:readonly number[];limit:number;minimumScore:number;sourceIds?:readonly string[]}){const rows=await this.database.rpc<Array<ChunkRow&{score:number;citation_label:string;document_title:string;source_metadata:OrbyJsonObject}>>('orby_search_knowledge',{target_organization:input.identity.organizationId,target_workspace:input.identity.workspaceId||null,query_embedding:input.vector as unknown as OrbyJsonValue,match_count:input.limit,minimum_score:input.minimumScore,source_filter:(input.sourceIds||[]) as unknown as OrbyJsonValue});return rows.map(row=>{const value=chunk(row);return{chunk:value,score:Number(row.score),citation:{id:randomUUID(),sourceId:value.sourceId,documentId:value.documentId,chunkId:value.id,label:row.citation_label,title:row.document_title,excerpt:value.content.slice(0,360),score:Number(row.score),metadata:row.source_metadata||{}}};});}
 async updateKnowledgeDocument(id:string,patch:Partial<Pick<OrbyKnowledgeDocument,'status'|'lastError'|'extractedAt'|'indexedAt'|'metadata'>>){await this.database.update('orby_knowledge_documents',`id=eq.${encodeURIComponent(id)}`,compact({status:patch.status,last_error:patch.lastError??(Object.prototype.hasOwnProperty.call(patch,'lastError')?null:undefined),extracted_at:patch.extractedAt,indexed_at:patch.indexedAt,metadata:patch.metadata,updated_at:new Date().toISOString()}),'return=minimal');}

 async publishEvent(value:OrbyIntelligenceEvent){await this.database.insert('orby_intelligence_events',{id:value.id,organization_id:value.organizationId,workspace_id:value.workspaceId||null,event_type:value.type,priority:value.priority,payload:value.payload,deduplication_key:value.deduplicationKey||null,occurred_at:value.occurredAt,available_at:value.availableAt,processed_at:value.processedAt||null},'resolution=ignore-duplicates,return=minimal');}
 async enqueue(value:Omit<OrbyIntelligenceJob,'id'|'status'|'attempts'|'createdAt'|'updatedAt'>){return job(await this.database.rpc<JobRow>('orby_enqueue_intelligence_job',{target_organization:value.organizationId,target_workspace:value.workspaceId||null,target_job_type:value.type,job_payload:value.payload,job_priority:value.priority,job_available_at:value.availableAt,job_max_attempts:value.maxAttempts,job_idempotency_key:value.idempotencyKey||null}));}
 async claimJobs(workerId:string,limit:number,leaseSeconds:number){return(await this.database.rpc<JobRow[]>('orby_claim_intelligence_jobs',{worker_id:workerId,claim_limit:limit,lease_seconds:leaseSeconds})).map(job);}
 async completeJob(jobId:string,workerId:string,result:OrbyJsonObject={}){await this.database.rpc('orby_complete_intelligence_job',{target_job:jobId,worker_id:workerId,job_result:result});}
 async failJob(jobId:string,workerId:string,errorCode:string,errorMessage:string,nextAttemptAt?:string){await this.database.rpc('orby_fail_intelligence_job',{target_job:jobId,worker_id:workerId,error_code:errorCode,error_message:errorMessage,next_attempt_at:nextAttemptAt||null});}
 async enqueueDueSchedules(limit:number){return this.database.rpc<number>('orby_enqueue_due_intelligence_schedules',{schedule_limit:limit});}
 async saveSchedule(value:Omit<OrbySchedule,'id'|'createdAt'|'updatedAt'> & {createdBy?:string}){const [row]=await this.database.insert<ScheduleRow>('orby_intelligence_schedules',{organization_id:value.organizationId,workspace_id:value.workspaceId||null,job_type:value.jobType,cron_expression:value.cronExpression||null,interval_seconds:value.intervalSeconds||null,payload:value.payload,enabled:value.enabled,next_run_at:value.nextRunAt,last_run_at:value.lastRunAt||null,timezone:value.timezone,created_by:value.createdBy||null});if(!row)throw new Error('ORBY_SCHEDULE_SAVE_FAILED');return schedule(row);}
 async listSchedules(identity:OrbyIdentity,limit:number){const p:Record<string,string>={select:'*',organization_id:`eq.${identity.organizationId}`,order:'next_run_at.asc',limit:String(limit)};if(identity.workspaceId)p.or=`(workspace_id.is.null,workspace_id.eq.${identity.workspaceId})`;return(await this.database.select<ScheduleRow>('orby_intelligence_schedules',params(p))).map(schedule);}
 async listDueEvents(limit:number){return(await this.database.select<EventRow>('orby_intelligence_events',params({select:'*',processed_at:'is.null',available_at:`lte.${new Date().toISOString()}`,order:'priority.asc,occurred_at.asc',limit:String(limit)}))).map(event);}
 async markEventProcessed(id:string){await this.database.update('orby_intelligence_events',`id=eq.${encodeURIComponent(id)}`,{processed_at:new Date().toISOString()},'return=minimal');}

 async upsertInsight(signalValue:Parameters<OrbyIntelligenceRepository['upsertInsight']>[0],cooldownMinutes:number){const value=await this.database.rpc<{row:InsightRow;created:boolean;suppressed:boolean}>('orby_upsert_insight',{signal_payload:signalValue as unknown as OrbyJsonValue,cooldown_minutes:cooldownMinutes});return{insight:insight(value.row),created:value.created,suppressed:value.suppressed};}
 async getInsight(id:string,identity:OrbyIdentity){const row=(await this.database.select<InsightRow>('orby_proactive_insights',params({select:'*',id:`eq.${id}`,organization_id:`eq.${identity.organizationId}`,limit:'1'})))[0];return row?insight(row):null;}
 async saveInsightWorkflow(id:string,workflow:OrbyJsonObject){await this.database.update('orby_proactive_insights',`id=eq.${encodeURIComponent(id)}`,{draft_workflow:workflow,updated_at:new Date().toISOString()},'return=minimal');}
 async listInsights(input:{identity:OrbyIdentity;status?:OrbyInsight['status'];limit:number}){const p:Record<string,string>={select:'*',organization_id:`eq.${input.identity.organizationId}`,order:'last_detected_at.desc',limit:String(input.limit)};if(input.identity.workspaceId)p.or=`(workspace_id.is.null,workspace_id.eq.${input.identity.workspaceId})`;if(input.status)p.status=`eq.${input.status}`;return(await this.database.select<InsightRow>('orby_proactive_insights',params(p))).map(insight);}
 async saveNotification(value:OrbyProactiveNotification){const [row]=await this.database.upsert<NotificationRow>('orby_proactive_notifications',{id:value.id,organization_id:value.organizationId,user_id:value.userId||null,workspace_id:value.workspaceId||null,insight_id:value.insightId||null,channel:value.channel,title:value.title,body:value.body,severity:value.severity,status:value.status,deduplication_key:value.deduplicationKey,available_at:value.availableAt,sent_at:value.sentAt||null,metadata:value.metadata,created_at:value.createdAt},'deduplication_key','resolution=ignore-duplicates,return=representation');const saved=row?notification(row):value;if(saved.channel==='in_app'&&saved.userId&&saved.status==='queued'&&Date.parse(saved.availableAt)<=Date.now())await this.database.insert('notifications',{user_id:saved.userId,title:saved.title,body:saved.body,link:saved.insightId?`/orby/insights/${saved.insightId}`:null},'return=minimal');return saved;}
 async getNotification(id:string){const row=(await this.database.select<NotificationRow>('orby_proactive_notifications',params({select:'*',id:`eq.${id}`,limit:'1'})))[0];return row?notification(row):null;}
 async updateNotification(id:string,patch:Partial<Pick<OrbyProactiveNotification,'status'|'sentAt'|'metadata'>>){await this.database.update('orby_proactive_notifications',`id=eq.${encodeURIComponent(id)}`,compact({status:patch.status,sent_at:patch.sentAt,metadata:patch.metadata}),'return=minimal');}
 async getNotificationPreferences(identity:OrbyIdentity){const row=(await this.database.select<{enabled:boolean;channels:OrbyNotificationPreference['channels'];minimum_severity:OrbyNotificationPreference['minimumSeverity'];quiet_hours:OrbyNotificationPreference['quietHours']|null;digest_mode:OrbyNotificationPreference['digestMode'];detector_settings:OrbyNotificationPreference['detectorSettings'];cooldown_minutes:number;metadata:OrbyJsonObject}>('orby_notification_preferences',params({select:'*',organization_id:`eq.${identity.organizationId}`,user_id:`eq.${identity.userId}`,workspace_id:identity.workspaceId?`eq.${identity.workspaceId}`:'is.null',limit:'1'})))[0];return row?{organizationId:identity.organizationId,userId:identity.userId,workspaceId:identity.workspaceId,enabled:row.enabled,channels:row.channels,minimumSeverity:row.minimum_severity,quietHours:row.quiet_hours||undefined,digestMode:row.digest_mode,detectorSettings:row.detector_settings||{},cooldownMinutes:row.cooldown_minutes,metadata:row.metadata||{}}:null;}
 async setNotificationPreferences(identity:OrbyIdentity,value:OrbyNotificationPreference){await this.database.upsert('orby_notification_preferences',{organization_id:identity.organizationId,user_id:identity.userId,workspace_id:identity.workspaceId||null,workspace_scope:identity.workspaceId||'00000000-0000-0000-0000-000000000000',enabled:value.enabled,channels:value.channels as unknown as OrbyJsonValue,minimum_severity:value.minimumSeverity,quiet_hours:(value.quietHours as unknown as OrbyJsonValue)||null,digest_mode:value.digestMode,detector_settings:value.detectorSettings as unknown as OrbyJsonValue,cooldown_minutes:value.cooldownMinutes,metadata:value.metadata,updated_at:new Date().toISOString()},'organization_id,user_id,workspace_scope','resolution=merge-duplicates,return=minimal');}
 async saveReport(value:Omit<OrbyPeriodicReport,'id'|'createdAt'|'updatedAt'>){const [row]=await this.database.insert<ReportRow>('orby_periodic_reports',{organization_id:value.organizationId,workspace_id:value.workspaceId||null,report_type:value.type,period_start:value.periodStart,period_end:value.periodEnd,title:value.title,summary:value.summary,sections:value.sections as unknown as OrbyJsonValue,citations:value.citations as unknown as OrbyJsonValue,status:value.status});if(!row)throw new Error('ORBY_REPORT_SAVE_FAILED');return report(row);}
 async listReports(input:{identity:OrbyIdentity;type?:OrbyReportType;limit:number}){const p:Record<string,string>={select:'*',organization_id:`eq.${input.identity.organizationId}`,order:'period_end.desc',limit:String(input.limit)};if(input.identity.workspaceId)p.or=`(workspace_id.is.null,workspace_id.eq.${input.identity.workspaceId})`;if(input.type)p.report_type=`eq.${input.type}`;return(await this.database.select<ReportRow>('orby_periodic_reports',params(p))).map(report);}
}
