import type {OrbyIdentity,OrbyJsonObject,OrbyJsonValue} from '../../core/contracts';
import type {OrbyMadarToolGateway,OrbyToolContext,OrbyToolHealth,OrbyToolResult} from '../contracts';
import {OrbyExecutionError} from '../errors';
import {toolFailure,toolResult} from '../tools';
import {FeatureFlagService,IntegrationDatabase,IntegrationQueue} from '@/src/lib/integration/platform';
import {params} from './supabase-shared';

export type OrbyAnalysisExecutor=(input:{prompt:string;sessionId?:string;identity:OrbyIdentity;signal:AbortSignal})=>Promise<{text:string;sessionId:string;providerId:string;modelId:string}>;

export class SupabaseMadarToolGateway implements OrbyMadarToolGateway {
 private readonly integrationQueue:IntegrationQueue;private readonly integrationFlags:FeatureFlagService;
 constructor(private readonly database=new IntegrationDatabase(),private readonly analyze?:OrbyAnalysisExecutor){this.integrationQueue=new IntegrationQueue(database);this.integrationFlags=new FeatureFlagService(database);}
 private async connection(connectionId:string,organizationId:string){const row=(await this.database.select<{id:string;status:string}>('integration_connections',params({select:'id,status',id:`eq.${connectionId}`,organization_id:`eq.${organizationId}`,deleted_at:'is.null',limit:'1'})))[0];if(!row)throw new OrbyExecutionError('اتصال النظام الخارجي غير موجود في مساحة العمل.','TOOL_INVALID',false,{connectionId});return row;}
 async execute(operation:string,input:OrbyJsonObject,context:OrbyToolContext):Promise<OrbyToolResult>{
  if(operation==='data.search'){const entityType=typeof input.entityType==='string'?input.entityType:undefined,limit=Math.min(100,Math.max(1,Number(input.limit||25))),query=String(input.query||'').toLowerCase(),search=params({select:'id,entity_type,canonical_data,quality_score,updated_at',organization_id:`eq.${context.identity.organizationId}`,lifecycle_status:'eq.active',order:'updated_at.desc',limit:String(limit)});if(entityType)search.set('entity_type',`eq.${entityType}`);const rows=await this.database.select<{id:string;entity_type:string;canonical_data:OrbyJsonObject;quality_score:number;updated_at:string}>('integration_udm_records',search),filtered=query?rows.filter(row=>JSON.stringify(row.canonical_data).toLowerCase().includes(query)):rows;return toolResult({status:'completed',count:filtered.length,items:filtered as unknown as OrbyJsonValue[]});}
  if(operation==='intelligence.analyze'){if(!this.analyze)return toolFailure('ANALYSIS_UNAVAILABLE','نواة التحليل غير متاحة.',true);if(context.mode==='sandbox')return toolResult({text:'معاينة تحليل دون استدعاء نموذج خارجي.',sessionId:'sandbox',providerId:'sandbox',modelId:'sandbox'});return toolResult(await this.analyze({prompt:String(input.prompt),sessionId:typeof input.sessionId==='string'?input.sessionId:undefined,identity:context.identity,signal:context.signal}) as unknown as OrbyJsonValue);}
  if(operation==='platform.notify.self'){if(context.mode==='sandbox')return toolResult({status:'preview',data:input});await this.database.insert('notifications',{user_id:context.identity.userId,title:String(input.title),body:String(input.body),link:typeof input.link==='string'?input.link:null},'return=minimal');return toolResult({status:'created'});}
  if(operation==='business.action.draft'||operation==='files.export.request'){const actionType=operation==='files.export.request'?'FILE_EXPORT_REQUEST':String(input.actionType),payload=operation==='files.export.request'?input:input.payload as OrbyJsonObject;if(context.mode==='sandbox')return toolResult({status:'preview',data:{actionType,payload}});const [created]=await this.database.insert<{id:string}>('orby_action_drafts',{organization_id:context.identity.organizationId,user_id:context.identity.userId,action_type:actionType,payload,status:'draft'});return toolResult({status:'draft',id:created?.id||''});}
  if(operation.startsWith('integration.')){const connectionId=String(input.connectionId||''),connection=await this.connection(connectionId,context.identity.organizationId);const jobType=operation==='integration.connection.test'?'connection.test':operation==='integration.sync.initial'?'sync.initial':'sync.incremental';if(jobType!=='connection.test'&&connection.status!=='active')return toolFailure('CONNECTION_NOT_ACTIVE','الاتصال غير نشط للمزامنة.',false,{connectionId,status:connection.status});if(context.mode==='sandbox')return toolResult({status:'preview',data:{connectionId:connection.id,jobType}});await this.integrationFlags.require('integration_engine_enabled',context.identity.organizationId);const job=await this.integrationQueue.enqueue({organizationId:context.identity.organizationId,connectionId:connection.id,jobType,payload:{streams:(input.streams||[]) as OrbyJsonValue,requested_by_orby:true,orby_run_id:context.runId,orby_action_id:context.actionId},idempotencyKey:`orby:${context.actionId}:${jobType}`,createdBy:context.identity.userId});return toolResult({status:'queued',id:job.id,data:{connectionId:connection.id,jobType}});}
  return toolFailure('UNSUPPORTED_OPERATION','عملية بوابة مَدار غير مدعومة.',false,{operation});
 }
 async cancel(){return;}
 async health(operation:string,signal?:AbortSignal):Promise<OrbyToolHealth>{const started=Date.now();try{if(signal?.aborted)throw new DOMException('Aborted','AbortError');await this.database.select('integration_feature_flags',params({select:'key',limit:'1'}));return{ok:true,checkedAt:new Date().toISOString(),latencyMs:Date.now()-started,metadata:{operation}};}catch(error){return{ok:false,checkedAt:new Date().toISOString(),latencyMs:Date.now()-started,message:error instanceof Error?error.message:'Gateway unavailable',metadata:{operation}};}}
}
