import type {OrbyIdentity,OrbyJsonObject,OrbyJsonValue} from '../../core/contracts';
import type {OrbyActionRecord,OrbyApprovalRecord,OrbyExecutionRepository,OrbyToolManifest,OrbyToolResult,OrbyWorkflowRecord,OrbyWorkflowRun} from '../contracts';
import {defaultExecutionConfiguration} from '../governance';
import {OrbyExecutionError} from '../errors';
import {IntegrationDatabase} from '@/src/lib/integration/platform';
import {action,approval,compact,params,run,workflow,type ActionRow,type ApprovalRow,type ConfigRow,type RunRow,type WorkflowRow} from './supabase-shared';

export class SupabaseOrbyExecutionRepository implements OrbyExecutionRepository {
 constructor(private readonly database=new IntegrationDatabase()){}
 private async configRow(organizationId:string|null){return(await this.database.select<ConfigRow>('orby_execution_config',params({select:'organization_id,enabled,config',organization_id:organizationId?`eq.${organizationId}`:'is.null',limit:'1'})))[0];}
 async configuration(organizationId:string){const [global,scoped]=await Promise.all([this.configRow(null),this.configRow(organizationId)]);return{...defaultExecutionConfiguration(),...(global?.config||{}),...(global?{enabled:global.enabled}:{}),...(scoped?.config||{}),...(scoped?{enabled:scoped.enabled}:{}),planningEnabled:scoped?.config?.planningEnabled??global?.config?.planningEnabled??false};}
 async saveWorkflow(value:OrbyWorkflowRecord){const [row]=await this.database.insert<WorkflowRow>('orby_workflows',{id:value.id,organization_id:value.organizationId,created_by:value.createdBy,goal:value.goal,plan:value.plan as unknown as OrbyJsonValue,status:value.status,version:value.version,created_at:value.createdAt,updated_at:value.updatedAt});if(!row)throw new OrbyExecutionError('تعذر حفظ سير عمل أوربي.','DATABASE_ERROR');return workflow(row);}
 async workflow(id:string){const row=(await this.database.select<WorkflowRow>('orby_workflows',params({select:'*',id:`eq.${id}`,limit:'1'})))[0];return row?workflow(row):null;}
 async createRun(value:OrbyWorkflowRun){const [row]=await this.database.insert<RunRow>('orby_workflow_runs',{id:value.id,workflow_id:value.workflowId,organization_id:value.organizationId,user_id:value.userId,workspace_id:value.workspaceId||null,status:value.status,reason:value.reason,state:value.state as unknown as OrbyJsonValue,result:value.result??null,error_code:value.errorCode||null,error_message:value.errorMessage||null,created_at:value.createdAt,started_at:value.startedAt||null,completed_at:value.completedAt||null,updated_at:value.updatedAt});if(!row)throw new OrbyExecutionError('تعذر إنشاء تشغيل أوربي.','DATABASE_ERROR');return run(row);}
 async run(id:string){const row=(await this.database.select<RunRow>('orby_workflow_runs',params({select:'*',id:`eq.${id}`,limit:'1'})))[0];return row?run(row):null;}
 async updateRun(id:string,patch:Partial<OrbyWorkflowRun>){const [row]=await this.database.update<RunRow>('orby_workflow_runs',`id=eq.${encodeURIComponent(id)}`,compact({workflow_id:patch.workflowId,organization_id:patch.organizationId,user_id:patch.userId,workspace_id:patch.workspaceId,status:patch.status,reason:patch.reason,state:patch.state as OrbyJsonValue|undefined,result:patch.result,error_code:patch.errorCode??(Object.prototype.hasOwnProperty.call(patch,'errorCode')?null:undefined),error_message:patch.errorMessage??(Object.prototype.hasOwnProperty.call(patch,'errorMessage')?null:undefined),started_at:patch.startedAt,completed_at:patch.completedAt,updated_at:patch.updatedAt||new Date().toISOString()}));if(!row)throw new OrbyExecutionError('تشغيل أوربي غير موجود.','RUN_NOT_FOUND');return run(row);}
 async createAction(value:OrbyActionRecord){const [row]=await this.database.insert<ActionRow>('orby_actions',{id:value.id,run_id:value.runId,organization_id:value.organizationId,user_id:value.userId,step_key:value.stepKey,tool_name:value.toolName,operation:value.operation,status:value.status,input:value.input,result:(value.result as unknown as OrbyJsonValue)??null,error_code:value.errorCode||null,error_message:value.errorMessage||null,attempt:value.attempt,max_attempts:value.maxAttempts,risk_level:value.riskLevel,execution_mode:value.executionMode,compensation:(value.compensation as unknown as OrbyJsonValue)??null,started_at:value.startedAt||null,completed_at:value.completedAt||null,created_at:value.createdAt,updated_at:value.updatedAt});if(!row)throw new OrbyExecutionError('تعذر إنشاء إجراء أوربي.','DATABASE_ERROR');return action(row);}
 async action(id:string){const row=(await this.database.select<ActionRow>('orby_actions',params({select:'*',id:`eq.${id}`,limit:'1'})))[0];return row?action(row):null;}
 async actionByStep(runId:string,stepKey:string){const row=(await this.database.select<ActionRow>('orby_actions',params({select:'*',run_id:`eq.${runId}`,step_key:`eq.${stepKey}`,limit:'1'})))[0];return row?action(row):null;}
 async updateAction(id:string,patch:Partial<OrbyActionRecord>){const [row]=await this.database.update<ActionRow>('orby_actions',`id=eq.${encodeURIComponent(id)}`,compact({status:patch.status,input:patch.input,result:patch.result as unknown as OrbyJsonValue|undefined,error_code:patch.errorCode??(Object.prototype.hasOwnProperty.call(patch,'errorCode')?null:undefined),error_message:patch.errorMessage??(Object.prototype.hasOwnProperty.call(patch,'errorMessage')?null:undefined),attempt:patch.attempt,max_attempts:patch.maxAttempts,risk_level:patch.riskLevel,execution_mode:patch.executionMode,compensation:patch.compensation as unknown as OrbyJsonValue|undefined,started_at:patch.startedAt,completed_at:patch.completedAt,updated_at:patch.updatedAt||new Date().toISOString()}));if(!row)throw new OrbyExecutionError('إجراء أوربي غير موجود.','ACTION_NOT_FOUND');return action(row);}
 async actions(runId:string){return(await this.database.select<ActionRow>('orby_actions',params({select:'*',run_id:`eq.${runId}`,order:'created_at.asc'}))).map(action);}
 async createApproval(value:OrbyApprovalRecord){const [row]=await this.database.insert<ApprovalRow>('orby_approvals',{id:value.id,run_id:value.runId,action_id:value.actionId||null,organization_id:value.organizationId,requested_by:value.requestedBy,scope:value.scope,status:value.status,reason:value.reason,decided_by:value.decidedBy||null,decision_reason:value.decisionReason||null,expires_at:value.expiresAt,metadata:value.metadata||{},created_at:value.createdAt,decided_at:value.decidedAt||null});if(!row)throw new OrbyExecutionError('تعذر إنشاء طلب موافقة أوربي.','DATABASE_ERROR');return approval(row);}
 async approval(id:string){const row=(await this.database.select<ApprovalRow>('orby_approvals',params({select:'*',id:`eq.${id}`,limit:'1'})))[0];return row?approval(row):null;}
 async approvalForAction(actionId:string){const row=(await this.database.select<ApprovalRow>('orby_approvals',params({select:'*',action_id:`eq.${actionId}`,order:'created_at.desc',limit:'1'})))[0];return row?approval(row):null;}
 async updateApproval(id:string,patch:Partial<OrbyApprovalRecord>){const [row]=await this.database.update<ApprovalRow>('orby_approvals',`id=eq.${encodeURIComponent(id)}`,compact({status:patch.status,decided_by:patch.decidedBy,decision_reason:patch.decisionReason,metadata:patch.metadata,decided_at:patch.decidedAt}));if(!row)throw new OrbyExecutionError('طلب الموافقة غير موجود.','APPROVAL_REQUIRED');return approval(row);}
 async appendEvent(input:{runId:string;actionId?:string;organizationId:string;eventType:string;payload:OrbyJsonObject}){await this.database.insert('orby_execution_events',{run_id:input.runId,action_id:input.actionId||null,organization_id:input.organizationId,event_type:input.eventType,payload:input.payload},'return=minimal');}
 async appendAudit(input:{runId:string;actionId?:string;approvalId?:string;organizationId:string;actorId?:string;eventType:string;reason?:string;outcome?:string;metadata?:OrbyJsonObject}){await this.database.insert('orby_execution_audit',{run_id:input.runId,action_id:input.actionId||null,approval_id:input.approvalId||null,organization_id:input.organizationId,actor_id:input.actorId||null,event_type:input.eventType,reason:input.reason||null,outcome:input.outcome||null,metadata:input.metadata||{}},'return=minimal');}
 async notify(input:{userId:string;title:string;body:string;link?:string}){await this.database.insert('notifications',{user_id:input.userId,title:input.title,body:input.body,link:input.link||null},'return=minimal');}
 async notifyApproval(input:{organizationId:string;requestedBy:string;scope:OrbyApprovalRecord['scope'];title:string;body:string;link?:string}){let recipients=[input.requestedBy];if(input.scope==='manager'){const rows=await this.database.select<{user_id:string}>('organization_members',params({select:'user_id',organization_id:`eq.${input.organizationId}`,role:'in.(OWNER,ADMIN)'}));recipients=[...new Set(rows.map(row=>row.user_id))];if(!recipients.length)recipients=[input.requestedBy];}await this.database.insert('notifications',recipients.map(userId=>({user_id:userId,title:input.title,body:input.body,link:input.link||null})),'return=minimal');}
 async saveSandbox(input:{runId:string;actionId:string;organizationId:string;userId:string;toolName:string;status:'running'|'completed'|'failed';input:OrbyJsonObject;result?:OrbyToolResult;createdAt:string;completedAt?:string}){await this.database.upsert('orby_sandbox_runs',{run_id:input.runId,action_id:input.actionId,organization_id:input.organizationId,user_id:input.userId,tool_name:input.toolName,status:input.status,input:input.input,result:(input.result as unknown as OrbyJsonValue)??null,created_at:input.createdAt,completed_at:input.completedAt||null},'action_id');}
 async consumeBudget(identity:OrbyIdentity,limits:{daily:number;perMinute:number}){return this.database.rpc<{allowed:boolean;dailyUsed:number;minuteUsed:number}>('orby_consume_execution_budget',{target_organization:identity.organizationId,target_user:identity.userId,daily_limit:limits.daily,minute_limit:limits.perMinute});}
 async enabledToolNames(){const rows=await this.database.select<{name:string}>('orby_tool_catalog',params({select:'name',enabled:'eq.true',status:'eq.active',order:'name.asc'}));return rows.map(row=>row.name);}
 async syncToolCatalog(manifests:readonly OrbyToolManifest[]){const existing=await this.database.select<{name:string;enabled:boolean}>('orby_tool_catalog',params({select:'name,enabled'})),byName=new Map(existing.map(item=>[item.name,item]));for(const manifest of manifests){const value={name:manifest.name,version:manifest.version,category:manifest.category,status:manifest.status,enabled:byName.get(manifest.name)?.enabled??false,manifest:manifest as unknown as OrbyJsonValue,updated_at:new Date().toISOString()};await this.database.upsert('orby_tool_catalog',value,'name','resolution=merge-duplicates,return=minimal');}}
}
