import type {OrbyJsonObject,OrbyJsonValue} from '../../core/contracts';
import type {OrbyActionRecord,OrbyApprovalRecord,OrbyExecutionConfiguration,OrbyQueueJob,OrbyToolResult,OrbyWorkflowRecord,OrbyWorkflowRun} from '../contracts';

export function compact(value:Record<string,unknown>){return Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined)) as OrbyJsonObject;}
export function params(value:Record<string,string>){return new URLSearchParams(value);}

export type ConfigRow={organization_id:string|null;enabled:boolean;config:Partial<OrbyExecutionConfiguration>};
export type WorkflowRow={id:string;organization_id:string;created_by:string;goal:string;plan:OrbyWorkflowRecord['plan'];status:OrbyWorkflowRecord['status'];version:number;created_at:string;updated_at:string};
export type RunRow={id:string;workflow_id:string;organization_id:string;user_id:string;workspace_id:string|null;status:OrbyWorkflowRun['status'];reason:string;state:OrbyWorkflowRun['state'];result:OrbyJsonValue|null;error_code:string|null;error_message:string|null;created_at:string;started_at:string|null;completed_at:string|null;updated_at:string};
export type ActionRow={id:string;run_id:string;organization_id:string;user_id:string;step_key:string;tool_name:string;operation:string;status:OrbyActionRecord['status'];input:OrbyJsonObject;result:OrbyToolResult|null;error_code:string|null;error_message:string|null;attempt:number;max_attempts:number;risk_level:OrbyActionRecord['riskLevel'];execution_mode:OrbyActionRecord['executionMode'];compensation:OrbyActionRecord['compensation']|null;started_at:string|null;completed_at:string|null;created_at:string;updated_at:string};
export type ApprovalRow={id:string;run_id:string;action_id:string|null;organization_id:string;requested_by:string;scope:OrbyApprovalRecord['scope'];status:OrbyApprovalRecord['status'];reason:string;decided_by:string|null;decision_reason:string|null;expires_at:string;metadata:OrbyJsonObject;created_at:string;decided_at:string|null};
export type QueueRow={id:string;run_id:string;organization_id:string;status:OrbyQueueJob['status'];priority:number;available_at:string;attempts:number;max_attempts:number;idempotency_key:string|null;locked_by:string|null;lease_expires_at:string|null;created_at:string;updated_at:string};

export function workflow(row:WorkflowRow):OrbyWorkflowRecord{return{id:row.id,organizationId:row.organization_id,createdBy:row.created_by,goal:row.goal,plan:row.plan,status:row.status,version:row.version,createdAt:row.created_at,updatedAt:row.updated_at};}
export function run(row:RunRow):OrbyWorkflowRun{return{id:row.id,workflowId:row.workflow_id,organizationId:row.organization_id,userId:row.user_id,workspaceId:row.workspace_id||undefined,status:row.status,reason:row.reason,state:row.state,result:row.result??undefined,errorCode:row.error_code||undefined,errorMessage:row.error_message||undefined,createdAt:row.created_at,startedAt:row.started_at||undefined,completedAt:row.completed_at||undefined,updatedAt:row.updated_at};}
export function action(row:ActionRow):OrbyActionRecord{return{id:row.id,runId:row.run_id,organizationId:row.organization_id,userId:row.user_id,stepKey:row.step_key,toolName:row.tool_name,operation:row.operation,status:row.status,input:row.input,result:row.result||undefined,errorCode:row.error_code||undefined,errorMessage:row.error_message||undefined,attempt:row.attempt,maxAttempts:row.max_attempts,riskLevel:row.risk_level,executionMode:row.execution_mode,compensation:row.compensation||undefined,startedAt:row.started_at||undefined,completedAt:row.completed_at||undefined,createdAt:row.created_at,updatedAt:row.updated_at};}
export function approval(row:ApprovalRow):OrbyApprovalRecord{return{id:row.id,runId:row.run_id,actionId:row.action_id||undefined,organizationId:row.organization_id,requestedBy:row.requested_by,scope:row.scope,status:row.status,reason:row.reason,decidedBy:row.decided_by||undefined,decisionReason:row.decision_reason||undefined,expiresAt:row.expires_at,metadata:row.metadata,createdAt:row.created_at,decidedAt:row.decided_at||undefined};}
export function queue(row:QueueRow):OrbyQueueJob{return{id:row.id,runId:row.run_id,organizationId:row.organization_id,status:row.status,priority:row.priority,availableAt:row.available_at,attempts:row.attempts,maxAttempts:row.max_attempts,idempotencyKey:row.idempotency_key||undefined,lockedBy:row.locked_by||undefined,leaseExpiresAt:row.lease_expires_at||undefined,createdAt:row.created_at,updatedAt:row.updated_at};}
