import Link from 'next/link';
import ActionFeedback from '@/components/business/ActionFeedback';
import {prepareBusinessImport} from '@/app/actions/imports';
import {requireBusinessWorkspace} from '@/src/lib/business';
import {supabaseFetch} from '@/src/lib/supabase/server';

export const dynamic='force-dynamic';export const metadata={title:'استيراد التجارة | مَدار'};
const entityLabels:{[key:string]:string}={products:'المنتجات والمخزون',customers:'العملاء',suppliers:'الموردون',expenses:'المصروفات',sales:'المبيعات السابقة'};
const statusLabels:{[key:string]:string}={uploaded:'بانتظار المطابقة',imported:'مستوردة',rolled_back:'تم التراجع',failed:'فشلت'};
export default async function ImportsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const{workspace}=await requireBusinessWorkspace(),params=await searchParams;
 const imports=await supabaseFetch(`/rest/v1/business_imports?organization_id=eq.${encodeURIComponent(workspace.id)}&select=id,entity_type,status,file_name,imported_count,created_at,committed_at,rolled_back_at&order=created_at.desc&limit=50`);
 return <main className="mx-auto max-w-7xl p-5 py-10"><p className="font-bold text-[#70E4D4]">ربط تجارة قائمة</p><h2 className="mt-2 text-4xl font-black">استيراد البيانات</h2><p className="mt-3 max-w-3xl leading-8 text-slate-300">ارفع CSV، راجع عينة من الصفوف، طابق أعمدتك مع حقول مَدار، ثم نفّذ الاستيراد. الحد الحالي 500 صف لكل عملية لحماية النسخة التجريبية.</p><div className="mt-8 grid gap-8 lg:grid-cols-[400px_1fr]"><section><ActionFeedback {...params}/><form action={prepareBusinessImport} encType="multipart/form-data" className="grid gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-6"><h3 className="text-xl font-black">عملية استيراد جديدة</h3><label className="grid gap-2 text-sm font-bold">نوع البيانات<select name="entity_type" required className="field rounded-xl p-3"><option value="products">المنتجات والمخزون الافتتاحي</option><option value="customers">العملاء</option><option value="suppliers">الموردون</option><option value="expenses">المصروفات</option><option value="sales">المبيعات السابقة</option></select></label><label className="grid gap-2 text-sm font-bold">ملف CSV<input name="file" type="file" accept=".csv,text/csv,text/plain" required className="field rounded-xl p-3 file:ml-3 file:rounded-lg file:border-0 file:bg-white file:px-3 file:py-2 file:font-bold file:text-slate-950"/></label><div className="rounded-xl border border-white/10 p-4 text-xs leading-6 text-slate-400"><p>• الصف الأول يجب أن يحتوي أسماء الأعمدة.</p><p>• يدعم الفاصلة والفاصلة المنقوطة وTab.</p><p>• الحد الأقصى 1MB و500 صف.</p><p>• لن تُضاف البيانات قبل مراجعة المطابقة.</p></div><button className="rounded-xl bg-gradient-to-l from-violet-500 to-emerald-400 p-3 font-black">رفع ومعاينة</button></form><div className="mt-4 grid grid-cols-2 gap-2 text-sm">{Object.entries(entityLabels).map(([entity,label])=><Link key={entity} href={`/workspace/imports/template/${entity}`} className="rounded-xl border border-white/10 p-3 text-center font-bold text-slate-300 hover:text-white">قالب {label}</Link>)}</div></section><section><h3 className="text-xl font-black">سجل الاستيراد</h3><div className="mt-4 space-y-3">{imports?.length?imports.map((item:{id:string;entity_type:string;status:string;file_name:string;imported_count:number;created_at:string})=><Link href={`/workspace/imports/${item.id}`} key={item.id} className="grid gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-5 transition hover:border-[#70E4D4]/40 sm:grid-cols-4 sm:items-center"><div><strong>{entityLabels[item.entity_type]||item.entity_type}</strong><p className="mt-1 text-xs text-slate-400">{item.file_name}</p></div><span>{statusLabels[item.status]||item.status}</span><span>{item.imported_count} صف</span><span className="text-xs text-slate-400">{new Date(item.created_at).toLocaleString('ar-YE')}</span></Link>):<p className="rounded-3xl border border-white/10 p-10 text-center text-slate-400">لم تُرفع ملفات استيراد بعد.</p>}</div></section></div></main>;
}
