import {requireSuperAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import {createOrbyBackup,setOrbyFlag,setPluginState,setPolicyState} from './actions';

export const dynamic='force-dynamic';
export const metadata={title:'مركز ORBY OS | مَدار'};

type Dashboard={release:{version?:string;status?:string;rollout?:number};workflows:{definitions:number;active:number;templates:number};plugins:{catalog:number;active:number;installations:number};governance:{policies:number;immutable:number};observability:{traces_24h:number;failed_24h:number;cost_30d:number};evaluation:{suites:number;last_run?:{status:string;score:number|null;started_at:string}|null};channels:{active:number;external_active:number};generated_at:string};
type Flag={id:string;key:string;enabled:boolean;rollout_percentage:number;configuration:Record<string,unknown>;updated_at:string};
type Release={id:string;component:string;component_key:string;version:string;status:string;rollout_percentage:number;created_at:string};
type Workflow={id:string;key:string;name:string;domain:string;status:string;updated_at:string};
type Plugin={id:string;key:string;name:string;kind:string;entrypoint:string;status:string;updated_at:string};
type Policy={id:string;key:string;name:string;priority:number;effect:string;enabled:boolean;immutable:boolean};
type Channel={id:string;key:string;name:string;status:string;supports_inbound:boolean;supports_outbound:boolean};
type EvalRun={id:string;status:string;score:number|null;passed_cases:number;failed_cases:number;started_at:string};
type Backup={id:string;backup_type:string;status:string;created_at:string;expires_at:string|null};

const scalar=<T,>(value:unknown)=>Array.isArray(value)?value[0] as T:value as T;
const number=(value:number)=>Number(value||0).toLocaleString('ar-EG');
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString('ar-EG'):'—';
const labels:Record<string,string>={orby_os_enabled:'ORBY OS',orby_workflows_enabled:'محرك التدفقات',orby_plugins_enabled:'نظام الإضافات',orby_multi_model_routing_enabled:'التوجيه متعدد النماذج',orby_observability_enabled:'المراقبة الشاملة',orby_evaluation_enabled:'التقييم والاختبارات',orby_provider_execution_enabled:'تشغيل المزود الخارجي',orby_ocr_enabled:'OCR للصور والملفات الممسوحة',orby_external_channels_enabled:'القنوات الخارجية'};

export default async function OrbyOsAdminPage(){
 await requireSuperAdmin();
 const [dashboardRaw,flags,releases,workflows,plugins,policies,channels,evaluations,backups]=await Promise.all([
  supabaseFetch('/rest/v1/rpc/orby_os_admin_dashboard',{method:'POST',body:'{}'}),
  supabaseFetch('/rest/v1/orby_feature_flags?organization_id=is.null&workspace_id=is.null&user_id=is.null&select=id,key,enabled,rollout_percentage,configuration,updated_at&order=key.asc'),
  supabaseFetch('/rest/v1/orby_os_releases?select=id,component,component_key,version,status,rollout_percentage,created_at&order=created_at.desc&limit=30'),
  supabaseFetch('/rest/v1/orby_workflow_definitions?select=id,key,name,domain,status,updated_at&order=domain.asc,key.asc&limit=100'),
  supabaseFetch('/rest/v1/orby_plugins?select=id,key,name,kind,entrypoint,status,updated_at&order=key.asc&limit=100'),
  supabaseFetch('/rest/v1/orby_governance_policies?select=id,key,name,priority,effect,enabled,immutable&order=priority.desc&limit=100'),
  supabaseFetch('/rest/v1/orby_channels?select=id,key,name,status,supports_inbound,supports_outbound&order=key.asc'),
  supabaseFetch('/rest/v1/orby_evaluation_runs?select=id,status,score,passed_cases,failed_cases,started_at&order=started_at.desc&limit=10'),
  supabaseFetch('/rest/v1/orby_backups?select=id,backup_type,status,created_at,expires_at&order=created_at.desc&limit=10'),
 ]);
 const dashboard=scalar<Dashboard>(dashboardRaw),flagRows=flags as Flag[],releaseRows=releases as Release[],workflowRows=workflows as Workflow[],pluginRows=plugins as Plugin[],policyRows=policies as Policy[],channelRows=channels as Channel[],evaluationRows=evaluations as EvalRun[],backupRows=backups as Backup[];
 return <main className="mx-auto max-w-[1500px] p-5 py-8 sm:p-8">
  <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-bold text-violet-200">Expansion, Governance & ORBY OS</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">مركز إدارة ORBY OS v1</h1><p className="mt-3 max-w-4xl leading-8 text-slate-400">نظام التحكم المؤسسي في التدفقات والإضافات والمجالات والسياسات والتوجيه والمراقبة والتكاليف والتقييم والإصدارات. مفاتيح المزود وOCR والقنوات الخارجية مؤجلة ومغلقة.</p></div><form action={createOrbyBackup}><button className="md-button md-button-secondary" type="submit">إنشاء نسخة إعدادات</button></form></div>
  <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Metric label="إصدار ORBY OS" value={dashboard.release.version||'—'}/><Metric label="Workflows النشطة" value={number(dashboard.workflows.active)}/><Metric label="Plugins النشطة" value={number(dashboard.plugins.active)}/><Metric label="سياسات الحوكمة" value={number(dashboard.governance.policies)}/><Metric label="Traces خلال 24س" value={number(dashboard.observability.traces_24h)}/><Metric label="القنوات الخارجية" value={number(dashboard.channels.external_active)} alert={dashboard.channels.external_active>0}/></section>
  <Section title="بوابات التشغيل" subtitle="البوابات المؤجلة لا يمكن تفعيلها من هذه المرحلة حتى بعد اختيار المزود ومراجعة الربط."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{flagRows.map(flag=><form action={setOrbyFlag} key={flag.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-4"><div><strong>{labels[flag.key]||flag.key}</strong><p className="mt-2 text-xs text-slate-500">Rollout {flag.rollout_percentage}%</p></div><Status value={flag.enabled?'active':'paused'}/></div><input type="hidden" name="key" value={flag.key}/><input type="hidden" name="enabled" value={String(!flag.enabled)}/><input type="hidden" name="rollout" value={flag.rollout_percentage||100}/><button className="md-button md-button-secondary md-button-sm mt-4" type="submit" disabled={['orby_provider_execution_enabled','orby_ocr_enabled','orby_external_channels_enabled'].includes(flag.key)}>{flag.enabled?'إيقاف':'تفعيل'}</button></form>)}</div></Section>
  <section className="mt-8 grid gap-6 xl:grid-cols-2"><Section title="Workflow Engine" subtitle={`${workflowRows.length} تعريفًا بإصدارات ثابتة وقوالب قابلة لإعادة الاستخدام.`}>{workflowRows.map(item=><Row key={item.id} title={item.name} meta={`${item.key} · ${item.domain}`} status={item.status}/>)}</Section><Section title="Plugin Architecture" subtitle="كل Entrypoint مترجم داخل المستودع؛ لا تحميل كود ديناميكي.">{pluginRows.map(item=><div key={item.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><strong>{item.name}</strong><p className="mt-1 text-xs text-slate-500">{item.key} · {item.entrypoint}</p></div><Status value={item.status}/></div><form action={setPluginState} className="mt-3 flex gap-2"><input type="hidden" name="plugin_id" value={item.id}/><input type="hidden" name="status" value={item.status==='active'?'paused':'active'}/><button className="md-button md-button-secondary md-button-sm" type="submit">{item.status==='active'?'إيقاف':'تفعيل'}</button></form></div>)}</Section></section>
  <Section title="ORBY Governance" subtitle="سياسات حتمية تسبق تقدير النموذج، مع Default Deny وموانع غير قابلة للتعطيل."><div className="grid gap-3 lg:grid-cols-2">{policyRows.map(policy=><div key={policy.id} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.025] p-4"><div><strong>{policy.name}</strong><p className="mt-1 text-xs text-slate-500">{policy.key} · {policy.effect} · أولوية {policy.priority}</p></div><div className="flex items-center gap-2"><Status value={policy.enabled?'active':'paused'}/>{!policy.immutable&&<form action={setPolicyState}><input type="hidden" name="policy_id" value={policy.id}/><input type="hidden" name="enabled" value={String(!policy.enabled)}/><button className="md-button md-button-secondary md-button-sm" type="submit">تغيير</button></form>}</div></div>)}</div></Section>
  <section className="mt-8 grid gap-6 xl:grid-cols-3"><Section title="Observability & Cost" subtitle="قياسات الخادم فقط؛ لا يتم تقدير مؤشرات الأعمال بواسطة النموذج."><Small label="فشل خلال 24 ساعة" value={number(dashboard.observability.failed_24h)} alert={dashboard.observability.failed_24h>0}/><Small label="تكلفة 30 يومًا" value={`${Number(dashboard.observability.cost_30d||0).toLocaleString('ar-EG')} USD`}/><Small label="آخر تحديث" value={date(dashboard.generated_at)}/></Section><Section title="Evaluation Engine" subtitle={`${dashboard.evaluation.suites} حزمة اختبار مفعلة.`}>{evaluationRows.length?evaluationRows.map(item=><Row key={item.id} title={item.status} meta={`النتيجة ${item.score??'—'} · نجاح ${item.passed_cases} · فشل ${item.failed_cases}`} status={item.status}/>):<Empty text="لم تُشغّل حزمة تقييم بعد."/>}</Section><Section title="Backup & Recovery" subtitle="الاستعادة تمر أولًا بفحص checksum ومراجعة صريحة.">{backupRows.length?backupRows.map(item=><Row key={item.id} title={item.backup_type} meta={`${date(item.created_at)} · ينتهي ${date(item.expires_at)}`} status={item.status}/>):<Empty text="لا توجد نسخ إعدادات بعد."/>}</Section></section>
  <Section title="Channel-Ready Architecture" subtitle="القنوات تمر عبر الهوية والمؤسسة والصلاحيات والسياسات والتدقيق وحدود الاستخدام."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{channelRows.map(channel=><div key={channel.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between"><strong>{channel.name}</strong><Status value={channel.status}/></div><p className="mt-2 text-xs text-slate-500">Inbound {channel.supports_inbound?'نعم':'لا'} · Outbound {channel.supports_outbound?'نعم':'لا'}</p></div>)}</div></Section>
 </main>;
}
function Section({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="mt-8 rounded-3xl border border-white/10 bg-white/[.015] p-5 sm:p-6"><h2 className="text-2xl font-black">{title}</h2><p className="mt-2 text-sm leading-7 text-slate-400">{subtitle}</p><div className="mt-5 space-y-3">{children}</div></section>}
function Metric({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <div className={`rounded-2xl border p-4 ${alert?'border-rose-300/30 bg-rose-300/[.05]':'border-white/10 bg-white/[.025]'}`}><span className="text-xs text-slate-500">{label}</span><strong className="mt-2 block text-2xl">{value}</strong></div>}
function Small({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <div className="flex items-center justify-between gap-4 border-b border-white/10 py-3"><span className="text-sm text-slate-400">{label}</span><strong className={alert?'text-rose-200':''}>{value}</strong></div>}
function Row({title,meta,status}:{title:string;meta:string;status:string}){return <div className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.025] p-4"><div><strong>{title}</strong><p className="mt-1 text-xs text-slate-500">{meta}</p></div><Status value={status}/></div>}
function Status({value}:{value:string}){const good=['active','ready','passed','succeeded','completed'].includes(value);return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${good?'bg-emerald-300/10 text-emerald-200':'bg-slate-500/10 text-slate-400'}`}>{value}</span>}
function Empty({text}:{text:string}){return <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">{text}</p>}
