/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import StoreEntityForm from '@/components/admin/store/StoreEntityForm';
import StoreTaxonomyForm from '@/components/admin/store/StoreTaxonomyForm';
import {FeaturedForm,OfferForm,SettingForm} from '@/components/admin/store/StoreSpecialForms';
import {softDeleteFeaturedItem,softDeleteOffer,softDeleteStoreEntity,softDeleteTaxonomy} from '@/app/actions/store';
import {Icon} from '@/components/ui/Icons';

export const dynamic='force-dynamic';
type Props={params:Promise<{section:string}>;searchParams:Promise<{edit?:string}>};
const entitySections={products:{kind:'product',table:'products',title:'إدارة المنتجات'},services:{kind:'service',table:'services',title:'إدارة الخدمات'},plans:{kind:'plan',table:'plans',title:'إدارة الاشتراكات'}} as const;
const taxonomySections={categories:{kind:'category',table:'categories',title:'إدارة التصنيفات'},subcategories:{kind:'subcategory',table:'subcategories',title:'إدارة الفئات الفرعية'},tags:{kind:'tag',table:'tags',title:'إدارة الوسوم'}} as const;
const titles:Record<string,string>={media:'إدارة الصور والملفات',offers:'إدارة العروض',featured:'إدارة العناصر المميزة',search:'إدارة البحث والفهرسة',settings:'إعدادات المتجر'};

export default async function Page({params,searchParams}:Props){await requireAdmin();const section=(await params).section,edit=(await searchParams).edit||'';const entity=entitySections[section as keyof typeof entitySections];if(entity)return <EntitySection config={entity} edit={edit}/>;const taxonomy=taxonomySections[section as keyof typeof taxonomySections];if(taxonomy)return <TaxonomySection config={taxonomy} edit={edit}/>;if(section==='offers')return <OffersSection edit={edit}/>;if(section==='featured')return <FeaturedSection edit={edit}/>;if(section==='settings')return <SettingsSection edit={edit}/>;if(section==='media')return <MediaSection/>;if(section==='search')return <SearchSection/>;notFound()}

async function baseTaxonomy(){let categories:any[]=[];let subcategories:any[]=[];let tags:any[]=[];try{[categories,subcategories,tags]=await Promise.all([supabaseFetch('/rest/v1/categories?deleted_at=is.null&select=id,name,slug,visibility,is_active,sort_order&order=sort_order.asc,name.asc'),supabaseFetch('/rest/v1/subcategories?deleted_at=is.null&select=id,name,slug,category_id,visibility,is_active,sort_order&order=sort_order.asc,name.asc'),supabaseFetch('/rest/v1/tags?deleted_at=is.null&select=id,name,slug,is_active&order=name.asc')])}catch{}return{categories,subcategories,tags}}

async function EntitySection({config,edit}:{config:(typeof entitySections)[keyof typeof entitySections];edit:string}){const{categories,subcategories,tags}=await baseTaxonomy();let rows:any[]=[];let selectedTagIds:string[]=[];try{rows=await supabaseFetch(`/rest/v1/${config.table}?deleted_at=is.null&select=*&order=updated_at.desc`);if(edit){const relation=`${config.kind}_tags`,foreignKey=`${config.kind}_id`,links=await supabaseFetch(`/rest/v1/${relation}?${foreignKey}=eq.${encodeURIComponent(edit)}&select=tag_id`);selectedTagIds=links.map((link:{tag_id:string})=>link.tag_id)}}catch{}const initial=rows.find(row=>row.id===edit);return <Shell title={config.title} description="أنشئ وعدّل وانشر العناصر من هنا؛ لا حاجة لأي تعديل في الكود أو قاعدة البيانات يدويًا."><StoreEntityForm kind={config.kind} initial={initial} categories={categories} subcategories={subcategories} tags={tags} selectedTagIds={selectedTagIds}/><EntityList rows={rows} kind={config.kind} section={config.table}/></Shell>}

function EntityList({rows,kind,section}:{rows:any[];kind:'product'|'service'|'plan';section:string}){return <section className="mt-7 space-y-3"><h2 className="text-xl font-black">العناصر الحالية ({rows.length})</h2>{rows.map(row=><article key={row.id} className="md-card flex flex-wrap items-center justify-between gap-4 p-4"><div className="min-w-0"><strong className="block truncate">{row.name}</strong><p className="mt-1 text-xs text-slate-500" dir="ltr">{row.slug}</p><div className="mt-2 flex flex-wrap gap-2"><span className="md-badge">{row.status}</span><span className="md-badge">{row.visibility||'hidden'}</span><span className={`md-badge ${row.is_active?'md-badge-success':''}`}>{row.is_active?'نشط':'غير نشط'}</span></div></div><div className="flex flex-wrap gap-2"><Link href={`/admin/store/${section}?edit=${row.id}`} className="md-button md-button-secondary md-button-sm">تعديل</Link><Link href={kind==='product'?`/products/${row.slug}`:kind==='service'?`/services/${row.slug}`:`/subscriptions/${row.slug}`} className="md-button md-button-ghost md-button-sm">معاينة</Link><form action={softDeleteStoreEntity}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="kind" value={kind}/><button className="md-button md-button-danger md-button-sm">حذف ناعم</button></form></div></article>)}{!rows.length&&<Empty text="لا توجد عناصر في هذا القسم."/>}</section>}

async function TaxonomySection({config,edit}:{config:(typeof taxonomySections)[keyof typeof taxonomySections];edit:string}){const{categories}=await baseTaxonomy();let rows:any[]=[];try{rows=await supabaseFetch(`/rest/v1/${config.table}?deleted_at=is.null&select=*&order=created_at.desc`)}catch{}const initial=rows.find(row=>row.id===edit);return <Shell title={config.title} description="تحكم في بنية التصنيف والبحث وترتيب الظهور."><StoreTaxonomyForm kind={config.kind} initial={initial} categories={categories}/><section className="mt-7 space-y-3">{rows.map(row=><article key={row.id} className="md-card flex flex-wrap items-center justify-between gap-4 p-4"><div><strong>{row.name}</strong><p className="mt-1 text-xs text-slate-500" dir="ltr">{row.slug}</p></div><div className="flex gap-2"><Link href={`/admin/store/${config.table}?edit=${row.id}`} className="md-button md-button-secondary md-button-sm">تعديل</Link><form action={softDeleteTaxonomy}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="kind" value={config.kind}/><button className="md-button md-button-danger md-button-sm">حذف ناعم</button></form></div></article>)}{!rows.length&&<Empty text="لا توجد بيانات بعد."/>}</section></Shell>}

async function OffersSection({edit}:{edit:string}){let rows:any[]=[];try{rows=await supabaseFetch('/rest/v1/offers?deleted_at=is.null&select=*&order=created_at.desc')}catch{}const initial=rows.find(row=>row.id===edit);return <Shell title={titles.offers} description="أنشئ الخصومات وحدد وقت بدايتها ونهايتها وحالة نشرها."><OfferForm initial={initial}/><SimpleRows rows={rows} section="offers" deleteAction={softDeleteOffer}/></Shell>}
async function FeaturedSection({edit}:{edit:string}){let rows:any[]=[];try{rows=await supabaseFetch('/rest/v1/featured_items?deleted_at=is.null&select=*&order=sort_order.asc,created_at.desc')}catch{}const initial=rows.find(row=>row.id===edit);return <Shell title={titles.featured} description="تحكم في مواضع الظهور المميز داخل المتجر والصفحة الرئيسية."><FeaturedForm initial={initial}/><SimpleRows rows={rows} section="featured" deleteAction={softDeleteFeaturedItem}/></Shell>}
async function SettingsSection({edit}:{edit:string}){let rows:any[]=[];try{rows=await supabaseFetch('/rest/v1/store_settings?deleted_at=is.null&select=*&order=setting_key.asc')}catch{}const initial=rows.find(row=>row.id===edit);return <Shell title={titles.settings} description="إعدادات مرنة بصيغة JSON للعرض والعملة والطلب دون تعديل الكود."><SettingForm initial={initial}/><section className="mt-7 grid gap-3">{rows.map(row=><Link key={row.id} href={`/admin/store/settings?edit=${row.id}`} className="md-card md-card-interactive p-4"><strong dir="ltr">{row.setting_key}</strong><p className="mt-1 text-sm text-slate-400">{row.description}</p></Link>)}</section></Shell>}

async function MediaSection(){let products:any[]=[];let services:any[]=[];try{[products,services]=await Promise.all([supabaseFetch('/rest/v1/products?deleted_at=is.null&select=id,name,thumbnail_url&order=updated_at.desc'),supabaseFetch('/rest/v1/services?deleted_at=is.null&select=id,name,thumbnail_url&order=updated_at.desc')])}catch{}return <Shell title={titles.media} description="ارفع صور الأغلفة ومعارض الصور وملفات PDF وZIP من مدير الوسائط الآمن الحالي."><div className="grid gap-5 lg:grid-cols-2"><MediaGroup title="صور وملفات المنتجات" rows={products} type="products"/><MediaGroup title="صور الخدمات" rows={services} type="services"/></div></Shell>}
function MediaGroup({title,rows,type}:{title:string;rows:any[];type:'products'|'services'}){return <section className="md-panel"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 space-y-2">{rows.map(row=><Link key={row.id} href={`/admin/${type}/${row.id}/edit`} className="flex items-center justify-between rounded-xl border border-white/10 p-3 hover:bg-white/[.04]"><span>{row.name}</span><span className="md-badge">{row.thumbnail_url?'له غلاف':'دون غلاف'}</span></Link>)}</div></section>}

async function SearchSection(){let products:any[]=[];let services:any[]=[];let plans:any[]=[];try{[products,services,plans]=await Promise.all([supabaseFetch('/rest/v1/products?deleted_at=is.null&select=id,name,slug,keywords,seo_title,seo_description&order=updated_at.desc'),supabaseFetch('/rest/v1/services?deleted_at=is.null&select=id,name,slug,keywords,seo_title,seo_description&order=updated_at.desc'),supabaseFetch('/rest/v1/plans?deleted_at=is.null&select=id,name,slug,keywords,seo_title,seo_description&order=updated_at.desc')])}catch{}const rows=[...products.map(row=>({...row,type:'products'})),...services.map(row=>({...row,type:'services'})),...plans.map(row=>({...row,type:'plans'}))];return <Shell title={titles.search} description="راجع جاهزية العناصر للبحث وSEO، وعدّل الكلمات المفتاحية والبيانات الوصفية من نموذج العنصر."><div className="grid gap-3">{rows.map(row=>{const ready=Boolean(row.seo_title&&row.seo_description&&row.keywords?.length);return <Link key={`${row.type}-${row.id}`} href={`/admin/store/${row.type}?edit=${row.id}`} className="md-card md-card-interactive flex items-center justify-between gap-4 p-4"><span><strong>{row.name}</strong><span className="mt-1 block text-xs text-slate-500" dir="ltr">{row.slug}</span></span><span className={`md-badge ${ready?'md-badge-success':''}`}>{ready?'جاهز للبحث':'يحتاج إكمال SEO'}</span></Link>})}</div></Shell>}

function SimpleRows({rows,section,deleteAction}:{rows:any[];section:string;deleteAction:(form:FormData)=>Promise<void>}){return <section className="mt-7 space-y-3">{rows.map(row=><article key={row.id} className="md-card flex items-center justify-between gap-4 p-4"><div><strong>{row.name||`${row.entity_type} · ${row.placement}`}</strong><p className="mt-1 text-xs text-slate-500">{row.status||row.entity_id}</p></div><div className="flex gap-2"><Link href={`/admin/store/${section}?edit=${row.id}`} className="md-button md-button-secondary md-button-sm">تعديل</Link><form action={deleteAction}><input type="hidden" name="id" value={row.id}/><button className="md-button md-button-danger md-button-sm">حذف ناعم</button></form></div></article>)}{!rows.length&&<Empty text="لا توجد سجلات."/>}</section>}
function Shell({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <main className="mx-auto max-w-7xl p-4 py-6 sm:p-6"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/store" className="text-sm text-emerald-300">إدارة المتجر ←</Link><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-2 max-w-3xl leading-7 text-slate-400">{description}</p></div><Link href="/store" className="md-button md-button-secondary"><Icon name="store"/>المتجر</Link></header>{children}</main>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">{text}</p>}
