import Link from 'next/link';
import {reviewJobApplication} from '@/app/actions/applications';
import ActionFeedback from '@/components/business/ActionFeedback';
import {requireSuperAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import {jobs} from '@/src/data/platform-content';

export const dynamic='force-dynamic';
export const metadata={title:'طلبات التوظيف | مَدار',robots:{index:false,follow:false}};

type Application={id:string;job_slug:string;full_name:string;phone:string|null;whatsapp_number:string|null;applicant_bio:string|null;application_reason:string|null;experience_summary:string;cv_storage_path:string|null;cv_file_name:string|null;status:'new'|'reviewing'|'shortlisted'|'rejected'|'hired';review_notes:string|null;reviewed_at:string|null;created_at:string};
const statusLabel:Record<Application['status'],string>={new:'جديد',reviewing:'قيد المراجعة',shortlisted:'مقبول مبدئيًا',rejected:'مرفوض',hired:'تم التوظيف'};
const statusClass:Record<Application['status'],string>={new:'bg-sky-300/10 text-sky-100',reviewing:'bg-amber-300/10 text-amber-100',shortlisted:'bg-emerald-300/10 text-emerald-100',rejected:'bg-red-300/10 text-red-100',hired:'bg-violet-300/10 text-violet-100'};

export default async function ApplicationsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 await requireSuperAdmin();const params=await searchParams;
 let rows:Application[]=[];let loadError=false;
 try{rows=await supabaseFetch('/rest/v1/job_applications?select=id,job_slug,full_name,phone,whatsapp_number,applicant_bio,application_reason,experience_summary,cv_storage_path,cv_file_name,status,review_notes,reviewed_at,created_at&order=created_at.desc&limit=200') as Application[];}catch{loadError=true;}
 const jobName=(slug:string)=>jobs.find(job=>job.slug===slug)?.title||slug;
 return <main className="mx-auto max-w-7xl p-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-violet-200">صلاحيات المؤسس</p><h1 className="mt-2 text-4xl font-black">طلبات التوظيف</h1><p className="mt-3 max-w-3xl leading-7 text-slate-400">مراجعة طلبات المدوّن والمطور والمسوق، وفتح السير الذاتية الخاصة، ثم الموافقة المبدئية أو الرفض.</p></div><Link href="/careers" className="rounded-xl border border-white/15 px-4 py-3 font-bold">عرض صفحة التوظيف</Link></div>
  <div className="mt-6"><ActionFeedback success={params.success} error={params.error}/></div>
  {loadError?<p role="alert" className="mt-7 rounded-2xl border border-red-400/20 bg-red-400/5 p-6">تعذر تحميل الطلبات. تحقق من اتصال قاعدة البيانات.</p>:rows.length?<section className="mt-7 grid gap-5">{rows.map(row=>{const wa=(row.whatsapp_number||'').replace(/\D/g,'');return <article key={row.id} className="rounded-3xl border border-white/10 bg-white/[.04] p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="text-[#70E4D4]">{jobName(row.job_slug)}</span><span className={`rounded-full px-3 py-1 ${statusClass[row.status]}`}>{statusLabel[row.status]}</span></div><h2 className="mt-3 text-2xl font-black">{row.full_name}</h2><p className="mt-2 text-xs text-slate-500">أُرسل في {new Date(row.created_at).toLocaleString('ar-YE')}{row.reviewed_at?` · روجع في ${new Date(row.reviewed_at).toLocaleString('ar-YE')}`:''}</p></div><div className="flex flex-wrap gap-2">{wa&&<a href={`https://wa.me/${wa}`} target="_blank" rel="noopener noreferrer" className="rounded-xl bg-[#00C292] px-4 py-2 font-black text-slate-950">واتساب</a>}{row.phone&&<a href={`tel:${row.phone}`} className="rounded-xl border border-white/15 px-4 py-2 font-bold">اتصال</a>}{row.cv_storage_path&&<a href={`/admin/applications/${row.id}/cv`} className="rounded-xl border border-violet-300/30 px-4 py-2 font-bold text-violet-100">السيرة الذاتية{row.cv_file_name?` · ${row.cv_file_name}`:''}</a>}</div></div>
   <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-black/10 p-5"><h3 className="font-black text-[#70E4D4]">نبذة ومواهب</h3><p className="mt-3 whitespace-pre-wrap leading-8 text-slate-300">{row.applicant_bio||row.experience_summary}</p></section><section className="rounded-2xl border border-white/10 bg-black/10 p-5"><h3 className="font-black text-violet-200">سبب التقديم</h3><p className="mt-3 whitespace-pre-wrap leading-8 text-slate-300">{row.application_reason||'لم يُسجّل في النموذج القديم.'}</p></section></div>
   <form action={reviewJobApplication} className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><input type="hidden" name="id" value={row.id}/><label className="grid gap-2 text-sm font-bold">ملاحظات المؤسس (اختياري)<textarea name="review_notes" defaultValue={row.review_notes||''} maxLength={1500} rows={3} className="field rounded-xl p-3" placeholder="ملاحظة داخلية عن القرار أو الخطوة التالية."/></label><div className="mt-4 flex flex-wrap gap-3"><button name="decision" value="approve" className="rounded-xl bg-[#00C292] px-5 py-3 font-black text-slate-950">موافقة مبدئية</button><button name="decision" value="reject" className="rounded-xl border border-red-300/30 px-5 py-3 font-black text-red-200">رفض الطلب</button></div></form>
  </article>})}</section>:<p className="mt-7 rounded-3xl border border-dashed border-white/10 p-12 text-center text-slate-500">لا توجد طلبات توظيف بعد.</p>}
 </main>;
}
