export declare const MOBILE_API_VERSION: '2.0';
export type OperatingMode = 'MADAR_NATIVE' | 'CONNECTED_EXTERNAL';
export type SourceOfTruth = 'MADAR' | 'EXTERNAL';
export type MobileSeverity = 'critical' | 'warning' | 'info' | 'success';
export type MobileCommandStatus = 'draft' | 'previewed' | 'queued' | 'sending' | 'executed' | 'synced' | 'failed' | 'needs_review' | 'cancelled';
export type MobileInternalAction = 'TASK_COMPLETE' | 'TASK_REOPEN' | 'TASK_RESCHEDULE' | 'TASK_NOTE' | 'ALERT_ACKNOWLEDGE' | 'ALERT_HIDE' | 'FOLLOWUP_CREATE';
export type MobileExternalAction = 'CUSTOMER_NOTE' | 'ORDER_STATUS_UPDATE' | 'INVENTORY_ADJUST' | 'FOLLOWUP_STATUS_UPDATE';
export type MobileBlockedAction = 'PRICE_CHANGE' | 'PAYMENT_TRANSFER' | 'SENSITIVE_DELETE' | 'TEAM_MANAGEMENT' | 'CONNECTOR_PERMISSION_CHANGE' | 'CONNECTOR_CREDENTIAL_CHANGE' | 'BULK_WRITE';
export type MobileCommandAction = MobileInternalAction | MobileExternalAction | MobileBlockedAction;
export declare const MOBILE_INTERNAL_ACTIONS: readonly MobileInternalAction[];
export declare const MOBILE_EXTERNAL_ACTIONS: readonly MobileExternalAction[];
export declare const MOBILE_BLOCKED_ACTIONS: readonly MobileBlockedAction[];
export type MobileAlert = { id: string; severity: MobileSeverity; title: string; body: string; generatedAt: string; acknowledgedAt?: string | null; hiddenAt?: string | null };
export type MobileTask = { id: string; title: string; priority: string; dueAt: string | null; status?: string; note?: string | null };
export type MobileOperation = { id: string; action: MobileCommandAction; label: string; status: MobileCommandStatus; targetType: string | null; targetId: string | null; createdAt: string; updatedAt: string; message?: string | null };
export type MobileWorkspace = { id: string; name: string; type: string; status: string; currency: 'YER' | 'SAR' | 'USD'; role: string; operatingMode: OperatingMode; sourceOfTruth: SourceOfTruth; setupStatus: string };
export type MobileDashboardSnapshot = {
  contractVersion: '2.0';
  profile: { id: string; fullName: string | null; email: string | null; avatarUrl: string | null };
  workspace: MobileWorkspace;
  availableWorkspaces: Array<{ id: string; name: string; role: string }>;
  vertical: { code: string; name: string; extension: 'commerce' | 'food_service' | 'hospitality' | string };
  subscriptionStatus: 'trialing' | 'active' | 'past_due' | 'expired' | 'cancelled' | 'missing';
  status: 'ok' | 'attention';
  summary: { products: number; customers: number; revenue30d: number; expenses30d: number; profit30d: number; todayRevenue: number; openTasks: number; lowStock: number; sector: Record<string, unknown> };
  alerts: MobileAlert[];
  tasks: MobileTask[];
  recentSales: Array<{ id: string; total: number; soldAt: string }>;
  dailySeries: Array<{ date: string; label: string; revenue: number; expenses: number }>;
  sync: { state: 'live' | 'delayed' | 'offline' | 'unknown'; lastSyncedAt: string; connectorState: 'connected' | 'disconnected' | 'degraded' | 'not_required' | 'unknown'; isStale: boolean; staleAfterSeconds: number };
  capabilities: { canWriteInternal: boolean; canWriteExternal: boolean; canUseOrby: boolean; canUploadAttachments: boolean; canUsePush: boolean };
  fetchedAt: string;
};
export type MobilePage<T> = { items: T[]; nextCursor: string | null; hasMore: boolean };
export type MobileCommandInput = { organizationId: string; action: MobileCommandAction; targetType?: string | null; targetId?: string | null; payload?: Record<string, unknown>; idempotencyKey: string };
export type MobileCommandPreview = { allowed: boolean; blockedReason: string | null; confirmationToken: string | null; executionPath: 'MADAR_NATIVE' | 'CONNECTED_EXTERNAL' | 'BLOCKED'; summary: string; warnings: string[]; requiresOnline: true; expiresAt: string | null };
export type MobileCommandResult = { operation: MobileOperation; systemConfirmed: boolean; madarSynced: boolean };
export type OrbyMode = 'GENERAL' | 'SALES' | 'INVENTORY' | 'CUSTOMERS' | 'PLANNING';
export type OrbyMessage = { id: string; role: 'user' | 'assistant'; text: string; createdAt: string; source?: 'ai' | 'smart-fallback'; attachments?: Array<{ id: string; name: string; mimeType: string; size: number }> };
export type OrbyConversation = { id: string; title: string; mode: OrbyMode; archived: boolean; updatedAt: string; messages?: OrbyMessage[] };
