export const MOBILE_API_VERSION = '2.0';
export const MOBILE_INTERNAL_ACTIONS = [
  'TASK_COMPLETE',
  'TASK_REOPEN',
  'TASK_RESCHEDULE',
  'TASK_NOTE',
  'ALERT_ACKNOWLEDGE',
  'ALERT_HIDE',
  'FOLLOWUP_CREATE',
];
export const MOBILE_EXTERNAL_ACTIONS = [
  'CUSTOMER_NOTE',
  'ORDER_STATUS_UPDATE',
  'INVENTORY_ADJUST',
  'FOLLOWUP_STATUS_UPDATE',
];
export const MOBILE_BLOCKED_ACTIONS = [
  'PRICE_CHANGE',
  'PAYMENT_TRANSFER',
  'SENSITIVE_DELETE',
  'TEAM_MANAGEMENT',
  'CONNECTOR_PERMISSION_CHANGE',
  'CONNECTOR_CREDENTIAL_CHANGE',
  'BULK_WRITE',
];
