import type { Metadata } from "next";
import { PageHeader } from "@/components/retail-v0/layout/page-header";
import { FlashMessage } from "@/components/retail-v0/ui/flash-message";
import { SubmitButton } from "@/components/retail-v0/ui/submit-button";
import { formatDateTime, formatMoney } from "@/src/lib/retail/format";
import { createClient } from "@/src/lib/retail/supabase/server";
import { relationValue } from "@/src/lib/retail/relations";
import { requireWorkspace } from "@/src/lib/retail/server/auth/context";
import { submitPaymentRequestAction, updateProfileAction, updateWorkspaceSettingsAction } from "./actions";

export const metadata: Metadata = { title: "الإعدادات والاشتراك" };

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const [context, params] = await Promise.all([requireWorkspace(), searchParams]);
  const { workspace, user, role, subscription } = context;
  const supabase = await createClient();
  const [profileResult, plansResult, methodsResult, requestsResult, workspaceResult] = await Promise.all([
    supabase.from("retail_profiles").select("full_name,phone,email").eq("id", user.id).single(),
    supabase.from("retail_plans").select("id,name_ar,description_ar,price_amount,currency,billing_months,trial_days").eq("status", "active").eq("is_public", true),
    supabase.from("retail_payment_methods").select("id,name_ar,kind,account_name,account_identifier,instructions_ar,currency").eq("status", "active").order("sort_order"),
    supabase.from("retail_payment_requests").select("id,amount,currency,status,payment_reference,created_at,review_note,plans:retail_plans(name_ar)").eq("workspace_id", workspace.id).order("created_at", { ascending: false }).limit(10),
    supabase.from("retail_workspaces").select("name,owner_name,phone,city,invoice_prefix,price_display,allow_credit_sales").eq("id", workspace.id).single(),
  ]);
  const profile = profileResult.data;
  const settings = workspaceResult.data;
  const payablePlans = (plansResult.data ?? []).filter((plan) => plan.price_amount != null && plan.billing_months != null);
  const canManage = role === "OWNER" || role === "MANAGER";
  return <div className="content-grid"><FlashMessage {...params} /><PageHeader eyebrow="الإعدادات" title="التجارة والحساب والاشتراك" description="Retail إضافة داخل مساحة مَدار نفسها، وخطتها وطلبات الدفع تُدار من مركز Retail." />
    <section className="grid gap-4 xl:grid-cols-2">
      <form action={updateProfileAction} className="surface grid gap-4 p-5"><h2 className="text-lg font-black">ملفك الشخصي</h2><label className="field"><span>الاسم</span><input className="input" name="full_name" defaultValue={profile?.full_name ?? ""} required /></label><label className="field"><span>البريد</span><input className="input" value={profile?.email ?? ""} disabled /></label><label className="field"><span>الهاتف</span><input className="input" name="phone" defaultValue={profile?.phone ?? ""} /></label><SubmitButton>حفظ الملف</SubmitButton></form>
      <form action={updateWorkspaceSettingsAction} className="surface grid gap-4 p-5"><h2 className="text-lg font-black">إعدادات التجارة</h2><label className="field"><span>اسم التجارة</span><input className="input" name="name" defaultValue={settings?.name} required disabled={!canManage} /></label><div className="grid grid-cols-2 gap-3"><label className="field"><span>اسم المالك</span><input className="input" name="owner_name" defaultValue={settings?.owner_name ?? ""} disabled={!canManage} /></label><label className="field"><span>الهاتف</span><input className="input" name="phone" defaultValue={settings?.phone ?? ""} disabled={!canManage} /></label></div><div className="grid grid-cols-2 gap-3"><label className="field"><span>المدينة</span><input className="input" name="city" defaultValue={settings?.city ?? ""} disabled={!canManage} /></label><label className="field"><span>بادئة الفاتورة</span><input className="input" name="invoice_prefix" defaultValue={settings?.invoice_prefix} dir="ltr" disabled={!canManage} /></label></div><label className="field"><span>عرض السعر</span><select className="input" name="price_display" defaultValue={settings?.price_display} disabled={!canManage}><option value="simple">بسيط</option><option value="tax_inclusive">شامل الضريبة مستقبلًا</option></select></label><label className="surface-soft flex items-center gap-3 p-3"><input type="checkbox" name="allow_credit_sales" defaultChecked={settings?.allow_credit_sales} disabled={!canManage} /><span>السماح بالبيع الآجل</span></label>{canManage ? <SubmitButton>حفظ إعدادات التجارة</SubmitButton> : <p className="muted text-sm">هذه الإعدادات للمالك والمدير.</p>}</form>
    </section>
    <section className="surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-black">الاشتراك</h2><p className="muted mt-1 text-sm">الحالة الحالية والخطة من قاعدة البيانات.</p></div><span className="status-pill">{subscription.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="surface-soft p-4"><span className="muted text-xs">الخطة</span><strong className="mt-1 block">{subscription.plan?.name_ar}</strong></div><div className="surface-soft p-4"><span className="muted text-xs">نهاية التجربة</span><strong className="mt-1 block">{formatDateTime(subscription.trial_ends_at)}</strong></div><div className="surface-soft p-4"><span className="muted text-xs">نهاية الاشتراك</span><strong className="mt-1 block">{formatDateTime(subscription.ends_at)}</strong></div></div>
      {role === "OWNER" && payablePlans.length && methodsResult.data?.length ? <form action={submitPaymentRequestAction} className="mt-5 grid gap-4 border-t border-slate-800 pt-5" encType="multipart/form-data"><input type="hidden" name="operation_id" value={crypto.randomUUID()} /><h3 className="font-black">إرسال إثبات دفع محلي</h3><div className="grid gap-3 sm:grid-cols-2"><label className="field"><span>الخطة</span><select className="input" name="plan_id">{payablePlans.map((plan) => <option value={plan.id} key={plan.id}>{plan.name_ar} — {formatMoney(plan.price_amount, plan.currency)}</option>)}</select></label><label className="field"><span>طريقة الدفع</span><select className="input" name="payment_method_id">{methodsResult.data.map((method) => <option value={method.id} key={method.id}>{method.name_ar} — {method.account_identifier}</option>)}</select></label><label className="field"><span>المبلغ المطابق للخطة</span><input className="input" type="number" name="amount" min="0" step="0.01" required /></label><label className="field"><span>رقم الحوالة/المرجع</span><input className="input" name="payment_reference" minLength={3} required /></label><label className="field sm:col-span-2"><span>الإثبات</span><input className="input" type="file" name="proof" accept="image/jpeg,image/png,image/webp,application/pdf" required /></label></div><SubmitButton>إرسال للمراجعة</SubmitButton></form> : <p className="muted mt-5 border-t border-slate-800 pt-4 text-sm">طلب الدفع سيتاح عندما تعتمد الإدارة سعر خطة وطريقة دفع محلية نشطة.</p>}
    </section>
    <section className="surface p-5"><h2 className="text-lg font-black">سجل طلبات الدفع</h2><div className="table-wrap mt-4"><table className="data-table"><thead><tr><th>المرجع</th><th>الخطة</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th><th>ملاحظة الإدارة</th></tr></thead><tbody>{(requestsResult.data ?? []).map((request) => <tr key={request.id}><td>{request.payment_reference}</td><td>{relationValue(request.plans, "name_ar")}</td><td>{formatMoney(request.amount, request.currency)}</td><td><span className="status-pill">{request.status}</span></td><td>{formatDateTime(request.created_at)}</td><td>{request.review_note ?? "—"}</td></tr>)}</tbody></table></div></section>
  </div>;
}
