import assert from 'node:assert/strict';
import {HashEmbeddingService} from '../src/lib/orby/intelligence/embedding';
import {NativeTextExtractor,OrbyDocumentChunker} from '../src/lib/orby/intelligence/knowledge';
import {DeterministicConversationSummarizer,OrbyMemoryPolicyEngine,DEFAULT_MEMORY_POLICY} from '../src/lib/orby/intelligence/memory';
import {OrbyCitationEngine,OrbyHallucinationGuard} from '../src/lib/orby/intelligence/rag';
import {SalesDropDetector,type OrbyMetricSnapshot} from '../src/lib/orby/intelligence/analytics';
import type {OrbyDetectorInput,OrbyKnowledgeDocument,OrbyRagContext} from '../src/lib/orby/intelligence/contracts';
import type {OrbyJsonObject} from '../src/lib/orby/core/contracts';

async function main(){
 type Check={key:string;status:'passed';details:OrbyJsonObject};const checks:Check[]=[];
 async function check(key:string,operation:()=>Promise<OrbyJsonObject>|OrbyJsonObject){checks.push({key,status:'passed',details:await operation()});}

 await check('local-embeddings',async()=>{const service=new HashEmbeddingService(128),vectors=await service.embed(['انخفاض المبيعات هذا الأسبوع','تحليل انخفاض المبيعات','وصفة طبخ منزلية']);assert.equal(vectors.length,3);assert.equal(vectors[0].length,128);const cosine=(a:number[],b:number[])=>a.reduce((sum,value,index)=>sum+value*b[index],0);assert.ok(cosine(vectors[0] as number[],vectors[1] as number[])>cosine(vectors[0] as number[],vectors[2] as number[]));return{model:service.model,dimensions:128};});
 await check('native-extraction-and-chunking',async()=>{const extracted=await new NativeTextExtractor().extract({mimeType:'application/json',text:JSON.stringify({sales:120,orders:8})});assert.match(extracted.text,/"sales": 120/);const document:OrbyKnowledgeDocument={id:'doc-1',sourceId:'source-1',organizationId:'org-1',title:'Sales report',mimeType:'application/json',checksum:'x',status:'chunking',metadata:{},version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const chunks=new OrbyDocumentChunker(80,10).chunk({document,text:`${extracted.text}\n\n${'تفاصيل المبيعات '.repeat(20)}`});assert.ok(chunks.length>1);assert.ok(chunks.every(chunk=>chunk.content.length<=80));return{chunks:chunks.length};});
 await check('conversation-summary',async()=>{const summary=await new DeterministicConversationSummarizer().summarize({messages:[{id:'1',role:'user',content:'أريد تقرير المبيعات',createdAt:new Date().toISOString()},{id:'2',role:'assistant',content:'سأعتمد على بيانات مساحة العمل',createdAt:new Date().toISOString()}],maxCharacters:500});assert.match(summary,/تقرير المبيعات/);return{characters:summary.length};});
 await check('memory-policy',()=>{const engine=new OrbyMemoryPolicyEngine();const enabledPolicy={...DEFAULT_MEMORY_POLICY,enabled:true};engine.assertAllowed({policy:enabledPolicy,kind:'short_term',key:'goal',content:'متابعة أداء المبيعات',sensitivity:'internal'});assert.throws(()=>engine.assertAllowed({policy:enabledPolicy,kind:'long_term',key:'password',content:'secret token',sensitivity:'restricted'}));return{longTermDefault:false,blockedSecrets:true};});
 await check('citations-guard',()=>{const context:OrbyRagContext={query:'المبيعات',text:'انخفضت المبيعات [S1]',characterCount:24,truncated:false,citations:[{id:'c1',sourceId:'s1',documentId:'d1',chunkId:'k1',label:'S1',title:'تقرير المبيعات',excerpt:'انخفضت المبيعات 20%',score:.9,metadata:{}}]};const citations=new OrbyCitationEngine();assert.equal(citations.validate('انخفضت المبيعات [S1]',context.citations).valid,true);assert.throws(()=>new OrbyHallucinationGuard().verify('انخفضت المبيعات',context));return{citationRequired:true};});
 await check('sales-drop-detector',async()=>{const snapshot:OrbyMetricSnapshot={current:{sales:60,revenue:60,orders:6,customers:8,traffic:70,supportOpen:0,paymentOverdue:2,lowInventory:0,systemErrors:0},previous:{sales:100,revenue:100,orders:10,customers:10,traffic:100,supportOpen:0,paymentOverdue:0,lowInventory:0,systemErrors:0},sampleSize:100,freshnessSeconds:60,qualityScore:.95,dimensions:{},evidence:[]};const detector=new SalesDropDetector({read:async()=>snapshot}),input:OrbyDetectorInput={identity:{organizationId:'org-1',userId:'user-1',workspaceId:'workspace-1'},windowStart:new Date(Date.now()-86400000).toISOString(),windowEnd:new Date().toISOString(),now:new Date().toISOString(),configuration:{}};const signals=await detector.detect(input);assert.equal(signals.length,1);assert.ok(signals[0].confidence>.8);assert.ok(signals[0].suggestedActions.every(action=>action.requiresApproval&&action.toolName==='madar.business.action.draft'));return{detector:signals[0].detector,severity:signals[0].severity,actions:signals[0].suggestedActions.length};});

 const report={suite:'ORBY-STAGE-3-MEMORY-KNOWLEDGE-PROACTIVE-1.0.0',status:'passed',total:checks.length,passed:checks.length,failed:0,checks};console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});
