import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ORBY_CHARACTER_CONSTITUTION,ORBY_CHARACTER_CONSTITUTION_VERSION,OrbyDialogueManager,OrbyPersonalityEngine} from '../src/lib/orby/personality';
import {ORBY_CONVERSATION_PROTOCOL_VERSION} from '../src/lib/orby/conversation';
import {createOrbyFoundation,MockOrbyProvider} from '../src/lib/orby';
import type {OrbyJsonObject,OrbyModelDescriptor} from '../src/lib/orby/core/contracts';

async function main(){
 type Check={key:string;status:'passed';details:OrbyJsonObject};const checks:Check[]=[];
 async function check(key:string,operation:()=>Promise<OrbyJsonObject>|OrbyJsonObject){checks.push({key,status:'passed',details:await operation()});}
 const dialogue=new OrbyDialogueManager(),personality=new OrbyPersonalityEngine();

 await check('constitution-owned-by-madar',()=>{assert.equal(ORBY_CHARACTER_CONSTITUTION_VERSION,'2.0.0');assert.match(ORBY_CHARACTER_CONSTITUTION.productIdentity,/مَدار \| ORBIT/);assert.match(ORBY_CHARACTER_CONSTITUTION.founder,/إدريس بن عارف/);assert.ok(ORBY_CHARACTER_CONSTITUTION.principles.some(item=>item.includes('الصدق قبل الإبهار')));return{version:ORBY_CHARACTER_CONSTITUTION_VERSION,founderOwned:true};});
 await check('intent-information-vs-execution',()=>{const information=dialogue.decide({message:'كم بلغت المبيعات هذا الشهر؟',sector:'commerce',hasWorkspaceContext:true}),execution=dialogue.decide({message:'احذف المنتج "العطر التجريبي" الآن',sector:'commerce',hasWorkspaceContext:true});assert.equal(information.classification.intent,'information');assert.equal(information.classification.operation,'read');assert.equal(execution.classification.intent,'execution');assert.equal(execution.classification.operation,'write');assert.equal(execution.strategy,'approval_preview');assert.equal(execution.classification.sensitivity,'sensitive');return{information:information.classification.intent,execution:execution.classification.intent,strategy:execution.strategy};});
 await check('personality-provider-independence',()=>{const first=dialogue.decide({message:'حلل انخفاض المبيعات',sector:'commerce',hasWorkspaceContext:true,metadata:{model:'provider-a'}}),second=dialogue.decide({message:'حلل انخفاض المبيعات',sector:'commerce',hasWorkspaceContext:true,metadata:{model:'provider-b'}});assert.deepEqual(first.systemPolicies,second.systemPolicies);assert.equal(first.promptVersion,second.promptVersion);assert.equal(first.classification.intent,second.classification.intent);return{stableAcrossModels:true,promptVersion:first.promptVersion};});
 await check('sector-terminology-isolation',()=>{const commerce=personality.terminology('commerce'),food=personality.terminology('food_service'),hotel=personality.terminology('hospitality');assert.equal(commerce.item,'منتج');assert.equal(food.item,'وصفة');assert.equal(hotel.item,'غرفة');assert.notEqual(hotel.transaction,commerce.transaction);assert.match(personality.policies({sector:'hospitality'}).join('\n'),/Folio/);assert.doesNotMatch(personality.policies({sector:'hospitality'}).join('\n'),/استخدم مصطلحات التجارة/);return{commerce:commerce.item,food:food.item,hospitality:hotel.item};});
 await check('core-capabilities-and-provider-contract',()=>{const provider=new MockOrbyProvider({id:'model-provider',responseText:'رد أوربي'}),models:OrbyModelDescriptor[]=[{id:'model-a',providerId:'model-provider',providerModel:'model-a',displayName:'A',enabled:true,priority:1,capabilities:{text:true,streaming:true}}],foundation=createOrbyFoundation({providers:[provider],models,configuration:{enabled:true,defaultModelId:'model-a'}});for(const key of ['chat','streaming','conversation-v2','personality-engine','intent-dialogue'])assert.equal(foundation.capabilities.require(key).enabled,true);assert.equal(foundation.providers.list()[0].id,'model-provider');return{capabilities:foundation.capabilities.list().length,providerInterface:true};});
 await check('conversation-protocol',()=>{assert.equal(ORBY_CONVERSATION_PROTOCOL_VERSION,'2.0.0');return{protocol:ORBY_CONVERSATION_PROTOCOL_VERSION};});
 await check('all-orby-chat-paths-use-core',async()=>{const [route,stream]=await Promise.all([readFile('app/api/orby/route.ts','utf8'),readFile('app/api/orby/stream/route.ts','utf8')]);assert.match(route,/createServerOrbyFoundation/);assert.match(route,/foundation\.kernel\.execute/);assert.match(stream,/createServerOrbyFoundation/);assert.match(stream,/foundation\.kernel\.stream/);for(const source of [route,stream]){assert.doesNotMatch(source,/openrouter\.ai|api\.openai\.com|generativelanguage\.googleapis\.com|api\.anthropic\.com/i);assert.doesNotMatch(source,/new OpenRouterProvider|new OpenAICompatibleProvider|new GeminiProvider|new AnthropicProvider/);}return{executeThroughCore:true,streamThroughCore:true,directProviderCalls:false};});
 await check('modern-conversation-cycle',async()=>{const chat=await readFile('components/orby/OrbyChat.tsx','utf8');for(const pattern of [/\/api\/orby\/stream/,/AbortController/,/function stop/,/function retry/,/navigator\.clipboard/,/onKeyDown/,/citations/,/status:'stopped'/])assert.match(chat,pattern);return{streaming:true,stop:true,retry:true,copy:true,edit:true,citations:true};});
 await check('prompt-built-outside-ui',async()=>{const [chat,constitution,engine]=await Promise.all([readFile('components/orby/OrbyChat.tsx','utf8'),readFile('src/lib/orby/personality/constitution.ts','utf8'),readFile('src/lib/orby/personality/engine.ts','utf8')]);assert.doesNotMatch(chat,/ORBY_CHARACTER_CONSTITUTION|systemPolicies|أنت أوربي، المساعد الذكي الرسمي/);assert.match(constitution,/orbyCharacterSystemPolicies/);assert.match(engine,/OrbyDialogueManager/);return{uiPromptConstruction:false,versionedCompilerLayer:true};});

 const report={suite:'ORBY-V2-O1-O3-ACCEPTANCE-2.0.0',status:'passed',total:checks.length,passed:checks.length,failed:0,checks};console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});
