import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {
 OrbyPolicyEngine,OrbyToolRegistry,defaultExecutionConfiguration,type OrbyTool,type OrbyToolContext,type OrbyToolManifest,
} from '../src/lib/orby/execution';
import {
 OrbyMemoryIsolationGuard,OrbyProactiveInsightLifecycle,OrbyVerticalAnalysisEngine,
} from '../src/lib/orby/intelligence';
import {
 BUILTIN_ORBY_VERTICALS,ORBY_SHARED_API_CONTRACT,ORBY_V2_REQUIRED_GATES,OrbyAdminControlCenter,OrbyBackupRecoveryEngine,
 OrbyChannelRegistry,OrbyCrossDeviceContinuity,OrbyDataGovernanceEngine,OrbySourceOfTruthEngine,OrbyV2ReleaseGate,OrbyVerticalRegistry,
 type OrbyReleaseGateEvidence,type OrbyVerticalContext,
} from '../src/lib/orby/os';
import type {OrbyJsonObject} from '../src/lib/orby/core/contracts';

const schema={type:'object' as const,additionalProperties:true};
const manifest:OrbyToolManifest={name:'test.safe-read',description:'Safe registered read',version:'1.0.0',category:'data',requiredPermissions:['data.read'],executionType:'read',inputSchema:schema,outputSchema:schema,riskLevel:'low',status:'active',support:'stable',requirements:[],maxTimeoutMs:1000,supportsSandbox:true,operation:'test.safe-read'};
const tool:OrbyTool={metadata:()=>manifest,validate:input=>input&&typeof input==='object'&&!Array.isArray(input)?{valid:true,normalizedInput:input as OrbyJsonObject}:{valid:false,issues:[{path:'$',message:'object required'}]},authorize:()=>({allowed:true}),execute:async(_context:OrbyToolContext,input)=>({ok:true,data:input}),cancel:async()=>{},health:async()=>({ok:true,checkedAt:new Date().toISOString(),latencyMs:0})};

async function main(){
 type Check={key:string;status:'passed';details:OrbyJsonObject};const checks:Check[]=[];
 const check=async(key:string,operation:()=>Promise<OrbyJsonObject>|OrbyJsonObject)=>checks.push({key,status:'passed',details:await operation()});

 await check('o4-closed-tool-registry',()=>{const registry=new OrbyToolRegistry().register(tool);assert.equal(registry.get('test.safe-read').metadata().name,'test.safe-read');assert.throws(()=>registry.get('test.unregistered'));return{registered:registry.list().length,unregisteredDenied:true};});
 await check('o4-sensitive-write-approval',()=>{const configuration={...defaultExecutionConfiguration(),enabled:true,planningEnabled:true},decision=new OrbyPolicyEngine().evaluate({manifest:{...manifest,name:'test.write',executionType:'write',riskLevel:'medium'},configuration,mode:'production',membership:{organizationId:'org-1',userId:'owner-1',role:'OWNER',organizationStatus:'active',workspaceAuthorized:true,permissions:['data.read','business.action.draft','orby.execute']}});assert.equal(decision.effect,'require_approval');assert.equal(configuration.allowExternalWrites,false);assert.equal(configuration.allowDeletes,false);return{approval:decision.approvalScope||'',externalWrites:false,deletes:false};});

 await check('o5-memory-isolation-and-secret-block',()=>{const guard=new OrbyMemoryIsolationGuard(),identity={organizationId:'org-1',workspaceId:'workspace-1',userId:'user-1'};assert.equal(guard.assertRecord(identity,{organizationId:'org-1',workspaceId:'workspace-1',userId:'user-1'}),true);assert.throws(()=>guard.assertRecord(identity,{organizationId:'org-2',workspaceId:'workspace-1',userId:'user-1'}));assert.throws(()=>guard.assertBoundary('BUSINESS','PERSONAL'));assert.throws(()=>guard.assertSafeContent('api_key=sk-abcdefghijklmnop'));return{crossTenantDenied:true,crossAccountDenied:true,secretsBlocked:true};});
 await check('o5-sector-analysis-evidence-confidence-actions',()=>{const engine=new OrbyVerticalAnalysisEngine(),observedAt=new Date().toISOString(),commerce=engine.analyzeCommerce({sales:60,previousSales:100,grossProfit:20,revenue:60,lowStockItems:4,stagnantProducts:2,expenses:35,previousExpenses:20,sourceRef:'commerce-period-1',observedAt}),food=engine.analyzeFoodService({revenue:1000,foodCost:480,wasteCost:120,previousWasteCost:60,lowMarginRecipes:3,delayedOrders:5,sourceRef:'food-period-1',observedAt}),hotel=engine.analyzeHospitality({availableRooms:30,occupiedRooms:10,previousOccupancyRate:.65,roomRevenue:900,outOfServiceRooms:3,housekeepingBacklog:4,cancellations:5,reservations:20,sourceRef:'hotel-period-1',observedAt});const all=[...commerce,...food,...hotel];assert.ok(all.length>=6);assert.ok(all.every(item=>item.reason&&item.evidence.length&&item.confidence>0&&item.suggestedActions.every(action=>action.requiresApproval)));const lifecycle=new OrbyProactiveInsightLifecycle(),first=lifecycle.upsert(all[0],60),duplicate=lifecycle.upsert(all[0],60);assert.equal(first.created,true);assert.equal(duplicate.suppressed,true);assert.equal(lifecycle.decide(all[0].fingerprint,'dismissed').status,'dismissed');return{commerce:commerce.length,food:food.length,hospitality:hotel.length,deduplicated:true};});

 const fullContext:OrbyVerticalContext={identity:{organizationId:'org-1',workspaceId:'workspace-1',userId:'owner-1'},vertical:'food_service',plan:'FULL',operatingMode:'CONNECTED_EXTERNAL',sourceOfTruth:'EXTERNAL',connectorAuthorized:true,lastSyncedAt:new Date().toISOString(),allowedWriteOperations:['RESTAURANT_ORDER_STATUS'],permissions:['data.read','intelligence.analyze','orby.execute']};
 await check('o6-domain-plugins-and-entitlements',()=>{const registry=new OrbyVerticalRegistry();assert.equal(registry.list().length,5);assert.deepEqual(registry.list().map(item=>item.key).sort(),['commerce','food_service','hospitality','personal','student']);const food=registry.resolve('food_service'),hotel=registry.resolve('hospitality');assert.equal(food.terminology.recipe,'وصفة');assert.equal(hotel.terminology.occupancy,'إشغال');assert.ok(registry.tools(fullContext).some(item=>item.name==='food.execute'));const basic={...fullContext,plan:'BASIC' as const,permissions:['data.read']};assert.deepEqual(registry.tools(basic).map(item=>item.name),['food.read']);return{verticals:BUILTIN_ORBY_VERTICALS.length,fullTools:registry.tools(fullContext).length,basicTools:registry.tools(basic).length};});
 await check('o6-source-of-truth-server-guard',()=>{const registry=new OrbyVerticalRegistry(),toolDefinition=registry.assertTool(fullContext,'food.execute'),engine=new OrbySourceOfTruthEngine(),allowed=engine.decideWrite({context:fullContext,tool:toolDefinition,operation:'RESTAURANT_ORDER_STATUS',target:'EXTERNAL'}),wrongTarget=engine.decideWrite({context:fullContext,tool:toolDefinition,operation:'RESTAURANT_ORDER_STATUS',target:'MADAR'});assert.equal(allowed.allowed,true);assert.equal(allowed.requiresApproval,true);assert.equal(wrongTarget.allowed,false);assert.throws(()=>engine.assertWrite({context:fullContext,tool:toolDefinition,operation:'PRICE_UPDATE',target:'EXTERNAL'}));return{correctSourceAllowed:true,wrongSourceDenied:true,allowlistEnforced:true};});
 await check('o6-cross-device-continuity',()=>{const continuity=new OrbyCrossDeviceContinuity(),identity=fullContext.identity,saved=continuity.save(identity,{conversationId:'conversation-1',channel:'web',version:1,lastMessageId:'message-1',activeRunId:'run-1',metadata:{}}),mobile=continuity.resume(identity,'conversation-1','mobile');assert.equal(saved.version,1);assert.equal(mobile.channel,'mobile');assert.equal(mobile.activeRunId,'run-1');assert.throws(()=>continuity.resume({...identity,userId:'other'},'conversation-1','mobile'));assert.ok(ORBY_SHARED_API_CONTRACT.sharedResources.includes('approvals'));return{webToMobile:true,runContinued:true,scopeProtected:true};});

 await check('o7-admin-control-center',()=>{const center=new OrbyAdminControlCenter(),superAdmin={userId:'founder-1',role:'SUPER_ADMIN' as const},auditor={userId:'auditor-1',role:'AUDITOR' as const};center.upsert(superAdmin,{kind:'model',key:'analysis-primary',version:'1.0.0',enabled:true,configuration:{provider:'openrouter'}},'اعتماد نموذج التحليل');center.disable(superAdmin,'model','analysis-primary','إيقاف طارئ');assert.equal(center.get(auditor,'model','analysis-primary')?.enabled,false);assert.throws(()=>center.upsert(auditor,{kind:'tool',key:'unsafe',version:'1.0.0',enabled:true,configuration:{}},'غير مسموح'));return{resources:center.snapshot(auditor).resources.length,audit:center.snapshot(auditor).audit.length,emergencyDisable:true};});
 await check('o7-release-gate-and-rollback-requirement',()=>{const evidence:OrbyReleaseGateEvidence[]=ORBY_V2_REQUIRED_GATES.map(key=>({key,passed:true,score:1,artifact:`artifact:${key}`})),result=new OrbyV2ReleaseGate().assertReady(evidence);assert.equal(result.passed,true);assert.equal(result.missing.length,0);assert.equal(ORBY_V2_REQUIRED_GATES.includes('rollback'),true);assert.throws(()=>new OrbyV2ReleaseGate().assertReady(evidence.filter(item=>item.key!=='security')));return{gates:ORBY_V2_REQUIRED_GATES.length,score:result.score,rollbackRequired:true};});
 await check('o7-data-governance-backup-channels',()=>{const governance=new OrbyDataGovernanceEngine();assert.equal(governance.classify('access_token'),'restricted');assert.equal(governance.canAccess({role:'ADMIN',classification:'restricted',reason:'support'}),false);assert.equal(governance.canAccess({role:'SUPER_ADMIN',classification:'restricted',reason:'incident',breakGlass:true}),true);const backup=new OrbyBackupRecoveryEngine().create({version:'2.0.0',components:['configuration','prompts','tools','memory','knowledge','conversations','approvals','workflows','insights'],encrypted:true,checksum:'1234567890abcdef1234567890abcdef',storageRegion:'me-central',metadata:{}});assert.equal(new OrbyBackupRecoveryEngine().verify(backup).valid,true);const channels=new OrbyChannelRegistry();assert.equal(channels.assertUsable('mobile','inbound').status,'active');assert.throws(()=>channels.assertUsable('whatsapp','outbound'));return{classification:'restricted',backupEncrypted:backup.encrypted,activeChannels:channels.list().filter(item=>item.status==='active').length,futureWhatsAppGated:true};});
 await check('o4-o7-database-contract',async()=>{const migration=await readFile('supabase/migrations/20260804110000_orby_v2_o4_o7_completion.sql','utf8');for(const table of ['orby_vertical_installations','orby_source_of_truth_states','orby_cross_device_state','orby_admin_control_versions','orby_release_gate_runs','orby_data_governance_requests','orby_backup_manifests','orby_channel_registry'])assert.match(migration,new RegExp(`create table if not exists public\\.${table}`));assert.match(migration,/enable row level security/g);assert.match(migration,/to service_role/g);assert.doesNotMatch(migration,/grant all privileges/i);assert.match(migration,/whatsapp[^;]+paused/is);return{tables:8,rls:true,serviceBoundary:true,whatsappPaused:true};});

 const report={suite:'ORBY-V2-O4-O7-COMPLETION-2.0.0',status:'passed',total:checks.length,passed:checks.length,failed:0,checks};console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});
