import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {
 CompositeTaskPlanner,InMemoryExecutionEventBus,InMemoryExecutionQueue,InMemoryExecutionRepository,InMemoryMembershipResolver,
 MADAR_EXECUTION_TOOL_MANIFESTS,ManifestTaskPlanner,OrbyExecutionError,OrbyPermissionEngine,OrbyToolLoader,OrbyToolRegistry,createOrbyAgentRuntime,
 type OrbyTaskPlan,type OrbyTool,type OrbyToolContext,type OrbyToolManifest,type OrbyToolResult,
} from '../src/lib/orby/execution/index';
import type {OrbyJsonObject} from '../src/lib/orby/core/contracts';

class TestTool implements OrbyTool {
 calls:{mode:string;input:OrbyJsonObject}[]=[];
 constructor(private readonly manifest:OrbyToolManifest,private readonly handler:(context:OrbyToolContext,input:OrbyJsonObject,calls:number)=>Promise<OrbyToolResult>|OrbyToolResult){}
 metadata(){return this.manifest;}
 validate(input:unknown){return input&&typeof input==='object'&&!Array.isArray(input)?{valid:true as const,normalizedInput:input as OrbyJsonObject}:{valid:false as const,issues:[{path:'$',message:'object required'}]};}
 authorize(){return{allowed:true as const};}
 async execute(context:OrbyToolContext,input:OrbyJsonObject){this.calls.push({mode:context.mode,input});return this.handler(context,input,this.calls.length);}
 async cancel(){}
 async health(){return{ok:true,checkedAt:new Date().toISOString(),latencyMs:0};}
}

const schema={type:'object' as const,additionalProperties:true};
function manifest(name:string,options:Partial<OrbyToolManifest>={}):OrbyToolManifest{return{name,description:`Synthetic ${name}`,version:'1.0.0',category:'data',requiredPermissions:['data.read'],executionType:'read',inputSchema:schema,outputSchema:schema,riskLevel:'low',status:'active',support:'stable',requirements:[],maxTimeoutMs:5000,supportsSandbox:true,operation:name,...options};}
function plan(goal:string,root:OrbyTaskPlan['root'],toolNames:string[],riskLevel:OrbyTaskPlan['riskLevel']='low'):OrbyTaskPlan{return{id:crypto.randomUUID(),goal,summary:goal,root,toolNames,dependencies:[],riskLevel,terminalCondition:'all required nodes completed',createdAt:new Date().toISOString(),planner:'test'};}

async function main(){
 type Check={key:string;status:'passed';details:OrbyJsonObject};const checks:Check[]=[];async function check(key:string,operation:()=>Promise<OrbyJsonObject>|OrbyJsonObject){checks.push({key,status:'passed',details:await operation()});}
 const registry=new OrbyToolRegistry();
 const read=new TestTool(manifest('test.read'),(_context,input)=>({ok:true,data:{ok:true,value:input.value??1}}));
 const list=new TestTool(manifest('test.list',{outputSchema:{type:'array',items:{type:'object',additionalProperties:true}}}),()=>({ok:true,data:[{id:1},{id:2},{id:3}]}));
 const retry=new TestTool(manifest('test.retry'),(_context,_input,calls)=>calls===1?{ok:false,data:null,error:{code:'TEMPORARY',message:'retry',retryable:true}}:{ok:true,data:{ok:true,attempts:calls}});
 const write=new TestTool(manifest('test.write',{category:'business',requiredPermissions:['business.action.draft'],executionType:'write',riskLevel:'medium'}),(context,input)=>({ok:true,data:{status:context.mode==='sandbox'?'preview':'written',value:input.value},metrics:context.mode==='sandbox'?{preview:true}:undefined}));
 const writeLow=new TestTool(manifest('test.write-low',{category:'business',requiredPermissions:['business.action.draft'],executionType:'write',riskLevel:'low'}),()=>({ok:true,data:{status:'written'}}));
 const compensate=new TestTool(manifest('test.compensate',{category:'business',requiredPermissions:['business.action.draft'],executionType:'write',riskLevel:'low'}),()=>({ok:true,data:{status:'undone'}}));
 const high=new TestTool(manifest('test.high',{category:'business',requiredPermissions:['business.action.draft'],executionType:'write',riskLevel:'high'}),(context)=>({ok:true,data:{status:context.mode==='sandbox'?'preview':'executed'},metrics:context.mode==='sandbox'?{sandbox:true}:undefined}));
 const adminOnly=new TestTool(manifest('test.admin',{category:'integration',requiredPermissions:['integration.sync'],executionType:'write',riskLevel:'low'}),()=>({ok:true,data:{status:'executed'}}));
 const fail=new TestTool(manifest('test.fail'),()=>({ok:false,data:null,error:{code:'PERMANENT',message:'failed',retryable:false}}));
 await new OrbyToolLoader(registry).load([read,list,retry,write,writeLow,compensate,high,adminOnly,fail].map(tool=>()=>tool));
 const repository=new InMemoryExecutionRepository({enabled:true,planningEnabled:true,maxWorkflowSteps:30,maxParallelActions:3,maxLoopIterations:5,dailyActionLimit:100,perMinuteActionLimit:100,allowExternalWrites:false,allowDeletes:false,sandboxRequiredForHighRisk:true});await repository.syncToolCatalog(registry.manifests());
 const queue=new InMemoryExecutionQueue(),memberships=new InMemoryMembershipResolver().register({organizationId:'org-1',userId:'owner-1',role:'OWNER',organizationStatus:'active',workspaceAuthorized:true,permissions:[]}).register({organizationId:'org-1',userId:'member-1',role:'MEMBER',organizationStatus:'active',workspaceAuthorized:true,permissions:[]}),permissions=new OrbyPermissionEngine(memberships),events=new InMemoryExecutionEventBus(),eventNames:string[]=[];
 for(const name of ['workflow.queued','workflow.started','workflow.waiting','workflow.completed','workflow.failed','tool.started','tool.finished','tool.failed','approval.requested','approval.granted','rollback.started','rollback.completed','sandbox.completed'] as const)events.on(name,()=>{eventNames.push(name);});
 const planner=new CompositeTaskPlanner([new ManifestTaskPlanner(registry)]),runtime=createOrbyAgentRuntime({planner,registry,repository,queue,permissions,events});const owner={organizationId:'org-1',userId:'owner-1',workspaceId:'org-1'},member={organizationId:'org-1',userId:'member-1',workspaceId:'org-1'};

 await check('tool-system-contract',()=>{assert.equal(registry.list().length,9);for(const tool of registry.list())for(const method of ['execute','validate','authorize','cancel','health','metadata'])assert.equal(typeof (tool as unknown as Record<string,unknown>)[method],'function');const categories=[...new Set(MADAR_EXECUTION_TOOL_MANIFESTS.map(item=>item.category))];assert.deepEqual(categories.sort(),['business','data','files','integration','intelligence','platform']);return{tools:registry.list().length,categories};});
 await check('planner-before-execution',async()=>{const result=await runtime.plan({goal:'use test.read to inspect data',identity:owner,metadata:{toolName:'test.read',toolInput:{value:7}}});assert.equal(result.root.type,'action');assert.equal(read.calls.length,0);return{planner:result.planner,executed:false};});
 let approvalRun='',approvalId='';
 await check('queue-only-submission',async()=>{const submitted=await runtime.submit({goal:'read then write',identity:owner,plan:plan('read then write',{id:'sequence',type:'sequence',children:[{id:'read',type:'action',toolName:'test.read',input:{value:4}},{id:'write',type:'action',toolName:'test.write',input:{value:{$ref:'results.root/sequence/read.value'}}}]},['test.read','test.write'],'medium')});approvalRun=submitted.run.id;assert.equal(read.calls.length,0);assert.equal(write.calls.length,0);assert.equal(queue.list().filter(item=>item.runId===approvalRun).length,1);return{runId:approvalRun,status:submitted.run.status};});
 await check('approval-gated-action',async()=>{const processed=await runtime.processNext('worker-1');assert.equal(processed[0].status,'waiting');assert.equal(read.calls.length,1);assert.equal(write.calls.length,0);const actions=await repository.actions(approvalRun),writeAction=actions.find(item=>item.toolName==='test.write')!;const approval=await repository.approvalForAction(writeAction.id);assert.equal(approval?.status,'pending');approvalId=approval!.id;return{approvalId,status:approval?.status||''};});
 await check('approval-resume-completion',async()=>{await runtime.decideApproval({approvalId,identity:owner,decision:'approved',reason:'approved in smoke'});await runtime.processNext('worker-2');const status=await runtime.status(approvalRun,owner);assert.equal(status.run.status,'completed');assert.equal(write.calls.length,1);return{status:status.run.status,writeCalls:write.calls.length};});
 await check('system-approval-internal-only',async()=>{const submitted=await runtime.submit({goal:'system approval',identity:owner,plan:plan('system approval',{id:'system-seq',type:'sequence',children:[{id:'system-gate',type:'approval',scope:'system',reason:'automated policy review'},{id:'system-read',type:'action',toolName:'test.read',input:{}}]},['test.read'])});await runtime.processNext('worker-system-1');const waiting=await runtime.status(submitted.run.id,owner);assert.equal(waiting.run.status,'waiting');const approval=(await repository.actions(submitted.run.id).then(actions=>repository.approvalForAction(actions.find(item=>item.toolName==='orby.approval')!.id)))!;let userDenied=false;try{await runtime.decideApproval({approvalId:approval.id,identity:owner,decision:'approved'});}catch(error){userDenied=error instanceof OrbyExecutionError&&error.code==='PERMISSION_DENIED';}assert.equal(userDenied,true);await runtime.decideSystemApproval({approvalId:approval.id,reason:'system checks passed'});await runtime.processNext('worker-system-2');assert.equal((await runtime.status(submitted.run.id,owner)).run.status,'completed');return{userDenied,systemApproved:true};});
 await check('retry-engine',async()=>{const submitted=await runtime.submit({goal:'retry',identity:owner,plan:plan('retry',{id:'retry',type:'action',toolName:'test.retry',input:{},retry:{maxAttempts:2,baseDelayMs:1,maxDelayMs:2}},['test.retry'])});await runtime.processNext('worker-3');assert.equal((await runtime.status(submitted.run.id,owner)).run.status,'completed');assert.equal(retry.calls.length,2);return{attempts:retry.calls.length};});
 await check('parallel-conditional-loop-event',async()=>{const complex=plan('complex',{id:'root-seq',type:'sequence',children:[{id:'parallel',type:'parallel',maxParallel:2,children:[{id:'a',type:'action',toolName:'test.read',input:{value:1}},{id:'b',type:'action',toolName:'test.read',input:{value:2}}]},{id:'list',type:'action',toolName:'test.list',input:{}},{id:'loop',type:'loop',itemsPath:'results.root/root-seq/list',itemVariable:'item',maxIterations:3,body:{id:'loop-read',type:'action',toolName:'test.read',input:{value:{$ref:'variables.item.id'}}}},{id:'condition',type:'condition',condition:{operator:'exists',path:'results.root/root-seq/parallel'},then:{id:'event',type:'event',name:'custom.test',payload:{ok:true}}}]},['test.read','test.list']);const submitted=await runtime.submit({goal:'complex',identity:owner,plan:complex});await runtime.processNext('worker-4');const complexStatus=await runtime.status(submitted.run.id,owner);assert.equal(complexStatus.run.status,'completed');assert.ok(repository.events.some(item=>item.eventType==='custom.test'));return{readCalls:read.calls.length,customEvent:true};});
 await check('delay-node-resume',async()=>{const submitted=await runtime.submit({goal:'delay',identity:owner,plan:plan('delay',{id:'seq',type:'sequence',children:[{id:'wait',type:'delay',durationMs:0},{id:'read',type:'action',toolName:'test.read',input:{}}]},['test.read'])});await runtime.processNext('worker-5');assert.equal((await runtime.status(submitted.run.id,owner)).run.status,'waiting');await runtime.processNext('worker-6');assert.equal((await runtime.status(submitted.run.id,owner)).run.status,'completed');return{resumed:true};});
 await check('sandbox-high-risk',async()=>{const submitted=await runtime.submit({goal:'high risk',identity:owner,plan:plan('high risk',{id:'high',type:'action',toolName:'test.high',input:{}},['test.high'],'high')});await runtime.processNext('worker-7');assert.equal(high.calls[0].mode,'sandbox');const action=(await repository.actions(submitted.run.id))[0],approval=await repository.approvalForAction(action.id);await runtime.decideApproval({approvalId:approval!.id,identity:owner,decision:'approved'});await runtime.processNext('worker-8');assert.equal(high.calls.at(-1)?.mode,'production');assert.equal((await runtime.status(submitted.run.id,owner)).run.status,'completed');return{modes:high.calls.map(item=>item.mode)};});
 await check('rollback-compensation',async()=>{const submitted=await runtime.submit({goal:'rollback',identity:owner,plan:plan('rollback',{id:'rollback-seq',type:'sequence',children:[{id:'write-low',type:'action',toolName:'test.write-low',input:{},compensation:{toolName:'test.compensate',input:{},reason:'undo'}},{id:'fail',type:'action',toolName:'test.fail',input:{}}]},['test.write-low','test.compensate','test.fail'],'medium')});await runtime.processNext('worker-9');const status=await runtime.status(submitted.run.id,owner);assert.equal(status.run.status,'failed');assert.equal(compensate.calls.length,1);assert.equal(status.actions.find(item=>item.toolName==='test.write-low')?.status,'compensated');return{runStatus:status.run.status,compensated:compensate.calls.length};});
 await check('permission-engine-deny',async()=>{const submitted=await runtime.submit({goal:'member integration',identity:member,plan:plan('member integration',{id:'admin',type:'action',toolName:'test.admin',input:{}},['test.admin'],'low')});await runtime.processNext('worker-10');const status=await runtime.status(submitted.run.id,member);assert.equal(status.run.status,'failed');assert.equal(status.run.errorCode,'PERMISSION_DENIED');assert.equal(adminOnly.calls.length,0);return{denied:true,executed:false};});
 await check('audit-events-notifications',()=>{assert.ok(repository.audit.length>=8);assert.ok(repository.events.length>=8);assert.ok(repository.notifications.length>=3);assert.ok(eventNames.includes('approval.requested'));assert.ok(eventNames.includes('rollback.completed'));return{audit:repository.audit.length,events:repository.events.length,notifications:repository.notifications.length};});
 await check('execution-limits',async()=>{const previous=await repository.configuration('org-1');repository.setConfiguration('org-1',{maxWorkflowSteps:2});let limited=false;try{await runtime.submit({goal:'too many',identity:owner,plan:plan('too many',{id:'seq-limit',type:'sequence',children:[{id:'1',type:'event',name:'a',payload:{}},{id:'2',type:'event',name:'b',payload:{}}]},[])});}catch(error){limited=error instanceof OrbyExecutionError&&error.code==='LIMIT_EXCEEDED';}repository.setConfiguration('org-1',previous);assert.equal(limited,true);return{limited};});
 await check('database-and-security-contract',async()=>{const migration=(await Promise.all(['20260728004000_orby_agent_execution_schema.sql','20260728004100_orby_agent_execution_security.sql','20260728004200_orby_agent_execution_queue.sql'].map(name=>readFile(`supabase/migrations/${name}`,'utf8')))).join('\n');for(const table of ['orby_tool_catalog','orby_workflows','orby_workflow_runs','orby_actions','orby_approvals','orby_execution_queue','orby_execution_events','orby_execution_audit','orby_sandbox_runs','orby_execution_usage'])assert.match(migration,new RegExp(`create table if not exists public\\.${table}`));assert.match(migration,/for update skip locked/i);assert.match(migration,/security definer set search_path=''/i);assert.match(migration,/revoke all on function public\.orby_claim_execution_jobs[\s\S]*authenticated/i);assert.match(migration,/create policy orby_execution_queue_service[\s\S]*to service_role/i);assert.match(migration,/grant select,insert,update,delete[\s\S]*to service_role/i);assert.doesNotMatch(migration,/grant all privileges[\s\S]*to service_role/i);assert.doesNotMatch(migration,/create policy orby_execution_config_manage|create policy orby_tool_catalog_manage/i);assert.doesNotMatch(migration,/api_key|access_token|provider_secret|dynamic_code/i);return{rls:(migration.match(/enable row level security/g)||[]).length,queueRpc:true,secretsStored:false};});
 await check('integration-boundary',async()=>{const source=await readFile('src/lib/orby/execution/adapters/gateway.ts','utf8');assert.match(source,/new IntegrationQueue\(database\)/);assert.match(source,/integration_udm_records/);assert.match(source,/orby_action_drafts/);assert.doesNotMatch(source,/integration_connection_secrets/);return{usesGateway:true,reusesQueue:true,reusesUdm:true};});

 const report={suite:'ORBY-STAGE-2-AGENT-EXECUTION-1.0.0',status:'passed',total:checks.length,passed:checks.length,failed:0,checks};console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});
