import {requireSuperAdmin} from '@/src/lib/auth';
import {supabaseFetch} from '@/src/lib/supabase/server';
import {backfillRawBatches,enqueueConnectionSync,resolveQualityIssue,setConnectionState,setIntegrationFlag} from './actions';

export const dynamic='force-dynamic';
export const metadata={title:'الاتصالات وجودة البيانات | مَدار'};

type Dashboard={connections:{total:number;active:number;error:number};pipeline:{runs_24h:number;failed_24h:number;records_24h:number;unified_24h:number};quality:{open:number;critical:number;duplicates:number;missing:number};udm:{records:number;entities:number};queue:{queued:number;dead:number};generated_at:string};
type Flag={key:string;enabled:boolean;organization_id:string|null;updated_at:string};
type Connection={id:string;organization_id:string;connector_key:string;name:string;status:string;connection_mode:string;last_tested_at:string|null;last_success_at:string|null;last_error_message:string|null;created_at:string};
type Run={id:string;connection_id:string;status:string;current_stage:string;total_records:number;valid_records:number;invalid_records:number;unified_records:number;duplicate_records:number;warning_count:number;error_count:number;started_at:string;finished_at:string|null};
type Issue={id:string;connection_id:string|null;severity:string;category:string;rule_key:string;field_path:string|null;message:string;created_at:string};
type Health={connection_id:string|null;status:string;success_rate:number;quality_score:number;invalid_ratio:number;open_issues:number;dead_jobs:number;captured_at:string};
type Mapping={id:string;stream_key:string;entity_type:string;connector_key:string|null;connection_id:string|null;version:number;is_active:boolean};

const scalar=<T,>(value:unknown)=>Array.isArray(value)?value[0] as T:value as T;
const number=(value:unknown)=>Number(value||0).toLocaleString('ar-EG');
const date=(value:string|null)=>value?new Date(value).toLocaleString('ar-EG'):'—';
const statusLabel:Record<string,string>={active:'نشط',paused:'متوقف مؤقتًا',error:'خطأ',verifying:'قيد التحقق',draft:'مسودة',disconnected:'مفصول',succeeded:'ناجح',partial:'جزئي',failed:'فشل',running:'يعمل',healthy:'سليم',degraded:'متراجع',unhealthy:'غير سليم',unknown:'غير معروف'};
const flagLabel:Record<string,string>={integration_engine_enabled:'محرك الربط',integration_worker_enabled:'عامل المهام',integration_scheduler_enabled:'الجدولة',integration_pipeline_enabled:'خط الجودة والـ UDM',integration_quality_center_enabled:'مركز الجودة',integration_write_enabled:'الكتابة للأنظمة الخارجية'};

export default async function IntegrationsAdminPage(){
 await requireSuperAdmin();
 const [overviewRaw,flags,connections,runs,issues,health,mappings]=await Promise.all([
  supabaseFetch('/rest/v1/rpc/integration_quality_dashboard',{method:'POST',body:'{}'}),
  supabaseFetch('/rest/v1/integration_feature_flags?organization_id=is.null&select=key,enabled,organization_id,updated_at&order=key.asc'),
  supabaseFetch('/rest/v1/integration_connections?deleted_at=is.null&select=id,organization_id,connector_key,name,status,connection_mode,last_tested_at,last_success_at,last_error_message,created_at&order=created_at.desc&limit=100'),
  supabaseFetch('/rest/v1/integration_pipeline_runs?select=id,connection_id,status,current_stage,total_records,valid_records,invalid_records,unified_records,duplicate_records,warning_count,error_count,started_at,finished_at&order=started_at.desc&limit=25'),
  supabaseFetch('/rest/v1/integration_quality_issues?status=eq.open&select=id,connection_id,severity,category,rule_key,field_path,message,created_at&order=created_at.desc&limit=40'),
  supabaseFetch('/rest/v1/integration_health_snapshots?select=connection_id,status,success_rate,quality_score,invalid_ratio,open_issues,dead_jobs,captured_at&order=captured_at.desc&limit=50'),
  supabaseFetch('/rest/v1/integration_mapping_rules?select=id,stream_key,entity_type,connector_key,connection_id,version,is_active&order=updated_at.desc&limit=50'),
 ]),overview=scalar<Dashboard>(overviewRaw),flagRows=(flags||[]) as Flag[],connectionRows=(connections||[]) as Connection[],runRows=(runs||[]) as Run[],issueRows=(issues||[]) as Issue[],healthRows=(health||[]) as Health[],mappingRows=(mappings||[]) as Mapping[],latestHealth=new Map<string,Health>();
 for(const item of healthRows)if(item.connection_id&&!latestHealth.has(item.connection_id))latestHealth.set(item.connection_id,item);
 return <main className="mx-auto max-w-[1500px] p-5 py-8 sm:p-8">
  <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-bold text-violet-200">Integration Control Plane</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">الاتصالات، نموذج البيانات وجودة المزامنة</h1><p className="mt-3 max-w-3xl leading-8 text-slate-400">مركز موحد لمراقبة Source → Raw → Validate → Transform → Map → Deduplicate → Unified. الحسابات والمؤشرات تنفذ داخل كود مَدار، ولا يعتمد المركز على تفسير أوربي.</p></div><form action={backfillRawBatches} className="flex items-center gap-2"><input type="hidden" name="limit" value="250"/><button className="md-button md-button-secondary" type="submit">إدخال الدفعات السابقة إلى الخط</button></form></div>

  <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Metric label="الاتصالات" value={overview.connections.total}/><Metric label="النشطة" value={overview.connections.active}/><Metric label="سجلات UDM" value={overview.udm.records}/><Metric label="سجلات موحدة 24س" value={overview.pipeline.unified_24h}/><Metric label="مشكلات مفتوحة" value={overview.quality.open} alert={overview.quality.critical>0}/><Metric label="مهام ميتة" value={overview.queue.dead} alert={overview.queue.dead>0}/></section>

  <section className="mt-8 rounded-3xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">بوابات التشغيل</h2><p className="mt-2 text-sm text-slate-400">تبقى الكتابة الخارجية مغلقة ما لم يتم تفعيلها صراحة.</p></div><span className="text-xs text-slate-500">آخر قراءة: {date(overview.generated_at)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{flagRows.map(flag=><form action={setIntegrationFlag} key={flag.key} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/10 p-4"><div><strong className="block text-sm">{flagLabel[flag.key]||flag.key}</strong><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${flag.enabled?'bg-emerald-300/10 text-emerald-200':'bg-slate-500/10 text-slate-400'}`}>{flag.enabled?'مفعّل':'متوقف'}</span></div><input type="hidden" name="flag_key" value={flag.key}/><input type="hidden" name="flag_enabled" value={String(!flag.enabled)}/><button type="submit" className="md-button md-button-secondary md-button-sm">{flag.enabled?'إيقاف':'تفعيل'}</button></form>)}</div></section>

  <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">إدارة الاتصالات</h2><p className="mt-2 text-sm text-slate-400">الحالة التشغيلية، الصحة، آخر مزامنة وتشغيل يدوي آمن.</p></div><span className="md-badge">{connectionRows.length} اتصال</span></div><div className="mt-5 grid gap-4 xl:grid-cols-2">{connectionRows.length?connectionRows.map(connection=>{const monitor=latestHealth.get(connection.id);return <article key={connection.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-black">{connection.name}</h3><Status value={connection.status}/><span className="md-badge">{connection.connection_mode}</span></div><p className="mt-2 text-sm text-slate-500">{connection.connector_key} · {connection.organization_id.slice(0,8)}</p></div>{monitor&&<div className="text-left"><Status value={monitor.status}/><p className="mt-2 text-xs text-slate-500">الجودة {Number(monitor.quality_score).toFixed(1)}٪</p></div>}</div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Small label="آخر نجاح" value={date(connection.last_success_at)}/><Small label="آخر اختبار" value={date(connection.last_tested_at)}/><Small label="معدل النجاح" value={monitor?`${Number(monitor.success_rate).toFixed(1)}٪`:'—'}/><Small label="مشكلات مفتوحة" value={monitor?number(monitor.open_issues):'—'}/></div>{connection.last_error_message&&<p className="mt-4 rounded-xl border border-rose-300/20 bg-rose-300/[.05] p-3 text-sm text-rose-100">{connection.last_error_message}</p>}<div className="mt-5 flex flex-wrap gap-2"><form action={setConnectionState}><input type="hidden" name="connection_id" value={connection.id}/><input type="hidden" name="status" value={connection.status==='paused'?'active':'paused'}/><button className="md-button md-button-secondary md-button-sm" type="submit">{connection.status==='paused'?'استئناف':'إيقاف مؤقت'}</button></form><form action={enqueueConnectionSync}><input type="hidden" name="connection_id" value={connection.id}/><input type="hidden" name="sync_mode" value="incremental"/><button className="md-button md-button-primary md-button-sm" type="submit" disabled={connection.status!=='active'}>مزامنة تزايدية</button></form><form action={enqueueConnectionSync}><input type="hidden" name="connection_id" value={connection.id}/><input type="hidden" name="sync_mode" value="initial"/><button className="md-button md-button-secondary md-button-sm" type="submit" disabled={connection.status!=='active'}>مزامنة أولية</button></form></div></article>}):<Empty text="لا توجد اتصالات خارجية مسجلة بعد."/>}</div></section>

  <section className="mt-10 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-3xl border border-white/10 p-5 sm:p-6"><h2 className="text-2xl font-black">سجل خط البيانات</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-right text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-3">الحالة</th><th className="p-3">المرحلة</th><th className="p-3">الإجمالي</th><th className="p-3">مقبول</th><th className="p-3">مرفوض</th><th className="p-3">موحد</th><th className="p-3">مكرر</th><th className="p-3">بدأ</th></tr></thead><tbody>{runRows.map(run=><tr key={run.id} className="border-t border-white/10"><td className="p-3"><Status value={run.status}/></td><td className="p-3 font-mono text-xs">{run.current_stage}</td><td className="p-3">{number(run.total_records)}</td><td className="p-3 text-emerald-200">{number(run.valid_records)}</td><td className="p-3 text-rose-200">{number(run.invalid_records)}</td><td className="p-3">{number(run.unified_records)}</td><td className="p-3">{number(run.duplicate_records)}</td><td className="p-3 text-xs text-slate-500">{date(run.started_at)}</td></tr>)}</tbody></table>{!runRows.length&&<Empty text="لم يعمل خط البيانات حتى الآن."/>}</div></div><div className="rounded-3xl border border-white/10 p-5 sm:p-6"><h2 className="text-2xl font-black">قواعد Mapping</h2><p className="mt-2 text-sm text-slate-400">كل Stream يتحول إلى كيان موحد بعقد صريح.</p><div className="mt-5 space-y-3">{mappingRows.slice(0,12).map(mapping=><div key={mapping.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3"><strong>{mapping.stream_key}</strong><span className="md-badge">v{mapping.version}</span></div><p className="mt-2 text-sm text-violet-200">→ {mapping.entity_type}</p><p className="mt-2 text-xs text-slate-500">{mapping.connection_id?'قاعدة اتصال مخصصة':mapping.connector_key||'قاعدة عامة'}</p></div>)}{!mappingRows.length&&<Empty text="لا توجد قواعد Mapping بعد؛ السجلات التي تحمل entity_type تستطيع المرور مؤقتًا."/>}</div></div></section>

  <section className="mt-10 rounded-3xl border border-white/10 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">مركز جودة البيانات</h2><p className="mt-2 text-sm text-slate-400">الأخطاء، الحقول المفقودة، المراجع غير المحلولة والسجلات المحتمل تكرارها.</p></div><div className="flex gap-2"><span className="md-badge">حرجة {overview.quality.critical}</span><span className="md-badge">مكررة {overview.quality.duplicates}</span><span className="md-badge">مفقودة {overview.quality.missing}</span></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{issueRows.map(issue=><article key={issue.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Status value={issue.severity}/><span className="md-badge">{issue.category}</span></div><span className="text-xs text-slate-500">{date(issue.created_at)}</span></div><h3 className="mt-3 font-black">{issue.rule_key}</h3><p className="mt-2 leading-7 text-slate-300">{issue.message}</p>{issue.field_path&&<code className="mt-3 inline-block rounded bg-black/20 px-2 py-1 text-xs text-violet-200">{issue.field_path}</code>}<div className="mt-4 flex gap-2"><form action={resolveQualityIssue}><input type="hidden" name="issue_id" value={issue.id}/><input type="hidden" name="status" value="resolved"/><input type="hidden" name="resolution" value="تمت المراجعة والمعالجة من مركز جودة البيانات."/><button className="md-button md-button-primary md-button-sm" type="submit">تمت المعالجة</button></form><form action={resolveQualityIssue}><input type="hidden" name="issue_id" value={issue.id}/><input type="hidden" name="status" value="ignored"/><input type="hidden" name="resolution" value="تم تجاهل المشكلة بقرار إداري موثق."/><button className="md-button md-button-secondary md-button-sm" type="submit">تجاهل موثق</button></form></div></article>)}{!issueRows.length&&<Empty text="لا توجد مشكلات جودة مفتوحة."/>}</div></section>
 </main>;
}

function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className={`rounded-2xl border p-4 ${alert?'border-rose-300/20 bg-rose-300/[.05]':'border-white/10 bg-white/[.025]'}`}><p className="text-xs text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{number(value)}</strong></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-black/10 p-3"><p className="text-[11px] text-slate-500">{label}</p><strong className="mt-2 block text-xs leading-5">{value}</strong></div>}
function Status({value}:{value:string}){const good=['active','succeeded','healthy','info'].includes(value),bad=['error','failed','unhealthy','critical'].includes(value),warning=['paused','partial','degraded','warning'].includes(value);return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${good?'bg-emerald-300/10 text-emerald-200':bad?'bg-rose-300/10 text-rose-200':warning?'bg-amber-300/10 text-amber-200':'bg-slate-500/10 text-slate-300'}`}>{statusLabel[value]||value}</span>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">{text}</div>}
