import type {OrbyEmbeddingResponse,OrbyModerationResult,OrbyProvider,OrbyProviderRequest,OrbyProviderStreamEvent} from '../core/contracts';
import {OrbyError,normalizeOrbyError} from '../core/errors';
import {providerCapabilities,providerHttpError,providerJsonRequest,providerNow,providerSseData,providerSseJson,timedProviderSignal,unsupportedProviderCapability} from './common';

export type AnthropicProviderOptions={apiKey:string;baseUrl?:string;id?:string;displayName?:string;version?:string};
export class AnthropicProvider implements OrbyProvider {
 readonly id:string;readonly displayName:string;readonly capabilities=providerCapabilities({text:true,streaming:true,vision:true,json:true});private readonly baseUrl:string;
 constructor(private readonly options:AnthropicProviderOptions){this.id=options.id||'anthropic';this.displayName=options.displayName||'Anthropic';this.baseUrl=(options.baseUrl||'https://api.anthropic.com/v1').replace(/\/$/,'');}
 private headers(){return {'Content-Type':'application/json','x-api-key':this.options.apiKey,'anthropic-version':this.options.version||'2023-06-01'};}
 private payload(request:OrbyProviderRequest,stream=false){const system=request.messages.filter(item=>item.role==='system').map(item=>item.content).join('\n\n'),messages=request.messages.filter(item=>item.role!=='system').map(item=>({role:item.role,content:item.content}));return {model:request.model,system,messages,max_tokens:request.options.maxOutputTokens||1024,temperature:request.options.temperature,top_p:request.options.topP,stop_sequences:request.options.stop,stream};}
 async generate(request:OrbyProviderRequest){const {body}=await providerJsonRequest(`${this.baseUrl}/messages`,{method:'POST',headers:this.headers(),body:JSON.stringify(this.payload(request))},request.options.timeoutMs,request.signal);const value=body as {id?:string;content?:Array<{type?:string;text?:string}>;stop_reason?:string;usage?:{input_tokens?:number;output_tokens?:number}};const text=(value.content||[]).filter(item=>item.type==='text').map(item=>item.text||'').join('');if(!text)throw new OrbyError('صيغة استجابة Anthropic غير متوقعة.','PROVIDER_BAD_RESPONSE',true);return {text,providerRequestId:value.id,finishReason:value.stop_reason,usage:{inputTokens:value.usage?.input_tokens,outputTokens:value.usage?.output_tokens,totalTokens:(value.usage?.input_tokens||0)+(value.usage?.output_tokens||0)}};}
 async *stream(request:OrbyProviderRequest):AsyncIterable<OrbyProviderStreamEvent>{const timed=timedProviderSignal(request.options.timeoutMs,request.signal);try{const response=await fetch(`${this.baseUrl}/messages`,{method:'POST',headers:this.headers(),body:JSON.stringify(this.payload(request,true)),signal:timed.signal,cache:'no-store'});if(!response.ok)throw providerHttpError(response.status,await response.json().catch(()=>null));yield {type:'start'};for await(const data of providerSseData(response)){const event=providerSseJson(data,this.id) as {type?:string;delta?:{text?:string;stop_reason?:string};usage?:{output_tokens?:number}};if(event.type==='content_block_delta'&&event.delta?.text)yield {type:'delta',text:event.delta.text};if(event.type==='message_delta'){if(event.usage)yield {type:'usage',usage:{outputTokens:event.usage.output_tokens}};yield {type:'end',finishReason:event.delta?.stop_reason};}}}finally{timed.dispose();}}
 async embeddings():Promise<OrbyEmbeddingResponse>{throw unsupportedProviderCapability(this.id,'embeddings');}
 async moderation():Promise<readonly OrbyModerationResult[]>{throw unsupportedProviderCapability(this.id,'moderation');}
 async models(signal?:AbortSignal){const {body}=await providerJsonRequest(`${this.baseUrl}/models`,{headers:this.headers()},15000,signal);const value=body as {data?:Array<{id?:string;display_name?:string}>};return (value.data||[]).flatMap(item=>item.id?[{id:item.id,displayName:item.display_name}]:[]);}
 async health(signal?:AbortSignal){const started=Date.now();try{await this.models(signal);return {providerId:this.id,ok:true,latencyMs:Date.now()-started,checkedAt:providerNow()};}catch(error){return {providerId:this.id,ok:false,latencyMs:Date.now()-started,checkedAt:providerNow(),message:normalizeOrbyError(error).message};}}
}
