import type {OrbyModerationRequest,OrbyModerationResult,OrbyProvider,OrbyProviderRequest,OrbyProviderStreamEvent} from '../core/contracts';
import {OrbyError,normalizeOrbyError} from '../core/errors';
import {providerCapabilities,providerHttpError,providerJsonRequest,providerNow,providerSseData,timedProviderSignal,unsupportedProviderCapability} from './common';

export type GeminiProviderOptions={apiKey:string;baseUrl?:string;id?:string;displayName?:string};
export class GeminiProvider implements OrbyProvider {
 readonly id:string;readonly displayName:string;readonly capabilities=providerCapabilities({text:true,streaming:true,embeddings:true,vision:true,json:true});private readonly baseUrl:string;
 constructor(private readonly options:GeminiProviderOptions){this.id=options.id||'gemini';this.displayName=options.displayName||'Google Gemini';this.baseUrl=(options.baseUrl||'https://generativelanguage.googleapis.com/v1beta').replace(/\/$/,'');}
 private url(path:string){return `${this.baseUrl}${path}${path.includes('?')?'&':'?'}key=${encodeURIComponent(this.options.apiKey)}`;}
 private payload(request:OrbyProviderRequest){const system=request.messages.filter(item=>item.role==='system').map(item=>item.content).join('\n\n'),contents=request.messages.filter(item=>item.role!=='system').map(item=>({role:item.role==='assistant'?'model':'user',parts:[{text:item.content}]}));return {systemInstruction:system?{parts:[{text:system}]}:undefined,contents,generationConfig:{temperature:request.options.temperature,topP:request.options.topP,maxOutputTokens:request.options.maxOutputTokens,stopSequences:request.options.stop,responseMimeType:request.options.responseFormat==='json'?'application/json':'text/plain'}};}
 async generate(request:OrbyProviderRequest){const {body}=await providerJsonRequest(this.url(`/models/${encodeURIComponent(request.model)}:generateContent`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(this.payload(request))},request.options.timeoutMs,request.signal);const value=body as {candidates?:Array<{finishReason?:string;content?:{parts?:Array<{text?:string}>}}> ;usageMetadata?:{promptTokenCount?:number;candidatesTokenCount?:number;totalTokenCount?:number}};const text=value.candidates?.[0]?.content?.parts?.map(item=>item.text||'').join('');if(!text)throw new OrbyError('صيغة استجابة Gemini غير متوقعة.','PROVIDER_BAD_RESPONSE',true);return {text,finishReason:value.candidates?.[0]?.finishReason,usage:{inputTokens:value.usageMetadata?.promptTokenCount,outputTokens:value.usageMetadata?.candidatesTokenCount,totalTokens:value.usageMetadata?.totalTokenCount}};}
 async *stream(request:OrbyProviderRequest):AsyncIterable<OrbyProviderStreamEvent>{const timed=timedProviderSignal(request.options.timeoutMs,request.signal);try{const response=await fetch(this.url(`/models/${encodeURIComponent(request.model)}:streamGenerateContent?alt=sse`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(this.payload(request)),signal:timed.signal,cache:'no-store'});if(!response.ok)throw providerHttpError(response.status,await response.json().catch(()=>null));yield {type:'start'};for await(const data of providerSseData(response)){const event=JSON.parse(data) as {candidates?:Array<{finishReason?:string;content?:{parts?:Array<{text?:string}>}}> ;usageMetadata?:{promptTokenCount?:number;candidatesTokenCount?:number;totalTokenCount?:number}};const text=event.candidates?.[0]?.content?.parts?.map(item=>item.text||'').join('');if(text)yield {type:'delta',text};if(event.usageMetadata)yield {type:'usage',usage:{inputTokens:event.usageMetadata.promptTokenCount,outputTokens:event.usageMetadata.candidatesTokenCount,totalTokens:event.usageMetadata.totalTokenCount}};const finish=event.candidates?.[0]?.finishReason;if(finish)yield {type:'end',finishReason:finish};}}finally{timed.dispose();}}
 async embeddings(request:Parameters<OrbyProvider['embeddings']>[0]){const vectors:number[][]=[];for(const input of request.inputs){const {body}=await providerJsonRequest(this.url(`/models/${encodeURIComponent(request.model)}:embedContent`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:`models/${request.model}`,content:{parts:[{text:input}]}})},undefined,request.signal);const values=(body as {embedding?:{values?:number[]}}).embedding?.values;if(!values)throw new OrbyError('صيغة استجابة تضمين Gemini غير متوقعة.','PROVIDER_BAD_RESPONSE',true);vectors.push(values);}return {vectors};}
 async moderation(_request:OrbyModerationRequest):Promise<readonly OrbyModerationResult[]>{throw unsupportedProviderCapability(this.id,'moderation');}
 async models(signal?:AbortSignal){const {body}=await providerJsonRequest(this.url('/models'),{},15000,signal);const value=body as {models?:Array<{name?:string;displayName?:string;inputTokenLimit?:number}>};return (value.models||[]).flatMap(item=>item.name?[{id:item.name.replace(/^models\//,''),displayName:item.displayName,contextWindow:item.inputTokenLimit}]:[]);}
 async health(signal?:AbortSignal){const started=Date.now();try{await this.models(signal);return {providerId:this.id,ok:true,latencyMs:Date.now()-started,checkedAt:providerNow()};}catch(error){return {providerId:this.id,ok:false,latencyMs:Date.now()-started,checkedAt:providerNow(),message:normalizeOrbyError(error).message};}}
}
