import type {OrbyEmbeddingRequest,OrbyEmbeddingResponse,OrbyModerationRequest,OrbyModerationResult,OrbyModelSummary,OrbyProvider,OrbyProviderRequest,OrbyProviderResponse,OrbyProviderStreamEvent} from '../core/contracts';
import {OrbyError,normalizeOrbyError} from '../core/errors';
import {providerCapabilities,providerHttpError,providerJsonRequest,providerNow,providerSseData,timedProviderSignal} from './common';

function messages(request:OrbyProviderRequest){return request.messages.map(message=>({role:message.role,content:message.content}));}
export type OpenAICompatibleProviderOptions={id?:string;displayName?:string;baseUrl?:string;apiKey:string;organization?:string;project?:string;defaultModerationModel?:string;headers?:Record<string,string>};

export class OpenAICompatibleProvider implements OrbyProvider {
 readonly id:string;readonly displayName:string;readonly capabilities=providerCapabilities({text:true,streaming:true,embeddings:true,moderation:true,vision:true,audio:true,json:true});protected readonly baseUrl:string;
 constructor(protected readonly options:OpenAICompatibleProviderOptions){this.id=options.id||'openai';this.displayName=options.displayName||'OpenAI';this.baseUrl=(options.baseUrl||'https://api.openai.com/v1').replace(/\/$/,'');}
 protected headers(){const headers=new Headers({'Content-Type':'application/json','Authorization':`Bearer ${this.options.apiKey}`,...this.options.headers});if(this.options.organization)headers.set('OpenAI-Organization',this.options.organization);if(this.options.project)headers.set('OpenAI-Project',this.options.project);return headers;}
 async generate(request:OrbyProviderRequest):Promise<OrbyProviderResponse>{const payload:{[key:string]:unknown}={model:request.model,messages:messages(request),temperature:request.options.temperature,max_tokens:request.options.maxOutputTokens,top_p:request.options.topP,stop:request.options.stop};if(request.options.responseFormat==='json')payload.response_format={type:'json_object'};const {body}=await providerJsonRequest(`${this.baseUrl}/chat/completions`,{method:'POST',headers:this.headers(),body:JSON.stringify(payload)},request.options.timeoutMs,request.signal);const value=body as {id?:string;choices?:Array<{finish_reason?:string;message?:{content?:string|null}}>;usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number}};const text=value.choices?.[0]?.message?.content;if(typeof text!=='string')throw new OrbyError('صيغة استجابة OpenAI غير متوقعة.','PROVIDER_BAD_RESPONSE',true,{providerId:this.id});return {text,finishReason:value.choices?.[0]?.finish_reason,providerRequestId:value.id,usage:{inputTokens:value.usage?.prompt_tokens,outputTokens:value.usage?.completion_tokens,totalTokens:value.usage?.total_tokens}};}
 async *stream(request:OrbyProviderRequest):AsyncIterable<OrbyProviderStreamEvent>{const timed=timedProviderSignal(request.options.timeoutMs,request.signal);try{const payload:{[key:string]:unknown}={model:request.model,messages:messages(request),stream:true,stream_options:{include_usage:true},temperature:request.options.temperature,max_tokens:request.options.maxOutputTokens,top_p:request.options.topP,stop:request.options.stop};if(request.options.responseFormat==='json')payload.response_format={type:'json_object'};const response=await fetch(`${this.baseUrl}/chat/completions`,{method:'POST',headers:this.headers(),body:JSON.stringify(payload),signal:timed.signal,cache:'no-store'});if(!response.ok)throw providerHttpError(response.status,await response.json().catch(()=>null));yield {type:'start'};for await(const data of providerSseData(response)){if(data==='[DONE]')break;const event=JSON.parse(data) as {choices?:Array<{delta?:{content?:string};finish_reason?:string}>;usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number}};const delta=event.choices?.[0]?.delta?.content;if(delta)yield {type:'delta',text:delta};if(event.usage)yield {type:'usage',usage:{inputTokens:event.usage.prompt_tokens,outputTokens:event.usage.completion_tokens,totalTokens:event.usage.total_tokens}};const finish=event.choices?.[0]?.finish_reason;if(finish)yield {type:'end',finishReason:finish};}}catch(error){throw normalizeOrbyError(error,'PROVIDER_UNAVAILABLE');}finally{timed.dispose();}}
 async embeddings(request:OrbyEmbeddingRequest):Promise<OrbyEmbeddingResponse>{const {body}=await providerJsonRequest(`${this.baseUrl}/embeddings`,{method:'POST',headers:this.headers(),body:JSON.stringify({model:request.model,input:request.inputs})},undefined,request.signal);const value=body as {data?:Array<{embedding?:number[]}>;usage?:{prompt_tokens?:number;total_tokens?:number}};const vectors=value.data?.map(item=>item.embedding).filter((item):item is number[]=>Array.isArray(item));if(!vectors||vectors.length!==request.inputs.length)throw new OrbyError('صيغة استجابة التضمين غير متوقعة.','PROVIDER_BAD_RESPONSE',true);return {vectors,usage:{inputTokens:value.usage?.prompt_tokens,totalTokens:value.usage?.total_tokens}};}
 async moderation(request:OrbyModerationRequest):Promise<readonly OrbyModerationResult[]>{const {body}=await providerJsonRequest(`${this.baseUrl}/moderations`,{method:'POST',headers:this.headers(),body:JSON.stringify({model:request.model||this.options.defaultModerationModel,input:request.inputs})},undefined,request.signal);const value=body as {results?:Array<{flagged?:boolean;categories?:Record<string,boolean>;category_scores?:Record<string,number>}>};if(!value.results)throw new OrbyError('صيغة استجابة الإشراف غير متوقعة.','PROVIDER_BAD_RESPONSE',true);return value.results.map(item=>({flagged:Boolean(item.flagged),categories:item.categories||{},scores:item.category_scores}));}
 async models(signal?:AbortSignal):Promise<readonly OrbyModelSummary[]>{const {body}=await providerJsonRequest(`${this.baseUrl}/models`,{headers:this.headers()},15000,signal);const value=body as {data?:Array<{id?:string}>};return (value.data||[]).flatMap(item=>item.id?[{id:item.id}]:[]);}
 async health(signal?:AbortSignal){const started=Date.now();try{await this.models(signal);return {providerId:this.id,ok:true,latencyMs:Date.now()-started,checkedAt:providerNow()};}catch(error){const normalized=normalizeOrbyError(error,'PROVIDER_UNAVAILABLE');return {providerId:this.id,ok:false,latencyMs:Date.now()-started,checkedAt:providerNow(),message:normalized.message};}}
}

export class LocalOpenAIProvider extends OpenAICompatibleProvider {constructor(options:Omit<OpenAICompatibleProviderOptions,'id'|'displayName'|'apiKey'> & {id?:string;displayName?:string;apiKey?:string}){super({...options,id:options.id||'local',displayName:options.displayName||'Local LLM',apiKey:options.apiKey||'local'});}}
