'use client';

import {useActionState} from 'react';
import {saveFeaturedItem,saveOffer,saveStoreSetting,type StoreActionState} from '@/app/actions/store';

export function OfferForm({initial={}}:{initial?:Record<string,unknown>}){const[state,action,pending]=useActionState<StoreActionState,FormData>(saveOffer,{});const v=(key:string)=>String(initial[key]??'');return <form action={action} className="md-panel grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={v('id')}/><h2 className="md:col-span-2 text-xl font-black">{initial.id?'تعديل العرض':'إضافة عرض'}</h2><Feedback state={state}/><Field name="name" label="اسم العرض" value={v('name')} required/><Field name="slug" label="الرابط المختصر" value={v('slug')} required dir="ltr"/><label className="text-sm font-bold">نوع الخصم<select name="discount_type" defaultValue={v('discount_type')||'percentage'} className="field mt-2"><option value="percentage">نسبة مئوية</option><option value="fixed">مبلغ ثابت</option><option value="override_price">سعر بديل</option></select></label><Field name="discount_value" label="قيمة الخصم" value={v('discount_value')||'0'} type="number" step="0.01"/><Field name="starts_at" label="بداية العرض" value={dateValue(v('starts_at'))} type="datetime-local"/><Field name="ends_at" label="نهاية العرض" value={dateValue(v('ends_at'))} type="datetime-local"/><label className="text-sm font-bold">حالة النشر<select name="status" defaultValue={v('status')||'draft'} className="field mt-2"><option value="draft">مسودة</option><option value="published">منشور</option><option value="archived">مؤرشف</option></select></label><label className="text-sm font-bold">الظهور<select name="visibility" defaultValue={v('visibility')||'hidden'} className="field mt-2"><option value="hidden">مخفي</option><option value="visible">مرئي</option></select></label><label className="md:col-span-2 text-sm font-bold">الوصف<textarea name="description" defaultValue={v('description')} rows={4} className="field mt-2"/></label><Check name="is_active" label="العرض نشط" checked={Boolean(initial.is_active)}/><Submit pending={pending}/></form>}

export function SettingForm({initial={}}:{initial?:Record<string,unknown>}){const[state,action,pending]=useActionState<StoreActionState,FormData>(saveStoreSetting,{});const v=(key:string)=>String(initial[key]??'');const json=initial.setting_value?JSON.stringify(initial.setting_value,null,2):'{}';return <form action={action} className="md-panel grid gap-4"><input type="hidden" name="id" value={v('id')}/><h2 className="text-xl font-black">{initial.id?'تعديل الإعداد':'إضافة إعداد'}</h2><Feedback state={state}/><Field name="setting_key" label="مفتاح الإعداد" value={v('setting_key')} required dir="ltr"/><label className="text-sm font-bold">القيمة بصيغة JSON<textarea name="setting_value" defaultValue={json} rows={10} dir="ltr" className="field mt-2 font-mono" required/></label><label className="text-sm font-bold">الوصف<textarea name="description" defaultValue={v('description')} rows={3} className="field mt-2"/></label><Check name="is_public" label="إعداد عام يمكن للواجهة قراءته" checked={Boolean(initial.is_public)}/><Submit pending={pending}/></form>}

export function FeaturedForm({initial={}}:{initial?:Record<string,unknown>}){const[state,action,pending]=useActionState<StoreActionState,FormData>(saveFeaturedItem,{});const v=(key:string)=>String(initial[key]??'');return <form action={action} className="md-panel grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={v('id')}/><h2 className="md:col-span-2 text-xl font-black">إضافة أو تعديل ظهور مميز</h2><Feedback state={state}/><label className="text-sm font-bold">نوع العنصر<select name="entity_type" defaultValue={v('entity_type')||'product'} className="field mt-2"><option value="product">منتج</option><option value="service">خدمة</option><option value="plan">اشتراك</option><option value="category">تصنيف</option></select></label><Field name="entity_id" label="معرف العنصر UUID" value={v('entity_id')} required dir="ltr"/><label className="text-sm font-bold">موضع الظهور<select name="placement" defaultValue={v('placement')||'store'} className="field mt-2"><option value="store">المتجر</option><option value="home">الرئيسية</option><option value="offers">العروض</option><option value="category">صفحة التصنيف</option></select></label><Field name="sort_order" label="الترتيب" value={v('sort_order')||'0'} type="number"/><Field name="title_override" label="عنوان بديل" value={v('title_override')}/><Field name="subtitle_override" label="وصف بديل" value={v('subtitle_override')}/><Field name="starts_at" label="بداية الظهور" value={dateValue(v('starts_at'))} type="datetime-local"/><Field name="ends_at" label="نهاية الظهور" value={dateValue(v('ends_at'))} type="datetime-local"/><Check name="is_active" label="نشط" checked={Boolean(initial.is_active)}/><Submit pending={pending}/></form>}

function Feedback({state}:{state:StoreActionState}){return <>{state.error&&<p className="md:col-span-2 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-red-100">{state.error}</p>}{state.success&&<p className="md:col-span-2 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3 text-emerald-100">{state.success}</p>}</>}
function Field({name,label,value,type='text',required=false,dir,step}:{name:string;label:string;value:string;type?:string;required?:boolean;dir?:'ltr'|'rtl';step?:string}){return <label className="text-sm font-bold">{label}<input name={name} defaultValue={value} type={type} required={required} dir={dir} step={step} className="field mt-2"/></label>}
function Check({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex items-center gap-3 rounded-xl border border-white/10 p-3 text-sm"><input name={name} type="checkbox" defaultChecked={checked}/>{label}</label>}
function Submit({pending}:{pending:boolean}){return <button disabled={pending} className="md-button md-button-primary justify-self-start">{pending?'جارٍ الحفظ…':'حفظ'}</button>}
function dateValue(value:string){return value?new Date(value).toISOString().slice(0,16):''}
