'use client';

import {useActionState} from 'react';
import {saveGalleryMedia,savePlanFeature} from '@/app/actions/store-relations';
import type {StoreActionState} from '@/app/actions/store';

type Option={id:string;name:string};
export function GalleryForm({products,initial={}}:{products:Option[];initial?:Record<string,unknown>}){const[state,action,pending]=useActionState<StoreActionState,FormData>(saveGalleryMedia,{});const v=(key:string)=>String(initial[key]??'');return <form action={action} className="md-panel grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={v('id')}/><h2 className="md:col-span-2 text-xl font-black">إضافة صورة أو فيديو للمعرض</h2><Feedback state={state}/><label className="text-sm font-bold">المنتج<select name="product_id" required defaultValue={v('product_id')} className="field mt-2"><option value="">اختر المنتج</option>{products.map(product=><option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="text-sm font-bold">نوع الوسائط<select name="media_type" defaultValue={v('media_type')||'image'} className="field mt-2"><option value="image">صورة</option><option value="video">فيديو</option></select></label><Field name="storage_path" label="مسار الملف في catalog-images" value={v('storage_path')} dir="ltr"/><Field name="external_url" label="أو رابط خارجي HTTPS" value={v('external_url')} dir="ltr"/><Field name="alt_text" label="النص البديل" value={v('alt_text')}/><Field name="caption" label="التعليق" value={v('caption')}/><Field name="sort_order" label="الترتيب" value={v('sort_order')||'0'} type="number"/><label className="flex items-center gap-3 rounded-xl border border-white/10 p-3 text-sm"><input name="is_cover" type="checkbox" defaultChecked={Boolean(initial.is_cover)}/>استخدام كصورة غلاف</label><button disabled={pending} className="md-button md-button-primary justify-self-start">{pending?'جارٍ الحفظ…':'حفظ الوسائط'}</button></form>}

export function PlanFeatureForm({plans,initial={}}:{plans:Option[];initial?:Record<string,unknown>}){const[state,action,pending]=useActionState<StoreActionState,FormData>(savePlanFeature,{});const v=(key:string)=>String(initial[key]??'');return <form action={action} className="md-panel grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={v('id')}/><h2 className="md:col-span-2 text-xl font-black">ميزة خطة اشتراك</h2><Feedback state={state}/><label className="text-sm font-bold">الخطة<select name="plan_id" required defaultValue={v('plan_id')} className="field mt-2"><option value="">اختر الخطة</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><Field name="name" label="اسم الميزة" value={v('name')} required/><Field name="feature_key" label="مفتاح الميزة" value={v('feature_key')} dir="ltr"/><Field name="value" label="القيمة JSON أو نص" value={initial.value===undefined?'true':JSON.stringify(initial.value)} dir="ltr"/><label className="md:col-span-2 text-sm font-bold">الوصف<textarea name="description" defaultValue={v('description')} rows={3} className="field mt-2"/></label><Field name="sort_order" label="الترتيب" value={v('sort_order')||'0'} type="number"/><label className="flex items-center gap-3 rounded-xl border border-white/10 p-3 text-sm"><input name="is_highlighted" type="checkbox" defaultChecked={Boolean(initial.is_highlighted)}/>ميزة بارزة</label><button disabled={pending} className="md-button md-button-primary justify-self-start">{pending?'جارٍ الحفظ…':'حفظ الميزة'}</button></form>}

function Feedback({state}:{state:StoreActionState}){return <>{state.error&&<p className="md:col-span-2 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-red-100">{state.error}</p>}{state.success&&<p className="md:col-span-2 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3 text-emerald-100">{state.success}</p>}</>}
function Field({name,label,value,type='text',required=false,dir}:{name:string;label:string;value:string;type?:string;required?:boolean;dir?:'ltr'|'rtl'}){return <label className="text-sm font-bold">{label}<input name={name} defaultValue={value} type={type} required={required} dir={dir} className="field mt-2"/></label>}
