-- Initial production catalog. Idempotent and safe to rerun.
insert into public.categories(name,slug,description,is_active,sort_order) values
 ('أنظمة الذكاء الاصطناعي','ai-systems','حلول ذكاء اصطناعي عملية للأعمال',true,1),
 ('قوالب Notion','notion-templates','قوالب عربية لتنظيم المشاريع والفرق',true,2),
 ('أتمتة الأعمال','business-automation','حلول لتقليل العمل اليدوي',true,3),
 ('Google Sheets','google-sheets','لوحات بيانات وتشغيل مرنة',true,4)
on conflict(slug) do update set name=excluded.name,description=excluded.description,is_active=excluded.is_active,sort_order=excluded.sort_order;

insert into public.products(name,slug,short_description,long_description,price,currency,category_id,status,is_featured,delivery_type,features,includes,published_at) values
 ('مساعد AI متقدم للأعمال','advanced-ai-assistant','مساعد ذكي عربي لإجابة العملاء وتلخيص البيانات وبناء قواعد معرفة داخلية.','نظام جاهز للتخصيص يساعد فرق المبيعات والدعم على تحويل الأسئلة المتكررة إلى إجابات موحدة، مع مسارات تشغيل قابلة للتكامل مع البريد وواتساب وأنظمة إدارة العملاء.',299,'SAR',(select id from public.categories where slug='ai-systems'),'published',true,'digital','["قاعدة معرفة قابلة للتوسع","سيناريوهات رد عربية","توثيق إعداد وتشغيل","بنية جاهزة للتكاملات"]','["ملفات القالب","دليل التشغيل","جلسة تهيئة قصيرة"]',now()),
 ('نظام إدارة المشاريع','project-management-notion-template','قالب Notion احترافي لإدارة المشاريع والمهام والمؤشرات.','مساحة عمل عربية منظمة للفرق الصغيرة ورواد الأعمال، تشمل المشاريع والمهام والاجتماعات والمؤشرات وقوالب التقارير.',99,'SAR',(select id from public.categories where slug='notion-templates'),'published',true,'digital','["لوحات مشاريع ومهام","قوالب اجتماعات","مؤشرات تقدم","دليل استخدام عربي"]','["رابط القالب","فيديو شرح مختصر","تحديثات لمدة 30 يوماً"]',now()),
 ('حزمة أتمتة العمليات','business-automation-suite','خرائط أتمتة جاهزة لتنظيم الاستقبال والمتابعة والتقارير.','حزمة عملية لتقليل العمل اليدوي في المتاجر والخدمات، مصممة كبنية قابلة للربط مع مزودي البريد والدفع والرسائل.',199,'SAR',(select id from public.categories where slug='business-automation'),'published',true,'digital','["خرائط تدفق جاهزة","نماذج رسائل متابعة","قوائم تحقق تشغيلية","إرشادات أمن البيانات"]','["ملفات الأتمتة","دليل الربط","قائمة اختبار قبل الإطلاق"]',now()),
 ('لوحة تحكم المبيعات','sales-dashboard-google-sheets','نظام Google Sheets لمتابعة المبيعات والتحويلات والمؤشرات اليومية.','لوحة قياس مرنة للشركات الصغيرة تجمع المبيعات والمصروفات ومؤشرات الأداء في جداول واضحة قابلة للتوسع.',149,'SAR',(select id from public.categories where slug='google-sheets'),'published',true,'digital','["مؤشرات مبيعات","تقارير شهرية","تنبيهات تحقق يدوية","صفحات إدخال منظمة"]','["القالب","دليل الصيغ","أمثلة بيانات"]',now())
on conflict(slug) do update set name=excluded.name,short_description=excluded.short_description,long_description=excluded.long_description,price=excluded.price,currency=excluded.currency,category_id=excluded.category_id,status=excluded.status,is_featured=excluded.is_featured,delivery_type=excluded.delivery_type,features=excluded.features,includes=excluded.includes,published_at=coalesce(public.products.published_at,excluded.published_at);

insert into public.services(name,slug,short_description,long_description,price_from,currency,status,is_featured,features,published_at) values
 ('استشارات وأتمتة العمليات','automation-consulting','تحليل سير العمل وبناء خطة أتمتة عملية قابلة للتنفيذ دون تغيير جذري في أدواتك الحالية.','نحلل العمليات ونرتب فرص الأتمتة ونقدم خارطة تنفيذ واضحة قابلة للقياس.',750,'SAR','published',true,'["خريطة عمليات","أولويات تنفيذ","متطلبات تكامل"]',now()),
 ('بناء منتجات رقمية','digital-product-build','تصميم قوالب وأنظمة تشغيل داخلية ولوحات بيانات لفريقك أو لبيعها كمنتج رقمي.','من الفكرة والمواصفات إلى نسخة قابلة للإطلاق مع توثيق الاستخدام.',2500,'SAR','published',true,'["مواصفات منتج","نسخة قابلة للإطلاق","توثيق استخدام"]',now()),
 ('تجهيز تدفقات AI','ai-workflows','تحويل المهام المتكررة إلى تدفقات مدعومة بالذكاء الاصطناعي مع ضوابط جودة ومراجعة.','نبني تدفقات ذكاء اصطناعي قابلة للمراجعة والقياس ومناسبة لسياق عملك.',1500,'SAR','published',true,'["تصميم prompts","قواعد مراجعة","خطة قياس"]',now())
on conflict(slug) do update set name=excluded.name,short_description=excluded.short_description,long_description=excluded.long_description,price_from=excluded.price_from,currency=excluded.currency,status=excluded.status,is_featured=excluded.is_featured,features=excluded.features,published_at=coalesce(public.services.published_at,excluded.published_at);
