begin;

create table if not exists public.currencies(
 code text primary key check(code=upper(code) and code~'^[A-Z0-9_]{2,12}$'),name text not null,symbol text not null,
 decimal_places smallint not null default 2 check(decimal_places between 0 and 8),is_active boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id) on delete set null);
insert into public.currencies(code,name,symbol,decimal_places,is_active) values('YER','ريال يمني','ر.ي',0,true),('SAR','ريال سعودي','ر.س',2,true),('USD','دولار أمريكي','$',2,true) on conflict(code) do nothing;

create table if not exists public.exchange_rates(
 id uuid primary key default gen_random_uuid(),base_currency text not null references public.currencies(code) on update cascade on delete restrict,
 quote_currency text not null references public.currencies(code) on update cascade on delete restrict,rate numeric(30,12) not null check(rate>0),
 status text not null default 'active' check(status in('active','inactive')),updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id) on delete set null,
 unique(base_currency,quote_currency),check(base_currency<>quote_currency));

alter table public.payment_methods add column if not exists currency_agnostic boolean not null default true;
alter table public.payment_methods add column if not exists logo_path text;
alter table public.payment_methods drop constraint if exists payment_methods_currency_check;
create table if not exists public.payment_method_currencies(payment_method_id uuid not null references public.payment_methods(id) on delete cascade,currency_code text not null references public.currencies(code) on update cascade on delete restrict,created_at timestamptz not null default now(),primary key(payment_method_id,currency_code));

alter table public.orders drop constraint if exists orders_currency_check;
alter table public.orders add column if not exists original_amount numeric(30,12);
alter table public.orders add column if not exists original_currency text;
alter table public.orders add column if not exists payment_amount numeric(30,12);
alter table public.orders add column if not exists payment_currency text;
alter table public.orders add column if not exists exchange_rate numeric(30,12);
alter table public.orders add column if not exists exchange_rate_id uuid references public.exchange_rates(id) on delete set null;
alter table public.orders add column if not exists payment_method_id uuid references public.payment_methods(id) on delete set null;
with inferred as(select o.id,min(coalesce(p.currency,s.currency)) inferred_currency,count(distinct coalesce(p.currency,s.currency)) currency_count from public.orders o join public.order_items oi on oi.order_id=o.id left join public.products p on p.id=oi.product_id left join public.services s on s.id=oi.service_id group by o.id)
update public.orders o set currency=i.inferred_currency,original_currency=i.inferred_currency,original_amount=o.total from inferred i where o.id=i.id and i.currency_count=1 and i.inferred_currency is not null and o.original_currency is null;
alter table public.products drop constraint if exists products_currency_fkey;
alter table public.products add constraint products_currency_fkey foreign key(currency) references public.currencies(code) on update cascade on delete restrict not valid;
alter table public.products validate constraint products_currency_fkey;
alter table public.orders add constraint orders_original_currency_fkey foreign key(original_currency) references public.currencies(code) on update cascade on delete restrict not valid;
alter table public.orders add constraint orders_payment_currency_fkey foreign key(payment_currency) references public.currencies(code) on update cascade on delete restrict not valid;
alter table public.orders add constraint orders_original_amount_check check(original_amount is null or original_amount>=0) not valid;
alter table public.orders add constraint orders_payment_amount_check check(payment_amount is null or payment_amount>=0) not valid;
alter table public.orders add constraint orders_exchange_rate_check check(exchange_rate is null or exchange_rate>0) not valid;
alter table public.orders validate constraint orders_original_currency_fkey;alter table public.orders validate constraint orders_payment_currency_fkey;alter table public.orders validate constraint orders_original_amount_check;alter table public.orders validate constraint orders_payment_amount_check;alter table public.orders validate constraint orders_exchange_rate_check;

create table if not exists public.product_entitlements(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,
 order_item_id uuid not null unique references public.order_items(id) on delete restrict,product_file_id uuid not null references public.product_files(id) on delete restrict,
 product_name text not null,thumbnail_path text,original_amount numeric(30,12) not null check(original_amount>=0),original_currency text not null references public.currencies(code) on update cascade on delete restrict,
 payment_amount numeric(30,12),payment_currency text references public.currencies(code) on update cascade on delete restrict,exchange_rate numeric(30,12),purchased_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(user_id,order_item_id));
create index if not exists product_entitlements_user_purchased_idx on public.product_entitlements(user_id,purchased_at desc);create index if not exists product_entitlements_file_idx on public.product_entitlements(product_file_id,user_id);
insert into public.product_entitlements(user_id,product_id,order_item_id,product_file_id,product_name,thumbnail_path,original_amount,original_currency,payment_amount,payment_currency,exchange_rate,purchased_at)
select o.user_id,oi.product_id,oi.id,pf.id,oi.title,p.thumbnail_url,oi.line_total,p.currency,o.payment_amount,o.payment_currency,o.exchange_rate,coalesce(o.paid_at,o.created_at)
from public.orders o join public.order_items oi on oi.order_id=o.id and oi.item_type='product' join public.products p on p.id=oi.product_id join lateral(select f.id from public.product_files f where f.product_id=oi.product_id and f.deleted_at is null order by f.is_active desc,f.version desc,f.created_at desc limit 1)pf on true where o.payment_status='approved' on conflict(order_item_id) do nothing;

alter table public.currencies enable row level security;alter table public.exchange_rates enable row level security;alter table public.payment_method_currencies enable row level security;alter table public.product_entitlements enable row level security;
drop policy if exists "active currencies public" on public.currencies;create policy "active currencies public" on public.currencies for select to anon,authenticated using(is_active or private.is_admin());
drop policy if exists "admins manage currencies" on public.currencies;create policy "admins manage currencies" on public.currencies for all to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy if exists "active exchange rates public" on public.exchange_rates;create policy "active exchange rates public" on public.exchange_rates for select to authenticated using(status='active' or private.is_admin());
drop policy if exists "admins manage exchange rates" on public.exchange_rates;create policy "admins manage exchange rates" on public.exchange_rates for all to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy if exists "payment method currency read" on public.payment_method_currencies;create policy "payment method currency read" on public.payment_method_currencies for select to authenticated using(exists(select 1 from public.payment_methods pm where pm.id=payment_method_id and(pm.is_active or private.is_admin())));
drop policy if exists "admins manage payment method currencies" on public.payment_method_currencies;create policy "admins manage payment method currencies" on public.payment_method_currencies for all to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy if exists "users read own product entitlements" on public.product_entitlements;create policy "users read own product entitlements" on public.product_entitlements for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());
drop policy if exists "admins or paid customers read files" on public.product_files;create policy "admins or entitled customers read files" on public.product_files for select to authenticated using(private.is_admin() or exists(select 1 from public.product_entitlements e where e.product_file_id=product_files.id and e.user_id=(select auth.uid())));
drop policy if exists "paid customers download products" on storage.objects;create policy "entitled customers download products" on storage.objects for select to authenticated using(bucket_id='digital-products' and(private.is_admin() or exists(select 1 from public.product_files pf join public.product_entitlements e on e.product_file_id=pf.id where pf.storage_path=storage.objects.name and e.user_id=(select auth.uid()))));

create or replace function private.create_product_payment_request_impl(p_order_id uuid,p_product_id uuid,p_payment_currency text,p_payment_method_id uuid,p_payment_reference text,p_proof_path text default null,p_proof_name text default null,p_proof_mime text default null,p_proof_size bigint default null) returns uuid language plpgsql security definer set search_path='public' as $$
declare v_user uuid:=(select auth.uid());v_profile public.profiles%rowtype;v_product public.products%rowtype;v_method public.payment_methods%rowtype;v_payment_currency text:=upper(trim(p_payment_currency));v_original_currency text;v_rate numeric(30,12):=1;v_rate_id uuid;v_decimals integer;v_payment_amount numeric(30,12);v_reference text:=nullif(trim(p_payment_reference),'');
begin
 if v_user is null then raise exception 'AUTH_REQUIRED';end if;if p_order_id is null or exists(select 1 from public.orders where id=p_order_id) then raise exception 'INVALID_ORDER_ID';end if;if v_reference is null or char_length(v_reference)<3 or char_length(v_reference)>120 then raise exception 'PAYMENT_REFERENCE_REQUIRED';end if;
 select * into v_profile from public.profiles where id=v_user and status='active';if not found or v_profile.email is null then raise exception 'PROFILE_REQUIRED';end if;
 select * into v_product from public.products where id=p_product_id and status='published' and visibility='visible' and is_active and show_in_store and availability='available' and deleted_at is null for share;if not found then raise exception 'PRODUCT_UNAVAILABLE';end if;
 if not exists(select 1 from public.product_files f where f.product_id=v_product.id and f.is_active and f.deleted_at is null) then raise exception 'PRODUCT_FILE_REQUIRED';end if;
 v_original_currency:=upper(v_product.currency);if not exists(select 1 from public.currencies where code=v_original_currency and is_active)then raise exception 'ORIGINAL_CURRENCY_INACTIVE';end if;select decimal_places into v_decimals from public.currencies where code=v_payment_currency and is_active;if not found then raise exception 'PAYMENT_CURRENCY_INACTIVE';end if;
 select * into v_method from public.payment_methods where id=p_payment_method_id and is_active for share;if not found then raise exception 'PAYMENT_METHOD_UNAVAILABLE';end if;if not v_method.currency_agnostic and not exists(select 1 from public.payment_method_currencies pmc where pmc.payment_method_id=v_method.id and pmc.currency_code=v_payment_currency)then raise exception 'PAYMENT_METHOD_CURRENCY_UNAVAILABLE';end if;
 if v_original_currency<>v_payment_currency then select id,rate into v_rate_id,v_rate from public.exchange_rates where base_currency=v_original_currency and quote_currency=v_payment_currency and status='active' limit 1;if not found then select id,(1/rate) into v_rate_id,v_rate from public.exchange_rates where base_currency=v_payment_currency and quote_currency=v_original_currency and status='active' limit 1;if not found then raise exception 'FX_RATE_MISSING';end if;end if;end if;
 v_payment_amount:=round(v_product.price*v_rate,v_decimals);
 insert into public.orders(id,order_number,user_id,status,payment_status,currency,subtotal,discount_total,total,original_amount,original_currency,payment_amount,payment_currency,exchange_rate,exchange_rate_id,payment_method_id,customer_name,customer_email,customer_phone,payment_reference,payment_submitted_at) values(p_order_id,'MDR-'||upper(substr(replace(p_order_id::text,'-',''),1,10)),v_user,'payment_review','under_review',v_original_currency,v_product.price,0,v_product.price,v_product.price,v_original_currency,v_payment_amount,v_payment_currency,v_rate,v_rate_id,v_method.id,coalesce(nullif(trim(v_profile.full_name),''),'عميل مدار'),v_profile.email,v_profile.phone,v_reference,now());
 insert into public.order_items(order_id,item_type,product_id,title,unit_price,quantity)values(p_order_id,'product',v_product.id,v_product.name,v_product.price,1);
 if p_proof_path is not null then if p_proof_name is null or p_proof_mime is null or p_proof_size is null then raise exception 'INVALID_PROOF_METADATA';end if;insert into public.payment_proofs(order_id,user_id,storage_path,original_filename,mime_type,file_size)values(p_order_id,v_user,p_proof_path,p_proof_name,p_proof_mime,p_proof_size);end if;
 insert into public.order_status_history(order_id,to_status,actor_id,note)values(p_order_id,'payment_review',v_user,'تم إرسال طلب شراء برقم عملية للمراجعة');insert into public.notifications(user_id,title,body,link)values(v_user,'تم إرسال طلب الشراء','استلمنا رقم العملية وسيتم إشعارك بعد مراجعة الإدارة.','/account/orders/'||p_order_id);return p_order_id;
end$$;
create or replace function public.create_product_payment_request(p_order_id uuid,p_product_id uuid,p_payment_currency text,p_payment_method_id uuid,p_payment_reference text,p_proof_path text default null,p_proof_name text default null,p_proof_mime text default null,p_proof_size bigint default null)returns uuid language sql set search_path='' as $$select private.create_product_payment_request_impl(p_order_id,p_product_id,p_payment_currency,p_payment_method_id,p_payment_reference,p_proof_path,p_proof_name,p_proof_mime,p_proof_size)$$;

create or replace function private.submit_order_payment_impl(p_order_id uuid,p_payment_reference text)returns void language plpgsql security definer set search_path='public' as $$declare v_user uuid:=(select auth.uid());v_old public.order_status;v_reference text:=nullif(trim(p_payment_reference),'');begin if v_user is null then raise exception 'AUTH_REQUIRED';end if;if v_reference is null or char_length(v_reference)<3 or char_length(v_reference)>120 then raise exception 'PAYMENT_REFERENCE_REQUIRED';end if;select status into v_old from public.orders where id=p_order_id and user_id=v_user and payment_status in('unpaid','rejected') for update;if not found then raise exception 'ORDER_NOT_PAYABLE';end if;update public.orders set status='payment_review',payment_status='under_review',payment_reference=v_reference,payment_submitted_at=now(),admin_note=null where id=p_order_id;insert into public.order_status_history(order_id,from_status,to_status,actor_id,note)values(p_order_id,v_old,'payment_review',v_user,'تم إرسال رقم العملية للمراجعة');end$$;

create or replace function private.review_order_payment_impl(p_order_id uuid,p_approved boolean,p_note text default null)returns void language plpgsql security definer set search_path='public' as $$
declare v_actor uuid:=(select auth.uid());v_user uuid;v_old public.order_status;v_next public.order_status;v_item record;v_file public.product_files%rowtype;v_order public.orders%rowtype;v_names text:='';begin if v_actor is null or not private.is_admin()then raise exception 'ADMIN_REQUIRED';end if;select * into v_order from public.orders where id=p_order_id and payment_status='under_review' for update;if not found then raise exception 'ORDER_NOT_REVIEWABLE';end if;v_user:=v_order.user_id;v_old:=v_order.status;
 if p_approved then for v_item in select * from public.order_items where order_id=p_order_id and item_type='product' loop select * into v_file from public.product_files where product_id=v_item.product_id and is_active and deleted_at is null order by version desc,created_at desc limit 1 for share;if not found then raise exception 'PRODUCT_FILE_REQUIRED';end if;insert into public.product_entitlements(user_id,product_id,order_item_id,product_file_id,product_name,thumbnail_path,original_amount,original_currency,payment_amount,payment_currency,exchange_rate,purchased_at)select v_user,v_item.product_id,v_item.id,v_file.id,v_item.title,p.thumbnail_url,v_item.line_total,coalesce(v_order.original_currency,p.currency,v_order.currency),v_order.payment_amount,v_order.payment_currency,v_order.exchange_rate,now() from public.products p where p.id=v_item.product_id on conflict(order_item_id)do nothing;update public.products set sales_count=sales_count+v_item.quantity where id=v_item.product_id;v_names:=concat_ws('، ',nullif(v_names,''),v_item.title);end loop;end if;
 v_next:=case when p_approved then 'paid'::public.order_status else 'rejected'::public.order_status end;update public.orders set status=v_next,payment_status=case when p_approved then 'approved'::public.payment_status else 'rejected'::public.payment_status end,reviewed_by=v_actor,reviewed_at=now(),admin_note=nullif(trim(p_note),''),paid_at=case when p_approved then now() else paid_at end where id=p_order_id;insert into public.order_status_history(order_id,from_status,to_status,actor_id,note)values(p_order_id,v_old,v_next,v_actor,nullif(trim(p_note),''));insert into public.notifications(user_id,title,body,link)values(v_user,case when p_approved then 'تمت الموافقة على عملية الشراء' else 'تعذر اعتماد دفعتك' end,case when p_approved then 'تمت الموافقة على عملية شراء '||coalesce(nullif(v_names,''),'طلبك')||'. المنتج متاح الآن في مكتبتك.' else 'راجع ملاحظة الإدارة ويمكنك إنشاء طلب جديد لاحقًا.' end,case when p_approved then '/account/purchases' else '/account/orders/'||p_order_id end);end$$;

grant select on public.currencies to anon,authenticated;grant select on public.exchange_rates,public.payment_method_currencies,public.product_entitlements to authenticated;grant execute on function public.create_product_payment_request(uuid,uuid,text,uuid,text,text,text,text,bigint)to authenticated;revoke execute on function public.create_product_payment_request(uuid,uuid,text,uuid,text,text,text,text,bigint)from anon;
insert into public.store_settings(setting_key,setting_value,description,is_public)values('reporting_currency','"SAR"'::jsonb,'العملة المرجعية للتحليل فقط ولا تفرض على الدفع.',false)on conflict(setting_key)do nothing;
delete from public.products p where p.created_by is null and not exists(select 1 from public.order_items oi where oi.product_id=p.id);
update public.products p set status='archived',visibility='hidden',is_active=false,show_in_store=false,show_on_home=false,deleted_at=coalesce(deleted_at,now()),updated_at=now() where exists(select 1 from public.order_items oi where oi.product_id=p.id);
commit;
