create or replace function private.create_customer_order_impl(p_items jsonb,p_coupon_code text default null,p_customer_phone text default null,p_customer_notes text default null)
returns uuid language plpgsql security definer set search_path='public' as $$
declare v_user uuid:=(select auth.uid());v_profile public.profiles%rowtype;v_order uuid:=gen_random_uuid();v_item jsonb;v_product public.products%rowtype;v_service public.services%rowtype;v_subtotal numeric(30,12):=0;v_discount numeric(30,12):=0;v_coupon public.coupons%rowtype;v_qty int;v_currency text;v_item_currency text;
begin
 if v_user is null then raise exception 'AUTH_REQUIRED';end if;select * into v_profile from public.profiles where id=v_user and status='active';if not found or v_profile.email is null then raise exception 'PROFILE_REQUIRED';end if;if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)<1 or jsonb_array_length(p_items)>20 then raise exception 'INVALID_ITEMS';end if;
 for v_item in select * from jsonb_array_elements(p_items) loop v_qty:=coalesce((v_item->>'quantity')::int,1);if v_qty<1 or v_qty>20 then raise exception 'INVALID_QUANTITY';end if;if v_item->>'type'='product' then select * into v_product from public.products where id=(v_item->>'id')::uuid and status='published' and deleted_at is null for share;if not found then raise exception 'PRODUCT_UNAVAILABLE';end if;v_item_currency:=v_product.currency;v_subtotal:=v_subtotal+(v_product.price*v_qty);elsif v_item->>'type'='service' then select * into v_service from public.services where id=(v_item->>'id')::uuid and status='published' and deleted_at is null for share;if not found then raise exception 'SERVICE_UNAVAILABLE';end if;v_item_currency:=v_service.currency;v_subtotal:=v_subtotal+(v_service.price_from*v_qty);else raise exception 'INVALID_ITEM_TYPE';end if;if v_currency is null then v_currency:=v_item_currency;elsif v_currency<>v_item_currency then raise exception 'MIXED_CURRENCY_CART';end if;end loop;
 insert into public.orders(id,order_number,user_id,currency,subtotal,total,original_amount,original_currency,customer_name,customer_email,customer_phone,customer_notes)values(v_order,'MDR-'||upper(substr(replace(v_order::text,'-',''),1,10)),v_user,v_currency,0,0,0,v_currency,coalesce(nullif(trim(v_profile.full_name),''),'عميل مدار'),v_profile.email,nullif(trim(p_customer_phone),''),nullif(trim(p_customer_notes),''));
 for v_item in select * from jsonb_array_elements(p_items) loop v_qty:=coalesce((v_item->>'quantity')::int,1);if v_item->>'type'='product' then select * into v_product from public.products where id=(v_item->>'id')::uuid for share;insert into public.order_items(order_id,item_type,product_id,title,unit_price,quantity)values(v_order,'product',v_product.id,v_product.name,v_product.price,v_qty);else select * into v_service from public.services where id=(v_item->>'id')::uuid for share;insert into public.order_items(order_id,item_type,service_id,title,unit_price,quantity,service_requirements)values(v_order,'service',v_service.id,v_service.name,v_service.price_from,v_qty,nullif(trim(v_item->>'requirements'),''));end if;end loop;
 if p_coupon_code is not null and trim(p_coupon_code)<>'' then select * into v_coupon from public.coupons where code=upper(trim(p_coupon_code)) and is_active and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>now())for update;if not found then raise exception 'INVALID_COUPON';end if;if v_subtotal<v_coupon.minimum_order then raise exception 'COUPON_MINIMUM';end if;if v_coupon.usage_limit is not null and(select count(*) from public.coupon_redemptions where coupon_id=v_coupon.id)>=v_coupon.usage_limit then raise exception 'COUPON_EXHAUSTED';end if;if(select count(*) from public.coupon_redemptions where coupon_id=v_coupon.id and user_id=v_user)>=v_coupon.per_user_limit then raise exception 'COUPON_USER_LIMIT';end if;v_discount:=case when v_coupon.discount_type='percent' then round(v_subtotal*v_coupon.discount_value/100,2) else least(v_coupon.discount_value,v_subtotal) end;if v_coupon.maximum_discount is not null then v_discount:=least(v_discount,v_coupon.maximum_discount);end if;insert into public.coupon_redemptions(coupon_id,order_id,user_id,discount_amount)values(v_coupon.id,v_order,v_user,v_discount);end if;
 update public.orders set subtotal=v_subtotal,discount_total=v_discount,total=v_subtotal-v_discount,original_amount=v_subtotal-v_discount,coupon_id=v_coupon.id where id=v_order;insert into public.order_status_history(order_id,to_status,actor_id,note)values(v_order,'awaiting_payment',v_user,'تم إنشاء الطلب');insert into public.notifications(user_id,title,body,link)values(v_user,'تم إنشاء طلبك','تم إنشاء الطلب وهو بانتظار رقم العملية.','/account/orders/'||v_order);return v_order;
end$$;
