import {NextResponse} from 'next/server';
import {currentUser,supabaseFetch} from '@/src/lib/supabase/server';

export const runtime='nodejs';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const tokenFrom=(request:Request)=>{const header=request.headers.get('authorization')||'';const[scheme,token]=header.split(/\s+/,2);return scheme?.toLowerCase()==='bearer'&&token?token:undefined;};
async function authorize(request:Request,organizationId:string){const token=tokenFrom(request),user=await currentUser(token);if(!user)return{error:NextResponse.json({error:'يجب تسجيل الدخول أولًا.'},{status:401})};const rows=await supabaseFetch(`/rest/v1/organization_members?organization_id=eq.${encodeURIComponent(organizationId)}&user_id=eq.${encodeURIComponent(user.id)}&select=organization_id,organizations(status)`,{},token) as Array<{organizations?:{status?:string}}> ;if(rows[0]?.organizations?.status!=='active')return{error:NextResponse.json({error:'لا تملك صلاحية إدارة محادثات هذه المساحة.'},{status:403})};return{token,user};}

export async function PATCH(request:Request){
 try{const body=await request.json() as {organizationId?:string;conversationId?:string;action?:'rename'|'archive'|'restore';title?:string},organizationId=String(body.organizationId||''),conversationId=String(body.conversationId||'');if(!uuid.test(organizationId)||!uuid.test(conversationId))return NextResponse.json({error:'معرّف المحادثة أو المساحة غير صالح.'},{status:400});const authorization=await authorize(request,organizationId);if('error'in authorization)return authorization.error;const patch:Record<string,unknown>={};if(body.action==='rename'){const title=String(body.title||'').trim();if(title.length<2||title.length>120)return NextResponse.json({error:'عنوان المحادثة يجب أن يكون بين حرفين و120 حرفًا.'},{status:400});patch.title=title;}else if(body.action==='archive')patch.status='archived';else if(body.action==='restore')patch.status='active';else return NextResponse.json({error:'الإجراء غير مدعوم.'},{status:400});const rows=await supabaseFetch(`/rest/v1/orby_conversations?id=eq.${encodeURIComponent(conversationId)}&organization_id=eq.${encodeURIComponent(organizationId)}&user_id=eq.${encodeURIComponent(authorization.user.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)},authorization.token) as Array<{id:string;title:string;status:string}>;if(!rows[0])return NextResponse.json({error:'المحادثة غير موجودة أو لا تملك صلاحيتها.'},{status:404});return NextResponse.json({conversation:rows[0]});}catch(error){console.error('ORBY conversation update failed',error instanceof Error?error.message:'unknown');return NextResponse.json({error:'تعذر تحديث المحادثة.'},{status:500});}
}

export async function DELETE(request:Request){
 try{const url=new URL(request.url),organizationId=String(url.searchParams.get('organizationId')||''),conversationId=String(url.searchParams.get('conversationId')||'');if(!uuid.test(organizationId)||!uuid.test(conversationId))return NextResponse.json({error:'معرّف المحادثة أو المساحة غير صالح.'},{status:400});const authorization=await authorize(request,organizationId);if('error'in authorization)return authorization.error;await supabaseFetch(`/rest/v1/orby_conversations?id=eq.${encodeURIComponent(conversationId)}&organization_id=eq.${encodeURIComponent(organizationId)}&user_id=eq.${encodeURIComponent(authorization.user.id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}},authorization.token);return NextResponse.json({deleted:true});}catch(error){console.error('ORBY conversation delete failed',error instanceof Error?error.message:'unknown');return NextResponse.json({error:'تعذر حذف المحادثة وفق سياسة البيانات الحالية.'},{status:500});}
}
